object EditForm1: TEditForm1
  Left = 277
  Top = 196
  Width = 598
  Height = 467
  Hint = 'C:\TASPRO7\DBA7\EvoBS.DFM'
  Caption = ' Business Status'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'EvoBS.OnClose'
  No_Refresh = False
  OpenFiles = 'EvoBS.OnOpenFiles'
  OnDisplayScreen = 'EvoBS.OnDisp'
  ScreenPos = tpDesktopCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'EvoBS'
  RememberSizeDate = 38862.986609687500000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Pages: TTASPageControl
    Left = 2
    Top = 4
    Width = 584
    Height = 403
    ActivePage = Status
    MultiLine = True
    TabOrder = 0
    PageIndex = 0
    PageName = 'Status'
    object Status: TTabSheet
      Caption = 'Status'
      object ARBOX: TGroupBox
        Left = 3
        Top = 9
        Width = 280
        Height = 162
        Hint = 'Click to Drill Down to Accounts Receivables'
        Caption = 'Accounts Receivable'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        object Label1: TLabel
          Left = 9
          Top = 28
          Width = 93
          Height = 16
          Caption = 'Current Balance'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label2: TLabel
          Left = 9
          Top = 48
          Width = 42
          Height = 16
          Caption = 'Billings'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label3: TLabel
          Left = 9
          Top = 70
          Width = 51
          Height = 16
          Caption = 'Receipts'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label4: TLabel
          Left = 9
          Top = 92
          Width = 58
          Height = 16
          Caption = 'Discounts'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label5: TLabel
          Left = 9
          Top = 115
          Width = 38
          Height = 16
          Caption = 'COGS'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label6: TLabel
          Left = 9
          Top = 137
          Width = 51
          Height = 16
          Caption = 'Deposits'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter1: TTASNumEnter
          Left = 150
          Top = 25
          Width = 121
          Height = 21
          TabStop = False
          AutoSelect = False
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.AR.BAL   '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter2: TTASNumEnter
          Left = 150
          Top = 47
          Width = 121
          Height = 21
          TabStop = False
          AutoSelect = False
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 1
          FieldName = 'ISBSF.AR.BILL  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object TASNumEnter3: TTASNumEnter
          Left = 150
          Top = 69
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 2
          FieldName = 'ISBSF.AR.RECP  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object TASNumEnter4: TTASNumEnter
          Left = 150
          Top = 91
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 3
          FieldName = 'ISBSF.AR.DISC  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter5: TTASNumEnter
          Left = 150
          Top = 113
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 4
          FieldName = 'ISBSF.AR.COGS  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object TASNumEnter6: TTASNumEnter
          Left = 150
          Top = 135
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 5
          FieldName = 'ISBSF.AR.DEPO  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object ARBillings: TGlyphBtn
          Left = 124
          Top = 47
          Width = 24
          Height = 21
          TabOrder = 6
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object ARReceipts: TGlyphBtn
          Left = 124
          Top = 69
          Width = 24
          Height = 21
          TabOrder = 7
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object ARDiscounts: TGlyphBtn
          Left = 124
          Top = 91
          Width = 24
          Height = 21
          TabOrder = 8
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object ARCogs: TGlyphBtn
          Left = 124
          Top = 113
          Width = 24
          Height = 21
          TabOrder = 9
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object ARDeposits: TGlyphBtn
          Left = 124
          Top = 135
          Width = 24
          Height = 21
          TabOrder = 10
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
      end
      object APBOX: TGroupBox
        Left = 4
        Top = 175
        Width = 280
        Height = 152
        Hint = 'Click to Drill Down to Accounts Payables'
        Caption = 'Accounts Payable'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 1
        object Label7: TLabel
          Left = 9
          Top = 30
          Width = 93
          Height = 16
          Caption = 'Current Balance'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label8: TLabel
          Left = 9
          Top = 50
          Width = 54
          Height = 16
          Caption = 'Payables'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label9: TLabel
          Left = 9
          Top = 72
          Width = 59
          Height = 16
          Caption = 'Payments'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label10: TLabel
          Left = 9
          Top = 94
          Width = 58
          Height = 16
          Caption = 'Discounts'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label11: TLabel
          Left = 9
          Top = 117
          Width = 95
          Height = 16
          Caption = 'Approved to Pay'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter7: TTASNumEnter
          Left = 150
          Top = 27
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.AP.BAL   '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter8: TTASNumEnter
          Left = 150
          Top = 49
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 1
          FieldName = 'ISBSF.AP.PAYA  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object TASNumEnter9: TTASNumEnter
          Left = 150
          Top = 71
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 2
          FieldName = 'ISBSF.AP.PAYM  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object TASNumEnter10: TTASNumEnter
          Left = 150
          Top = 93
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 3
          FieldName = 'ISBSF.AP.DISC  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter11: TTASNumEnter
          Left = 150
          Top = 115
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 4
          FieldName = 'ISBSF.AP.ATP   '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object APPayables: TGlyphBtn
          Left = 124
          Top = 49
          Width = 24
          Height = 21
          TabOrder = 5
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object APPayments: TGlyphBtn
          Left = 124
          Top = 71
          Width = 24
          Height = 21
          TabOrder = 6
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object APDiscounts: TGlyphBtn
          Left = 124
          Top = 93
          Width = 24
          Height = 21
          TabOrder = 7
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object APATP: TGlyphBtn
          Left = 124
          Top = 115
          Width = 24
          Height = 21
          TabOrder = 8
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
      end
      object SOBOX: TGroupBox
        Left = 291
        Top = 10
        Width = 280
        Height = 89
        Hint = 'Click to Drill Down to Sales Orders'
        Caption = 'Sales Orders'
        Ctl3D = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentCtl3D = False
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 2
        object Label12: TLabel
          Left = 9
          Top = 18
          Width = 74
          Height = 16
          Caption = 'Open Orders'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label13: TLabel
          Left = 9
          Top = 39
          Width = 87
          Height = 16
          Caption = 'Booked Orders'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label14: TLabel
          Left = 9
          Top = 60
          Width = 62
          Height = 16
          Caption = 'Shipments'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter12: TTASNumEnter
          Left = 150
          Top = 15
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.SO.OPEN  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter13: TTASNumEnter
          Left = 150
          Top = 37
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 1
          FieldName = 'ISBSF.SO.BOOK  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter14: TTASNumEnter
          Left = 150
          Top = 59
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 2
          FieldName = 'ISBSF.SO.SHIP  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object SOOpen: TGlyphBtn
          Left = 124
          Top = 15
          Width = 24
          Height = 21
          TabOrder = 3
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object SOShipments: TGlyphBtn
          Left = 124
          Top = 59
          Width = 24
          Height = 21
          TabOrder = 4
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object SOBooked: TGlyphBtn
          Left = 124
          Top = 37
          Width = 24
          Height = 21
          TabOrder = 5
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
      end
      object POBOX: TGroupBox
        Left = 292
        Top = 102
        Width = 280
        Height = 89
        Hint = 'Click to Drill Down to Purchase Orders'
        Caption = 'Purchase Orders'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 3
        object Label16: TLabel
          Left = 9
          Top = 18
          Width = 61
          Height = 16
          Caption = 'Open POs'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label17: TLabel
          Left = 9
          Top = 39
          Width = 76
          Height = 16
          Caption = 'Booked PO'#39's'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label18: TLabel
          Left = 9
          Top = 60
          Width = 51
          Height = 16
          Caption = 'Receipts'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter16: TTASNumEnter
          Left = 150
          Top = 15
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.PO.OPEN  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter17: TTASNumEnter
          Left = 150
          Top = 37
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 1
          FieldName = 'ISBSF.PO.BOOK  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter18: TTASNumEnter
          Left = 150
          Top = 59
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 2
          FieldName = 'ISBSF.PO.RECP  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object POOpen: TGlyphBtn
          Left = 124
          Top = 15
          Width = 24
          Height = 21
          TabOrder = 3
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object POBooked: TGlyphBtn
          Left = 124
          Top = 37
          Width = 24
          Height = 21
          TabOrder = 4
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object POReceipts: TGlyphBtn
          Left = 124
          Top = 59
          Width = 24
          Height = 21
          TabOrder = 5
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
      end
      object WOBOX: TGroupBox
        Left = 292
        Top = 193
        Width = 280
        Height = 89
        Hint = 'Click to Drill Down to Work Orders'
        Caption = 'Work Orders'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 4
        object Label15: TLabel
          Left = 9
          Top = 18
          Width = 76
          Height = 16
          Caption = 'WIP Balance'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label19: TLabel
          Left = 9
          Top = 39
          Width = 38
          Height = 16
          Caption = 'Issues'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label20: TLabel
          Left = 9
          Top = 60
          Width = 87
          Height = 16
          Caption = 'FP / Variances'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter15: TTASNumEnter
          Left = 150
          Top = 15
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.WO.WIPBAL'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter19: TTASNumEnter
          Left = 150
          Top = 37
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 1
          FieldName = 'ISBSF.WO.ISSU  '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object TASNumEnter20: TTASNumEnter
          Left = 150
          Top = 59
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 2
          FieldName = 'ISBSF.WO.FPVAR '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          DirectInput = False
          NumGlyphs = 1
          ButtonWidth = 0
        end
        object WOWIPBal: TGlyphBtn
          Left = 124
          Top = 15
          Width = 24
          Height = 21
          TabOrder = 3
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F72F292E433842322732F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7A4A4A1ACA6A55D
            4F5A261C25F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            8582818A8585A9A8A5DEE0DBC8C8C3958A8F675B636D6A69675C64382C37F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7635F5FA4A09DB7B6AFBFBFB8CCCDC6D7D9D2CF
            CFC9DBD8D8E8E7E6AAA5A2675D63F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7585155
            988E90A8A2A0ADACA6838480BEBFB8D0D2CDE2E3DFF2F3F1D7D6D5635F5FF0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F774686FA39B9C453C43F0F3F766666297
            9993C8C9C3DFE1DCD5D1D25E515B221922F0F3F7F0F3F7F0F3F7F0F3F7524750
            81707DA8A3A2645962F0F3F7F0F3F7F0F3F7989993CBCDC6CCCBC7968B905E50
            5B342833F0F3F7F0F3F7F0F3F73B2D3B6C586AAAA3A7988D94281F28F0F3F7F0
            F3F772726DB9BAB2CFD1CAC7C6C2ADA7A6453A44F0F3F7F0F3F7F0F3F7F0F3F7
            423342887D84B5B2AE7A6C76292029F0F3F7F0F3F782827DC1C2BAD2D4CDC7C8
            C1494047F0F3F7F0F3F7F0F3F7F0F3F7F0F3F73C2C3C9B9499B5B3AF9E939971
            656E5F555CA49F9CB3B1ABB9B8B3999995F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F72C202D3123317F747BA59DA3A1999D968A909A9193ACA8A3827C7CF0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F73B2C3B5D485D60
            4D5E61545E8A7D849992927D7979F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7302431483A47F0F3F7564A54595056F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          GlyphKind = bkCustom
        end
        object WOIssues: TGlyphBtn
          Left = 124
          Top = 37
          Width = 24
          Height = 21
          TabOrder = 4
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
        object WOFPVar: TGlyphBtn
          Left = 124
          Top = 59
          Width = 24
          Height = 21
          TabOrder = 5
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
      end
      object INBOX: TGroupBox
        Left = 292
        Top = 284
        Width = 280
        Height = 42
        Hint = 'Click to Drill Down to Inventory'
        Caption = 'Inventory'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 5
        object Label21: TLabel
          Left = 9
          Top = 18
          Width = 88
          Height = 16
          Caption = 'Inventory Value'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter21: TTASNumEnter
          Left = 150
          Top = 13
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.IC.VALUE '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object INVal: TGlyphBtn
          Left = 124
          Top = 13
          Width = 24
          Height = 21
          TabOrder = 1
          Visible = False
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
            C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0
            D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CBD3D6D8DDE0CAD8CF6FA77224842500
            78000078001F82205F9C62ABBCB3C0C7CAC5CDD1C8D0D4C8D0D4C8D0D4CCD4D7
            DDE2E49CC19F0078001AA31F33CE3E45EB574AED5F3ED25024A73000780079A4
            7FBBC2C6C4CCD0C8D0D4C8D0D4DCE1E39EC2A1057E0633D33C40E34D3FD04929
            AD312BAE3549D65957EE724DDD69087F0D74A27BBAC1C5C8D0D4D3D9DCD3E0D6
            00780033D33C3ED8493EC34327A32B80B58080B5802DA8334BCF575AE77556E0
            760078009CB0A5C0C7CBDDE2E477AE791BA42041E44F3EC4453FC146439843FF
            FFFFFFFFFF318F334CCF5A51D66169F48E30AB43449048B7BEC2E7EAEC298729
            34CE4041D14B42C54A1A921EC9DEC9FFFFFFFFFFFFC9DEC920982757DB6861E6
            7B5BDC7E178019B0B7BBEDF0F100780048EC5A43CF4E37B63E80B580FFFFFFFF
            FFFFFFFFFFFFFFFF71AD7149C95963E77D7AFDA9007800ABB2B6EDF0F1007800
            4DEE6243CC50228B23F2F7F2FFFFFFFFFFFFFFFFFFFFFFFFF2F7F2258F2964E5
            7F80FDB0007800ABB2B6E7EAEC29872940D35436BB45ADCEADFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFADCEAD52C96D70E69A178019B0B7BBDDE2E477AE79
            27A73353E56F1A91201B91201D9323FFFFFFFFFFFF239A2D249A2E259A307CEE
            A93DAD534F9353B7BEC2D3D9DCD3E0D600780051DE6D5EE97A57DC691D9323FF
            FFFFFFFFFF1D932373FA9084FCAE77E7A20078009CB0A5C0C7CBC8D0D4DCE1E3
            9EC2A10A7F0D5AE17A6EF6941D93231D93231D93231D93238BFDBA79E7A30D80
            1374A27BBAC1C5C8D0D4C8D0D4CCD4D7DDE2E49CC19F00780033AB465FDD827F
            FDAD85FDB56CDE933EAD5400780079A47FBBC2C6C8D0D4C8D0D4C8D0D4C8D0D4
            CBD3D6D8DDE0CAD8CF6FA7722484250078000078001F8220529655ABBCB3C0C7
            CAC5CDD1C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CED4D8D3D9DCD5DADCD4
            D8DBCFD4D6C9CFD2C5CCCFC4CCD0C8D0D4C8D0D4C8D0D4C8D0D4}
          GlyphKind = bkCustom
        end
      end
      object RefreshPan: TPanel
        Left = 178
        Top = 156
        Width = 240
        Height = 72
        TabOrder = 6
        Visible = False
        object BSCAP: TLabel
          Left = 56
          Top = 28
          Width = 175
          Height = 16
          AutoSize = False
          Caption = 'Initializing...'
        end
        object Animate14: TAnimate
          Left = 16
          Top = 20
          Width = 32
          Height = 32
          Active = True
          FileName = 'EvoBS.avi'
          StopFrame = 16
        end
      end
      object CASHBOX: TGroupBox
        Left = 293
        Top = 327
        Width = 280
        Height = 42
        Caption = 'Cash'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 7
        object Label22: TLabel
          Left = 9
          Top = 18
          Width = 47
          Height = 16
          Caption = 'Balance'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object TASNumEnter22: TTASNumEnter
          Left = 150
          Top = 13
          Width = 121
          Height = 21
          AutoSize = False
          Ctl3D = False
          ParentCtl3D = False
          ReadOnly = True
          TabOrder = 0
          FieldName = 'ISBSF.CASH.TOTA'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object Cash: TGlyphBtn
          Left = 124
          Top = 13
          Width = 24
          Height = 21
          TabOrder = 1
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000FFFFFFFFFFFF
            FFFFFF7BB37EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF94C39760A5656AAD6E4D9751DBEADCFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            7CBA81B6DEBA66AB6B74B5794D975082B685AACDACFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFAAD2AD9BCD9F6EB1728CC791A9DCAE75B57A50
            9A5476B67A66A669FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7ABA7F
            76B67B90CB96AADEB09BD7A1A9DDAF76B67B5FAB64ADD8B18AC3907CB27F96C1
            98FFFFFFFFFFFFFFFFFFAED4B17EBC8396CE9BACDFB26EB27395D59C9CD8A2A9
            DDAF77B77B71B975C2E7C8B1DAB46CB871559D58AACCACFFFFFF7ABA7F8DC892
            AEDFB4A0DAA697D79E96D69D7DBF8281C086AADDAF78B87C62AD66C3E7C8C0E4
            C3B8E0BD4E9952FFFFFFC6E4C97CBA818EC893AFE0B5A1DAA77EC084A3D0A6DD
            EEDF7FB782AADEB079B87E559E59C3E7C877B77BA2C9A4FFFFFFFFFFFFFFFFFF
            7EBC838FC994AFE0B584C189F7FCF894C196DDEEDF81C186AADEB07AB97E579F
            5B58A05CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF81BE8690CA95B0E0B5D9F3DDF7
            FCF8A3D0A67DBF839ED9A4ABDEB17ABA7F579F5BFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFF83BF8891CB96B0E1B584C2897FC08498D79F97D79E9ED9A4ABDF
            B17CBA805CA260FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF84C08992CC97B0
            E1B6A2DBA89AD8A172B376AEDFB386C28B64A968FFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFF85C18A93CC98B1E2B6A2DCA9AFE0B58BC5916DB0
            72FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF86
            C28B93CD99B2E2B692CB9776B67BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF87C38D95CD9A7FBD84FFFFFFFFFF
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            FFFFFFFFFF89C48EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
          GlyphKind = bkCustom
        end
      end
      object GroupBox8: TGroupBox
        Left = 5
        Top = 327
        Width = 280
        Height = 42
        Caption = 'Period'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 8
        object Label23: TLabel
          Left = 9
          Top = 18
          Width = 63
          Height = 16
          Caption = 'Start Date:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label24: TLabel
          Left = 160
          Top = 18
          Width = 27
          Height = 16
          Caption = 'End:'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object startdate: TLabel
          Left = 89
          Top = 18
          Width = 56
          Height = 18
          Caption = '01/01/06'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -15
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object enddate: TLabel
          Left = 207
          Top = 18
          Width = 56
          Height = 18
          Caption = '01/01/06'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -15
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
    end
    object BCharts: TTabSheet
      Caption = 'Bar Charts'
      object BarChart: TBarChart
        Left = -1
        Top = 0
        Width = 579
        Height = 341
        XCaption = '01/01/01    02/02/02     03/03/03'
        XAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
        YAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
        Options = []
        WallColor = clWhite
        XGridColor = clBtnShadow
        YGridColor = clBtnShadow
        Percent3D = 25
        YInitValue.Enabled = True
        XLabelPos = xlLeft
        HintOptions = [hoSeries, hoPoint, hoValue, hoPercent, hoFocus]
        SaveToBitmapBool = False
        BitmapImageH = 0
        BitmapImageW = 0
        BitmapImageB = 0
        SeriesColor1 = clBlack
        SeriesColor2 = clRed
        SeriesColor3 = clLime
        SeriesColor4 = clAqua
        SeriesColor5 = clYellow
        SeriesColor6 = clFuchsia
        SeriesColor7 = clBlack
        SeriesColor8 = clBlack
        SeriesColor9 = clBlack
        SeriesColor10 = clBlack
        SeriesColor11 = clBlack
        SeriesColor12 = clBlack
        SeriesColor13 = clBlack
        SeriesColor14 = clBlack
        SeriesColor15 = clBlack
        SeriesColor16 = clBlack
        SeriesColor17 = clBlack
        SeriesColor18 = clBlack
        SeriesColor19 = clBlack
        SeriesColor20 = clBlack
        SeriesColor21 = clBlack
        SeriesColor22 = clBlack
        SeriesColor23 = clBlack
        SeriesColor24 = clBlack
        SeriesColor25 = clBlack
        SeriesColor26 = clBlack
        SeriesColor27 = clBlack
        SeriesColor28 = clBlack
        SeriesColor29 = clBlack
        SeriesColor30 = clBlack
        SeriesColor31 = clBlack
        SeriesColor32 = clBlack
        SeriesColor33 = clBlack
        SeriesColor34 = clBlack
        SeriesColor35 = clBlack
        SeriesColor36 = clBlack
        BarStyle1 = bsBar
        BarStyle2 = bsBar
        BarStyle3 = bsBar
        BarStyle4 = bsBar
        BarStyle5 = bsBar
        BarStyle6 = bsBar
        BarStyle7 = bsBar
        BarStyle8 = bsBar
        BarStyle9 = bsBar
        BarStyle10 = bsBar
        BarStyle11 = bsBar
        BarStyle12 = bsBar
        BarStyle13 = bsBar
        BarStyle14 = bsBar
        BarStyle15 = bsBar
        BarStyle16 = bsBar
        BarStyle17 = bsBar
        BarStyle18 = bsBar
        BarStyle19 = bsBar
        BarStyle20 = bsBar
        BarStyle21 = bsBar
        BarStyle22 = bsBar
        BarStyle23 = bsBar
        BarStyle24 = bsBar
        BarStyle25 = bsBar
        BarStyle26 = bsBar
        BarStyle27 = bsBar
        BarStyle28 = bsBar
        BarStyle29 = bsBar
        BarStyle30 = bsBar
        BarStyle31 = bsBar
        BarStyle32 = bsBar
        BarStyle33 = bsBar
        BarStyle34 = bsBar
        BarStyle35 = bsBar
        BarStyle36 = bsBar
        NSeries = 5
        NPoint = 3
        BorderWidth = 15
        ForeColor = clWindowText
        BackColor = clWhite
        Legend.Alignment = laBottom
        Legend.Color = clWindow
        Legend.Frame = False
        Legend.Visible = True
        Legend.MaxWidth = 50
        AntiAlias = aaLo
        ValueFormat = Currency
        ParentShowHint = False
        ShowHint = True
      end
      object PrintBar: TGlyphBtn
        Left = 499
        Top = 346
        Width = 75
        Height = 25
Caption = '&Print'       
        TabOrder = 0
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
          FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
          99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
          ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
          666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
          A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
          8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
          EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
          BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
          E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
          E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
          CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
          F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
          C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
          CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
          C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
          DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
          EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
          B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
        GlyphKind = bkCustom
      end
    end
    object PCharts: TTabSheet
      Caption = 'Pie Charts'
      object PieChart: TPieChart
        Left = 2
        Top = 1
        Width = 574
        Height = 338
        Options = []
        Exploded = True
        PercentExplode = 30
        HintOptions = [hoSeries, hoPoint, hoValue, hoPercent, hoFocus]
        BitmapImageH = 0
        BitmapImageW = 0
        BitmapImageB = 0
        SeriesColor1 = clBlack
        SeriesColor2 = clBlack
        SeriesColor3 = clBlack
        SeriesColor4 = clBlack
        SeriesColor5 = clBlack
        SeriesColor6 = clBlack
        SeriesColor7 = clBlack
        SeriesColor8 = clBlack
        SeriesColor9 = clBlack
        SeriesColor10 = clBlack
        SeriesColor11 = clBlack
        SeriesColor12 = clBlack
        SeriesColor13 = clBlack
        SeriesColor14 = clBlack
        SeriesColor15 = clBlack
        SeriesColor16 = clBlack
        SeriesColor17 = clBlack
        SeriesColor18 = clBlack
        SeriesColor19 = clBlack
        SeriesColor20 = clBlack
        SeriesColor21 = clBlack
        SeriesColor22 = clBlack
        SeriesColor23 = clBlack
        SeriesColor24 = clBlack
        SeriesColor25 = clBlack
        SeriesColor26 = clBlack
        SeriesColor27 = clBlack
        SeriesColor28 = clBlack
        SeriesColor29 = clBlack
        SeriesColor30 = clBlack
        SeriesColor31 = clBlack
        SeriesColor32 = clBlack
        SeriesColor33 = clBlack
        SeriesColor34 = clBlack
        SeriesColor35 = clBlack
        SeriesColor36 = clBlack
        NSeries = 5
        NPoint = 1
        BorderWidth = 15
        ForeColor = clWindowText
        BackColor = clWhite
        Legend.Alignment = laBottom
        Legend.Color = clWindow
        Legend.Frame = False
        Legend.Visible = True
        Legend.MaxWidth = 50
        AntiAlias = aaLo
        ValueFormat = None
        ParentShowHint = False
        ShowHint = True
      end
      object PrintPie: TGlyphBtn
        Left = 499
        Top = 346
        Width = 75
        Height = 25
Caption = '&Print'       
        TabOrder = 0
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
          FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
          99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
          ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
          666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
          A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
          8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
          EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
          BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
          E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
          E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
          CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
          F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
          C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
          CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
          C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
          DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
          EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
          B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
        GlyphKind = bkCustom
      end
      object PAR: TButton
        Left = 5
        Top = 346
        Width = 27
        Height = 25
        Caption = 'AR'
        TabOrder = 1
      end
      object PAP: TButton
        Left = 35
        Top = 346
        Width = 27
        Height = 25
        Caption = 'AP'
        TabOrder = 2
      end
      object PSO: TButton
        Left = 65
        Top = 346
        Width = 27
        Height = 25
        Caption = 'SO'
        TabOrder = 3
      end
      object PPO: TButton
        Left = 95
        Top = 346
        Width = 27
        Height = 25
        Caption = 'PO'
        TabOrder = 4
      end
      object PWO: TButton
        Left = 125
        Top = 346
        Width = 27
        Height = 25
        Caption = 'WO'
        TabOrder = 5
      end
      object PCash: TButton
        Left = 155
        Top = 346
        Width = 36
        Height = 25
        Caption = 'Cash'
        TabOrder = 6
      end
    end
    object LCharts: TTabSheet
      Caption = 'Line Charts'
      object LineChart: TLineChart
        Left = 1
        Top = 1
        Width = 575
        Height = 334
        NSeries = 1
        NPoint = 12
        BorderWidth = 15
        ForeColor = clWindowText
        BackColor = clWhite
        Legend.Alignment = laBottom
        Legend.Color = clWindow
        Legend.Frame = False
        Legend.Visible = True
        Legend.MaxWidth = 50
        AntiAlias = aaLo
        BitmapImageH = 0
        BitmapImageW = 0
        BitmapImageB = 0
        SeriesColor1 = clBlue
        SeriesColor2 = clRed
        SeriesColor3 = clLime
        SeriesColor4 = clAqua
        SeriesColor5 = clYellow
        SeriesColor6 = clBlack
        SeriesColor7 = clBlack
        SeriesColor8 = clBlack
        SeriesColor9 = clBlack
        SeriesColor10 = clBlack
        SeriesColor11 = clBlack
        SeriesColor12 = clBlack
        SeriesColor13 = clBlack
        SeriesColor14 = clBlack
        SeriesColor15 = clBlack
        SeriesColor16 = clBlack
        SeriesColor17 = clBlack
        SeriesColor18 = clBlack
        SeriesColor19 = clBlack
        SeriesColor20 = clBlack
        SeriesColor21 = clBlack
        SeriesColor22 = clBlack
        SeriesColor23 = clBlack
        SeriesColor24 = clBlack
        SeriesColor25 = clBlack
        SeriesColor26 = clBlack
        SeriesColor27 = clBlack
        SeriesColor28 = clBlack
        SeriesColor29 = clBlack
        SeriesColor30 = clBlack
        SeriesColor31 = clBlack
        SeriesColor32 = clBlack
        SeriesColor33 = clBlack
        SeriesColor34 = clBlack
        SeriesColor35 = clBlack
        SeriesColor36 = clBlack
        BarStyle1 = bsBar
        BarStyle2 = bsBar
        BarStyle3 = bsBar
        BarStyle4 = bsBar
        BarStyle5 = bsBar
        BarStyle6 = bsBar
        BarStyle7 = bsBar
        BarStyle8 = bsBar
        BarStyle9 = bsBar
        BarStyle10 = bsBar
        BarStyle11 = bsBar
        BarStyle12 = bsBar
        BarStyle13 = bsBar
        BarStyle14 = bsBar
        BarStyle15 = bsBar
        BarStyle16 = bsBar
        BarStyle17 = bsBar
        BarStyle18 = bsBar
        BarStyle19 = bsBar
        BarStyle20 = bsBar
        BarStyle21 = bsBar
        BarStyle22 = bsBar
        BarStyle23 = bsBar
        BarStyle24 = bsBar
        BarStyle25 = bsBar
        BarStyle26 = bsBar
        BarStyle27 = bsBar
        BarStyle28 = bsBar
        BarStyle29 = bsBar
        BarStyle30 = bsBar
        BarStyle31 = bsBar
        BarStyle32 = bsBar
        BarStyle33 = bsBar
        BarStyle34 = bsBar
        BarStyle35 = bsBar
        BarStyle36 = bsBar
        ChartKind1 = ncLine
        ChartKind2 = ncLine
        ChartKind3 = ncLine
        ChartKind4 = ncLine
        ChartKind5 = ncLine
        ChartKind6 = ncLine
        ChartKind7 = ncLine
        ChartKind8 = ncLine
        ChartKind9 = ncLine
        ChartKind10 = ncLine
        ChartKind11 = ncLine
        ChartKind12 = ncLine
        ChartKind13 = ncLine
        ChartKind14 = ncLine
        ChartKind15 = ncLine
        ChartKind16 = ncLine
        ChartKind17 = ncLine
        ChartKind18 = ncLine
        ChartKind19 = ncLine
        ChartKind20 = ncLine
        ChartKind21 = ncLine
        ChartKind22 = ncLine
        ChartKind23 = ncLine
        ChartKind24 = ncLine
        ChartKind25 = ncLine
        ChartKind26 = ncLine
        ChartKind27 = ncLine
        ChartKind28 = ncLine
        ChartKind29 = ncLine
        ChartKind30 = ncLine
        ChartKind31 = ncLine
        ChartKind32 = ncLine
        ChartKind33 = ncLine
        ChartKind34 = ncLine
        ChartKind35 = ncLine
        ChartKind36 = ncLine
        XAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
        YLeftAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
        YRightAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
        Options = [coRotateXLabel]
        WallColor = clWhite
        XGridColor = clBtnShadow
        YLeftGridColor = clBtnShadow
        YRightGridColor = clBtnShadow
        Percent3D = 25
        NVisiblePoint = 12
        LeftVisiblePoint = 1
        HintOptions = [hoSeries, hoPoint, hoValue, hoPercent, hoFocus]
      end
      object PrintLine: TGlyphBtn
        Left = 499
        Top = 346
        Width = 75
        Height = 25
Caption = '&Print'       
        TabOrder = 0
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
          FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
          99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
          ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
          666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
          A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
          8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
          EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
          BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
          E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
          E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
          CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
          F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
          C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
          CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
          C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
          DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
          EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
          B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
        GlyphKind = bkCustom
      end
      object LAR: TButton
        Left = 5
        Top = 346
        Width = 27
        Height = 25
        Caption = 'AR'
        TabOrder = 1
      end
      object LAP: TButton
        Left = 35
        Top = 346
        Width = 27
        Height = 25
        Caption = 'AP'
        TabOrder = 2
      end
      object months12: TTASRadioButton
        Left = 321
        Top = 350
        Width = 85
        Height = 17
        Caption = '12 months'
        Checked = True
        TabOrder = 3
        TabStop = True
        FieldName = 'months12'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object months24: TTASRadioButton
        Left = 410
        Top = 350
        Width = 85
        Height = 17
        Caption = '24 months'
        TabOrder = 4
        FieldName = 'months24'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object LSO: TButton
        Left = 65
        Top = 346
        Width = 27
        Height = 25
        Caption = 'SO'
        TabOrder = 5
      end
      object LPO: TButton
        Left = 95
        Top = 346
        Width = 27
        Height = 25
        Caption = 'PO'
        TabOrder = 6
      end
      object LWO: TButton
        Left = 125
        Top = 346
        Width = 27
        Height = 25
        Caption = 'WO'
        TabOrder = 7
      end
      object LIC: TButton
        Left = 155
        Top = 346
        Width = 27
        Height = 25
        Caption = 'Inv'
        TabOrder = 8
      end
      object LCASH: TButton
        Left = 185
        Top = 346
        Width = 36
        Height = 25
        Caption = 'Cash'
        TabOrder = 9
      end
    end
  end
  object Exit: TGlyphBtn
    Left = 512
    Top = 412
    Width = 75
    Height = 25
Caption = 'E&xit '  
    TabOrder = 1
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
      DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
      E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
      19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
      5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
      EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
      43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
      707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
      D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
      6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
      7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
      D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
      FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
      8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
      D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
      F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
      91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
      DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
      77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
      8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
      EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
      90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
      3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
      AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
      BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
    GlyphKind = bkCustom
  end
  object Refresh: TGlyphBtn
    Left = 435
    Top = 412
    Width = 75
    Height = 25
    Caption = 'Refresh'
    TabOrder = 2
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000CD895CBAB9B6
      B9C1C5BEC6CAC0ADA0C58960CA753BCD6F30C5895FC09D84B5BDC0BBC2C6C3CB
      CFC8D0D4C8D0D4C8D0D4D76312D0702EBEA38FCF6F2DE38939F0B666F9D382F9
      D483F3BD6DE48D3DCE7538B8B6B3BAC2C5C4CBCFC8D0D4C8D0D4DC701FF2BB6B
      DD7625F8CF7EFEDD88FBCB6FF6C061F2BB5DEEBB61F3CC7AF2BA68D17634B8B6
      B4BDC4C8C6CED2C8D0D4DC701FFFEB9EFFE99DFED77AFDCC6BFAC767F7C466F4
      C66DF3CB78F1C875F3CF7DEDAB5AC88253B6BEC1C4CBCFC8D0D4DC701FFEE28D
      FED779FDD170FCCF6FFBD882F7CD7CEAA050E28231E07C2BE69342F3BE6BDC70
      1FBAB1A9C0C7CBC7CFD3DC701FFDE38DFDD575FCD375FDE496ECA453CE7639C3
      987AC6BDB6C28E6AC4692CD0681DE07C2BC59472BEC6CAC6CED2DC701FFDEBA0
      FDE799FDE596FDE99FF1BA6AD0702EBBBAB7BFC7CAC4CBCFC29C81C19D7BCF67
      1ECD7D47C2CACEC4CCD0D56416DC701FDC701FDC701FDC701FDC701FD76312CC
      9168C0C8CCB8BFC3B8B6B3B8B1A8BAAFA3BCA89AB5BDC0B9C0C4C8D0D4C5C0BB
      BFBBB4BEB7AFC4C6C5C8D0D4C8D0D4CBA991CF7233CD6F31CC6E2FCC6E2FCC6E
      2FCC6E2FCA753BB5BDC0C8D0D4CD7F4ACA7537B99472BDA08BC4CBCFC6CED2C8
      B7ABD35D0DE9A154F3C57AF3C77DF3C980F3CA82D45600B5BDC0C8D0D4CD9169
      D45600C8661FBB652BBB9A84B9C1C5BCBAB8C97D49DC701FFDE79AFAD37AF9D1
      72FDE698D45600B5BDC0C8D0D4CAB9ACD76312E28636D05300CD5200CD6F30D6
      5C0AE69446F8D485FCD883FBCB6AFBD071FDE495D45600B5BDC0C8D0D4C8D0D4
      D07435EDB060F4CC7AEEB667F3C374FAD786FBD37EFCCA6DFDC564FECF71FEE7
      9AFDE89BD45600B5BDC0C8D0D4C8D0D4CAB9ACD76312F3C676EDB860EEAF52F3
      B454F8BA59FDC261FFD57BFDE191E59346F4C679D45600B5BDC0C8D0D4C8D0D4
      C8D0D4CCA285D66A1EEEAE5EF7CE7AF9D17CFCD782F8CB7AEAA051D76312CD81
      4DD65C0AD45600BAC2C5C8D0D4C8D0D4C8D0D4C8D0D4C9C1BACF834FD2651AD4
      5600D45600D2651ACD895CC8BFB8C8D0D4CCA285D35D0DC5CDD1}
    GlyphKind = bkCustom
  end
  object next: TGlyphBtn
    Left = 90
    Top = 412
    Width = 75
    Height = 25
    Caption = '&Next'
    ModalResult = 5
    TabOrder = 3
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8BBC0C4999D9E76787962
      6261626261757777919596B1B8BAF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8B7BABC97979591908D9F9D9AA5A3A19C9A988583816262616B6D6D9CA0
      A2F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8C4C7C8B4B3B0BFBCB8D4D0CCE3DFDBE8
      E3DFE5E1DCD7D3D0B8B5B28583815F605F9CA0A2F8F8F8F8F8F8F8F8F8CCD2D4
      D3D2CFD9D5D1E5E1DCEDE8E3EFEBE6F0EBE7F0EBE7EFEBE6E7E3DFCBC6C38C8A
      886B6D6DB3B8BCF8F8F8F8F8F8DBDDDDEFEAE5ECE7E3EFEAE5D3C1B4DFD3CAF0
      EBE7F0EBE7F0EBE7EFEBE6E8E3DFC0BCB97B7A79949899F8F8F8F8F8F8E6E5E3
      F0ECE7F0EBE7EFEBE6BAA190B89D89CAB4A6EBE3DEF0EBE7F0EBE7EFEBE6DBD7
      D49D9B99828384F8F8F8F8F8F8EFEBE8F1EDE8F0EBE7F0EBE7AE9989AA8971B6
      9985BDA493D4C4B8F0EBE7F0EBE7E8E3DFB7B4B081807FF8F8F8F8F8F8EFEBE8
      F1EDEAF0EBE7F0EBE7AE9989A68570AC8A73AE8D76B2927DC9B3A4F0EBE7EEE9
      E4C8C3C092918EF8F8F8F8F8F8E7E7E6F1EFEBF0ECE8F0EBE7AE9989A4846EA0
      816D9A806ED0C4BAF0EBE7F0EBE7EFEBE6CCC8C4A9A9A8F8F8F8F8F8F8DCDFE0
      F2EFEDF1EEEAF0EBE7A79385907665BCACA0F0EBE7F0EBE7F0EBE7F0EBE7EEE9
      E4CECAC5BCC0C0F8F8F8F8F8F8D0D6D8EBEBEAF2EFECF1EDE9D7CCC4EBE6E0F0
      EBE7F0EBE7F0EBE7F0EBE7F0EBE7F0EBE7D4D3D0C9CFD0F8F8F8F8F8F8F8F8F8
      D9DCDFEFEFEEF2EFEDF1EEEBF0ECE8F0ECE7F0EBE7F0ECE7F0ECE8F1EDE9EEEB
      E6D6D8D9F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8D9DCDFEBEBEBF2F0EFF2EFEDF1
      EFEBF1EFEBF1EEEBF1EEEBEAE9E6D8DBDCF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8D0D6D9DCE0E2E7E9E8EFEFECEFEEEBE7E7E7DCDFDFD0D6D8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
    Layout = blGlyphRight
    GlyphKind = bkCustom
  end
  object Prev: TGlyphBtn
    Left = 14
    Top = 412
    Width = 75
    Height = 25
    Caption = '&Previous'
    TabOrder = 4
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8B1B8BA91959675777762
      6261626261767879999D9EBBC0C4F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F89CA0A26B6D6D6262618583819C9A98A5A3A19F9D9A91908D979795B7BA
      BCF8F8F8F8F8F8F8F8F8F8F8F8F8F8F89CA0A25F605F858381B8B5B2D7D3D0E5
      E1DCE8E3DFE3DFDBD4D0CCBFBCB8B4B3B0C4C7C8F8F8F8F8F8F8F8F8F8B3B8BC
      6B6D6D8C8A88CBC6C3E7E3DFEFEBE6F0EBE7F0EBE7EFEBE6EDE8E3E5E1DCD9D5
      D1D3D2CFCCD2D4F8F8F8F8F8F89498997B7A79C0BCB9E8E3DFEFEBE6F0EBE7F0
      EBE7F0EBE7DFD3CAD3C1B4EFEAE5ECE7E3EFEAE5DBDDDDF8F8F8F8F8F8828384
      9D9B99DBD7D4EFEBE6F0EBE7F0EBE7EBE3DECAB4A6B89D89BAA190EFEBE6F0EB
      E7F0ECE7E6E5E3F8F8F8F8F8F881807FB7B4B0E8E3DFF0EBE7F0EBE7D4C4B8BD
      A493B69985AA8971AE9989F0EBE7F0EBE7F1EDE8EFEBE8F8F8F8F8F8F892918E
      C8C3C0EEE9E4F0EBE7C9B3A4B2927DAE8D76AC8A73A68570AE9989F0EBE7F0EB
      E7F1EDEAEFEBE8F8F8F8F8F8F8A9A9A8CCC8C4EFEBE6F0EBE7F0EBE7D0C4BA9A
      806EA0816DA4846EAE9989F0EBE7F0ECE8F1EFEBE7E7E6F8F8F8F8F8F8BCC0C0
      CECAC5EEE9E4F0EBE7F0EBE7F0EBE7F0EBE7BCACA0907665A79385F0EBE7F1EE
      EAF2EFEDDCDFE0F8F8F8F8F8F8C9CFD0D4D3D0F0EBE7F0EBE7F0EBE7F0EBE7F0
      EBE7F0EBE7EBE6E0D7CCC4F1EDE9F2EFECEBEBEAD0D6D8F8F8F8F8F8F8F8F8F8
      D6D8D9EEEBE6F1EDE9F0ECE8F0ECE7F0EBE7F0ECE7F0ECE8F1EEEBF2EFEDEFEF
      EED9DCDFF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8D8DBDCEAE9E6F1EEEBF1EEEBF1
      EFEBF1EFEBF2EFEDF2F0EFEBEBEBD9DCDFF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8D0D6D8DCDFDFE7E7E7EFEEEBEFEFECE7E9E8DCE0E2D0D6D9F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
    GlyphKind = bkCustom
  end
end
