object EditForm8: TEditForm8
  Left = 278
  Top = 201
  Hint = 'C:\TASPRO7\DBA7\T6ISINBLNK.DFM'
  AutoScroll = False
  Caption = ' Item Links'
  ClientHeight = 355
  ClientWidth = 630
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  No_Refresh = False
  OnStart = 'LINKOnStart'
  ScreenPos = tpDesktopCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T6ISINB'
  RememberSize = True
  RememberSizeDate = 38870.123391643520000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 630
    Height = 328
    TabOrder = 0
    object Label1: TLabel
      Left = 28
      Top = 10
      Width = 74
      Height = 16
      Caption = 'Item Number'
    end
    object Label2: TLabel
      Left = 28
      Top = 34
      Width = 65
      Height = 16
      Caption = 'Description'
    end
    object Label3: TLabel
      Left = 416
      Top = 10
      Width = 28
      Height = 16
      Caption = 'Type'
    end
    object LinkPanel: TPanel
      Left = 7
      Top = 81
      Width = 618
      Height = 218
      TabOrder = 4
      object Label71: TLabel
        Left = 18
        Top = 13
        Width = 32
        Height = 16
        Caption = 'Order'
      end
      object Label72: TLabel
        Left = 18
        Top = 40
        Width = 24
        Height = 16
        Caption = 'Link'
      end
      object Label73: TLabel
        Left = 18
        Top = 77
        Width = 102
        Height = 16
        Caption = 'Use Global Path?'
      end
      object Label74: TLabel
        Left = 18
        Top = 102
        Width = 141
        Height = 16
        Caption = 'Use f&ile Associations or '
      end
      object Label75: TLabel
        Left = 160
        Top = 102
        Width = 39
        Height = 16
        Caption = '&Other?'
      end
      object Label76: TLabel
        Left = 245
        Top = 102
        Width = 36
        Height = 16
        Caption = 'Other '
      end
      object Bevel1: TBevel
        Left = 5
        Top = 122
        Width = 605
        Height = 11
        Shape = bsBottomLine
      end
      object Label77: TLabel
        Left = 6
        Top = 135
        Width = 44
        Height = 16
        Caption = 'Printing'
      end
      object Label78: TLabel
        Left = 59
        Top = 159
        Width = 117
        Height = 16
        Caption = 'Image &Thumbnail or '
      end
      object Label79: TLabel
        Left = 17
        Top = 187
        Width = 69
        Height = 16
        Caption = 'For &Parent, '
      end
      object Label80: TLabel
        Left = 177
        Top = 159
        Width = 24
        Height = 16
        Caption = '&Link'
      end
      object Label81: TLabel
        Left = 86
        Top = 187
        Width = 85
        Height = 16
        Caption = '&Component, or'
      end
      object Label82: TLabel
        Left = 176
        Top = 187
        Width = 27
        Height = 16
        Caption = '&Both'
      end
      object Label83: TLabel
        Left = 215
        Top = 134
        Width = 18
        Height = 16
        Caption = 'Tra'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label84: TLabel
        Left = 250
        Top = 134
        Width = 20
        Height = 16
        Caption = 'Est'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label85: TLabel
        Left = 285
        Top = 134
        Width = 23
        Height = 16
        Caption = 'PO '
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label86: TLabel
        Left = 320
        Top = 134
        Width = 27
        Height = 16
        Caption = 'RFQ'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label87: TLabel
        Left = 355
        Top = 134
        Width = 24
        Height = 16
        Caption = 'Quo'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label88: TLabel
        Left = 390
        Top = 134
        Width = 23
        Height = 16
        Caption = 'Ack'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label89: TLabel
        Left = 425
        Top = 134
        Width = 15
        Height = 16
        Caption = 'Inv'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label90: TLabel
        Left = 460
        Top = 134
        Width = 23
        Height = 16
        Caption = 'Pck'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label91: TLabel
        Left = 495
        Top = 134
        Width = 22
        Height = 16
        Caption = 'SOl'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object Label92: TLabel
        Left = 530
        Top = 134
        Width = 15
        Height = 16
        Caption = 'INl'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = [fsUnderline]
        ParentFont = False
      end
      object TASNumEnter12: TTASNumEnter
        Left = 74
        Top = 11
        Width = 40
        Height = 21
        AutoSize = False
        DecimalPlaces = 0
        DisplayFormat = ',0;-,0'
        TabOrder = 0
        FieldName = 'I.ORDER'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object LinkFile: TTASComboEnter
        Left = 74
        Top = 38
        Width = 528
        Height = 21
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
          F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7BEC8
          D2203040B9C0C8F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
          F3F7F0F3F7F0F3F7F0F3F7BEC8D23050604078C0304860BEC8CDF0F3F7F0F3F7
          F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7BEC8D23050703080
          D04098E050B0F050687070889070788060707050606040505030384030384040
          485050505050505050586040709040A0E060C8FF7090A0D2D9DC708890A0E0F0
          70D0F050B8E030B0E030A0C0708080B0A8A0D0C0B0D0B0A08078705058506090
          B07098B0405060F0F3F7808890B0E8F090E8FF80E0FF70D8FF80A0B0C0B8B0FF
          F0E0FFE8E0F0D8C0F0D0B08078704070905080A0202830F0F3F78090A0B0E8F0
          A0E8FF90E8FF80E0FF909090F0E8E0FFF8F0FFF0F0FFE8E0F0D8D0D0B0A05060
          601080B0303840F0F3F78090A0B0F0FFB0F0FFA0E8FF90E0FF909890F0E8E0FF
          FFFFFFF8F0FFF0F0FFE8E0E0C0B05068701080B0404050F0F3F78098A0C0F0FF
          B0F0F0A0F0FFA0E8FF90B8C0C0C0C0FFFFFFFFFFFFFFF8F0FFF0E0B0A0905080
          A01088C0505060F0F3F78098A0C0F0FFB0F0FFB0F0FFA0E8FF90E0F0A0B0B0C0
          C0C0F0E8E0F0E8E0B0B0A070809040A8E01090C0506070F0F3F790A0A0C0F0FF
          B0F0FFB0F0FFB0F0F0A0F0FF90E0F090B8C090989090909070A0B050B8E050B8
          F02098D0607080F0F3F790A0B0C0F0FFC0F0FFC0F0FFC0F0FFB0F0FFB0F0FFA0
          E8FF90E8FF90E0FF80D8FF70D0FF70C8F060C0F0607080F0F3F790A0B090A0B0
          90A0B090A0B090A0B090A0B090A0A09098A08098A08098A08098A08098A08098
          A08098A0C9D2D5F0F3F790A8B0B0E8F0B0F0FFB0F0FFB0F0F090E0F090A0B0BF
          D3D7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7E4F1F690A8B0
          90A8B090A8B090A8B090A8B0E3E9EBF0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
          F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
          F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
        NumGlyphs = 1
        TabOrder = 1
        Text = 'LinkFile'
        FieldName = 'I.LINK'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = -1
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object TASENTER5: TTASENTER
        Left = 205
        Top = 100
        Width = 20
        Height = 24
        TabOrder = 3
        FieldName = 'I.OTHER'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER29: TTASENTER
        Left = 284
        Top = 100
        Width = 111
        Height = 24
        TabOrder = 4
        FieldName = 'I.ILOLINK'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER30: TTASENTER
        Left = 205
        Top = 75
        Width = 20
        Height = 24
        TabOrder = 2
        FieldName = 'I.GPATH'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER31: TTASENTER
        Left = 215
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 5
        FieldName = 'IMAGE.TL[1]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER32: TTASENTER
        Left = 250
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 6
        FieldName = 'IMAGE.TL[2]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER33: TTASENTER
        Left = 320
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 8
        FieldName = 'IMAGE.TL[4]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER34: TTASENTER
        Left = 285
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 7
        FieldName = 'IMAGE.TL[3]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER35: TTASENTER
        Left = 355
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 9
        FieldName = 'IMAGE.TL[5]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER36: TTASENTER
        Left = 390
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 10
        FieldName = 'IMAGE.TL[6]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER37: TTASENTER
        Left = 425
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 11
        FieldName = 'IMAGE.TL[7]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER38: TTASENTER
        Left = 460
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 12
        FieldName = 'IMAGE.TL[8]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER39: TTASENTER
        Left = 495
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 13
        FieldName = 'IMAGE.TL[9]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER40: TTASENTER
        Left = 530
        Top = 157
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 14
        FieldName = 'IMAGE.TL[10]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'TL'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER41: TTASENTER
        Left = 215
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 15
        FieldName = 'IMAGE.PCB[1]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER42: TTASENTER
        Left = 250
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 16
        FieldName = 'IMAGE.PCB[2]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER43: TTASENTER
        Left = 285
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 17
        FieldName = 'IMAGE.PCB[3]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER44: TTASENTER
        Left = 320
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 18
        FieldName = 'IMAGE.PCB[4]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER45: TTASENTER
        Left = 355
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 19
        FieldName = 'IMAGE.PCB[5]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER46: TTASENTER
        Left = 390
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 20
        FieldName = 'IMAGE.PCB[6]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER47: TTASENTER
        Left = 425
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 21
        FieldName = 'IMAGE.PCB[7]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER48: TTASENTER
        Left = 460
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 22
        FieldName = 'IMAGE.PCB[8]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER49: TTASENTER
        Left = 495
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 23
        FieldName = 'IMAGE.PCB[9]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER50: TTASENTER
        Left = 530
        Top = 185
        Width = 20
        Height = 24
        CharCase = ecUpperCase
        TabOrder = 24
        FieldName = 'IMAGE.PCB[10]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'PCB'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
    end
    object Item14: TTASComboEnter
      Left = 125
      Top = 8
      Width = 121
      Height = 21
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      ReadOnly = True
      TabOrder = 0
      Text = 'Item'
      FieldName = 'BKIC.PROD.CODE '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER1: TTASENTER
      Left = 124
      Top = 32
      Width = 251
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 1
      Text = 'TASENTER1'
      FieldName = 'BKIC.PROD.DESC '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER2: TTASENTER
      Left = 124
      Top = 56
      Width = 252
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 2
      Text = 'TASENTER1'
      FieldName = 'BKIC.PROD.NOTE '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object Itype: TTASENTER
      Left = 488
      Top = 5
      Width = 18
      Height = 21
      TabStop = False
      AutoSize = False
      CharCase = ecUpperCase
      ReadOnly = True
      TabOrder = 3
      FieldName = 'MTIC.PROD.TYPE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = 'YNEOD'
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object LinkSave: TGlyphBtn
      Left = 369
      Top = 302
      Width = 58
      Height = 22
      Hint = 'Save Link'
      Caption = 'Save'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 5
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object LinkAdd: TGlyphBtn
      Left = 428
      Top = 302
      Width = 63
      Height = 22
      Hint = 'Add Link'
      Caption = 'Add'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 6
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7ABB0AB6D8368426A3932
        60273B6435576E567D837DB5B5B5F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7608C5F198211158B00158B001D8B002C7A002C6F042868154864488F8F
        8FF0F3F7F0F3F7F0F3F7F0F3F7F0F3F7429143029C0202A00402A004029C0202
        97000994011C85013773002C6F04355D338F8F8FF0F3F7F0F3F7F0F3F767A068
        08A9130AA40D019C091AB12575E59385EAA46AE38B08A9130788003773002C6F
        04486448F0F3F7F0F3F7C0CEC01DAD2412AA230AA118019C09279D22E6EFE3FF
        FFFFCBF4D600A80E0788000788003773002868157D837DF0F3F779B77B28B63C
        18B12D0CBB2D02BB2616A527D8E9D8FFFFFFB4F0C500B81500A80E0BAB192385
        012C6F04576E56F0F3F74EAC5440C75B039B188ACD97BBE8CBB8E1C4EAEDEAF8
        F4F7E4F6EAB4F0C5CBF4D66AE38B0994012C7A003B6435F0F3F742AD4A51D374
        039B18BFCABCFFEAFDF9EEF8ECECECF0F0F0FAF4F9FFFBFFFFFBFF85EAA4029C
        02238501326027F0F3F74EAC5467DF8C09A022A4C0A1DCDDDADFDFDEEAE9EAEC
        ECECEAE9EAD8E9D8DDEDDD7AE89802A0041D8B00426A39F0F3F775C77972DB91
        34BF5824AA3C24AA3C3C9E3DD8DCD8F9EEF8B0DCBA24A22524A2251CB52905A2
        09158B006C8467F0F3F7B6CCB65BD77272E19C25CA5D19C64F24AA3CDCDBD9FF
        EAFDB1E5C202BB2605A11205A1120AA40D198211ABB0ABF0F3F7F0F3F765CB6C
        80E0A45EDB8C25CA5D25AB419FBF9BBFCABC8ACD9716BA3712AA230BAB190AA4
        0D638E61F0F3F7F0F3F7F0F3F7F0F3F753BC607FE0A16CE09B37C75E0DA42B03
        9B1809A02216BA3718B12D0BAB19429143F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F765CB6C5DDA7772E19C63E2914AD67637C75E28B63C1AB12567A068F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7B6CCB675C7794FB25842
        AD4A4EAC5479B77BC0CEC0F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      GlyphKind = bkCustom
    end
    object LinkEdit: TGlyphBtn
      Left = 492
      Top = 302
      Width = 63
      Height = 22
      Hint = 'Edit Link'
      Caption = 'Edit'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 7
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFFFFFFFF
        FFFFFFFFFFFF0000006B6B6B7B7B7BEFEFEFEFEFEFBDBDBDDEDEDEDEDEDED6D6
        D6ADADADA5A5A5ADADADFFFFFFFFFFFFFFFFFF0000006B6B6B7B7B7BEFEFEFDE
        DEDEDEDEDEDEDEDEBDBDBDADADADA5A5A531313131394200316BFFFFFFFFFFFF
        0000006B6B6B7B7B7BEFEFEFEFEFEFBDBDBDADADADADADAD29293142424A3139
        42313942294A731052A5FFFFFF0000006B6B6B7B7B7BEFEFEFEFEFEFEFEFEF31
        31313939394A5A73526BA5426BB5426BB54A73BD3963CE317BE7000000000000
        7B7B7BEFEFEFEFEFEFEFEFEFEFEFEF4A4A4A4A4A4A638494C6D6F7B5CEF7B5CE
        F78CADF78CADF7638CDE000000000000EFEFEFEFEFEF000000EFEFEFEFEFEFEF
        EFEFEFEFEFBDBDBD738CBD4A84B59CA5D6BDBDE7CEE7FFCEE7FF000000FFFFFF
        000000ADADAD7B7B7BEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFBDBDBDEFEFEFDEDE
        DE7B7B7B396B84294A73FFFFFF000000000000000000ADADADEFEFEF000000EF
        EFEFEFEFEFEFEFEFEFEFEFBDBDBDDEDEDEDEDEDEDEDEDEDEDEDEFFFFFFFFFFFF
        000000FFFFFF000000ADADAD7B7B7BEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFBDBD
        BDDEDEDEDEDEDEDEDEDEFFFFFFFFFFFFFFFFFF000000FFFFFF000000ADADADEF
        EFEF000000EFEFEFDEDEDEDEDEDEDEDEDEDEDEDEDEDEDE000000FFFFFFFFFFFF
        FFFFFFFFFFFF000000000000000000ADADAD7B7B7BEFEFEFEFEFEFDEDEDEDEDE
        DEDEDEDE000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFF00
        0000ADADADDEDEDE000000DEDEDEDEDEDE000000FFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFF000000000000000000ADADAD7B7B7BDEDEDE0000
        00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
        0000FFFFFF000000ADADAD000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFF000000FFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
      GlyphKind = bkCustom
    end
    object LinkDelete: TGlyphBtn
      Left = 556
      Top = 302
      Width = 68
      Height = 22
      Hint = 'Delete Link'
      Caption = 'Delete'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 8
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
        F8F8F80000000000005A5A5A5A5A5A525252525252292929000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8212121949494FFFFFFCECECEDEDEDE94
        8C8CA5A5A56B6B6B636363393929000000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252B5ADADEFEFEF949494C6BDBD9494949494945252526B6B6B5A5A5A2121
        10F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEFA5A5A5C6C6C69494949C9C9C4A4A4A6B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F85252529C9C9CD6D6D6C6BDBD9C9C9C94
        94946B6B6B6B6B6B737373292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        393929949494C6BDBDCECECEC6BDBDA5A5A5A5A5A5A5A5A56B6B6B4A4A4A1010
        10F8F8F8F8F8F8F8F8F8F8F8F8000000A5A594DEDEDEC6C6C6BDB5B5BDBDBDBD
        BDBD8C8C8C8484846B6B6B6363635A5A5A000000F8F8F8F8F8F8F8F8F8000000
        737352D6CECEFFFFFFE7E7E7CECECEC6C6C6293939525252C6C6C69C94947B7B
        7B000000F8F8F8F8F8F8F8F8F80000005A5A5AADA5A5EFEFEFDEDEDE4A5A4A42
        5263848473525252B5B5B57B7B7B4A4A4A000000F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F80000000000003939392121217B7B6B314242000000000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F800
        0000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
      GlyphKind = bkCustom
    end
    object LinkBack: TGlyphBtn
      Left = 310
      Top = 302
      Width = 58
      Height = 22
      Hint = 'Back to the List of links'
      Caption = 'Back'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 9
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
        C8D0D4C8D0D4D3D9DCDDE2E4E7EAECEDF0F1EDF0F1E7EAECDDE2E4D3D9DCC8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CCD4D7DCE1E3D3E0D677AE7929872900
        780000780029872977AE79D3E0D6DCE1E3CCD4D7C8D0D4C8D0D4C8D0D4CBD3D6
        DDE2E49EC2A10078001BA42034CE4048EC5A4DEE6240D35427A7330078009EC2
        A1DDE2E4CBD3D6C8D0D4C8D0D4D8DDE09CC19F057E0633D33C41E44F41D14B43
        CF4E43CC5036BB4553E56F51DE6D0A7F0D9CC19FD8DDE0C8D0D4CED4D8CAD8CF
        00780033D33C3ED8493EC44542C54A37B63E228B23ADCEAD1A91205EE97A5AE1
        7A007800CAD8CFCED4D8D3D9DC6FA7721AA31F40E34D3EC3433FC1461A921E80
        B580F2F7F2FFFFFF1B912057DC696EF69433AB466FA772D3D9DCD5DADC248425
        33CE3E3FD04927A32B439843C9DEC9FFFFFFFFFFFFFFFFFF1D93235CE17066EA
        835FDD82248425D5DADCD4D8DB00780045EB5729AD3180B580FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFF1F952763E87A69EC857FFDAD007800D4D8DBCFD4D6007800
        4AED5F2BAE3580B580FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2298296AF0836FF1
        8D85FDB5007800CFD4D6C9CFD21F82203ED25049D6592DA833318F33C9DEC9FF
        FFFFFFFFFFFFFFFF239A2D70F78D78F79A6CDE931F8220C9CFD2C5CCCF5F9C62
        24A73057EE724BCF574CCF5A20982771AD71F2F7F2FFFFFF249A2E73FA908BFD
        BA3EAD54529655C5CCCFC4CCD0ABBCB30078004DDD695AE77551D66157DB6849
        C959258F29ADCEAD259A3084FCAE79E7A3007800ABBCB3C4CCD0C8D0D4C0C7CA
        79A47F087F0D56E07669F48E61E67B63E77D64E57F52C96D7CEEA977E7A20D80
        1379A47FC0C7CAC8D0D4C8D0D4C5CDD1BBC2C674A27B00780030AB435BDC7E7A
        FDA980FDB070E69A3DAD5300780074A27BBBC2C6C5CDD1C8D0D4C8D0D4C8D0D4
        C4CCD0BAC1C59CB0A54490481780190078000078001780194F93539CB0A5BAC1
        C5C4CCD0C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C0C7CBB7BEC2B0B7BBAB
        B2B6ABB2B6B0B7BBB7BEC2C0C7CBC8D0D4C8D0D4C8D0D4C8D0D4}
      GlyphKind = bkCustom
    end
  end
  object LinkGrid: TTASDataGrid
    Left = 7
    Top = 81
    Width = 618
    Height = 218
    ColCount = 1
    Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
    TabOrder = 2
    UpCase = False
    StartAtEnd = False
    PrePrgLoc = 0
    PostPrgLoc = 0
    Navigation.AllowInsertRow = False
    Navigation.AllowDeleteRow = True
    Navigation.AdvanceOnEnter = False
    Navigation.AdvanceAtEnd = False
    Navigation.AdvanceDirection = adLeftRight
    Navigation.AdvanceAuto = False
    Navigation.InsertPosition = pInsertBefore
    Navigation.CursorWalkEditor = False
    Navigation.AllowAddRecListF = False
    MouseActions.ColSelect = False
    MouseActions.RowSelect = False
    MouseActions.DirectEdit = False
    MouseActions.DirectComboDrop = False
    MouseActions.CaretPositioning = False
    PasswordChar = '*'
    Columns = <
      item
        Color = clWindow
        Width = 593
        Alignment = taLeftJustify
        Header = 'Link'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = True
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'LINK'
        CharCase = ecNormal
        Name = 'Link'
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
      end>
    ExtraFields = <>
    AutoNumAlign = False
    SelectionColor = clHighlight
    SelectionTextColor = clHighlightText
    SelectionRectangle = False
    FixedFont.Charset = DEFAULT_CHARSET
    FixedFont.Color = clWindowText
    FixedFont.Height = -13
    FixedFont.Name = 'Arial'
    FixedFont.Style = []
    VAlignment = vtaTop
    Hovering = False
    EnhRowColMove = True
    HintColor = clYellow
    CurrentRow = 1
    CurrentCol = 1
    GridFileHandle = 0
    GridFileKeyNum = 0
    NoAutoUpdate = False
    ColWidths = (
      593)
  end
  object ExitMRP: TGlyphBtn
    Left = 555
    Top = 330
    Width = 75
    Height = 25
    Caption = 'Exit'
    ModalResult = 2
    TabOrder = 1
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
      DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
      E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
      19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
      5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
      EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
      43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
      707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
      D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
      6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
      7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
      D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
      FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
      8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
      D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
      F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
      91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
      DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
      77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
      8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
      EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
      90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
      3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
      AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
      BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
    GlyphKind = bkCustom
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Top = 327
  end
end
