object EditForm1: TEditForm1
  Left = 379
  Top = 247
  Hint = 'C:\TASPRO7\DBA7\T7BOL.DFM'
  AutoScroll = False
  BorderIcons = [biSystemMenu]
  Caption = 'Shipping'
  ClientHeight = 617
  ClientWidth = 694
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7BOL.OnClose'
  No_Refresh = False
  OnStart = 'T7BOL.OnStart'
  OpenFiles = 'T7BOL.OnOpenFiles'
  OnDisplayScreen = 'T7BOL.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 1
  SpecifiedLeft = 1
  SourceFile = 'T7BOL'
  RememberSizeDate = 45481.523235208330000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object CarrierPanel: TPanel
    Left = 0
    Top = 29
    Width = 694
    Height = 554
    Align = alClient
    TabOrder = 7
    object Label42: TLabel
      Left = 208
      Top = 75
      Width = 125
      Height = 16
      Caption = 'Authorization Number'
    end
    object Label43: TLabel
      Left = 208
      Top = 99
      Width = 90
      Height = 16
      Caption = 'Control Number'
    end
    object Label7: TLabel
      Left = 208
      Top = 181
      Width = 77
      Height = 16
      Caption = 'Load Number'
    end
    object Label8: TLabel
      Left = 208
      Top = 204
      Width = 75
      Height = 16
      Caption = 'Seal Number'
    end
    object Label40: TLabel
      Left = 208
      Top = 156
      Width = 84
      Height = 16
      Caption = 'Trailer Number'
    end
    object Label45: TLabel
      Left = 208
      Top = 293
      Width = 78
      Height = 16
      Caption = 'Pick Up Time'
    end
    object Label46: TLabel
      Left = 208
      Top = 269
      Width = 77
      Height = 16
      Caption = 'Pick Up Date'
    end
    object Label47: TLabel
      Left = 208
      Top = 340
      Width = 106
      Height = 16
      Caption = 'Driver Arrived Time'
    end
    object Label48: TLabel
      Left = 208
      Top = 363
      Width = 109
      Height = 16
      Caption = 'Loading Start Time'
    end
    object Label49: TLabel
      Left = 208
      Top = 387
      Width = 104
      Height = 16
      Caption = 'Loading End Time'
    end
    object Label50: TLabel
      Left = 208
      Top = 411
      Width = 120
      Height = 16
      Caption = 'Driver Departed Time'
    end
    object EnterLoadNum: TTASENTER
      Left = 341
      Top = 179
      Width = 142
      Height = 21
      Hint = 'RTM Field: LOAD.NUMBER'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      Text = 'EnterBOLNum'
      FieldName = 'load.number'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterSealNumber: TTASENTER
      Left = 341
      Top = 202
      Width = 142
      Height = 21
      Hint = 'RTM Field: SEAL.NUMBER'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      Text = 'EnterBOLNum'
      FieldName = 'seal.number'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER13: TTASENTER
      Left = 341
      Top = 154
      Width = 142
      Height = 21
      Hint = 'RTM Field: TRAILER.NUMBER'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      Text = 'EnterBOLNum'
      FieldName = 'trailer.number'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER16: TTASENTER
      Left = 341
      Top = 73
      Width = 142
      Height = 21
      Hint = 'RTM Field: AUTHOR.NUMBER'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      Text = 'EnterBOLNum'
      FieldName = 'author.number'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER17: TTASENTER
      Left = 341
      Top = 97
      Width = 142
      Height = 21
      Hint = 'RTM Field: CONTROL.NUMBER'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      Text = 'EnterBOLNum'
      FieldName = 'control.number'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER19: TTASENTER
      Left = 341
      Top = 291
      Width = 100
      Height = 21
      Hint = 'RTM Field: PICKUP.TIME'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 6
      Text = 'EnterBOLNum'
      FieldName = 'pickup.time'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER20: TTASENTER
      Left = 341
      Top = 338
      Width = 100
      Height = 21
      Hint = 'RTM Field: DRIVER.ARRIVED'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 7
      Text = 'EnterBOLNum'
      FieldName = 'driver.arrived'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER21: TTASENTER
      Left = 341
      Top = 361
      Width = 100
      Height = 21
      Hint = 'RTM Field: LOADING.START'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 8
      Text = 'EnterBOLNum'
      FieldName = 'loading.start'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER22: TTASENTER
      Left = 341
      Top = 385
      Width = 100
      Height = 21
      Hint = 'RTM Field: LOADING.END'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 9
      Text = 'EnterBOLNum'
      FieldName = 'loading.end'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER23: TTASENTER
      Left = 341
      Top = 409
      Width = 100
      Height = 21
      Hint = 'RTM Field: DRIVER.DEPARTED'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 10
      Text = 'EnterBOLNum'
      FieldName = 'driver.departed'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASDateEdit1: TTASDateEdit
      Left = 341
      Top = 267
      Width = 100
      Height = 21
      Hint = 'RTM Field: PICKUP.DATE'
      BlanksChar = '0'
      NumGlyphs = 2
      ParentShowHint = False
      ShowHint = True
      StartOfWeek = Sun
      TabOrder = 5
      FieldName = 'pickup.date'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object btnPUTime: TGlyphBtn
      Left = 442
      Top = 290
      Width = 25
      Height = 23
      TabOrder = 11
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFECBCBCB747373807C7984
        7B76807976716E6D7B6E6EC4C6C7FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEA09492817B7994918FA5978FA39792AB9B94A49891B0928F8D817FCDC5
        C5FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEAEA8A5909588BAA58BD3CAB7CEC1BD7D
        88CCADB0C9D6D3D1B2B1A0AC8D87AE9C98C9C9CAFFFFFEFFFFFEFFFFFEFFFFFE
        A19E9DC2B89FEFE0C1F8ECD0F1DDB8D1C2B9E4D9CCFDFBF6F3F4F1B7AFA99E93
        8F9F8A80CFCBC8FFFFFEFFFFFEA9A8A8CBBBA6F4E2BFF8E2B9F8E1B5F8E1B5F8
        E1B5F1D5A7F5DCAFFEFDFAF8F5F1BEB1A3A198926A6868FFFFFEFFFFFEAAA8A8
        DBC7ABF8E9C9F8E5BEF8ECD0F7E2B9F4DDB1F7DFB2F1D4A6F7E0B4F9F2E2DED5
        C4B4A38F747171FFFFFEFFFFFEAAA9A8D8CBB7F0EBD8F8EFD9F7ECD0EADDC1C1
        B191CEB28ECDC29CDAC2A1EFE4C8CFD8D7AAA59E907D79FFFFFEFFFFFEAAA9A8
        93A3C8CAD4E8F8F5EAF7EFDBC7C8B177756E5C514954574C6C635D8D8880A1B0
        DC7B86A68B7E7CFFFFFEFFFFFEA9A8A8CDCACFEDF0F8FBF9F3F8F2E4E2DDC59D
        99965152528C6B58CEBC9AD3C3A5D7CDCAAC9B9C847C78FFFFFEFFFFFEEAE7E1
        A9A8A8FCFAF4FDFDFBF9F6ECF8F2E4F6EEDBB3B89E525650A68B67F8ECD0D2D0
        B594998C747373FFFFFEFFFFFEFFFFFEA9A8A8F3EAE3FDFDFBFDFDF9FBF9F3F8
        F5EBF8EFDBAFB498535251AA9483C8B89D878382979492FFFFFEFFFFFEFFFFFE
        ECE6E1ABAAA9F2EAE5FCFAF4EEF1F8C2D5EEE8F0ECF8E8C7C2B19E706A67A497
        8F9F9D9CDEE0E0FFFFFEFFFFFEFFFFFEFFFFFEEAE3E1ABA9A9ACAAA9D1CCCF8A
        A4CAC5D0D0DACDBCCFBEA6ADA7A4B1B0AFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEF1EDEAECE7E3ABA9A9AAA9A8C8BFB6C0BBB6B4B0ADFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnArriveTime: TGlyphBtn
      Left = 443
      Top = 337
      Width = 25
      Height = 23
      TabOrder = 12
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFECBCBCB747373807C7984
        7B76807976716E6D7B6E6EC4C6C7FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEA09492817B7994918FA5978FA39792AB9B94A49891B0928F8D817FCDC5
        C5FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEAEA8A5909588BAA58BD3CAB7CEC1BD7D
        88CCADB0C9D6D3D1B2B1A0AC8D87AE9C98C9C9CAFFFFFEFFFFFEFFFFFEFFFFFE
        A19E9DC2B89FEFE0C1F8ECD0F1DDB8D1C2B9E4D9CCFDFBF6F3F4F1B7AFA99E93
        8F9F8A80CFCBC8FFFFFEFFFFFEA9A8A8CBBBA6F4E2BFF8E2B9F8E1B5F8E1B5F8
        E1B5F1D5A7F5DCAFFEFDFAF8F5F1BEB1A3A198926A6868FFFFFEFFFFFEAAA8A8
        DBC7ABF8E9C9F8E5BEF8ECD0F7E2B9F4DDB1F7DFB2F1D4A6F7E0B4F9F2E2DED5
        C4B4A38F747171FFFFFEFFFFFEAAA9A8D8CBB7F0EBD8F8EFD9F7ECD0EADDC1C1
        B191CEB28ECDC29CDAC2A1EFE4C8CFD8D7AAA59E907D79FFFFFEFFFFFEAAA9A8
        93A3C8CAD4E8F8F5EAF7EFDBC7C8B177756E5C514954574C6C635D8D8880A1B0
        DC7B86A68B7E7CFFFFFEFFFFFEA9A8A8CDCACFEDF0F8FBF9F3F8F2E4E2DDC59D
        99965152528C6B58CEBC9AD3C3A5D7CDCAAC9B9C847C78FFFFFEFFFFFEEAE7E1
        A9A8A8FCFAF4FDFDFBF9F6ECF8F2E4F6EEDBB3B89E525650A68B67F8ECD0D2D0
        B594998C747373FFFFFEFFFFFEFFFFFEA9A8A8F3EAE3FDFDFBFDFDF9FBF9F3F8
        F5EBF8EFDBAFB498535251AA9483C8B89D878382979492FFFFFEFFFFFEFFFFFE
        ECE6E1ABAAA9F2EAE5FCFAF4EEF1F8C2D5EEE8F0ECF8E8C7C2B19E706A67A497
        8F9F9D9CDEE0E0FFFFFEFFFFFEFFFFFEFFFFFEEAE3E1ABA9A9ACAAA9D1CCCF8A
        A4CAC5D0D0DACDBCCFBEA6ADA7A4B1B0AFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEF1EDEAECE7E3ABA9A9AAA9A8C8BFB6C0BBB6B4B0ADFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnStartTime: TGlyphBtn
      Left = 443
      Top = 360
      Width = 25
      Height = 23
      TabOrder = 13
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFECBCBCB747373807C7984
        7B76807976716E6D7B6E6EC4C6C7FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEA09492817B7994918FA5978FA39792AB9B94A49891B0928F8D817FCDC5
        C5FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEAEA8A5909588BAA58BD3CAB7CEC1BD7D
        88CCADB0C9D6D3D1B2B1A0AC8D87AE9C98C9C9CAFFFFFEFFFFFEFFFFFEFFFFFE
        A19E9DC2B89FEFE0C1F8ECD0F1DDB8D1C2B9E4D9CCFDFBF6F3F4F1B7AFA99E93
        8F9F8A80CFCBC8FFFFFEFFFFFEA9A8A8CBBBA6F4E2BFF8E2B9F8E1B5F8E1B5F8
        E1B5F1D5A7F5DCAFFEFDFAF8F5F1BEB1A3A198926A6868FFFFFEFFFFFEAAA8A8
        DBC7ABF8E9C9F8E5BEF8ECD0F7E2B9F4DDB1F7DFB2F1D4A6F7E0B4F9F2E2DED5
        C4B4A38F747171FFFFFEFFFFFEAAA9A8D8CBB7F0EBD8F8EFD9F7ECD0EADDC1C1
        B191CEB28ECDC29CDAC2A1EFE4C8CFD8D7AAA59E907D79FFFFFEFFFFFEAAA9A8
        93A3C8CAD4E8F8F5EAF7EFDBC7C8B177756E5C514954574C6C635D8D8880A1B0
        DC7B86A68B7E7CFFFFFEFFFFFEA9A8A8CDCACFEDF0F8FBF9F3F8F2E4E2DDC59D
        99965152528C6B58CEBC9AD3C3A5D7CDCAAC9B9C847C78FFFFFEFFFFFEEAE7E1
        A9A8A8FCFAF4FDFDFBF9F6ECF8F2E4F6EEDBB3B89E525650A68B67F8ECD0D2D0
        B594998C747373FFFFFEFFFFFEFFFFFEA9A8A8F3EAE3FDFDFBFDFDF9FBF9F3F8
        F5EBF8EFDBAFB498535251AA9483C8B89D878382979492FFFFFEFFFFFEFFFFFE
        ECE6E1ABAAA9F2EAE5FCFAF4EEF1F8C2D5EEE8F0ECF8E8C7C2B19E706A67A497
        8F9F9D9CDEE0E0FFFFFEFFFFFEFFFFFEFFFFFEEAE3E1ABA9A9ACAAA9D1CCCF8A
        A4CAC5D0D0DACDBCCFBEA6ADA7A4B1B0AFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEF1EDEAECE7E3ABA9A9AAA9A8C8BFB6C0BBB6B4B0ADFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnEndTime: TGlyphBtn
      Left = 443
      Top = 384
      Width = 25
      Height = 23
      TabOrder = 14
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFECBCBCB747373807C7984
        7B76807976716E6D7B6E6EC4C6C7FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEA09492817B7994918FA5978FA39792AB9B94A49891B0928F8D817FCDC5
        C5FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEAEA8A5909588BAA58BD3CAB7CEC1BD7D
        88CCADB0C9D6D3D1B2B1A0AC8D87AE9C98C9C9CAFFFFFEFFFFFEFFFFFEFFFFFE
        A19E9DC2B89FEFE0C1F8ECD0F1DDB8D1C2B9E4D9CCFDFBF6F3F4F1B7AFA99E93
        8F9F8A80CFCBC8FFFFFEFFFFFEA9A8A8CBBBA6F4E2BFF8E2B9F8E1B5F8E1B5F8
        E1B5F1D5A7F5DCAFFEFDFAF8F5F1BEB1A3A198926A6868FFFFFEFFFFFEAAA8A8
        DBC7ABF8E9C9F8E5BEF8ECD0F7E2B9F4DDB1F7DFB2F1D4A6F7E0B4F9F2E2DED5
        C4B4A38F747171FFFFFEFFFFFEAAA9A8D8CBB7F0EBD8F8EFD9F7ECD0EADDC1C1
        B191CEB28ECDC29CDAC2A1EFE4C8CFD8D7AAA59E907D79FFFFFEFFFFFEAAA9A8
        93A3C8CAD4E8F8F5EAF7EFDBC7C8B177756E5C514954574C6C635D8D8880A1B0
        DC7B86A68B7E7CFFFFFEFFFFFEA9A8A8CDCACFEDF0F8FBF9F3F8F2E4E2DDC59D
        99965152528C6B58CEBC9AD3C3A5D7CDCAAC9B9C847C78FFFFFEFFFFFEEAE7E1
        A9A8A8FCFAF4FDFDFBF9F6ECF8F2E4F6EEDBB3B89E525650A68B67F8ECD0D2D0
        B594998C747373FFFFFEFFFFFEFFFFFEA9A8A8F3EAE3FDFDFBFDFDF9FBF9F3F8
        F5EBF8EFDBAFB498535251AA9483C8B89D878382979492FFFFFEFFFFFEFFFFFE
        ECE6E1ABAAA9F2EAE5FCFAF4EEF1F8C2D5EEE8F0ECF8E8C7C2B19E706A67A497
        8F9F9D9CDEE0E0FFFFFEFFFFFEFFFFFEFFFFFEEAE3E1ABA9A9ACAAA9D1CCCF8A
        A4CAC5D0D0DACDBCCFBEA6ADA7A4B1B0AFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEF1EDEAECE7E3ABA9A9AAA9A8C8BFB6C0BBB6B4B0ADFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnDepartTime: TGlyphBtn
      Left = 443
      Top = 408
      Width = 25
      Height = 23
      TabOrder = 15
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFECBCBCB747373807C7984
        7B76807976716E6D7B6E6EC4C6C7FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEA09492817B7994918FA5978FA39792AB9B94A49891B0928F8D817FCDC5
        C5FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEAEA8A5909588BAA58BD3CAB7CEC1BD7D
        88CCADB0C9D6D3D1B2B1A0AC8D87AE9C98C9C9CAFFFFFEFFFFFEFFFFFEFFFFFE
        A19E9DC2B89FEFE0C1F8ECD0F1DDB8D1C2B9E4D9CCFDFBF6F3F4F1B7AFA99E93
        8F9F8A80CFCBC8FFFFFEFFFFFEA9A8A8CBBBA6F4E2BFF8E2B9F8E1B5F8E1B5F8
        E1B5F1D5A7F5DCAFFEFDFAF8F5F1BEB1A3A198926A6868FFFFFEFFFFFEAAA8A8
        DBC7ABF8E9C9F8E5BEF8ECD0F7E2B9F4DDB1F7DFB2F1D4A6F7E0B4F9F2E2DED5
        C4B4A38F747171FFFFFEFFFFFEAAA9A8D8CBB7F0EBD8F8EFD9F7ECD0EADDC1C1
        B191CEB28ECDC29CDAC2A1EFE4C8CFD8D7AAA59E907D79FFFFFEFFFFFEAAA9A8
        93A3C8CAD4E8F8F5EAF7EFDBC7C8B177756E5C514954574C6C635D8D8880A1B0
        DC7B86A68B7E7CFFFFFEFFFFFEA9A8A8CDCACFEDF0F8FBF9F3F8F2E4E2DDC59D
        99965152528C6B58CEBC9AD3C3A5D7CDCAAC9B9C847C78FFFFFEFFFFFEEAE7E1
        A9A8A8FCFAF4FDFDFBF9F6ECF8F2E4F6EEDBB3B89E525650A68B67F8ECD0D2D0
        B594998C747373FFFFFEFFFFFEFFFFFEA9A8A8F3EAE3FDFDFBFDFDF9FBF9F3F8
        F5EBF8EFDBAFB498535251AA9483C8B89D878382979492FFFFFEFFFFFEFFFFFE
        ECE6E1ABAAA9F2EAE5FCFAF4EEF1F8C2D5EEE8F0ECF8E8C7C2B19E706A67A497
        8F9F9D9CDEE0E0FFFFFEFFFFFEFFFFFEFFFFFEEAE3E1ABA9A9ACAAA9D1CCCF8A
        A4CAC5D0D0DACDBCCFBEA6ADA7A4B1B0AFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEF1EDEAECE7E3ABA9A9AAA9A8C8BFB6C0BBB6B4B0ADFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
  end
  object ItemsPanel: TPanel
    Left = 0
    Top = 29
    Width = 694
    Height = 554
    Align = alClient
    TabOrder = 6
    object Label18: TLabel
      Left = 6
      Top = 264
      Width = 65
      Height = 16
      Caption = 'Description'
    end
    object Label20: TLabel
      Left = 6
      Top = 292
      Width = 81
      Height = 16
      Caption = 'Total Item Qty'
    end
    object Label21: TLabel
      Left = 6
      Top = 354
      Width = 81
      Height = 16
      Caption = 'Total Item Wt:'
    end
    object Label22: TLabel
      Left = 6
      Top = 315
      Width = 68
      Height = 16
      Caption = 'Total Cases'
    end
    object Label23: TLabel
      Left = 6
      Top = 398
      Width = 75
      Height = 16
      Caption = 'Tot Pallet Wt'
    end
    object Label25: TLabel
      Left = 6
      Top = 431
      Width = 81
      Height = 16
      Caption = 'Additional Info'
    end
    object Label26: TLabel
      Left = 427
      Top = 254
      Width = 97
      Height = 16
      Caption = 'HANDLING UNIT'
    end
    object Label27: TLabel
      Left = 344
      Top = 271
      Width = 49
      Height = 16
      Caption = 'Quantity'
    end
    object Label28: TLabel
      Left = 344
      Top = 296
      Width = 27
      Height = 16
      Caption = 'Type'
    end
    object Label29: TLabel
      Left = 545
      Top = 488
      Width = 47
      Height = 16
      Caption = 'H.M. (X)'
    end
    object Label30: TLabel
      Left = 345
      Top = 463
      Width = 58
      Height = 16
      Caption = 'Type Total'
    end
    object Label31: TLabel
      Left = 345
      Top = 367
      Width = 49
      Height = 16
      Caption = 'Quantity'
    end
    object Label32: TLabel
      Left = 345
      Top = 391
      Width = 27
      Height = 16
      Caption = 'Type'
    end
    object Label33: TLabel
      Left = 345
      Top = 483
      Width = 44
      Height = 16
      Caption = 'NMFC#'
    end
    object Label34: TLabel
      Left = 345
      Top = 508
      Width = 43
      Height = 16
      Caption = 'CLASS'
    end
    object Label35: TLabel
      Left = 345
      Top = 319
      Width = 58
      Height = 16
      Caption = 'Type Total'
    end
    object Label36: TLabel
      Left = 424
      Top = 347
      Width = 63
      Height = 16
      Caption = 'PACKAGE'
    end
    object Label10: TLabel
      Left = 6
      Top = 376
      Width = 78
      Height = 16
      Caption = 'Pallet Weight'
    end
    object Label19: TLabel
      Left = 6
      Top = 458
      Width = 101
      Height = 16
      Caption = 'Additional Pallets'
    end
    object Label24: TLabel
      Left = 345
      Top = 440
      Width = 59
      Height = 16
      Caption = 'Pallet/Slip'
    end
    object Label37: TLabel
      Left = 6
      Top = 480
      Width = 81
      Height = 16
      Caption = 'Add Pallet Wt'
    end
    object Label51: TLabel
      Left = 345
      Top = 415
      Width = 41
      Height = 16
      Caption = 'Weight'
    end
    object Label52: TLabel
      Left = 6
      Top = 528
      Width = 70
      Height = 16
      Caption = 'Commodity '
    end
    object Label39: TLabel
      Left = 6
      Top = 507
      Width = 67
      Height = 16
      Caption = 'Department'
    end
    object PairsLabel: TLabel
      Left = 553
      Top = 367
      Width = 30
      Height = 16
      Caption = 'Pairs'
    end
    object ItemsGrid: TTASDataGrid
      Left = 1
      Top = 1
      Width = 677
      Height = 250
      ColCount = 7
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
      TabOrder = 22
      UpCase = False
      StartAtEnd = True
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = False
      Navigation.AllowDeleteRow = True
      Navigation.AdvanceOnEnter = True
      Navigation.AdvanceAtEnd = False
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = False
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = True
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 158
          Alignment = taLeftJustify
          Header = 'Description'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.DESC'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 84
          Alignment = taRightJustify
          Header = 'Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.QTY'
          CharCase = ecNormal
          Name = 'ColShpvia'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 57
          Alignment = taRightJustify
          Header = 'Cases'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CASES'
          CharCase = ecNormal
          Name = 'DescCol'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 58
          Alignment = taRightJustify
          Header = 'Weight'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.WT'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 73
          Alignment = taLeftJustify
          Header = 'Pallet/Slip'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.PALLET'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 78
          Alignment = taLeftJustify
          Header = 'Deliver Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.DUEDATE'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 126
          Alignment = taLeftJustify
          Header = 'Additional Info'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.SHIPINFO'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = False
      HintColor = clYellow
      FastSearchFld = 'fastalpha'
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        158
        84
        57
        58
        73
        78
        126)
    end
    object TASENTER12: TTASENTER
      Left = 109
      Top = 262
      Width = 200
      Height = 21
      TabStop = False
      AutoSize = False
      TabOrder = 0
      Text = 'TASENTER11'
      FieldName = 'edit.desc'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdQty: TTASNumEnter
      Left = 109
      Top = 290
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      DisplayFormat = '0.00'
      TabOrder = 1
      FieldName = 'edit.qty'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterEdItemWT: TTASNumEnter
      Left = 109
      Top = 352
      Width = 121
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 3
      FieldName = 'edit.item.wt'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterEdCases: TTASNumEnter
      Left = 109
      Top = 313
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      DisplayFormat = '0.00'
      TabOrder = 2
      FieldName = 'edit.cases'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterEdPallWT: TTASNumEnter
      Left = 109
      Top = 396
      Width = 121
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 5
      FieldName = 'edit.pallet.wt'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterEdInfo: TTASENTER
      Left = 109
      Top = 428
      Width = 200
      Height = 21
      TabStop = False
      AutoSize = False
      TabOrder = 10
      Text = 'TASENTER11'
      FieldName = 'edit.info'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdHType: TTASENTER
      Left = 424
      Top = 294
      Width = 119
      Height = 21
      AutoSize = False
      TabOrder = 12
      Text = 'TASENTER11'
      FieldName = 'edit.htype'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdHQty: TTASNumEnter
      Left = 424
      Top = 271
      Width = 119
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 11
      FieldName = 'edit.hqty'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_hqty()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterEdPQty: TTASNumEnter
      Left = 424
      Top = 365
      Width = 119
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 14
      FieldName = 'edit.pqty'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterEdPType: TTASENTER
      Left = 424
      Top = 389
      Width = 119
      Height = 21
      AutoSize = False
      TabOrder = 16
      Text = 'TASENTER11'
      FieldName = 'edit.ptype'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdHM: TTASENTER
      Left = 624
      Top = 486
      Width = 27
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 19
      Text = 'TASENTER11'
      FieldName = 'edit.HM'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = ' X'
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdNMFC: TTASENTER
      Left = 424
      Top = 483
      Width = 108
      Height = 21
      TabStop = False
      AutoSize = False
      TabOrder = 20
      Text = 'TASENTER11'
      FieldName = 'edit.nmfc'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdClass: TTASENTER
      Left = 424
      Top = 506
      Width = 108
      Height = 21
      TabStop = False
      AutoSize = False
      TabOrder = 21
      Text = 'TASENTER11'
      FieldName = 'edit.class'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdHTypeTot: TTASENTER
      Left = 424
      Top = 317
      Width = 108
      Height = 21
      AutoSize = False
      TabOrder = 13
      Text = 'TASENTER11'
      FieldName = 'tot.carr.htype'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterEdPTypeTot: TTASENTER
      Left = 424
      Top = 461
      Width = 108
      Height = 21
      AutoSize = False
      TabOrder = 18
      Text = 'TASENTER11'
      FieldName = 'tot.carr.ptype'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterOneWT: TTASNumEnter
      Left = 109
      Top = 374
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 4
      FieldName = 'one.pallet.wt'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_onepallet()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterAddPallets: TTASNumEnter
      Left = 109
      Top = 456
      Width = 121
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 6
      FieldName = 'add.pallets'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterPackPallet: TTASENTER
      Left = 424
      Top = 438
      Width = 119
      Height = 21
      AutoSize = False
      TabOrder = 17
      Text = 'EnterPackPallet'
      FieldName = 'edit.pallet'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_packtype()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterAddPallWt: TTASNumEnter
      Left = 109
      Top = 478
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 7
      FieldName = 'add.pallet.wt'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_onepallet()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterWeight: TTASENTER
      Left = 424
      Top = 413
      Width = 119
      Height = 21
      AutoSize = False
      TabOrder = 23
      Text = 'TASENTER11'
      FieldName = 'edit.pweight'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
  end
    object TASENTER24: TTASENTER
      Left = 109
      Top = 527
      Width = 195
      Height = 21
      Hint = 'RTM Field: COMMODITY'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 9
      Text = 'EnterBOLNum'
      FieldName = 'commodity'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER11: TTASENTER
      Left = 109
      Top = 504
      Width = 195
      Height = 21
      Hint = 'RTM Field: DEPARTMENT'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 8
      Text = 'EnterBOLNum'
      FieldName = 'department'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object enterPairs: TTASNumEnter
      Left = 588
      Top = 365
      Width = 91
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 15
      FieldName = 'edit.pairs'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
  end
  object AddressPanel: TPanel
    Left = 0
    Top = 29
    Width = 694
    Height = 554
    Align = alClient
    TabOrder = 5
    object Label16: TLabel
      Left = 88
      Top = 130
      Width = 154
      Height = 16
      Caption = 'Drop Ship Company Name'
    end
    object Label17: TLabel
      Left = 192
      Top = 162
      Width = 48
      Height = 16
      Caption = 'Address'
    end
    object EnterDShpNme: TTASENTER
      Left = 255
      Top = 128
      Width = 280
      Height = 21
      AutoSize = False
      TabOrder = 0
      Text = 'EnterDShpNme'
      FieldName = 'drop.shpnme'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER6: TTASENTER
      Left = 255
      Top = 159
      Width = 280
      Height = 21
      AutoSize = False
      TabOrder = 1
      Text = 'EnterDShpNme'
      FieldName = 'drop.ship.to[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER7: TTASENTER
      Left = 255
      Top = 182
      Width = 280
      Height = 21
      AutoSize = False
      TabOrder = 2
      Text = 'EnterDShpNme'
      FieldName = 'drop.ship.to[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER8: TTASENTER
      Left = 255
      Top = 205
      Width = 280
      Height = 21
      AutoSize = False
      TabOrder = 3
      Text = 'EnterDShpNme'
      FieldName = 'drop.ship.to[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterDAddress4: TTASENTER
      Left = 255
      Top = 228
      Width = 280
      Height = 21
      AutoSize = False
      TabOrder = 4
      Text = 'EnterDShpNme'
      FieldName = 'drop.ship.to[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_add4()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
  end
  object ReprintPanel: TPanel
    Left = 0
    Top = 29
    Width = 694
    Height = 554
    Align = alClient
    ParentBackground = False
    TabOrder = 0
    object ShipNumLabel: TLabel
      Left = 79
      Top = 186
      Width = 93
      Height = 16
      Caption = 'Shipper Number'
      Transparent = True
    end
    object Label1: TLabel
      Left = 33
      Top = 345
      Width = 169
      Height = 16
      Caption = 'Marks and Exceptions Line 1'
    end
    object Label2: TLabel
      Left = 167
      Top = 366
      Width = 35
      Height = 16
      Caption = 'Line 2'
    end
    object Label3: TLabel
      Left = 167
      Top = 386
      Width = 35
      Height = 16
      Caption = 'Line 3'
    end
    object Label4: TLabel
      Left = 167
      Top = 405
      Width = 35
      Height = 16
      Caption = 'Line 4'
    end
    object Label9: TLabel
      Left = 472
      Top = 433
      Width = 87
      Height = 16
      Caption = 'Shipping Class'
    end
    object Label5: TLabel
      Left = 79
      Top = 113
      Width = 49
      Height = 16
      Caption = 'Ship Via'
      Transparent = True
    end
    object Label11: TLabel
      Left = 79
      Top = 234
      Width = 129
      Height = 16
      Hint = 
        'C - Collect'#13#10'T - Third Party'#13#10'B - Bill Shipper'#13#10'P = Prepaid'#13#10'A =' +
        ' Prepaid and Add'#13#10'N - None'
      Caption = 'Billing Type (CTBNPA)'
      ParentShowHint = False
      ShowHint = True
      Transparent = True
    end
    object BillingLabel: TLabel
      Left = 258
      Top = 234
      Width = 66
      Height = 16
      Caption = 'BillingLabel'
    end
    object Label12: TLabel
      Left = 79
      Top = 256
      Width = 106
      Height = 16
      Caption = 'Billing Account No'
      Transparent = True
    end
    object Label14: TLabel
      Left = 79
      Top = 162
      Width = 132
      Height = 16
      Hint = 'I - Intermediate Shipper'#13#10'D - Drop Ship Address'#13#10'N - None'
      Caption = 'Intermediate/Drop Ship'
      ParentShowHint = False
      ShowHint = True
      Transparent = True
    end
    object IShipToLabel: TLabel
      Left = 367
      Top = 163
      Width = 73
      Height = 16
      Caption = 'IShipToLabel'
    end
    object SOLabel: TLabel
      Left = 79
      Top = 48
      Width = 56
      Height = 16
      Caption = 'Customer'
      Transparent = True
    end
    object Label15: TLabel
      Left = 79
      Top = 71
      Width = 103
      Height = 16
      Caption = 'Ship To Customer'
      Transparent = True
    end
    object SONumLabel: TLabel
      Left = 79
      Top = 27
      Width = 68
      Height = 16
      Caption = 'SO Number'
      Transparent = True
    end
    object Label13: TLabel
      Left = 78
      Top = 281
      Width = 128
      Height = 16
      Caption = 'Third Party Cust Code'
      Transparent = True
    end
    object TPLabel: TLabel
      Left = 366
      Top = 279
      Width = 47
      Height = 16
      Caption = 'TPLabel'
    end
    object Label6: TLabel
      Left = 80
      Top = 302
      Width = 123
      Height = 16
      Caption = 'Bill of Lading Number'
    end
    object AddSOLabel: TLabel
      Left = 339
      Top = 27
      Width = 80
      Height = 16
      Caption = 'Additional SO'
      Transparent = True
    end
    object Label38: TLabel
      Left = 79
      Top = 210
      Width = 57
      Height = 16
      Caption = 'Ship Date'
      Transparent = True
    end
    object Label41: TLabel
      Left = 341
      Top = 114
      Width = 36
      Height = 16
      Caption = 'SCAC'
    end
    object Label44: TLabel
      Left = 79
      Top = 136
      Width = 76
      Height = 16
      Caption = 'Carrier Name'
    end
    object EnterShipNum: TTASComboEnter
      Left = 213
      Top = 184
      Width = 120
      Height = 21
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 16
      Text = 'SHIPPER NUM'
      FieldName = 'sShip.Num'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = '012345678 9'
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERSHIPNUM.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object cbShipments: TTASCheckBox
      Left = 190
      Top = 4
      Width = 176
      Height = 17
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Reprint from Shipments?'
      TabOrder = 2
      FieldName = 'SCAN.INV'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER1: TTASENTER
      Left = 213
      Top = 344
      Width = 336
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 22
      Text = 'TASENTER1'
      FieldName = 'marks[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER2: TTASENTER
      Left = 213
      Top = 364
      Width = 336
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 23
      Text = 'TASENTER1'
      FieldName = 'marks[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER3: TTASENTER
      Left = 213
      Top = 384
      Width = 336
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 24
      Text = 'TASENTER1'
      FieldName = 'marks[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER4: TTASENTER
      Left = 213
      Top = 404
      Width = 336
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 25
      Text = '12345678901234567890123456789012345678990123456789'
      FieldName = 'marks[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object skidGrid: TTASDataGrid
      Left = 10
      Top = 429
      Width = 438
      Height = 118
      ColCount = 6
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing, goEditing]
      ScrollBars = ssNone
      TabOrder = 26
      UpCase = False
      StartAtEnd = False
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = False
      Navigation.AllowDeleteRow = False
      Navigation.AdvanceOnEnter = True
      Navigation.AdvanceAtEnd = True
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = True
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = False
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 56
          Alignment = taCenter
          Header = 'Number'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'MS Sans Serif'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = True
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SKID.NUMBER'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 70
          Alignment = taCenter
          Header = 'Length (in.)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SKID.DEPTH'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 68
          Alignment = taCenter
          Header = 'Width (in.)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SKID.WIDTH'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 72
          Alignment = taCenter
          Header = 'Height (in.)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SKID.HEIGHT'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 102
          Alignment = taCenter
          Header = 'Total Wt (lbs)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SKID.WEIGHT'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 61
          Alignment = taCenter
          Header = 'Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SKID.QTY'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = False
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        56
        70
        68
        72
        102
        61)
    end
    object TASENTER5: TTASENTER
      Left = 580
      Top = 430
      Width = 75
      Height = 21
      AutoSize = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clRed
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      TabOrder = 27
      Text = 'Shipping Class'
      FieldName = 'total.class'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterShpVia: TTASComboEnter
      Left = 213
      Top = 111
      Width = 120
      Height = 21
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 11
      Text = 'SHIPPER NUM'
      FieldName = 'shpvia'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = '012345678 9'
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERSHPVIA.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterBilling: TTASENTER
      Left = 215
      Top = 231
      Width = 32
      Height = 21
      Hint = 
        'C - Collect'#13#10'T - Third Party'#13#10'B - Bill Shipper'#13#10'P = Prepaid'#13#10'A =' +
        ' Prepaid and Add'#13#10'N - None'
      AutoSize = False
      CharCase = ecUpperCase
      ParentShowHint = False
      ShowHint = True
      TabOrder = 18
      Text = 'ENTERBILLING'
      FieldName = 'billing.type'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = 'CTBNPA'
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterAcctNo: TTASENTER
      Left = 213
      Top = 254
      Width = 243
      Height = 21
      AutoSize = False
      ParentShowHint = False
      ShowHint = False
      TabOrder = 19
      Text = 'EnterBilling'
      FieldName = 'billing.acct'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object cbSR: TTASCheckBox
      Left = 393
      Top = 4
      Width = 131
      Height = 17
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Service and Repair'
      TabOrder = 3
      FieldName = 'SCAN.SR'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object EnterIShpCod: TTASComboEnter
      Left = 240
      Top = 160
      Width = 117
      Height = 21
      TabStop = False
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 15
      Text = 'ENTERFCUST'
      FieldName = 'drop.shpcod'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_IShpCod()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERISHPCOD.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterDrop: TTASENTER
      Left = 213
      Top = 160
      Width = 24
      Height = 21
      Hint = 'I - Intermediate Shipper'#13#10'D - Drop Ship Address'#13#10'N - None'
      AutoSize = False
      CharCase = ecUpperCase
      ParentShowHint = False
      ShowHint = True
      TabOrder = 14
      Text = 'ENTERDROP'
      FieldName = 'inter.drop'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_interdrop()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = 'IND'
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object btnAddress: TGlyphBtn
      Left = 448
      Top = 160
      Width = 80
      Height = 24
      Caption = '&Address'
      TabOrder = 28
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEB7A29363493563493563493563493563493563493563
        4935634935634935634935634935634935634935634935634935B7A293FDFBF9
        E1DCD8E0D7D2E0D7D2DFD2CADFCEC3DDC8BBDCC3B3DBBFADDBBBA7DBBBA7DBBB
        A7DBBBA7CFB4A3634935B7A293FEFEFED2B9ABCFB4A6CFB4A6CDAFA0FBECE3C7
        A594C5A08EC29B89F6D6C2BE937FBE937FBC8F7ACFB4A3634935B7A293FEFEFE
        FEFEFEFDFBF9FDFBF9FDF7F3FCF2ECFBECE3FAE7DBF8E1D2F7DBC9F6D6C2F6D6
        C2F6D2BCCFB4A3634935B7A293FEFEFEFEFEFEFDFBF9FDFBF9FDF7F3FCF2ECFB
        ECE3FAE7DBF8E1D2F7DBC9F6D6C2F6D6C2F6D2BCCFB4A3634935B7A293FEFEFE
        D6C1B5D4BDB1D4BDB1D2B9ABFDF7F3CDAFA0CAAA9AC7A594F8E1D2C29B89C29B
        89C09783CFB4A3634935BAA596FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FD
        F7F3FCF2ECFBECE3FAE7DBF8E1D2F8E1D2F7DBC9D0B9AB634935BEA99AFEFEFE
        DAC8BDD8C5BAD8C5BAD6C1B5FEFEFED2B9ABCFB4A6CDAFA0FBECE3C7A594C7A5
        94C5A08ED1C1B6634935C3AE9EFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFDFBF9FDF7F3FCF2ECFBECE3FBECE3FAE7DBD1C1B6634935C8B2A3FEFEFE
        DBCAC0DBCAC0DBCAC0DAC8BDFEFEFED6C1B5D4BDB1D2B9ABFDF7F3CDAFA0CDAF
        A0CAAA9AD1C1B6634935CCB6A7FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEFEFEFDFBF9FDF7F3FDF7F3FCF2ECFBECE3634935CCB6A7FEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FDF7
        F3FCF2ECFBECE3634935EAAA8BEAAA8BEAAA8BE9A584E9A584E99F7AE7976EE6
        8E62E58656E37D4AE37640E27239E27239E27239E27239C8622FEAAA8BFFC2A2
        FEC09FFDBD9AFDBD9AFCB996FBB590FAB08BF9AB84F8A77DF6A277F59D71F59D
        71F5996AF39565CD6531EAAA8BEAAA8BEAAA8BEAAA8BEAAA8BEAA686E9A17FE8
        9B76E7946CE68E62E58758E4814EE4814EE47B46E3763EE27239}
      GlyphKind = bkCustom
    end
    object EnterFCust: TTASComboEnter
      Left = 213
      Top = 47
      Width = 120
      Height = 21
      TabStop = False
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      ReadOnly = True
      TabOrder = 8
      Text = 'ENTERFCUST'
      FieldName = 'bill.custcode'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_cust('#39'F'#39')'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERFCUST.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterFSCust: TTASComboEnter
      Left = 213
      Top = 69
      Width = 120
      Height = 21
      TabStop = False
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 9
      Text = 'ENTERFCUST'
      FieldName = 'ship.custcode'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_fscust()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERFSCUST.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterFSONum: TTASComboEnter
      Left = 213
      Top = 25
      Width = 118
      Height = 21
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 0
      Text = 'SO FROM'
      FieldName = 'sFROM.SONUM'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_sonum()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = '012345678 9'
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERFSONUM.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER9: TTASENTER
      Left = 336
      Top = 47
      Width = 188
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 29
      Text = 'TASENTER9'
      FieldName = 'bill.custname'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER10: TTASENTER
      Left = 336
      Top = 69
      Width = 188
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 30
      Text = 'TASENTER9'
      FieldName = 'ship.custname'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object cbSONum: TTASCheckBox
      Left = 79
      Top = 3
      Width = 93
      Height = 17
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Sales Orders'
      TabOrder = 1
      FieldName = 'SCAN.SO'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object EnterTPCust: TTASENTER
      Left = 213
      Top = 277
      Width = 142
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 20
      Text = 'EnterTPCust'
      FieldName = 'third.party'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object btnSOList: TGlyphBtn
      Left = 422
      Top = 22
      Width = 75
      Height = 24
      Hint = 'Select additional SOs.'
      Caption = 'S&Os'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 31
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFF5FA6D658A2D2FEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF78B7DC2D8BC78F
        CDEB6DB7E4408EC86BADD7FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFF94CCE53F9CCE82C4E5CDF3FFC6EFFE8BD2F188CFF15FA6D62D8BC785BB
        DEFEFEFFFEFEFFFEFEFFFEFEFFB1D9EC56ADD67DC0E0C6EFFECDF3FFAAE8FF95
        E0FE41BAE745B2E589CAEF82C1EB5397D03B94CAA1CAE5FEFEFF75BDDD75BDDD
        BCE4F3DBF5FFC0EEFFA5E4FF9DE2FF95E0FE45C3EA3DB5E638AAE256AFE587C6
        ED74B3E44A90CA58A2D246AAD4E7FAFDDBF5FFC0EEFFB5EAFFAAE8FFA5E4FF95
        E0FE48C6ED43BDE93DB5E638AAE2329FDE6DB7E483C5ED2D8BC74EB0D7E2F6FD
        D5F3FFC9F0FFC0EEFFB5EAFFADE7FF7CD9FE48C6ED45C3EA43BDE93DB5E638AA
        E240A7E183C5ED338EC852B2D7E2F6FDD5F3FFCDF3FFC8EFFFBBEBFF92DBFB4F
        BEEB48C3F93BBDF048C6ED43BDE93DB5E645B2E589CAEF3593CA55B6D9E2F6FD
        DBF5FFD5F3FFBBEBFF8AD6F769C9F54CB4E98DDBFD8DDBFD48C3F93BB6EB43BD
        E94FBEEB8CD0F03593CA55B6D9E2F8FED5F3FFB0E4FA88CFF17FD0F578D0F54C
        B1E4B0E4FAB5EAFF9DE2FF78D6FE40BDF53BB6EB92D6F33B94CA4FB5D9E2F8FE
        CDEBF992D2ED84CBEC6FBFE556B1DB3B94CACEECFADBF5FFBBEBFF95E0FE77D5
        FFA5E4FF84DCFB3593CA91D2E74FB5D9A4D9ECCFEBF5BEDCED95C9DE89C3DB70
        B8D669B9DD92D6F37FD0F59DDBF8AAE2FA84CBEC51A6D57ABADDFEFEFFFEFEFF
        79C6E27EC6E0D2EDF6F6FFFFF0FEFFCBEDFB50AED98AD6F7AAE2FA92D6F363B2
        DA63B2DAC2E1F0FEFEFFFEFEFFFEFEFFFEFEFFBCE4F365BFDE94CCE5E7FAFDE2
        F6FDAFDDF2B2E4F772C0E156ADD6ADD8EBFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFA4D9EC55B6D99CD5EA88CCE74EB0D798D0E7FEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF83
        CAE479C6E2FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF}
      GlyphKind = bkCustom
    end
    object SONumGrid: TTASDataGrid
      Left = 576
      Top = 74
      Width = 102
      Height = 177
      TabStop = False
      ColCount = 1
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
      TabOrder = 32
      UpCase = False
      StartAtEnd = False
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = False
      Navigation.AllowDeleteRow = False
      Navigation.AdvanceOnEnter = False
      Navigation.AdvanceAtEnd = False
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = False
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = False
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 80
          Alignment = taLeftJustify
          Header = 'SO Numbers'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'MS Sans Serif'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'SO.LIST'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = False
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        80)
  end
    object EnterBOLNum: TTASENTER
      Left = 213
      Top = 300
      Width = 142
      Height = 21
      Hint = 'RTM Field: BOL.NUMBER'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 21
      Text = 'EnterBOLNum'
      FieldName = 'bol.number'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object cbWalmartShip: TTASCheckBox
      Left = 538
      Top = 36
      Width = 131
      Height = 17
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Walmart Shipment'
      TabOrder = 6
      FieldName = 'walmartShipment'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbWalmartMstr: TTASCheckBox
      Left = 538
      Top = 52
      Width = 131
      Height = 17
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Walmart Master'
      TabOrder = 7
      Visible = False
      FieldName = 'walmartMaster'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object EnterShipDate: TTASDateEdit
      Left = 214
      Top = 208
      Width = 119
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      TabOrder = 17
      FieldName = 'ship.date'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASCheckBox1: TTASCheckBox
      Left = 538
      Top = 20
      Width = 131
      Height = 17
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Print Manifest'
      TabOrder = 5
      FieldName = 'prt.manifest'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbUseBillTO: TTASCheckBox
      Left = 79
      Top = 91
      Width = 148
      Height = 17
      Hint = 'Check This Box the print Biil To Address on the Bill.'
      Alignment = taLeftJustify
      Caption = 'Print Bill To Address'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 10
      FieldName = 'use.bill.to'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
  end
    object cbPrtSupplement: TTASCheckBox
      Left = 538
      Top = 4
      Width = 131
      Height = 17
      Hint = 'Print Supplement Pages for BOLs with > 8 Sales Orders'
      TabStop = False
      Alignment = taLeftJustify
      Caption = 'Print Supplement'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      FieldName = 'prt.supplement'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
  end
    object TASENTER14: TTASENTER
      Left = 382
      Top = 111
      Width = 77
      Height = 21
      Hint = 'RTM Field: SCAC'
      TabStop = False
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 12
      Text = 'EnterBOLNum'
      FieldName = 'SCAC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER18: TTASENTER
      Left = 214
      Top = 134
      Width = 242
      Height = 21
      Hint = 'RTM Field:  CARRIER.NAME'
      AutoSize = False
      ParentShowHint = False
      ShowHint = True
      TabOrder = 13
      Text = 'TASENTER18'
      FieldName = 'carrier.name'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
  end
  end
  object ToolBar1: TToolBar
    Left = 0
    Top = 0
    Width = 694
    Height = 29
    Caption = 'ToolBar1'
    EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
    EdgeInner = esLowered
    TabOrder = 3
    object btnClear: TGlyphBtn
      Left = 0
      Top = 0
      Width = 75
      Height = 22
      Caption = '&Clear'
      TabOrder = 0
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4000000
        000000000000000000C8D0D4000000000000000000C8D0D4C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D400000000000000000000000000000000000000000000
        0000C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000
        C8D0D4C8D0D4000000000000000000C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D4000000000000C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4C8D0D4000000000000C8D0D4000000000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D400
        0000000080000080000000C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4000000C8D0D40000000000FF0000FF0000FF000080000000C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D400000000
        00FF0000FF0000FF0000FF000080000000C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4000000C8D0D4C8D0D40000000000FF0000FF0000FF0000000080
        80000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D4C8
        D0D40000000000FF00000000FFFF000000008080000000C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00000000FF
        FF000000008080000000C8D0D4C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D400000000FFFF00000000FFFF008080008080C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FF
        FF00FFFF00FFFF008080C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00FFFF00FFFFC8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0
        D400000000FFFF00FFFFC8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF}
      GlyphKind = bkCustom
  end
    object btnMultiSO: TGlyphBtn
      Left = 75
      Top = 0
      Width = 85
      Height = 22
      Hint = 'Print BOL for SO Lines'
      Caption = 'Multi SO'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFF858585808080A6ABADFEFEFFFEFEFFFEFEFFFEFEFF9DA2A46464646161
        61FEFEFFFEFEFFFEFEFFFEFEFFAEB2B48F8F8FABABABC9C9C9A5A5A57D7D7D78
        7878747474707070989898C4C4C49494946F7071FEFEFFFEFEFFFEFEFFB1B5B7
        C8D0D4AFB4B6929394ABB0B2FEFEFFFEFEFFFEFEFFFEFEFFA1A6A87677789EA3
        A5676868FEFEFFFEFEFFFEFEFFC1C8CCACAFB19696969191918C8C8C87878783
        83837E7E7E7A7A7A757575717171FEFEFF6D6D6DFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF7272
        72757576FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFA0A0A09C9C9C9797979292928E
        8E8E8989898484848080807E7E7EB0B0B0737373FEFEFFFEFEFFFEFEFFFEFEFF
        B9BDBFCACACADADADAB1B1B1D7D7D7A9A9A9D3D3D3A2A2A2D0D0D09A9A9ACCCC
        CC777777FEFEFFFEFEFFFEFEFFFEFEFFAFAFAFFEFEFFB8B8B8C0C6C9B1B1B1BE
        C4C7AAAAAABCC2C5A3A3A3BAC0C39B9B9B7D7D7DFEFEFFFEFEFFFEFEFFB7B7B7
        D2D2D2BFBFBFDEDEDEB9B9B9DBDBDBB2B2B2D7D7D7ABABABD4D4D4A3A3A3D0D0
        D0888888FEFEFFFEFEFFFEFEFFBBBBBBC5C5C5C4CACDC0C0C0C2C8CBBABABAC0
        C6C9B2B2B2BEC4C7ABABABBCC2C5A4A4A4999999FEFEFFFEFEFFC1C1C1D8D8D8
        E3E3E3C7C7C7E1E1E1C1C1C1DFDFDFBABABADBDBDBB3B3B3D8D8D8ABABABD4D4
        D4AAAAAAB6BCBFFEFEFFC3C3C3FCFCFCF9F9F9F9F9F9F9F9F9F9F9F9F9F9F9F9
        F9F9F9F9F9F9F9F9F3F3F3A0A1A2F1F1F1D8D8D8959697ADB2B4C4C4C4C4C4C4
        C2C2C2BFBFBFBCBCBCB9B9B9B6B6B6B2B2B2AEAEAEAAAAAAA6A6A6A1A1A1C4C4
        C4FBFBFBE4E4E498999AFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFA2A2A29D9D9D999999B5BABDFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF}
      GlyphKind = bkCustom
  end
  end
  object EvoToolBar: TToolBar
    Left = 575
    Top = 3
    Width = 117
    Height = 23
    Align = alCustom
    Anchors = [akTop, akRight]
    EdgeBorders = []
    Images = EvoToobarImages
    TabOrder = 1
    Transparent = True
    Visible = False
    object ETB5: TToolButton
      Left = 0
      Top = 0
      Caption = 'ETB5'
      Visible = False
    end
    object ETB4: TToolButton
      Left = 23
      Top = 0
      Caption = 'ETB4'
      Visible = False
    end
    object ETB3: TToolButton
      Left = 46
      Top = 0
      Caption = 'ETB3'
      Visible = False
    end
    object ETB2: TToolButton
      Left = 69
      Top = 0
      Caption = 'ETB2'
      Visible = False
    end
    object ETB1: TToolButton
      Left = 92
      Top = 0
      Caption = 'ETB1'
      Visible = False
    end
  end
  object ETBcombo: TTASComboBox
    Left = 462
    Top = 1
    Width = 168
    Height = 24
    Style = csDropDownList
    ItemHeight = 16
    TabOrder = 2
    Visible = False
    FieldName = 'ETBcomboval'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Panel2: TPanel
    Left = 0
    Top = 583
    Width = 694
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 4
    object btnBOLExit: TGlyphBtn
      Left = 599
      Top = 5
      Width = 75
      Height = 24
      Caption = 'E&xit'
      TabOrder = 1
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnBOLPrint: TGlyphBtn
      Left = 523
      Top = 5
      Width = 75
      Height = 24
      Caption = '&Print'
      TabOrder = 0
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
        99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
        ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
        666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
        A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
        8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
        EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
        BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
        E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
        E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
        CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
        F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
        C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
        CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
        C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
        DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
        EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
        B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
      GlyphKind = bkCustom
    end
    object btnBack: TGlyphBtn
      Left = 447
      Top = 5
      Width = 75
      Height = 24
      Caption = '&Back'
      TabOrder = 2
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFE3A592C3F572DFFFFFEFFFFFE3A582FFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE3263357EB987336430FFFFFE26653380
        B78A3D5D3AFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE33693A
        65B8916AC69D1E6D3A1D6C396AC69B67B89139673CFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFE48724271BC8671D8B36AD8B47ADCA880DDA677D9AD74
        C7A0447049FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE4A7A4A7CCC97
        71DFBB6AE0BD7EE3AF8AE4A87CCD963D7A4EFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFE3E815469C9A47DE7BE2B864F3B854B498150FF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        41845781CB974B854EFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE5B8659648559FFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnCFG: TGlyphBtn
      Left = 447
      Top = 5
      Width = 75
      Height = 24
      Caption = 'Se&ttings'
      TabOrder = 3
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object btnItems: TGlyphBtn
      Left = 4
      Top = 5
      Width = 75
      Height = 24
      Caption = '&Lines'
      TabOrder = 4
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFEFEFEFE
        D7CFBEB7A9968A78617D6650C2AB95FEFEFEFEFEFEFEFEFEA8AAAA6B7275626E
        70899694FEFEFEFEFEFEFEFEFEB4B19C817962C9B49EDEBFA8A8816B9A72609E
        7E71B7A49F7375768A9AA165818C64818F58707C6B7B87CDD3DAFEFEFE7F7F67
        CCC5ACFFFAE0D3AA939B6652BC8878A9827A655150A3ADB4D5F2FF719EB34A78
        906588A2485D7851566FFEFEFEA6A98FFAF1D6F8DBC0D1A189BD806CB17368AD
        807C8E7D8099A9B5B0DBEE649EBB296688507DA35A739D60648DFEFEFE707359
        E8E1C6D0B59BA0745CB47B66B98275A9837E6E6365A2B8C35E90A440809E2363
        863666906784B1626897FEFEFE8C8B769B957EA18B72BB9C83D0A791A37F6D7F
        6B6081828058747B54829384BDD675AECE45709748648D57608BFEFEFE7A7566
        7B7362C1B3A0E0D2BBE0D0B9BFB49E6D6E5E4C5C5153727179A2AB8FBDCF92BE
        D68BADCA68809E535E7CFEFEFEFEFEFEA69D94626153A9B09B95A489778E7284
        A188809E8B3B5B50628180526F7487A0AA6A808C8597A2FEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEADC6B25E866AA6D8B6BDEFCF5784694F6F5C62786C42504CB2BA
        B9FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE9DC2AE71AC8D9FE4BF8F
        D2AB7AB28F7A9D8393A693676B5FC9C7BDFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEB7DDCB579676A0E9C18FD7AD3A775141674972866F757869D4D1
        C3FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEA8C8B76DA18364A37C37
        7950609B75709C7F55725B556254CAD0C5FEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEBED4C2466C4E72A580A7DEB7ADE5C2B6E6CA6087724D675AC5D5
        CEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEA3B99C72926F74
        9E7BB0E1C1679B836697877BA59EFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFE94B7953A694972A891FEFEFEFEFEFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE}
      GlyphKind = bkCustom
  end
    object btnEditSave: TGlyphBtn
      Left = 210
      Top = 5
      Width = 65
      Height = 23
      Caption = '&Save'
      TabOrder = 5
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object btnDelete: TGlyphBtn
      Left = 145
      Top = 5
      Width = 65
      Height = 23
      Caption = '&Delete'
      TabOrder = 6
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4000000
        000000000000000000C8D0D4000000000000000000C8D0D4C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D400000000000000000000000000000000000000000000
        0000C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000
        C8D0D4C8D0D4000000000000000000C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D4000000000000C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4C8D0D4000000000000C8D0D4000000000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D400
        0000000080000080000000C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4000000C8D0D40000000000FF0000FF0000FF000080000000C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D400000000
        00FF0000FF0000FF0000FF000080000000C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4000000C8D0D4C8D0D40000000000FF0000FF0000FF0000000080
        80000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D4C8
        D0D40000000000FF00000000FFFF000000008080000000C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00000000FF
        FF000000008080000000C8D0D4C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D400000000FFFF00000000FFFF008080008080C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FF
        FF00FFFF00FFFF008080C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00FFFF00FFFFC8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0
        D400000000FFFF00FFFFC8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF}
      GlyphKind = bkCustom
    end
    object btnEdit: TGlyphBtn
      Left = 80
      Top = 5
      Width = 65
      Height = 23
      Caption = '&Edit'
      TabOrder = 7
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF75716E57
        5451000000919698FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFA39D98FDFEFE5193A90E1216939C9FFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFB7A29363493563493563493563493586796EA39D9888
        B7C774CEE2499AB20E1216777570634935634935634935FEFEFFB7A293FDFBF9
        E1DCD8E0D7D2DFD2CADFCEC3C3BDB84D9CB38CE0EE62BFD7499AB20E1216B3A6
        9BCFB4A3634935FEFEFFB7A293FEFEFED2B9ABCFB4A6CDAFA0FBECE3C2A79AAC
        A4A057A0B58CE0EE62BFD7499AB20E1216AAA198634935FEFEFFB7A293FEFEFE
        FEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD7D0C965A6B78CE0EE62BFD7499A
        B20E12166F6A63FEFEFFB7A293FEFEFED6C1B5D4BDB1D2B9ABFDF7F3CDAFA0CA
        AA9AC7A594D7D0C973ACB98CE0EE6CC4D97D86863535908D90A6BAA596FEFEFE
        FEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD7D0C97DB0BBCAB8
        AC7385D15E6CAD353590BEA99AFEFEFEDAC8BDD8C5BAD6C1B5FEFEFED2B9ABCF
        B4A6CDAFA0FBECE3C7A594AFA7A35E6CAD708FDF5E76D05E6CADC3AE9EFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD0C9
        D45E6CAD5E6CADAEB2BEC8B2A3FEFEFEDBCAC0DBCAC0DAC8BDFEFEFED6C1B5D4
        BDB1D2B9ABFDF7F3CDAFA0CAAA9AC8AFA2D1C1B6857568FEFEFFCCB6A7FEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFCF2
        ECFBECE3634935FEFEFFEAAA8BEAAA8BEAAA8BE9A584E99F7AE7976EE68E62E5
        8656E37D4AE37640E27239E27239E27239E27239C8622FFEFEFFEAAA8BFFC2A2
        FEC09FFDBD9AFCB996FBB590FAB08BF9AB84F8A77DF6A277F59D71F5996AF395
        65F39565CD6531FEFEFFEAAA8BEAAA8BEAAA8BEAAA8BEAA686E9A17FE89B76E7
        946CE68E62E58758E4814EE47B46E3763EE3763EE27239FEFEFF}
      GlyphKind = bkCustom
    end
    object btnSaveExit: TGlyphBtn
      Left = 600
      Top = 5
      Width = 75
      Height = 24
      Caption = 'E&xit'
      TabOrder = 8
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnCarrier: TGlyphBtn
      Left = 81
      Top = 5
      Width = 75
      Height = 24
      Caption = '&Carrier'
      TabOrder = 9
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C0C0C0000000
        000000000000C0C0C0000000000000000000000000C0C0C0C0C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0000000000000000000000000319CCE009CCE00
        3131009CCE000000000000C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0000000000000
        319CCE00639C009CCE000000009CCE00313100CEFF00CEFF009CCE0000000000
        00C0C0C0C0C0C0C0C0C0000000009CCE00CEFF00313100636300639C009CCE00
        313100000000000000CEFF00CEFF009CCE000000000000C0C0C0C0C0C0000000
        00CEFF003131319CCE319CCE009CCE003131C0C0C0C0C0C000000000000000CE
        FF00CEFF009CCE000000C0C0C000000000CEFF00636352525200639C009CCE00
        3131000000C0C0C0C0C0C0C0C0C0000000000000000000C0C0C0C0C0C0000000
        000000009CCE52525200639C00CEFF000000009CCE000000000000C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C000000000CEFF525252009CCE00313100
        000000CEFF00CEFF009CCE000000C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0
        00000000000000CEFF00CEFF000000C0C0C0000000000000000000C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0000000C0C0C0000000000000C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0
        000000C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0000000C0C0C0C0C0C0C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0
        000000000000C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0000000000000C0C0C0000000C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0000000C0C0C0
        000000C0C0C0000000C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0000000000000000000C0C0C0C0C0C0C0C0C0C0
        C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0C0}
      GlyphKind = bkCustom
    end
    object btnCarrierExit: TGlyphBtn
      Left = 601
      Top = 5
      Width = 75
      Height = 24
      Caption = '&Back'
      TabOrder = 10
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFE3A592C3F572DFFFFFEFFFFFE3A582FFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE3263357EB987336430FFFFFE26653380
        B78A3D5D3AFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE33693A
        65B8916AC69D1E6D3A1D6C396AC69B67B89139673CFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFE48724271BC8671D8B36AD8B47ADCA880DDA677D9AD74
        C7A0447049FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE4A7A4A7CCC97
        71DFBB6AE0BD7EE3AF8AE4A87CCD963D7A4EFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFE3E815469C9A47DE7BE2B864F3B854B498150FF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        41845781CB974B854EFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE5B8659648559FFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
  end
  object EvoToobarImages: TImageList
    Left = 171
    Top = 65521
    Bitmap = {
      494C010106000900B40010001000FFFFFFFFFF10FFFFFFFFFFFFFFFF424D3600
      0000000000003600000028000000400000002000000001002000000000000020
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000007373730073737300737373000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000CE944200CE8C3100D69C
      5200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000073737300BD632900AD6B42006B524A007373730000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000DEA55200BD843900000000000000
      0000D69C5200B57B39006B5231006B5231006B5231006B5231006B5231000000
      000000000000000000000000000000000000000000007373730073737300BD63
      2900EF7B0800FF732100FF940800FFAD310094634A007373730073737300B57B
      5A00737373007373730073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFAD4200AD7B4200000000000000
      00006B523100C67B3100DE943900EFAD4200F7B55200DEB56300EFAD42006B52
      31006B5231000000000000000000000000008452520084525200E79C5A00EF84
      1000D6846300FFAD3100FF8C0800FFA51000FFBD6300AD7B6B0084525200FF94
      0000845252008452520073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFB54A00AD7B4200000000006B52
      3100E79C3100F79C3900EF943100EF9C3100F7A53900F7BD5200FFD67300EFCE
      8C00B57B39006B523100000000000000000094634A00F7F7E700F7F7E700F7F7
      E700FFF7E700F7DEAD00F7941800FF940000FFAD3100FFC68400FFBD5A00FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000E7AD6300DE9C29006B523100F7A5
      3100EF9C3100E7942900E79429007352310073523100B5732900F7B54200FFD6
      6B00F7D69400B57B3900000000000000000094636300FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00F7DEAD00FF9C0800FF9C0800FFBD5A00FFC68400FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000F7B53900F7AD3100EFA5
      2900E7942900DE8C290084522900000000000000000000000000B5732900F7AD
      3900FFD66B00DEB57B00B57B390000000000A56B6B00FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00F7941800FFAD2900FF940000FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000E7B56300F7B53100EFA5
      2900E7942100A56318006B5231006B5231006B5231006B5231006B5231006B52
      31006B5231006B5231006B52310000000000AD7B6B00FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FF5A3100EF6B4200EF523100EF6B4200FF5A
      3100FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F7BD3900EFAD
      2900E79C2100D67B2900D67B2900D67B2900D67B2900D67B2900D67B2900D67B
      2900D67B2900D67B2900B57B390000000000B58C7300FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00CECECE00D6D6D600F7EFDE00F7E7
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000F7C6
      4200EFAD2900E79C2100DE942100E7942900E7942900E7942900E7942900EF94
      3100F79C3900EFA54200B57B390000000000B58C7300FFFFFF00FF5A3100EF6B
      4200E7522900C6734200C68C7B00FFFFFF00FFFFFF00FFFFFF00294A84007394
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000EFCE940000000000F7C6
      4200F7C64200BD8429006B4A21000000000000000000B5732900CE8C3100EF94
      2900EF9C3100EF9C3100B57B390000000000C6947B00FFFFFF00FF8C0800FF8C
      0800FF5A3100AD4A1800FFF7EF00FFFFFF00FFFFFF00FFFFFF007394D6007394
      D600FFFFF700AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000EFCE94000000
      0000F7C64200E7AD39006B5229005A42290073523100B5732900E79C2900E794
      2900F7A53900B57B39000000000000000000D6A58400FFFFFF00FF8C0800FFBD
      5A00FFAD2900F7941800BD632900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
      FF00FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000D6BD8C00E7CE
      8C0000000000F7DE8C00E7B53900B5842100CE8C2100E7A52900E79C2100EFA5
      2900EFA53900B57B39000000000000000000DEAD8400DEAD8400FF8C0800DEAD
      8400F7A55A00FFC68400EF943900BD632900C69C9400C69C9400C69C9400C69C
      9400C69C9400AD7B7B0000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000D6BD
      8C00D6BD8C00E7D66300E7D66300F7D64200F7B53100EFAD2900EFAD2900EFA5
      3100B57B390000000000EFAD4200000000000000000000000000FF8C08000000
      000000000000F7A55A00FFDEAD00EFB58C00BD632900BD523900C6734200A563
      4200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000D6BD8C00D6BD8C00D6BD8C00DEB55200FFCE4A00B57B3900B57B
      39000000000000000000EFAD4200000000000000000000000000000000000000
      00000000000000000000F7A55A00FFEFBD00FFE7AD00DE8C5200944A18000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000AD9A880046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000AD9A8800CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000212121004242
      3900424239004242390042423900424239004242390042423900424239004242
      3900424239004242390042423900000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000AD9A
      8800FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B7B00F7F7
      FF00F7F7FF00F7F7FF00BDBDBD00F7F7FF00F7F7FF00003939005A5A5A00F7EF
      E700F7F7FF00F7F7FF0042423900000000000000000046403800464038004640
      380046403800464038004640380046403800464038004640380046403800FFE8
      D400FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000027596100000000000000000027596100000000000000
      00000000000000000000000000000000000000000000000000005A5A5A00BDBD
      BD00BDBDBD00BDBDBD009C9C9400BDBDBD00BDBDBD005A5A5A0042BDBD005252
      4A00BDBDBD00BDBDBD004242390000000000AD9A8800FFE5CE00CAB39E00CAB3
      9E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00FFE8D400FFEB
      D900FFEBD900FFEBD900BBA69200464038008080000080800000800000008000
      0000800000008000000080000000800000008000000080000000800000008000
      0000800000008000000080000000000000000000000027596100000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000275961000000000000000000000000005A5A5A00DED6
      D600DED6D600DED6D600ADADAD00DED6D600DED6D600F7F7FF005A5A5A005ADE
      DE0052524A00F7EFE7004242390000000000AD9A8800FFEDDD00FFE3C900FFE3
      C900FFE3C900FFE3C9008B7C6D0000000000EDD2B900FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BBA692004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      6100000000000000000080808000808080008080800080808000000000000000
      0000275961002759610000000000000000000000000000000000393900003939
      00003939000039390000393900003939000052523100ADADAD009C9C94005A5A
      5A005ADEDE0052524A002121210000000000AD9A8800FFF1E400FFE3C900FFE3
      C900FFE3C900FFE3C900F2D6BD00ECD1B800FFE5CE00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BFAA96004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF00FFFF
      FF00C8D0D4000000000080000000000000000000000000000000275961002759
      6100000000008080800091919100838383008080800080808000808080000000
      0000275961002759610000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000DED6D600BDBDBD00F7F7
      FF007B7B7B006BADAD004242390000000000AD9A8800FFF4EA00FDE0C600FFE3
      C900FFE3C900FFE3C9008B7C6D0076695C00DCC3AD00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400C4AE99004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      61000000000080808000AAAAAA00919191008383830080808000808080000000
      00002759610027596100000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD005A5A5A005ADEDE0021212100AD9A8800FFF7F000FADEC400FADE
      C400FFE3C900FFE3C900DCC3AD00655A4E006F635700F4D8BF00FFE8D400FFE8
      D400FFE8D400FFE8D400CAB39E004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF000000
      0000FFFFFF0000000000800000000000000000000000000000002E6770002E67
      70000000000080808000AAAAAA00AAAAAA009191910080808000808080000000
      00002E6770002E67700000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF00393939005A9C9C00AD9A8800FFF9F300FADEC400FADE
      C400FADEC400FFE3C900FFE3C900DCC3AD00524840005F544A00FADEC400FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000377E8800377E
      8800000000000000000080808000808080008080800080808000000000000000
      0000377E8800377E880000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD00BDBDBD004242390000000000AD9A8800FFF9F300F6DAC000FADE
      C400EDD2B900D1BAA400DCC3AD00FFE3C900B29D8B0083746600C2AC9700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF000000000000C8D0
      D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400808000008080
      00008080000080800000800000000000000000000000000000004397A3004397
      A3004397A3000000000000000000000000000000000000000000000000004397
      A3004397A3004397A300000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF004242390000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00D1BAA400524840005C524800ECD1B800726559005F544A00D5BCA700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF0000000000FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00C8D0D400808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B0000393900005A5A5A005A5A5A007B7B
      7B007B7B7B007B7B7B002121210000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00F4D8BF00AA978500000000000000000000000000B29D8B00FFE3C900FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF0000000000000000
      0000000000000000000000000000000000000000000000000000808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      00000000000091919100000000004EA9B6004EA9B60000000000919191000000
      00000000000000000000000000000000000000000000000000009C9C0000ADAD
      6B00BD9C7B00BD9C7B00BD9C7B007B7339003939000042423900000000000000
      000000000000000000000000000000000000AD9A8800FFF9F300FFF9F300FFF9
      F300FFF9F300FFF9F300FFF9F300FFF9F300FFF9F300FFF4EA00FFF1E400FFF1
      E400FFEBD900FFEBD900FFE5CE004640380080800000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF0080800000000000000000000000000000000000000000
      0000000000000000000091919100000000000000000091919100000000000000
      00000000000000000000000000000000000000000000000000007B7B00005A5A
      5A005A5A5A005A5A5A005A5A5A00313131003939000042423900000000000000
      00000000000000000000000000000000000000000000AD9A8800AD9A8800AD9A
      8800A69382009C8B7B0092827300857669007B6D600072655900655A4E005248
      4000524840004640380046403800000000000000000080800000808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080800000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B00007B7B
      00007B7B00007B7B00007B7B00007B7B00002121000000000000000000000000
      000000000000000000000000000000000000424D3E000000000000003E000000
      2800000040000000200000000100010000000000000100000000000000000000
      000000000000000000000000FFFFFF00FFFFFFFF00000000FFFFF8FF00000000
      8FFFF07F00000000301F80010000000030070001000000002003000100000000
      000300010000000081C10001000000008001000100000000C001000100000000
      E001000100000000A181000100000000D003000100000000C803000300000000
      E005D80F00000000F80DFC1F00000000FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFF1FFFFFFFFC001FFE1FFFFFFFFC00180018001FC3FC001000000008001C001
      0000000080018000000000008001800000000000800180000000000080018000
      00000000800180000000000080018001000000008001800100000000C813803F
      00000000FC3F803F80018001FFFF807F00000000000000000000000000000000
      000000000000}
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 222
    Top = 65528
  end
end
