object EditForm1: TEditForm1
  Left = 446
  Top = 253
  Hint = 'C:\TASPRO7\DBA7\T7INAUSG.DFM'
  AutoScroll = False
  Caption = 'Item Usage'
  ClientHeight = 499
  ClientWidth = 622
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  No_Refresh = False
  OnStart = 'USGOnStart'
  OnDisplayScreen = 'T7INAUSG.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  RememberSize = True
  RememberSizeDate = 45594.699228425930000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object MultiUsageGrid: TTASDataGrid
    Left = 0
    Top = 80
    Width = 622
    Height = 385
    Align = alClient
    Color = clMenu
    ColCount = 7
    RowCount = 19
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    GridLineWidth = 0
    Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
    ParentFont = False
    TabOrder = 3
    UpCase = False
    StartAtEnd = False
    PrePrgLoc = 0
    PostPrgLoc = 0
    Navigation.AllowInsertRow = False
    Navigation.AllowDeleteRow = True
    Navigation.AdvanceOnEnter = False
    Navigation.AdvanceAtEnd = False
    Navigation.AdvanceDirection = adLeftRight
    Navigation.AdvanceAuto = False
    Navigation.InsertPosition = pInsertBefore
    Navigation.CursorWalkEditor = False
    Navigation.AllowAddRecListF = False
    MouseActions.ColSelect = False
    MouseActions.RowSelect = False
    MouseActions.DirectEdit = False
    MouseActions.DirectComboDrop = False
    MouseActions.CaretPositioning = False
    PasswordChar = '*'
    Columns = <
      item
        Color = clMenu
        Width = 96
        Alignment = taLeftJustify
        Header = 'Period'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.MONTH'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
    end
      item
        Color = clMenu
        Width = 85
        Alignment = taRightJustify
        Header = 'Current Year'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.CURRENT'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
    end
      item
        Color = clMenu
        Width = 86
        Alignment = taRightJustify
        Header = '1 Year'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.YEAR1'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
      end
      item
        Color = clMenu
        Width = 85
        Alignment = taRightJustify
        Header = '2 Years'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.YEAR2'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
      end
      item
        Color = clMenu
        Width = 76
        Alignment = taRightJustify
        Header = '3 Years'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.YEAR3'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
      end
      item
        Color = clMenu
        Width = 79
        Alignment = taRightJustify
        Header = '4 Years'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.YEAR4'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
      end
      item
        Color = clMenu
        Width = 86
        Alignment = taRightJustify
        Header = '5 Years'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        Editor = edDefault
        Fixed = False
        ReadOnly = False
        Password = False
        ComboItemsSort = False
        SpinMin = 0
        SpinMax = 0
        SpinStep = 0
        EditLength = 0
        Borders = []
        BorderPen.Color = clSilver
        FieldName = 'USAGE.YEAR5'
        CharCase = ecNormal
        PrePrgLoc = 0
        PostPrgLoc = 0
        ValidPrgLoc = 0
        ClickPrgLoc = 0
        ChangePrgLoc = 0
        DecimalChrs = 2
        FormatOnEnter = True
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        TimeFieldType = tf_5
        ElapsedTime = False
      end>
    ExtraFields = <>
    AutoNumAlign = False
    SelectionColor = clHighlight
    SelectionTextColor = clHighlightText
    SelectionRectangle = False
    FixedFont.Charset = DEFAULT_CHARSET
    FixedFont.Color = clWindowText
    FixedFont.Height = -13
    FixedFont.Name = 'Arial'
    FixedFont.Style = []
    VAlignment = vtaTop
    Hovering = False
    EnhRowColMove = True
    HintColor = clYellow
    CurrentRow = 1
    CurrentCol = 1
    GridFileHandle = 0
    GridFileKeyNum = 0
    NoAutoUpdate = False
    ColWidths = (
      96
      85
      86
      85
      76
      79
      86)
    end
    object UsageGrid: TTASDataGrid
    Left = 0
    Top = 80
    Width = 622
    Height = 385
    Align = alClient
      Color = clMenu
      ColCount = 1
      RowCount = 19
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = []
      GridLineWidth = 0
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
      ParentFont = False
    TabOrder = 2
      UpCase = False
      StartAtEnd = False
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = False
      Navigation.AllowDeleteRow = True
      Navigation.AdvanceOnEnter = False
      Navigation.AdvanceAtEnd = False
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = False
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = False
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clMenu
          Width = 484
          Alignment = taLeftJustify
          Header = '  Date                                            Totals'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Courier New'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'USAGE.TOTALS'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = True
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        484)
    end
  object Panel2: TPanel
    Left = 0
    Top = 465
    Width = 622
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    object ExitUSAGE: TGlyphBtn
      Left = 529
      Top = 5
      Width = 75
      Height = 25
      Caption = 'E&xit'
      ModalResult = 2
      TabOrder = 0
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnUPDUsage: TGlyphBtn
      Left = 10
      Top = 5
      Width = 75
      Height = 25
      Hint = 'Show/Update 5 Year Usage'
      Caption = '5 Years'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        180000000000000300000000000000000000000000000000000030241847372A
        3927164B351C3D260C4B351C4B3620412E19362210422E1C442E1C49311D4C31
        1C3A1E06694A31644329594A3AFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE433120FEFEFE
        63482D603C14663F1374502AFEFEFE795B3E664A2C53341563401EFFDBB67347
        1E6B3C1073441890623964513CFEFEFE4D3011FAD1A4F1C596704A20FEFEFE5A
        3B1C498D548EC69789634092673C9A693B73400E8D592A99683C432E18FEFEFE
        694B28F4CA9DFCD1A058310AFEFEFE583A1FACD5B36CB5778D6744E4B78CFFE4
        B4FFD19EFFF5C3D9A87C5B452CFEFEFE563612FAD0A3F4C8995C3711FEFEFE5E
        43296CB57735663DFFF3D163360BFFD7A7FFCB98EFBA88FFCFA54E371DFEFEFE
        684824F8CEA1FFD8AB66421EFEFEFE5A422C6CB5776CB577FFFCDE73471EEFBE
        90FFD8A6F3C193F9CCA6624B35FEFEFE543718F1CAA3F2C9A2623F1EFEFEFE53
        392135663DD8EBDBFFFFE5724720F7CA9EFFD0A4EEBE94F7CDAA4D3D2DFEFEFE
        664D39E9C9ACEFCCAB664322FEFEFE7A583A35663DD8EBDBFFFFE2693F1AF0C7
        A0F2C9A2FFD8B3EDC7A544352CFEFEFE311C0DEACEB6D1B396654627FEFEFE46
        230235663DACD5B3D8EBDB643E1BF7D3AFDDB896F5D2B0E5C3A54C3D34FEFEFE
        6855464D351F5D4228785B40FEFEFE5D3D206CB5776CB577D8EBDB6444215C3B
        1A68462854351672543943362EFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE69
        4E346CB57735663DACD5B3FFFFE6FFFADCFFFFE9FFFCE2FFEAD2493E36FEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFE705B45ACD5B36CB5772C5433B49D83EFDA
        BFFFEDD4FFF1DBD2BFAA281F16FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE45
        36238EC6978EC6972C54338E7C6595856E51402B5445329A8C7A494037FEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFE342A194E42304C3E2B40321FFEFEFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE}
      GlyphKind = bkCustom
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 622
    Height = 80
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 0
    object Label1: TLabel
      Left = 28
      Top = 10
      Width = 74
      Height = 16
      Caption = 'Item Number'
    end
    object Label2: TLabel
      Left = 28
      Top = 34
      Width = 65
      Height = 16
      Caption = 'Description'
    end
    object Label3: TLabel
      Left = 416
      Top = 10
      Width = 27
      Height = 16
      Caption = 'Type'
    end
    object Item14: TTASComboEnter
      Left = 125
      Top = 8
      Width = 121
      Height = 21
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      ReadOnly = True
      TabOrder = 0
      Text = 'Item'
      FieldName = 'BKIC.PROD.CODE '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER1: TTASENTER
      Left = 124
      Top = 32
      Width = 251
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 1
      Text = 'TASENTER1'
      FieldName = 'BKIC.PROD.DESC '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER2: TTASENTER
      Left = 124
      Top = 56
      Width = 252
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 2
      Text = 'TASENTER1'
      FieldName = 'BKIC.PROD.NOTE '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object Itype: TTASENTER
      Left = 488
      Top = 5
      Width = 18
      Height = 21
      TabStop = False
      AutoSize = False
      CharCase = ecUpperCase
      ReadOnly = True
      TabOrder = 3
      FieldName = 'MTIC.PROD.TYPE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = 'YNEOD'
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
end
