object EditForm1: TEditForm1
  Left = 333
  Top = 241
  Hint = 'C:\TASPRO7\DBA7\T7POENG.DFM'
  AutoScroll = False
  Caption = 'PO-ENG'
  ClientHeight = 617
  ClientWidth = 783
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7POENG.OnClose'
  No_Refresh = False
  OnStart = 'T7POENG.OnStart'
  OpenFiles = 'T7POENG.OnOpenFiles'
  OnDisplayScreen = 'T7POENG.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7POENG'
  RememberSize = True
  RememberSizeDate = 45404.598401296290000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Userdefined: TPanel
    Left = 0
    Top = 58
    Width = 765
    Height = 473
    ParentBackground = False
    TabOrder = 5
    object Label12: TLabel
      Left = 232
      Top = 29
      Width = 292
      Height = 23
      Caption = 'User Defined  Sort / Break Report'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Arial Black'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label76: TLabel
      Left = 233
      Top = 94
      Width = 39
      Height = 16
      Caption = 'Layout'
    end
    object Label77: TLabel
      Left = 233
      Top = 149
      Width = 42
      Height = 16
      Caption = 'Index 1'
    end
    object Label78: TLabel
      Left = 233
      Top = 175
      Width = 42
      Height = 16
      Caption = 'Index 2'
    end
    object Label79: TLabel
      Left = 233
      Top = 201
      Width = 42
      Height = 16
      Caption = 'Index 3'
    end
    object Label80: TLabel
      Left = 233
      Top = 227
      Width = 42
      Height = 16
      Caption = 'Index 4'
    end
    object Label81: TLabel
      Left = 233
      Top = 253
      Width = 42
      Height = 16
      Caption = 'Index 5'
    end
    object Label82: TLabel
      Left = 233
      Top = 279
      Width = 42
      Height = 16
      Caption = 'Index 6'
    end
    object Label83: TLabel
      Left = 233
      Top = 305
      Width = 42
      Height = 16
      Caption = 'Index 7'
    end
    object Label84: TLabel
      Left = 233
      Top = 331
      Width = 42
      Height = 16
      Caption = 'Index 8'
    end
    object Label85: TLabel
      Left = 233
      Top = 357
      Width = 42
      Height = 16
      Caption = 'Index 9'
    end
    object Label86: TLabel
      Left = 233
      Top = 383
      Width = 49
      Height = 16
      Caption = 'Index 10'
    end
    object Label2: TLabel
      Left = 302
      Top = 126
      Width = 56
      Height = 16
      Caption = 'Sort Field'
    end
    object cbIndex1: TTASComboBox
      Left = 289
      Top = 146
      Width = 120
      Height = 24
      Ctl3D = True
      ItemHeight = 16
      ParentCtl3D = False
      TabOrder = 1
      Text = 'TASComboBox1'
      FieldName = 'index.text[1]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(1)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex2: TTASComboBox
      Left = 289
      Top = 172
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 2
      Text = 'TASComboBox1'
      FieldName = 'index.text[2]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(2)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex3: TTASComboBox
      Left = 289
      Top = 198
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 3
      Text = 'TASComboBox1'
      FieldName = 'index.text[3]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(3)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex4: TTASComboBox
      Left = 289
      Top = 224
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 4
      Text = 'TASComboBox1'
      FieldName = 'index.text[4]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(4)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex5: TTASComboBox
      Left = 289
      Top = 250
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 5
      Text = 'TASComboBox1'
      FieldName = 'index.text[5]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(5)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex6: TTASComboBox
      Left = 289
      Top = 276
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 6
      Text = 'TASComboBox1'
      FieldName = 'index.text[6]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(6)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex7: TTASComboBox
      Left = 289
      Top = 302
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 7
      Text = 'TASComboBox1'
      FieldName = 'index.text[7]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(7)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex8: TTASComboBox
      Left = 289
      Top = 328
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 8
      Text = 'TASComboBox1'
      FieldName = 'index.text[8]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(8)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex9: TTASComboBox
      Left = 289
      Top = 354
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 9
      Text = 'TASComboBox1'
      FieldName = 'index.text[9]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(9)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbIndex10: TTASComboBox
      Left = 289
      Top = 378
      Width = 120
      Height = 24
      ItemHeight = 16
      TabOrder = 10
      Text = 'TASComboBox1'
      FieldName = 'index.text[10]'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_index(10)'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object GroupBox1: TGroupBox
      Left = 422
      Top = 63
      Width = 185
      Height = 360
      Ctl3D = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentBackground = False
      ParentCtl3D = False
      ParentFont = False
      TabOrder = 11
      object Label3: TLabel
        Left = 19
        Top = 62
        Width = 66
        Height = 16
        Caption = 'Break Field'
      end
      object rbLayout: TTASRadioButton
        Left = 17
        Top = 29
        Width = 72
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Break'
        TabOrder = 0
        FieldName = 'use.lay.break'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex1: TTASRadioButton
        Left = 40
        Top = 86
        Width = 15
        Height = 17
        TabOrder = 1
        FieldName = 'UDBRK.ARRAY[1]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex2: TTASRadioButton
        Left = 40
        Top = 112
        Width = 15
        Height = 17
        TabOrder = 2
        FieldName = 'UDBRK.ARRAY[2]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex3: TTASRadioButton
        Left = 40
        Top = 138
        Width = 15
        Height = 17
        TabOrder = 3
        FieldName = 'UDBRK.ARRAY[3]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex4: TTASRadioButton
        Left = 40
        Top = 164
        Width = 15
        Height = 17
        TabOrder = 4
        FieldName = 'UDBRK.ARRAY[4]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex5: TTASRadioButton
        Left = 40
        Top = 190
        Width = 15
        Height = 17
        TabOrder = 5
        FieldName = 'UDBRK.ARRAY[5]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex6: TTASRadioButton
        Left = 40
        Top = 216
        Width = 15
        Height = 17
        TabOrder = 6
        FieldName = 'UDBRK.ARRAY[6]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex7: TTASRadioButton
        Left = 40
        Top = 242
        Width = 15
        Height = 17
        TabOrder = 7
        FieldName = 'UDBRK.ARRAY[7]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex8: TTASRadioButton
        Left = 40
        Top = 268
        Width = 15
        Height = 17
        TabOrder = 8
        FieldName = 'UDBRK.ARRAY[8]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex9: TTASRadioButton
        Left = 40
        Top = 294
        Width = 15
        Height = 17
        TabOrder = 9
        FieldName = 'UDBRK.ARRAY[9]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object rbIndex10: TTASRadioButton
        Left = 40
        Top = 320
        Width = 15
        Height = 17
        TabOrder = 10
        FieldName = 'UDBRK.ARRAY[10]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = False
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
    end
    object cbLayout: TTASComboBox
      Left = 289
      Top = 90
      Width = 120
      Height = 24
      Ctl3D = True
      ItemHeight = 16
      ParentCtl3D = False
      TabOrder = 0
      Text = 'cbLayout'
      FieldName = 'laysort.text'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_laysort()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object ToolBar1: TToolBar
    Left = 0
    Top = 0
    Width = 783
    Height = 30
    Caption = 'ToolBar1'
    EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
    EdgeInner = esLowered
    TabOrder = 2
    Transparent = True
    object Label1: TLabel
      Left = 0
      Top = 0
      Width = 38
      Height = 22
      AutoSize = False
      Caption = ' Title'
      Transparent = True
    end
    object REPORT_TITLE: TTASENTER
      Left = 38
      Top = 0
      Width = 488
      Height = 22
      TabStop = False
      AutoSelect = False
      AutoSize = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentCtl3D = False
      ParentFont = False
      ReadOnly = True
      TabOrder = 0
      FieldName = 'REPORT.TITLE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object EvoToolBar: TToolBar
    Left = 645
    Top = 3
    Width = 116
    Height = 25
    Align = alCustom
    Anchors = [akTop, akRight]
    EdgeBorders = []
    Images = EvoToobarImages
    TabOrder = 3
    Transparent = False
    Visible = False
    object ETB5: TToolButton
      Left = 0
      Top = 0
      Caption = 'ETB5'
      Visible = False
    end
    object ETB4: TToolButton
      Left = 23
      Top = 0
      Caption = 'ETB4'
      Visible = False
    end
    object ETB3: TToolButton
      Left = 46
      Top = 0
      Caption = 'ETB3'
      Visible = False
    end
    object ETB2: TToolButton
      Left = 69
      Top = 0
      Caption = 'ETB2'
      Visible = False
    end
    object ETB1: TToolButton
      Left = 92
      Top = 0
      Caption = 'ETB1'
      Visible = False
    end
  end
  object ETBcombo: TTASComboBox
    Left = 561
    Top = 2
    Width = 168
    Height = 24
    Style = csDropDownList
    ItemHeight = 16
    TabOrder = 4
    Visible = False
    FieldName = 'ETBcomboval'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Panel3: TPanel
    Left = 0
    Top = 583
    Width = 783
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    object btnExit: TGlyphBtn
      Left = 697
      Top = 6
      Width = 75
      Height = 23
      Caption = 'E&xit'
      TabOrder = 1
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnPrint: TGlyphBtn
      Left = 621
      Top = 6
      Width = 75
      Height = 23
      Caption = '&Print'
      TabOrder = 0
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
        99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
        ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
        666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
        A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
        8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
        EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
        BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
        E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
        E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
        CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
        F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
        C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
        CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
        C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
        DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
        EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
        B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
      GlyphKind = bkCustom
    end
    object btnCFG: TGlyphBtn
      Left = 545
      Top = 6
      Width = 75
      Height = 23
      Caption = 'Se&ttings'
      TabOrder = 2
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object btnUserDef: TGlyphBtn
      Left = 7
      Top = 6
      Width = 113
      Height = 23
      Caption = '&User Defined'
      TabOrder = 3
      TabStop = False
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        18000000000000030000000000000000000000000000000000004B4B4B000000
        0000000000000000000000000000000000000000000000000000000000000000
        00000000000000000000888888E6F1F2CECECECFCFCFCFCFCFCECECECFCFCFCE
        CECECFCFCFCFCFCFCFCFCFCFCFCFCFCFCFCECECE898989000000898989FFFFFF
        E6F1F2E6F1F2E6F1F1E6F1F2E6F1F1E6F1F1E6F1F2E6F2F2E6F1F1E6F1F1E6F1
        F1E6F1F1CFCFCF000000898989FFFFFFE6F1F1E6F1F1E6F1F2E6F1F1E6F1F2E6
        F1F2E6F1F2E6F1F1E6F1F1E7F2F2E6F1F1E6F1F2CFCFCF000000888888FFFFFF
        E7F2F2CFCFCFE6F1F1CFCFCFE6F1F1CFCFCFCECECECFCFCFCECECECECECECECE
        CEE6F1F2CFCFCF000000898989FFFFFFE6F1F2CFCFCFCFCFCFCECECECECECEE6
        F1F1E6F2F2E6F1F2E6F1F1E6F1F1E6F1F1E6F1F2CFCFCF000000898989E6F1F2
        CFCFCF8989894C4C4C4C4C4CB4858A898989CFCFCFCFCFCFCFCFCFCECECECECE
        CEE6F1F2CFCFCF000000898989000000F8B3B8E6F1F2E6F1F1E6F1F1CFCFCFB3
        8589000000CFCFCFE6F1F1E6F1F2E6F1F1E6F1F2CFCFCF000000CFCFCFFFFFFF
        FFFFFFD6A833AE3E2AAE3E2AD6A833CFCFCFCFCFCF4C4C4CCFCFCFCFCFCFCFCF
        CFE6F1F1CFCFCF000000FFFFFFFFFFFFF8B4B8D6A833AE3F2AAE3F2AAE3E2AD6
        A833CFCFCFF8B4B84C4C4CCFCFCFE6F1F1E6F1F1CECECE000000CECECEFFFFFF
        AE3E2AFFFFFFFFFFFFAE3E2AAF3F2BAE3E2ACFCFCFF8B4B84B4B4BCECECECFCF
        CFE6F2F2CFCFCF000000000000FFFFFFD6A833AE3E2AFFFFFFD6A833AE3E2AD6
        A833F8B3B84C4C4CCFCFCFCFCFCFE6F1F1E6F1F2CFCFCF000000898989000000
        000000AE3E2AAE3F2BAE3E2AAE3E2A000000000000B4858AB38589AE3E2AAE3E
        2AAE3F2AAE3E2A000000898989F8B3B8B385894C4C4C0000000000004C4C4CB3
        8589F8B3B8898989000000D6A833D5A733D6A833D6A833000000898989000000
        4C4C4CCECECECECECECFCFCFCFCFCF8989894B4B4B4C4C4C8989898989898989
        898989898989894C4C4CFFFFFEFFFFFECECECE8989894C4C4C0000004C4C4C88
        8888CFCFCFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
  end
  object POENGPAGE: TTASPageControl
    Left = 0
    Top = 29
    Width = 782
    Height = 555
    ActivePage = TabSheet1
    TabOrder = 0
    TabStop = False
    PageIndex = 0
    PageName = 'TabSheet1'
    object TabSheet1: TTabSheet
      Caption = 'Header Filters'
      object Panel1: TPanel
        Left = 0
        Top = 0
        Width = 764
        Height = 546
        BevelInner = bvLowered
        BevelOuter = bvLowered
        TabOrder = 0
        object Label4: TLabel
          Left = 11
          Top = 229
          Width = 109
          Height = 16
          Caption = 'PO Number Range'
          Transparent = True
        end
        object Label41: TLabel
          Left = 145
          Top = 229
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label5: TLabel
          Left = 145
          Top = 251
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label31: TLabel
          Left = 11
          Top = 319
          Width = 82
          Height = 16
          Caption = 'Ship to Range'
        end
        object Label32: TLabel
          Left = 145
          Top = 319
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label34: TLabel
          Left = 145
          Top = 343
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label30: TLabel
          Left = 11
          Top = 364
          Width = 105
          Height = 16
          Caption = 'Vend State Range'
        end
        object Label33: TLabel
          Left = 145
          Top = 364
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label16: TLabel
          Left = 145
          Top = 386
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label21: TLabel
          Left = 11
          Top = 274
          Width = 81
          Height = 16
          Caption = 'Vendor Range'
        end
        object Label22: TLabel
          Left = 145
          Top = 274
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label25: TLabel
          Left = 145
          Top = 296
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label6: TLabel
          Left = 11
          Top = 409
          Width = 102
          Height = 16
          Caption = 'Ship State Range'
        end
        object Label7: TLabel
          Left = 145
          Top = 409
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label8: TLabel
          Left = 145
          Top = 431
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label10: TLabel
          Left = 359
          Top = 16
          Width = 97
          Height = 16
          Caption = 'Print in Currency'
        end
        object Label13: TLabel
          Left = 357
          Top = 49
          Width = 57
          Height = 16
          Caption = 'Use Form'
        end
        object Label14: TLabel
          Left = 11
          Top = 11
          Width = 69
          Height = 16
          Caption = 'Report Type'
        end
        object Label15: TLabel
          Left = 11
          Top = 94
          Width = 104
          Height = 16
          Caption = 'Order Date Range'
          Transparent = True
        end
        object Label17: TLabel
          Left = 145
          Top = 94
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label18: TLabel
          Left = 145
          Top = 116
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label19: TLabel
          Left = 11
          Top = 139
          Width = 106
          Height = 32
          Alignment = taCenter
          Caption = 'Recp. Date Range'#13#10'(Est.)'
          Transparent = True
        end
        object Label20: TLabel
          Left = 145
          Top = 139
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label23: TLabel
          Left = 145
          Top = 163
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label24: TLabel
          Left = 11
          Top = 187
          Width = 106
          Height = 32
          Alignment = taCenter
          Caption = 'Recp. Date Range'#13#10'(Act.)'
          Transparent = True
        end
        object Label26: TLabel
          Left = 145
          Top = 184
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label27: TLabel
          Left = 145
          Top = 206
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Bevel1: TBevel
          Left = 2
          Top = 83
          Width = 778
          Height = 14
          Shape = bsTopLine
        end
        object Label9: TLabel
          Left = 359
          Top = 94
          Width = 91
          Height = 16
          Caption = 'Vend Zip Range'
          Transparent = True
        end
        object Label11: TLabel
          Left = 359
          Top = 139
          Width = 88
          Height = 16
          Alignment = taCenter
          Caption = 'Ship Zip Range'
          Transparent = True
        end
        object Label28: TLabel
          Left = 359
          Top = 184
          Width = 105
          Height = 16
          Alignment = taCenter
          Caption = 'Vend Cntry Range'
          Transparent = True
        end
        object Label29: TLabel
          Left = 359
          Top = 229
          Width = 102
          Height = 16
          Caption = 'Ship Cntry Range'
          Transparent = True
        end
        object Label54: TLabel
          Left = 359
          Top = 274
          Width = 80
          Height = 16
          Caption = 'PO Type [PS]'
        end
        object Label42: TLabel
          Left = 359
          Top = 297
          Width = 93
          Height = 16
          Caption = 'Currency Range'
        end
        object Label55: TLabel
          Left = 359
          Top = 319
          Width = 129
          Height = 16
          Caption = 'PO Description Range'
        end
        object Label60: TLabel
          Left = 359
          Top = 365
          Width = 106
          Height = 16
          Caption = 'Entered By Range'
        end
        object Label40: TLabel
          Left = 493
          Top = 94
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label39: TLabel
          Left = 493
          Top = 116
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label38: TLabel
          Left = 493
          Top = 139
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label37: TLabel
          Left = 493
          Top = 161
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label36: TLabel
          Left = 493
          Top = 184
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label35: TLabel
          Left = 493
          Top = 206
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label43: TLabel
          Left = 493
          Top = 229
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label44: TLabel
          Left = 493
          Top = 251
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label45: TLabel
          Left = 493
          Top = 297
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label56: TLabel
          Left = 493
          Top = 319
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label57: TLabel
          Left = 493
          Top = 341
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label58: TLabel
          Left = 493
          Top = 365
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label46: TLabel
          Left = 616
          Top = 297
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label59: TLabel
          Left = 616
          Top = 365
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label52: TLabel
          Left = 359
          Top = 388
          Width = 90
          Height = 16
          Caption = 'Location Range'
        end
        object Label51: TLabel
          Left = 359
          Top = 433
          Width = 110
          Height = 16
          Caption = 'Job Number Range'
        end
        object Label47: TLabel
          Left = 493
          Top = 388
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label48: TLabel
          Left = 493
          Top = 410
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label49: TLabel
          Left = 493
          Top = 433
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label50: TLabel
          Left = 493
          Top = 453
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object UnAppLabel: TLabel
          Left = 11
          Top = 457
          Width = 178
          Height = 16
          Hint = 'O=Only'
          Caption = 'Print UnApproved POs (Y/N/O)'
          Transparent = True
        end
        object reworkLabel: TLabel
          Left = 11
          Top = 480
          Width = 152
          Height = 16
          Hint = 'O=Only'
          Caption = 'Print Rework POs (Y/N/O)'
          Transparent = True
        end
        object Label96: TLabel
          Left = 359
          Top = 478
          Width = 105
          Height = 16
          Caption = 'Pack Slip Number'
        end
        object Label97: TLabel
          Left = 493
          Top = 478
          Width = 30
          Height = 16
          Caption = 'From'
        end
        object Label98: TLabel
          Left = 493
          Top = 498
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object ZBKSA_THRU4: TTASComboEnter
          Left = 210
          Top = 250
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 12
          Text = 'ZBKSA_THRU4'
          FieldName = 'sBKSA.THRU4'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_ponum('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = '012345678 9'
          ReturnIsTab = True
          KeyTraps = 'F2|zbksa_thru4.click'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM4: TTASComboEnter
          Left = 210
          Top = 228
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 11
          Text = 'ZBKSA_FROM4'
          FieldName = 'sBKSA.FROM4'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_ponum('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = '012345678 9'
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM4.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM6: TTASComboEnter
          Left = 210
          Top = 318
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 15
          Text = 'ZBKSA_FROM6'
          FieldName = 'ZBKSA.FROM6'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipto('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM6.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU6: TTASComboEnter
          Left = 210
          Top = 340
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 16
          Text = 'ZBKSA_THRU6'
          FieldName = 'ZBKSA.THRU6'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipto('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_THRU6.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM7: TTASENTER
          Left = 210
          Top = 363
          Width = 60
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 17
          Text = 'ZBKSA_FROM7'
          FieldName = 'ZBKSA.FROM7'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vendst('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU7: TTASENTER
          Left = 210
          Top = 385
          Width = 60
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 18
          Text = 'ZBKSA_THRU7'
          FieldName = 'ZBKSA.THRU7'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vendst('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU5: TTASComboEnter
          Left = 210
          Top = 295
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 14
          Text = 'ZBKSA_THRU5'
          FieldName = 'zBKSA.THRU5'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vend('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_THRU5.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM5: TTASComboEnter
          Left = 210
          Top = 273
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 13
          Text = 'ZBKSA_FROM5'
          FieldName = 'zBKSA.FROM5'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vend('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM5.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU8: TTASENTER
          Left = 210
          Top = 430
          Width = 60
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 20
          Text = 'ZBKSA_THRU8'
          FieldName = 'ZBKSA.THRU8'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipst('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM8: TTASENTER
          Left = 210
          Top = 408
          Width = 60
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 19
          Text = 'ZBKSA_FROM8'
          FieldName = 'ZBKSA.FROM8'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipst('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object FILT: TTASCheckBox
          Left = 11
          Top = 55
          Width = 213
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Print Filters? '
          TabOrder = 2
          FieldName = 'ISFILT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object DETAIL_ONLY: TTASCheckBox
          Left = 11
          Top = 36
          Width = 213
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Details?'
          TabOrder = 1
          FieldName = 'DETAIL.ONLY'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object LONG_SHORT: TTASComboBox
          Left = 551
          Top = 47
          Width = 90
          Height = 24
          ItemHeight = 16
          ItemIndex = 0
          TabOrder = 4
          Text = 'Short'
          Items.Strings = (
            'Short'
            'Long')
          FieldName = 'LONG.SHORT'
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 1
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BASE: TTASComboBox
          Left = 551
          Top = 14
          Width = 90
          Height = 24
          ItemHeight = 16
          ItemIndex = 0
          TabOrder = 3
          Text = 'Base'
          Items.Strings = (
            'Base'
            'Source')
          FieldName = 'BASE'
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 1
          ReturnIsTab = True
          SelectStart = 0
          FocusOnObject = 'long_short'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object SORT_TEXT: TTASComboBox
          Left = 210
          Top = 7
          Width = 120
          Height = 24
          ItemHeight = 16
          ItemIndex = 0
          TabOrder = 0
          Text = 'Vendor'
          Items.Strings = (
            'Vendor'
            'Item Number'
            'PO Number'
            'User Defined')
          FieldName = 'SORT.TEXT'
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_sort()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 1
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_FROM1: TTASDateEdit
          Left = 210
          Top = 92
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 5
          FieldName = 'ZBKSA.FROM1'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_orddate('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_THRU1: TTASDateEdit
          Left = 210
          Top = 115
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 6
          FieldName = 'ZBKSA.THRU1'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_orddate('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_FROM2: TTASDateEdit
          Left = 210
          Top = 138
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 7
          FieldName = 'ZBKSA.FROM2'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_erddate('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_THRU2: TTASDateEdit
          Left = 210
          Top = 160
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 8
          FieldName = 'ZBKSA.THRU2'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_erddate('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_FROM3: TTASDateEdit
          Left = 210
          Top = 183
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 9
          FieldName = 'ZBKSA.FROM3'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_arddate('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_THRU3: TTASDateEdit
          Left = 210
          Top = 205
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 10
          FieldName = 'ZBKSA.THRU3'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_arddate('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_FROM9: TTASENTER
          Left = 550
          Top = 92
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 24
          Text = 'ZBKSA_FROM9'
          FieldName = 'ZBKSA.FROM9'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vendzip('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU9: TTASENTER
          Left = 550
          Top = 114
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 25
          Text = 'ZBKSA_THRU9'
          FieldName = 'ZBKSA.THRU9'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vendzip('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM10: TTASENTER
          Left = 550
          Top = 137
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 26
          Text = 'ZBKSA_FROM10'
          FieldName = 'ZBKSA.FROM10'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipzip('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU10: TTASENTER
          Left = 550
          Top = 159
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 27
          Text = 'ZBKSA_THRU10'
          FieldName = 'ZBKSA.THRU10'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipzip('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM11: TTASENTER
          Left = 550
          Top = 182
          Width = 209
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 28
          Text = 'ZBKSA_FROM11'
          FieldName = 'ZBKSA.FROM11'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vendcntry('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU11: TTASENTER
          Left = 550
          Top = 204
          Width = 210
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 29
          Text = 'ZBKSA_THRU11'
          FieldName = 'ZBKSA.THRU11'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_vendcntry('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM12: TTASENTER
          Left = 550
          Top = 227
          Width = 210
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 30
          Text = 'ZBKSA_FROM12'
          FieldName = 'ZBKSA.FROM12'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipcntry('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU12: TTASENTER
          Left = 550
          Top = 249
          Width = 210
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 31
          Text = 'ZBKSA_THRU12'
          FieldName = 'ZBKSA.THRU12'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_shipcntry('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object POTYPE: TTASENTER
          Left = 550
          Top = 272
          Width = 61
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 32
          Text = 'POTYPE'
          FieldName = 'POTYPE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = 'PS'
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM26: TTASComboEnter
          Left = 550
          Top = 295
          Width = 61
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 33
          Text = 'ZBKSA_FROM26'
          FieldName = 'ZBKSA.FROM26'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_cur('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM26.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU26: TTASComboEnter
          Left = 649
          Top = 295
          Width = 61
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 34
          Text = 'ZBKSA_THRU26'
          FieldName = 'ZBKSA.THRU26'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_cur('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'f2|ZBKSA_THRU26.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM19: TTASENTER
          Left = 550
          Top = 317
          Width = 226
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 35
          Text = 'ZBKSA_FROM19'
          FieldName = 'ZBKSA.FROM19'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_podesc('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU19: TTASENTER
          Left = 550
          Top = 339
          Width = 226
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 36
          Text = 'ZBKSA_THRU19'
          FieldName = 'ZBKSA.THRU19'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_podesc('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM13: TTASENTER
          Left = 550
          Top = 363
          Width = 61
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 37
          Text = 'ZBKSA_FROM13'
          FieldName = 'ZBKSA.FROM13'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_entby('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU13: TTASENTER
          Left = 649
          Top = 363
          Width = 61
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 38
          Text = 'ZBKSA_THRU13'
          FieldName = 'ZBKSA.THRU13'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_entby('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM17: TTASComboEnter
          Left = 549
          Top = 386
          Width = 160
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 39
          Text = 'ZBKSA_FROM17'
          FieldName = 'ZBKSA.FROM17'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_loc('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM17.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU17: TTASComboEnter
          Left = 549
          Top = 408
          Width = 160
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 40
          Text = 'ZBKSA_THRU17'
          FieldName = 'ZBKSA.THRU17'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_loc('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_THRU17.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM18: TTASENTER
          Left = 549
          Top = 431
          Width = 160
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 41
          Text = 'ZBKSA_FROM18'
          FieldName = 'ZBKSA.FROM18'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_job('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU18: TTASENTER
          Left = 549
          Top = 453
          Width = 160
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 42
          Text = 'ZBKSA_THRU18'
          FieldName = 'ZBKSA.THRU18'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_job('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterUnAppPO: TTASENTER
          Left = 210
          Top = 455
          Width = 37
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 21
          Text = 'ENTERSIGNPO'
          FieldName = 'prt.unapproved'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = 'YNO'
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterReworkPO: TTASENTER
          Left = 210
          Top = 478
          Width = 37
          Height = 21
          Hint = 'Y = Yes'#13#10'N= No'#13#10'O = Only'#13#10#13#10'Add REWORK.PO field to the rtm.'
          AutoSize = False
          CharCase = ecUpperCase
          ParentShowHint = False
          ShowHint = True
          TabOrder = 22
          Text = 'ENTERSIGNPO'
          FieldName = 'prt.rework'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = 'YNO'
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterFPckslp: TTASENTER
          Left = 549
          Top = 476
          Width = 160
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 43
          Text = 'ZBKSA_FROM18'
          FieldName = 'from.pckslp'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_pckslp('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
      end
        object EnterTPckslp: TTASENTER
          Left = 549
          Top = 498
          Width = 160
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 44
          Text = 'ZBKSA_THRU18'
          FieldName = 'thru.pckslp'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_pckslp('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object cbOpenASOF: TTASCheckBox
          Left = 11
          Top = 504
          Width = 312
          Height = 17
          Hint = 
            'When enabled, Items received after the Order Thru Date will be c' +
            'onsidered as '#39'Open'#39'.'
          Alignment = taLeftJustify
          Caption = 'Print Open PO as of Order Thru Date'
          ParentShowHint = False
          ShowHint = True
          TabOrder = 23
          FieldName = 'openPO.asof'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
      end
      end
    end
    object TabSheet3: TTabSheet
      Caption = 'Line Filters'
      object Panel5: TPanel
        Left = 0
        Top = 0
        Width = 774
        Height = 524
        Align = alClient
        BevelInner = bvLowered
        BevelOuter = bvLowered
        TabOrder = 0
        object Label53: TLabel
          Left = 23
          Top = 35
          Width = 115
          Height = 16
          Caption = 'Item Number Range'
          Transparent = True
        end
        object Label61: TLabel
          Left = 181
          Top = 58
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label62: TLabel
          Left = 23
          Top = 81
          Width = 103
          Height = 16
          Caption = 'Item Class Range'
        end
        object Label63: TLabel
          Left = 23
          Top = 127
          Width = 142
          Height = 16
          Caption = 'Product Category Range'
        end
        object Label64: TLabel
          Left = 181
          Top = 148
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label65: TLabel
          Left = 181
          Top = 104
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label66: TLabel
          Left = 23
          Top = 171
          Width = 108
          Height = 16
          Caption = 'Work Order Range'
          Transparent = True
        end
        object Label67: TLabel
          Left = 181
          Top = 171
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label68: TLabel
          Left = 181
          Top = 193
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label69: TLabel
          Left = 23
          Top = 217
          Width = 94
          Height = 16
          Caption = 'Rcvd Qty Range'
          Transparent = True
        end
        object Label70: TLabel
          Left = 181
          Top = 217
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label71: TLabel
          Left = 181
          Top = 239
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label72: TLabel
          Left = 23
          Top = 260
          Width = 117
          Height = 16
          Caption = 'Rcvd Amount Range'
          Transparent = True
        end
        object Label73: TLabel
          Left = 181
          Top = 260
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label74: TLabel
          Left = 181
          Top = 282
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label75: TLabel
          Left = 181
          Top = 127
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label87: TLabel
          Left = 181
          Top = 81
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label88: TLabel
          Left = 181
          Top = 35
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label89: TLabel
          Left = 23
          Top = 307
          Width = 142
          Height = 16
          Caption = 'Invoice Post Date Range'
          Transparent = True
        end
        object Label90: TLabel
          Left = 181
          Top = 307
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label91: TLabel
          Left = 181
          Top = 329
          Width = 25
          Height = 16
          Caption = 'Thru'
          Transparent = True
        end
        object Label92: TLabel
          Left = 484
          Top = 58
          Width = 165
          Height = 16
          Caption = 'Confirmed/Unconfirmed/Both'
        end
        object Label93: TLabel
          Left = 23
          Top = 350
          Width = 119
          Height = 16
          Caption = 'Planner Code Range'
        end
        object Label94: TLabel
          Left = 181
          Top = 373
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label95: TLabel
          Left = 181
          Top = 350
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object Label99: TLabel
          Left = 585
          Top = 215
          Width = 68
          Height = 16
          Hint = 'Use this field to Limit WO purchases or WO Open Allocations.'
          Caption = 'WO Priority'
          ParentShowHint = False
          ShowHint = True
          Transparent = True
        end
        object GLLabel1: TLabel
          Left = 23
          Top = 397
          Width = 109
          Height = 16
          Caption = 'GL Account Range'
        end
        object GLLabel2: TLabel
          Left = 181
          Top = 421
          Width = 25
          Height = 16
          Caption = 'Thru'
        end
        object Label100: TLabel
          Left = 181
          Top = 397
          Width = 30
          Height = 16
          Caption = 'From'
          Transparent = True
        end
        object ZBKSA_THRU21: TTASComboEnter
          Left = 225
          Top = 56
          Width = 175
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 1
          Text = 'ZBKSA_THRU21'
          FieldName = 'ZBKSA.THRU21'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_item('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_THRU21.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM21: TTASComboEnter
          Left = 225
          Top = 33
          Width = 175
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 0
          Text = 'ZBKSA_FROM21'
          FieldName = 'ZBKSA.FROM21'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_item('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM21.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM22: TTASComboEnter
          Left = 225
          Top = 79
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 2
          Text = 'ZBKSA_FROM22'
          FieldName = 'ZBKSA.FROM22'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_class('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_FROM22.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU22: TTASComboEnter
          Left = 225
          Top = 102
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 3
          Text = 'ZBKSA_THRU22'
          FieldName = 'ZBKSA.THRU22'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_class('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'f2|ZBKSA_THRU22.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_FROM27: TTASENTER
          Left = 225
          Top = 125
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 4
          Text = 'ZBKSA_FROM27'
          FieldName = 'ZBKSA.FROM27'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_cat('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU27: TTASENTER
          Left = 225
          Top = 146
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 5
          Text = 'ZBKSA_THRU27'
          FieldName = 'ZBKSA.THRU27'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_cat('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU14: TTASComboEnter
          Left = 225
          Top = 191
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 8
          Text = 'ZBKSA_THRU14'
          FieldName = 'sBKSA.THRU14'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_wo('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ZBKSA_THRU14.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object ZBKSA_THRU15: TTASNumEnter
          Left = 349
          Top = 191
          Width = 50
          Height = 21
          AutoSize = False
          DisplayFormat = '0'
          TabOrder = 9
          FieldName = 'sBKSA.THRU15'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_wo('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          KeyTraps = 'F2|ZBKSA_THRU14.CLICK'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object ZBKSA_FROM15: TTASNumEnter
          Left = 349
          Top = 169
          Width = 50
          Height = 21
          AutoSize = False
          DisplayFormat = '0'
          TabOrder = 7
          FieldName = 'sBKSA.FROM15'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_wo('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          KeyTraps = 'F2|ZBKSA_FROM14.CLICK'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object ZBKSA_FROM14: TTASComboEnter
          Left = 225
          Top = 169
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 6
          Text = 'ZBKSA_FROM14'
          FieldName = 'sBKSA.FROM14'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_wo('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'f2|ZBKSA_FROM14.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object USE_STD_COST: TTASCheckBox
          Left = 484
          Top = 35
          Width = 278
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Use Standard Cost?'
          TabOrder = 22
          FieldName = 'USE.STD.COST'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ZBKSA_FROM24: TTASNumEnter
          Left = 225
          Top = 214
          Width = 121
          Height = 21
          AutoSize = False
          DisplayFormat = '0.00;-0.00'
          TabOrder = 10
          FieldName = 'ZBKSA.FROM24'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_recqty('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object ZBKSA_THRU24: TTASNumEnter
          Left = 225
          Top = 236
          Width = 121
          Height = 21
          AutoSize = False
          DisplayFormat = '0.00;-0.00'
          TabOrder = 11
          FieldName = 'ZBKSA.THRU24'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_recqty('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object ZBKSA_FROM25: TTASNumEnter
          Left = 225
          Top = 258
          Width = 121
          Height = 21
          AutoSize = False
          TabOrder = 12
          FieldName = 'ZBKSA.FROM25'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_recamt('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object ZBKSA_THRU25: TTASNumEnter
          Left = 225
          Top = 280
          Width = 121
          Height = 21
          AutoSize = False
          TabOrder = 13
          FieldName = 'ZBKSA.THRU25'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_recamt('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object zbksa_from28: TTASDateEdit
          Left = 225
          Top = 303
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          TabOrder = 14
          FieldName = 'ZBKSA.FROM28'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object zbksa_thru28: TTASDateEdit
          Left = 225
          Top = 325
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          TabOrder = 15
          FieldName = 'ZBKSA.THRU28'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object TASENTER1: TTASENTER
          Left = 744
          Top = 56
          Width = 19
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 23
          Text = 'TASENTER1'
          FieldName = 'CONF'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = 'CUB'
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object cbZeroBal: TTASCheckBox
          Left = 484
          Top = 81
          Width = 278
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Include 0 Balances Lines on Open Orders?'
          TabOrder = 24
          FieldName = 'incl.zero.bal'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object cbQCItems: TTASCheckBox
          Left = 484
          Top = 104
          Width = 278
          Height = 17
          Hint = 
            'Include QC receipts not yet bought off.  POIE/POIF, sort by Item' +
            's ONLY.'
          Alignment = taLeftJustify
          Caption = 'Include Items Received into QC'
          ParentShowHint = False
          ShowHint = True
          TabOrder = 25
          FieldName = 'incl.qc.items'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
      end
        object EnterFPlan: TTASENTER
          Left = 225
          Top = 348
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 16
          Text = 'ENTERFPLAN'
          FieldName = 'FROM.PLAN'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_plan('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
      end
        object EnterTPlan: TTASENTER
          Left = 225
          Top = 371
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 17
          Text = 'ENTERTPLAN'
          FieldName = 'THRU.PLAN'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_plan('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object cbUsage: TTASCheckBox
          Left = 484
          Top = 125
          Width = 278
          Height = 17
          Hint = 
            'Include QC receipts not yet bought off.  POIE, sort by Items ONL' +
            'Y.'
          Alignment = taLeftJustify
          Caption = 'Include previous 12 Month Usage'
          ParentShowHint = False
          ShowHint = True
          TabOrder = 26
          FieldName = 'incl.usage'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
      end
        object TASCheckBox1: TTASCheckBox
          Left = 484
          Top = 146
          Width = 278
          Height = 17
          Hint = 
            'Use the WO in the Job Num Field rather than the WO entered for t' +
            'he PO Line.   Must be in format  Prefix-Suffix.'
          Alignment = taLeftJustify
          Caption = 'Use Item Job Num WO Number'
          ParentShowHint = False
          ShowHint = True
          TabOrder = 27
          FieldName = 'use.jobnum.wo'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
      end
        object cbLimitWO: TTASCheckBox
          Left = 484
          Top = 169
          Width = 278
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Include Only Items Purchased for WOs'
          TabOrder = 28
          FieldName = 'limit.to.wo'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
      end
        object EnterWOPrio: TTASENTER
          Left = 667
          Top = 213
          Width = 96
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 30
          Text = 'ENTERFPLAN'
          FieldName = 'wo.priority'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_plan('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object cbLimitAlloc: TTASCheckBox
          Left = 484
          Top = 191
          Width = 278
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Include Only Items with Open WO Allocations'
          TabOrder = 29
          FieldName = 'limit.to.alloc'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
      end
        object EnterFglacct: TTASComboEnter
          Left = 225
          Top = 395
          Width = 121
          Height = 21
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 18
          Text = 'EnterFglacct'
          FieldName = 'from.glacct'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_glacct('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ENTERFGLACCT.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
      end
        object EnterTglacct: TTASComboEnter
          Left = 225
          Top = 419
          Width = 121
          Height = 21
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 20
          Text = 'EnterTglacct'
          FieldName = 'thru.glacct'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_glacct('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ENTERTGLACCT.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterFgldpt: TTASENTER
          Left = 351
          Top = 395
          Width = 45
          Height = 21
          AutoSize = False
          TabOrder = 19
          Text = 'EnterFgldpt'
          FieldName = 'from.gldpt'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_glacct('#39'F'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ENTERFGLACCT.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterTgldpt: TTASENTER
          Left = 351
          Top = 419
          Width = 45
          Height = 21
          AutoSize = False
          TabOrder = 21
          Text = 'EnterTgldpt'
          FieldName = 'thru.gldpt'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_glacct('#39'T'#39')'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|ENTERTGLACCT.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
      end
    end
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 533
    Top = 17
  end
  object EvoToobarImages: TImageList
    Left = 577
    Top = 17
    Bitmap = {
      494C010106000900A80010001000FFFFFFFFFF10FFFFFFFFFFFFFFFF424D3600
      0000000000003600000028000000400000002000000001002000000000000020
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000007373730073737300737373000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000CE944200CE8C3100D69C
      5200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000073737300BD632900AD6B42006B524A007373730000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000DEA55200BD843900000000000000
      0000D69C5200B57B39006B5231006B5231006B5231006B5231006B5231000000
      000000000000000000000000000000000000000000007373730073737300BD63
      2900EF7B0800FF732100FF940800FFAD310094634A007373730073737300B57B
      5A00737373007373730073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFAD4200AD7B4200000000000000
      00006B523100C67B3100DE943900EFAD4200F7B55200DEB56300EFAD42006B52
      31006B5231000000000000000000000000008452520084525200E79C5A00EF84
      1000D6846300FFAD3100FF8C0800FFA51000FFBD6300AD7B6B0084525200FF94
      0000845252008452520073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFB54A00AD7B4200000000006B52
      3100E79C3100F79C3900EF943100EF9C3100F7A53900F7BD5200FFD67300EFCE
      8C00B57B39006B523100000000000000000094634A00F7F7E700F7F7E700F7F7
      E700FFF7E700F7DEAD00F7941800FF940000FFAD3100FFC68400FFBD5A00FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000E7AD6300DE9C29006B523100F7A5
      3100EF9C3100E7942900E79429007352310073523100B5732900F7B54200FFD6
      6B00F7D69400B57B3900000000000000000094636300FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00F7DEAD00FF9C0800FF9C0800FFBD5A00FFC68400FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000F7B53900F7AD3100EFA5
      2900E7942900DE8C290084522900000000000000000000000000B5732900F7AD
      3900FFD66B00DEB57B00B57B390000000000A56B6B00FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00F7941800FFAD2900FF940000FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000E7B56300F7B53100EFA5
      2900E7942100A56318006B5231006B5231006B5231006B5231006B5231006B52
      31006B5231006B5231006B52310000000000AD7B6B00FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FF5A3100EF6B4200EF523100EF6B4200FF5A
      3100FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F7BD3900EFAD
      2900E79C2100D67B2900D67B2900D67B2900D67B2900D67B2900D67B2900D67B
      2900D67B2900D67B2900B57B390000000000B58C7300FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00CECECE00D6D6D600F7EFDE00F7E7
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000F7C6
      4200EFAD2900E79C2100DE942100E7942900E7942900E7942900E7942900EF94
      3100F79C3900EFA54200B57B390000000000B58C7300FFFFFF00FF5A3100EF6B
      4200E7522900C6734200C68C7B00FFFFFF00FFFFFF00FFFFFF00294A84007394
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000EFCE940000000000F7C6
      4200F7C64200BD8429006B4A21000000000000000000B5732900CE8C3100EF94
      2900EF9C3100EF9C3100B57B390000000000C6947B00FFFFFF00FF8C0800FF8C
      0800FF5A3100AD4A1800FFF7EF00FFFFFF00FFFFFF00FFFFFF007394D6007394
      D600FFFFF700AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000EFCE94000000
      0000F7C64200E7AD39006B5229005A42290073523100B5732900E79C2900E794
      2900F7A53900B57B39000000000000000000D6A58400FFFFFF00FF8C0800FFBD
      5A00FFAD2900F7941800BD632900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
      FF00FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000D6BD8C00E7CE
      8C0000000000F7DE8C00E7B53900B5842100CE8C2100E7A52900E79C2100EFA5
      2900EFA53900B57B39000000000000000000DEAD8400DEAD8400FF8C0800DEAD
      8400F7A55A00FFC68400EF943900BD632900C69C9400C69C9400C69C9400C69C
      9400C69C9400AD7B7B0000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000D6BD
      8C00D6BD8C00E7D66300E7D66300F7D64200F7B53100EFAD2900EFAD2900EFA5
      3100B57B390000000000EFAD4200000000000000000000000000FF8C08000000
      000000000000F7A55A00FFDEAD00EFB58C00BD632900BD523900C6734200A563
      4200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000D6BD8C00D6BD8C00D6BD8C00DEB55200FFCE4A00B57B3900B57B
      39000000000000000000EFAD4200000000000000000000000000000000000000
      00000000000000000000F7A55A00FFEFBD00FFE7AD00DE8C5200944A18000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000AD9A880046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000AD9A8800CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000212121004242
      3900424239004242390042423900424239004242390042423900424239004242
      3900424239004242390042423900000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000AD9A
      8800FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B7B00F7F7
      FF00F7F7FF00F7F7FF00BDBDBD00F7F7FF00F7F7FF00003939005A5A5A00F7EF
      E700F7F7FF00F7F7FF0042423900000000000000000046403800464038004640
      380046403800464038004640380046403800464038004640380046403800FFE8
      D400FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000027596100000000000000000027596100000000000000
      00000000000000000000000000000000000000000000000000005A5A5A00BDBD
      BD00BDBDBD00BDBDBD009C9C9400BDBDBD00BDBDBD005A5A5A0042BDBD005252
      4A00BDBDBD00BDBDBD004242390000000000AD9A8800FFE5CE00CAB39E00CAB3
      9E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00FFE8D400FFEB
      D900FFEBD900FFEBD900BBA69200464038008080000080800000800000008000
      0000800000008000000080000000800000008000000080000000800000008000
      0000800000008000000080000000000000000000000027596100000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000275961000000000000000000000000005A5A5A00DED6
      D600DED6D600DED6D600ADADAD00DED6D600DED6D600F7F7FF005A5A5A005ADE
      DE0052524A00F7EFE7004242390000000000AD9A8800FFEDDD00FFE3C900FFE3
      C900FFE3C900FFE3C9008B7C6D0000000000EDD2B900FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BBA692004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      6100000000000000000080808000808080008080800080808000000000000000
      0000275961002759610000000000000000000000000000000000393900003939
      00003939000039390000393900003939000052523100ADADAD009C9C94005A5A
      5A005ADEDE0052524A002121210000000000AD9A8800FFF1E400FFE3C900FFE3
      C900FFE3C900FFE3C900F2D6BD00ECD1B800FFE5CE00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BFAA96004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF00FFFF
      FF00C8D0D4000000000080000000000000000000000000000000275961002759
      6100000000008080800091919100838383008080800080808000808080000000
      0000275961002759610000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000DED6D600BDBDBD00F7F7
      FF007B7B7B006BADAD004242390000000000AD9A8800FFF4EA00FDE0C600FFE3
      C900FFE3C900FFE3C9008B7C6D0076695C00DCC3AD00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400C4AE99004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      61000000000080808000AAAAAA00919191008383830080808000808080000000
      00002759610027596100000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD005A5A5A005ADEDE0021212100AD9A8800FFF7F000FADEC400FADE
      C400FFE3C900FFE3C900DCC3AD00655A4E006F635700F4D8BF00FFE8D400FFE8
      D400FFE8D400FFE8D400CAB39E004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF000000
      0000FFFFFF0000000000800000000000000000000000000000002E6770002E67
      70000000000080808000AAAAAA00AAAAAA009191910080808000808080000000
      00002E6770002E67700000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF00393939005A9C9C00AD9A8800FFF9F300FADEC400FADE
      C400FADEC400FFE3C900FFE3C900DCC3AD00524840005F544A00FADEC400FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000377E8800377E
      8800000000000000000080808000808080008080800080808000000000000000
      0000377E8800377E880000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD00BDBDBD004242390000000000AD9A8800FFF9F300F6DAC000FADE
      C400EDD2B900D1BAA400DCC3AD00FFE3C900B29D8B0083746600C2AC9700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF000000000000C8D0
      D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400808000008080
      00008080000080800000800000000000000000000000000000004397A3004397
      A3004397A3000000000000000000000000000000000000000000000000004397
      A3004397A3004397A300000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF004242390000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00D1BAA400524840005C524800ECD1B800726559005F544A00D5BCA700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF0000000000FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00C8D0D400808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B0000393900005A5A5A005A5A5A007B7B
      7B007B7B7B007B7B7B002121210000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00F4D8BF00AA978500000000000000000000000000B29D8B00FFE3C900FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF0000000000000000
      0000000000000000000000000000000000000000000000000000808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      00000000000091919100000000004EA9B6004EA9B60000000000919191000000
      00000000000000000000000000000000000000000000000000009C9C0000ADAD
      6B00BD9C7B00BD9C7B00BD9C7B007B7339003939000042423900000000000000
      000000000000000000000000000000000000AD9A8800FFF9F300FFF9F300FFF9
      F300FFF9F300FFF9F300FFF9F300FFF9F300FFF9F300FFF4EA00FFF1E400FFF1
      E400FFEBD900FFEBD900FFE5CE004640380080800000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF0080800000000000000000000000000000000000000000
      0000000000000000000091919100000000000000000091919100000000000000
      00000000000000000000000000000000000000000000000000007B7B00005A5A
      5A005A5A5A005A5A5A005A5A5A00313131003939000042423900000000000000
      00000000000000000000000000000000000000000000AD9A8800AD9A8800AD9A
      8800A69382009C8B7B0092827300857669007B6D600072655900655A4E005248
      4000524840004640380046403800000000000000000080800000808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080800000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B00007B7B
      00007B7B00007B7B00007B7B00007B7B00002121000000000000000000000000
      000000000000000000000000000000000000424D3E000000000000003E000000
      2800000040000000200000000100010000000000000100000000000000000000
      000000000000000000000000FFFFFF00FFFFFFFF00000000FFFFF8FF00000000
      8FFFF07F00000000301F80010000000030070001000000002003000100000000
      000300010000000081C10001000000008001000100000000C001000100000000
      E001000100000000A181000100000000D003000100000000C803000300000000
      E005D80F00000000F80DFC1F00000000FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFF1FFFFFFFFC001FFE1FFFFFFFFC00180018001FC3FC001000000008001C001
      0000000080018000000000008001800000000000800180000000000080018000
      00000000800180000000000080018001000000008001800100000000C813803F
      00000000FC3F803F80018001FFFF807F00000000000000000000000000000000
      000000000000}
  end
  object PrintTimer: TRtnTimer
    Enabled = False
    CallPrgLoc = 0
    SecondsBtwnCalls = 1
    Left = 248
    Top = 3
  end
end
