object EditForm1: TEditForm1
  Left = 347
  Top = 248
  Hint = 'C:\taspro7\DBA7\t7polinehist.DFM'
  AutoScroll = False
  Caption = 'New Screen'
  ClientHeight = 440
  ClientWidth = 662
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 't7showlinehist.OnClose'
  No_Refresh = False
  OnStart = 't7showlinehist.OnStart'
  OpenFiles = 't7showlinehist.OnOpenFiles'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  RememberSize = True
  OnDisplayScreen = 't7polinehist.OnDisp'    
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Panel2: TPanel
    Left = 0
    Top = 0
    Width = 662
    Height = 72
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvLowered
    ParentBackground = False
    TabOrder = 2
    object Label1: TLabel
      Left = 4
      Top = 16
      Width = 46
      Height = 16
      Caption = 'Current:'
    end
    object Label2: TLabel
      Left = 107
      Top = 16
      Width = 30
      Height = 16
      Caption = 'Price'
    end
    object Label4: TLabel
      Left = 342
      Top = 16
      Width = 27
      Height = 16
      Caption = 'ERD'
    end
    object Label5: TLabel
      Left = 433
      Top = 16
      Width = 68
      Height = 16
      Caption = 'GL Account'
    end
    object Label6: TLabel
      Left = 208
      Top = 16
      Width = 21
      Height = 16
      Caption = 'Qty'
    end
    object Label7: TLabel
      Left = 256
      Top = 16
      Width = 27
      Height = 16
      Caption = 'VPD'
    end
    object Label8: TLabel
      Left = 550
      Top = 16
      Width = 67
      Height = 16
      Caption = 'Work Order'
    end
    object Label3: TLabel
      Left = 479
      Top = 41
      Width = 4
      Height = 16
      Caption = '-'
    end
    object Label9: TLabel
      Left = 601
      Top = 41
      Width = 4
      Height = 16
      Caption = '-'
    end
    object TASNumEnter1: TTASNumEnter
      Left = 55
      Top = 40
      Width = 90
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DecimalPlaces = 4
      DisplayFormat = '0.0000'
      ReadOnly = True
      TabOrder = 0
      FieldName = 'line.prod.prce[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter3: TTASNumEnter
      Left = 146
      Top = 40
      Width = 90
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = '0.00'
      ReadOnly = True
      TabOrder = 1
      FieldName = 'line.prod.oqty[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASDateEdit1: TTASDateEdit
      Left = 237
      Top = 40
      Width = 85
      Height = 21
      TabStop = False
      BlanksChar = '0'
      Color = clMenu
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 2
      FieldName = 'line.prod.ard[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit2: TTASDateEdit
      Left = 323
      Top = 40
      Width = 85
      Height = 21
      TabStop = False
      BlanksChar = '0'
      Color = clMenu
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 3
      FieldName = 'line.prod.erd[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER1: TTASENTER
      Left = 409
      Top = 40
      Width = 67
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      ReadOnly = True
      TabOrder = 4
      Text = 'TASENTER1'
      FieldName = 'line.prod.gla[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER2: TTASENTER
      Left = 485
      Top = 40
      Width = 39
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      ReadOnly = True
      TabOrder = 5
      Text = 'TASENTER2'
      FieldName = 'line.prod.gld[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER3: TTASENTER
      Left = 531
      Top = 40
      Width = 67
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      ReadOnly = True
      TabOrder = 6
      Text = 'TASENTER1'
      FieldName = 'line.wo.pre[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER4: TTASENTER
      Left = 607
      Top = 40
      Width = 39
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      ReadOnly = True
      TabOrder = 7
      Text = 'TASENTER2'
      FieldName = 'line.wo.suf[mcntr]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 72
    Width = 662
    Height = 336
    Align = alClient
    BevelInner = bvLowered
    BevelOuter = bvLowered
    ParentBackground = False
    TabOrder = 0
    object chgGrid: TTASDataGrid
      Left = 2
      Top = 2
      Width = 658
      Height = 332
      Align = alClient
      ColCount = 22
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
      TabOrder = 0
      UpCase = False
      StartAtEnd = False
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = False
      Navigation.AllowDeleteRow = False
      Navigation.AdvanceOnEnter = False
      Navigation.AdvanceAtEnd = False
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = False
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = False
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 60
          Alignment = taLeftJustify
          Header = 'Date'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.CDATE '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 75
          Alignment = taLeftJustify
          Header = 'New Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BPRICE'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 75
          Alignment = taLeftJustify
          Header = 'Old Price'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.APRICE'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 60
          Alignment = taLeftJustify
          Header = 'New Disc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BDISC '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 60
          Alignment = taLeftJustify
          Header = 'Old Disc'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.ADISC '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 75
          Alignment = taLeftJustify
          Header = 'New Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BOOQTY'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 75
          Alignment = taLeftJustify
          Header = 'Old Qty'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AOOQTY'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 65
          Alignment = taLeftJustify
          Header = 'New VPD'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BARD  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 65
          Alignment = taLeftJustify
          Header = 'Old VPD'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AARD  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 65
          Alignment = taLeftJustify
          Header = 'New ERD'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BERD  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 65
          Alignment = taLeftJustify
          Header = 'Old ERD'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AERD  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 85
          Alignment = taLeftJustify
          Header = 'New GL Acct.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BGLA  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 35
          Alignment = taLeftJustify
          Header = 'Dept.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BGLD '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 85
          Alignment = taLeftJustify
          Header = 'Old GL Acct.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AGLA  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 35
          Alignment = taLeftJustify
          Header = 'Dept.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AGLD  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 85
          Alignment = taLeftJustify
          Header = 'New WO'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BWOP  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 50
          Alignment = taLeftJustify
          Header = 'Suf'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BWOS  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 65
          Alignment = taLeftJustify
          Header = 'New Oper'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.BOPER '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 85
          Alignment = taLeftJustify
          Header = 'Old WO'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AWOP  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 50
          Alignment = taLeftJustify
          Header = 'Suf'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AWOS  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 60
          Alignment = taLeftJustify
          Header = 'Old Oper'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.AOPER '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 154
          Alignment = taLeftJustify
          Header = 'Who Made This Change'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'ISAP.CHG.USER  '
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = False
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        60
        75
        75
        60
        60
        75
        75
        65
        65
        65
        65
        85
        35
        85
        35
        85
        50
        65
        85
        50
        60
        154)
    end
  end
  object Panel6: TPanel
    Left = 0
    Top = 408
    Width = 662
    Height = 32
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    DesignSize = (
      662
      32)
    object btnHistExit: TGlyphBtn
      Left = 597
      Top = 5
      Width = 62
      Height = 22
      Anchors = [akRight, akBottom]
      Caption = 'E&xit'
      TabOrder = 0
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object HHistNotes: TPanel
      Left = 2
      Top = 1
      Width = 28
      Height = 27
      BevelOuter = bvNone
      Color = clMenu
      Ctl3D = False
      ParentBackground = False
      ParentCtl3D = False
      TabOrder = 1
      object HistNotes: TSpeedButton
        Left = 2
        Top = 2
        Width = 23
        Height = 24
        Hint = 'Notes for Changes'
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
          FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE0000006B6B6B7B7B7BEF
          EFEFEFEFEFBDBDBDDEDEDEDEDEDED6D6D6ADADADA5A5A5ADADADFFFFFEFFFFFE
          FFFFFE0000006B6B6B7B7B7BEFEFEFDEDEDEDEDEDEDEDEDEBDBDBDADADADA5A5
          A531313131394200316BFFFFFEFFFFFE0000006B6B6B7B7B7BEFEFEFEFEFEFBD
          BDBDADADADADADAD29293142424A313942313942294A731052A5FFFFFE000000
          6B6B6B7B7B7BEFEFEFEFEFEFEFEFEF3131313939394A5A73526BA5426BB5426B
          B54A73BD3963CE317BE70000000000007B7B7BEFEFEFEFEFEFEFEFEFEFEFEF4A
          4A4A4A4A4A638494C6D6F7B5CEF7B5CEF78CADF78CADF7638CDE000000000000
          EFEFEFEFEFEF000000EFEFEFEFEFEFEFEFEFEFEFEFBDBDBD738CBD4A84B59CA5
          D6BDBDE7CEE7FFCEE7FF000000C8D0D4000000ADADAD7B7B7BEFEFEFEFEFEFEF
          EFEFEFEFEFEFEFEFBDBDBDEFEFEFDEDEDE7B7B7B396B84294A73FFFFFE000000
          000000000000ADADADEFEFEF000000EFEFEFEFEFEFEFEFEFEFEFEFBDBDBDDEDE
          DEDEDEDEDEDEDEDEDEDEFFFFFEFFFFFE000000C8D0D4000000ADADAD7B7B7BEF
          EFEFEFEFEFEFEFEFEFEFEFEFEFEFBDBDBDDEDEDEDEDEDEDEDEDEFFFFFEFFFFFE
          FFFFFE000000C8D0D4000000ADADADEFEFEF000000EFEFEFDEDEDEDEDEDEDEDE
          DEDEDEDEDEDEDE000000FFFFFEFFFFFEFFFFFEFFFFFE000000000000000000AD
          ADAD7B7B7BEFEFEFEFEFEFDEDEDEDEDEDEDEDEDE000000FFFFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFE000000C8D0D4000000ADADADDEDEDE000000DEDEDEDEDE
          DE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE00000000
          0000000000ADADAD7B7B7BDEDEDE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000C8D0D4000000ADADAD000000FFFF
          FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFE000000C8D0D4000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
        ParentShowHint = False
        ShowHint = True
      end
    end
    object HHistLinks: TPanel
      Left = 30
      Top = 2
      Width = 28
      Height = 27
      BevelOuter = bvNone
      Ctl3D = True
      ParentBackground = False
      ParentCtl3D = False
      TabOrder = 2
      object HistLinks: TSpeedButton
        Left = 2
        Top = 2
        Width = 23
        Height = 24
        Hint = 'Links for changes'
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFA4A4FFA4A4
          0E65890E6589FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4
          A4FFA4A4FFA4A4FFA4A4FFA4A40E658946FFFF54A2CD0E6589FFA4A4FFA4A4FF
          A4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4126A8E
          00D2D246FFFF54A2CD11698E1878A01878A01878A0FFA4A4FFA4A4FFA4A4FFA4
          A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A416709400D2D246FFFF54A2CD16709500
          D2D246FFFF1878A0FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FF9B9BFF9B9B
          FF9B9B1C779D00D2D246FFFF54A2CD227EA500D2D246FFFF1878A0FFA4A4FFA4
          A4FFA4A4FFA4A4FFA4A4FF9B9BFF9B9BFF9B9B5EA1BD227FA400D2D246FFFF22
          7EA516709400D2D246FFFF1878A0FFA4A4FFA4A4FFA4A4FFA4A4FF8888FF9B9B
          FF9B9B1B7BA346FFFF2685AC2785ABFFA4A4FFA4A416709400D2D246FFFF1878
          A0FFA4A4FFA4A4FFA4A4FF8888FF8888FF9B9B2080A800D2D246FFFF167094FF
          A4A4FFA4A4FFA4A416709400D2D246FFFF1878A0FFA4A4FFA4A4FF8888FF8888
          FF8888FF9B9B2585AD00D2D246FFFF167094FFA4A4FFA4A40E65890E658900D2
          D21878A0FFA4A4FFA4A4FF7777FF8888FF8888FF8888FF9B9B2B8BB300D2D246
          FFFF1670940E658946FFFF54A2CD0E65893898C0FFA4A4FFA4A4FF7777FF7777
          FF8888FF8888FF8888FF9B9B3190B800D2D246FFFF126A8E00D2D246FFFF54A2
          CD11698EFFA4A4FFA4A4FF7777FF7777FF7777FF8888FF8888FF8888FF9B9B35
          95BC00D2D246FFFF16709400D2D246FFFF54A2CD167095FFA4A4FF6C6CFF7777
          FF7777FF7777FF8888FF8888FF8888FF9B9B3898C03898C074B7D31C779D00D2
          D246FFFF54A2CD227EA5FF6C6CFF6C6CFF7777FF7777FF7777FF8888FF8888FF
          8888FF9B9BFF9B9BFF9B9BFF9B9B227FA400D2D246FFFF227EA5FF6C6CFF6C6C
          FF6C6CFF7777FF7777FF7777FF8888FF8888FF8888FF9B9BFF9B9BFF9B9BFF9B
          9B2685AC2785ABFFA4A4FF6C6CFF6C6CFF6C6CFF6C6CFF7777FF7777FF7777FF
          8888FF8888FF8888FF9B9BFF9B9BFF9B9BFF9B9BFF9B9BFF9B9B}
        ParentShowHint = False
        ShowHint = True
      end
    end
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 104
    Top = 428
  end
end
