object EditForm1: TEditForm1
  Left = 377
  Top = 244
  Hint = 'C:\taspro7\DBA7\T7woknb.DFM'
  AutoScroll = False
  Caption = 'Live Requests'
  ClientHeight = 411
  ClientWidth = 1381
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7WOKNB.OnClose'
  No_Refresh = False
  OnStart = 'T7WOKNB.OnStart'
  OpenFiles = 'T7WOKNB.OnOpenFiles'
  OnDisplayScreen = 'T7woknb.OnDisp'
  ScreenPos = tpSpecified
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7WOKNA'
  RememberSize = True
  RememberSizeDate = 43340.694753460650000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object DCPanel: TPanel
    Left = 0
    Top = 0
    Width = 1381
    Height = 377
    Align = alClient
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 0
    object GroupBox1: TGroupBox
      Left = 2
      Top = 2
      Width = 1377
      Height = 373
      Align = alClient
      Caption = 'Open Requests'
      Color = clInactiveCaption
      ParentBackground = False
      ParentColor = False
      TabOrder = 1
      object reqGrid: TTASDataGrid
        Left = 2
        Top = 18
        Width = 1373
        Height = 353
        Align = alClient
        ColCount = 16
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing, goRowSelect]
        TabOrder = 0
        UpCase = False
        StartAtEnd = False
        PrePrgLoc = 0
        PostPrgLoc = 0
        Navigation.AllowInsertRow = False
        Navigation.AllowDeleteRow = False
        Navigation.AdvanceOnEnter = True
        Navigation.AdvanceAtEnd = False
        Navigation.AdvanceDirection = adLeftRight
        Navigation.AdvanceAuto = False
        Navigation.InsertPosition = pInsertBefore
        Navigation.CursorWalkEditor = False
        Navigation.AllowAddRecListF = False
        MouseActions.ColSelect = False
        MouseActions.RowSelect = False
        MouseActions.DirectEdit = False
        MouseActions.DirectComboDrop = False
        MouseActions.CaretPositioning = False
        PasswordChar = '*'
        Columns = <
          item
            Color = clWhite
            Width = 50
            Alignment = taLeftJustify
            Header = 'Emp #'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.EMP    '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 161
            Alignment = taLeftJustify
            Header = 'Name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'EMPNAME'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 50
            Alignment = taLeftJustify
            Header = 'Work'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.WOPRE  '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 36
            Alignment = taLeftJustify
            Header = 'Ord'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.WOSUF  '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 39
            Alignment = taLeftJustify
            Header = 'Oper'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.OPER   '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 59
            Alignment = taLeftJustify
            Header = 'Date'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.RDATE  '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 130
            Alignment = taLeftJustify
            Header = 'Item'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.PART   '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 234
            Alignment = taLeftJustify
            Header = 'Desc'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'DESC'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 80
            Alignment = taRightJustify
            Header = 'Qty'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.QTY    '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 80
            Alignment = taRightJustify
            Header = 'UOH'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'UOH'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 159
            Alignment = taLeftJustify
            Header = 'Reason'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.REASON '
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 50
            Alignment = taCenter
            Header = 'Printed'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edCheckBox
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'PRINTED'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 50
            Alignment = taCenter
            Header = 'Tag'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edCheckBox
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'TAGGED'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clInfoBk
            Width = 50
            Alignment = taCenter
            Header = 'NOB'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.NOB'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 80
            Alignment = taLeftJustify
            Header = 'Bin'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'BIN'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 80
            Alignment = taLeftJustify
            Header = 'Location'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'IS.PREQ.LOC'
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end>
        ExtraFields = <>
        AutoNumAlign = False
        SelectionColor = clHighlight
        SelectionTextColor = clHighlightText
        SelectionRectangle = False
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -13
        FixedFont.Name = 'Arial'
        FixedFont.Style = []
        VAlignment = vtaTop
        Hovering = False
        EnhRowColMove = False
        HintColor = clYellow
        CurrentRow = 1
        CurrentCol = 1
        GridFileHandle = 0
        GridFileKeyNum = 0
        NoAutoUpdate = False
        ColWidths = (
          50
          161
          50
          36
          39
          59
          130
          234
          80
          80
          159
          50
          50
          50
          80
          80)
      end
    end
    object DCDPanel: TPanel
      Left = 380
      Top = 97
      Width = 185
      Height = 41
      BevelInner = bvLowered
      Caption = 'Updating Requests'
      ParentBackground = False
      TabOrder = 0
      Visible = False
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 377
    Width = 1381
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    DesignSize = (
      1381
      34)
    object SORTLABEL: TLabel
      Left = 304
      Top = 10
      Width = 148
      Height = 16
      AutoSize = False
      Caption = 'SORTLABEL'
      Visible = False
    end
    object btnWOKNBExit: TGlyphBtn
      Left = 1298
      Top = 5
      Width = 75
      Height = 24
      Anchors = [akRight]
      Caption = 'E&xit'
      TabOrder = 0
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnSortSH: TGlyphBtn
      Left = 188
      Top = 5
      Width = 109
      Height = 24
      Anchors = [akLeft]
      Caption = 'Change &Sort'
      TabOrder = 1
      TabStop = False
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        393A942A3A766370A358659D2A3A856370A3FFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FE6A6D6FFFFFFEFFFFFEFFFFFEFFFFFE9D92BB404090989CC1FFFFFEFFFFFE6E
        70ADFFFFFEFFFFFEFFFFFEFFFFFEAFB4B5000000A1A6A7FFFFFEFFFFFEFFFFFE
        FFFFFE7C68993A4194FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE4345
        46000000353737FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE5048905A679EFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEB3B7B9000000000000000000A5A9AAFFFFFEFFFFFE
        FFFFFEFFFFFE8F87BA203080A3ABC6FFFFFEFFFFFEFFFFFEFFFFFE6F7172FFFF
        FE000000FFFFFE616364FFFFFEFFFFFE7C78ABFFFFFEFFFFFE58519537468CFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000FFFFFEFFFFFEFFFFFEFFFFFE
        9384AB8C7BA69B8DB18C7BA66B65A0A0A2C8FFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000FFFFFEFFFFFEFFFFFEBD876A
        905830FFFFFEFFFFFE95593B905030926C52FFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FE000000FFFFFEFFFFFEFFFFFEFFFFFEB36F4AFFFFFEFFFFFED0BCB6905030D5
        CEC8FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000FFFFFEFFFFFEFFFFFEFFFFFE
        BA805FB67755B6978295593BA57C5EFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FE000000FFFFFEFFFFFEFFFFFEFFFFFEDECCC2B36F4AFFFFFE905030D2BDB7FF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000FFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEC57F55B7785595593BFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFECD9781B06840C3ACA2FFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000FFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEC27759FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnPRTagAll: TGlyphBtn
      Left = 862
      Top = 5
      Width = 80
      Height = 24
      Anchors = [akRight]
      Caption = 'Tag &All'
      TabOrder = 2
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEB1543023
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEB154302320178E43268E43268E43268E43268E43268E43
        268E4326232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017B15430B1
        5430B15430B15430B15430B15430B15430B15430B15430232017FFFFFEFFFFFE
        FFFFFEFFFFFE232017232017CD6C47CD6C47CD6C47000000CD6C47CD6C47CD6C
        47CD6C47CD6C47232017FFFFFEFFFFFEFFFFFE232017B15430232017D58262D5
        8262000000000000000000D58262D58262D58262D58262232017FFFFFEFFFFFE
        232017232017CD6C47232017DB9377000000E1A48CE1A48CE1A48C000000DB93
        77DB9377DB9377232017FFFFFE232017B15430232017CD6C47232017E1A48CE1
        A48CE1A48CE1A48CE1A48CE1A48C000000E1A48CE1A48C232017FFFFFE232017
        CD6C47232017D58262232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BC
        AB000000E9BCAB232017FFFFFE232017D58262232017D58262232017F0D1C6F0
        D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6232017FFFFFE232017
        D58262232017D58262232017232017F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1
        C6F0D1C6232017B15430FFFFFE232017E9BCAB232017E9BCABE9BCAB23201723
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFE232017
        E9BCAB232017232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BCAB2320
        17FFFFFEFFFFFEFFFFFEFFFFFE232017E9BCABE9BCAB23201723201723201723
        2017232017232017232017232017B15430FFFFFEFFFFFEFFFFFEFFFFFEB15430
        232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BCAB232017FFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEB1543023201723201723201723201723
        2017232017232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object BtnPRUntagall: TGlyphBtn
      Left = 945
      Top = 5
      Width = 80
      Height = 24
      Anchors = [akRight]
      Caption = '&Untag All'
      TabOrder = 3
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEB1543023
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEB154302320178E43268E43268E43268E43268E43268E43
        268E4326232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017B15430B1
        5430B15430B15430B15430B15430B15430B15430B15430232017FFFFFEFFFFFE
        FFFFFEFFFFFE232017232017CD6C47CD6C47CD6C47C26643CD6C47CD6C47CD6C
        47CD6C47CD6C47232017FFFFFEFFFFFEFFFFFE232017B15430232017D58262D5
        8262CA7B5DCA7B5DCA7B5DD58262D58262D58262D58262232017FFFFFEFFFFFE
        232017232017CD6C47232017DB9377D08B71E1A48CE1A48CE1A48CD08B71DB93
        77DB9377DB9377232017FFFFFE232017B15430232017CD6C47232017E1A48CE1
        A48CE1A48CE1A48CE1A48CE1A48CD59B85E1A48CE1A48C232017FFFFFE232017
        CD6C47232017D58262232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BC
        ABDDB2A2E9BCAB232017FFFFFE232017D58262232017D58262232017F0D1C6F0
        D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6232017FFFFFE232017
        D58262232017D58262232017232017F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1
        C6F0D1C6232017B15430FFFFFE232017E9BCAB232017E9BCABE9BCAB23201723
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFE232017
        E9BCAB232017232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BCAB2320
        17FFFFFEFFFFFEFFFFFEFFFFFE232017E9BCABE9BCAB23201723201723201723
        2017232017232017232017232017B15430FFFFFEFFFFFEFFFFFEFFFFFEB15430
        232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BCAB232017FFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEB1543023201723201723201723201723
        2017232017232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnPRTag: TGlyphBtn
      Left = 1028
      Top = 5
      Width = 62
      Height = 24
      Anchors = [akRight]
      Caption = '&Tag'
      TabOrder = 4
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEB1543023
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEB154302320178E43268E43268E43268E43268E43268E43
        268E4326232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017B15430B1
        5430B15430B15430B15430B15430B15430B15430B15430232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017CD6C47CD6C47CD6C47000000CD6C47CD6C47CD6C
        47CD6C47CD6C47232017FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017D58262D5
        8262000000000000000000D58262D58262D58262D58262232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017DB9377000000E1A48CE1A48CE1A48C000000DB93
        77DB9377DB9377232017FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017E1A48CE1
        A48CE1A48CE1A48CE1A48CE1A48C000000E1A48CE1A48C232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BC
        AB000000E9BCAB232017FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017F0D1C6F0
        D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017232017F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1
        C6F0D1C6232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEE9BCAB23201723
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnPRUntag: TGlyphBtn
      Left = 1093
      Top = 6
      Width = 71
      Height = 24
      Anchors = [akRight]
      Caption = '&Untag'
      TabOrder = 5
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEB1543023
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEB154302320178E43268E43268E43268E43268E43268E43
        268E4326232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017B15430B1
        5430B15430B15430B15430B15430B15430B15430B15430232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017CD6C47CD6C47CD6C47C26643CD6C47CD6C47CD6C
        47CD6C47CD6C47232017FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017D58262D5
        8262CA7B5DCA7B5DCA7B5DD58262D58262D58262D58262232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017DB9377D08B71E1A48CE1A48CE1A48CD08B71DB93
        77DB9377DB9377232017FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017E1A48CE1
        A48CE1A48CE1A48CE1A48CE1A48CD59B85E1A48CE1A48C232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017E9BCABE9BCABE9BCABE9BCABE9BCABE9BCABE9BC
        ABDDB2A2E9BCAB232017FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE232017F0D1C6F0
        D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6232017FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFE232017232017F0D1C6F0D1C6F0D1C6F0D1C6F0D1C6F0D1
        C6F0D1C6232017B15430FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEE9BCAB23201723
        2017232017232017232017232017232017232017B15430FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnPrint: TGlyphBtn
      Left = 1171
      Top = 5
      Width = 126
      Height = 24
      Anchors = [akRight]
      Caption = '&Print Tagged'
      TabOrder = 6
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
        99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
        ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
        666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
        A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
        8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
        EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
        BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
        E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
        E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
        CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
        F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
        C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
        CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
        C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
        DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
        EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
        B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
      GlyphKind = bkCustom
    end
    object btnSwap: TGlyphBtn
      Left = 7
      Top = 5
      Width = 98
      Height = 24
      Caption = 'Su&bstitute '
      TabOrder = 7
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFE659E7315773012792D127C2D12802D12822C12
        832B12832B12812A127E2A127A2A12762A16742E639D71FFFFFEFFFFFE1A752C
        006C00007A0000880000950000A00000A70000A80000A100F3F6F3F3F6F3097F
        09006C00166F26FFFFFEFFFFFE116D1F007000007F00008E00009D0000AB0000
        B60000B60000AC0076B176E7E7E7B2D3B2097509116B1FFFFFFEFFFFFE106B1B
        00710000800000900000A00001B0015DD65D6DDB6D6CD26C6AC46AF5F6F5F7F7
        F7B4D1B41A6F23FFFFFEFFFFFE0E6916006F00007F00008E00009D0022B222F9
        F9F9FEFEFEFEFEFEF6F6F6F7F7F7F8F8F8F8F8F8518A57FFFFFEFFFFFE0C6612
        006B00007A0026992631AA3100A000249A24309B303097303A943AF6F6F6F7F7
        F77A9C7A0F6413FFFFFEFFFFFE0A640E006700358E35E1E8E1CEE0CE169C1616
        A11615A1150D990DB2DCB2EFEFEF7BA07B0166010B620DFFFFFEFFFFFE217324
        65A065F6F7F6F7F7F769A3694AA84A4AAB4A4AAB4A4FAB4F9FBB9F92AD924490
        443082300E650FFFFFFEFFFFFE468A48F7F7F7F7F7F7F8F8F8D1E0D1D3E3D3D5
        E6D5CDE3CD64AB645AA35A5A9E5A5A9B5A5A9C5A4E8D4FFFFFFEFFFFFE468849
        F6F6F6F7F7F7F6F6F6F4F5F4F5F5F5F8F8F8F8F8F871A8716AA56A6AA56A6AA5
        6A6AA56A4E8F4EFFFFFEFFFFFE3D8A3F87AA87F6F6F6F8F8F891BA9179AE7979
        AE7979AE797AAE7A7AAE7A7AAE7A7AAE7A7AAE7A539353FFFFFEFFFFFE459147
        8AB88A91B091F6F6F6D2DAD28AB88A8AB88A8AB88A8AB88A8AB88A8AB88A8AB8
        8A8AB88A589958FFFFFEFFFFFE599E5B99C29999C29997B39797B29799C29999
        C29999C29999C29999C29999C29999C29999C29962A061FFFFFEFFFFFE639D70
        4591474591474591474591474591474591474591474591474591474591474591
        47459147629D6FFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnRestore: TGlyphBtn
      Left = 107
      Top = 5
      Width = 79
      Height = 24
      Caption = '&Restore'
      TabOrder = 8
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFED58C69EC8350E3BC9CFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFED47E56EB723EE4BC9CFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFED96F40EB74
        41E5BD9DFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFECA9981E7703DF19E6CFFFFFEFFFFFEFFFFFEFFFFFE
        E07840C06840C06840C06840B05830B89784FFFFFEFFFFFEFFFFFEFFFFFEBA5F
        35ED8553E8BF9FFFFFFEFFFFFEFFFFFEE07840DC5F27E07030E27D4EBA9886FF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEB05E37EA7A47F2B58AFFFFFEFFFFFEFFFFFE
        E07840E07030F09060E98758D47F56FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEAF5F
        38E97644F2B68BFFFFFEFFFFFEFFFFFEE07840E88D60F0A070EC9466E38355AD
        6947FFFFFEFFFFFEFFFFFEFFFFFEB25E36E97846F3B68BFFFFFEFFFFFEFFFFFE
        E07840E68E62E99567F0A070EC9466D5794DB06D4CFFFFFEFFFFFEBF9C89BD63
        39E97A49F3B68BFFFFFEFFFFFEFFFFFEE07840EEC3A3FFFFFEECA173F0A070EC
        9466D67A4EAF5F39AE6440B76239E87F4EEA8251EEC3A3FFFFFEFFFFFEFFFFFE
        EFC4A4FFFFFEFFFFFEFFFFFEEFA97BF0A070EC9466EC9466E98556E98353E981
        51F1A979FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEF4
        BA8DEB9466E98A5CE98759EA895AEFA171FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEF4D6B4F4D3B1F3D4B5FFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
  end
  object TIMER: TRtnTimer
    Interval = 5000
    CallPrgLoc = 0
    SecondsBtwnCalls = 5
    Left = 152
  end
end
