object EditForm3: TEditForm3
  Left = 277
  Top = 194
  Width = 545
  Height = 640
  Hint = 'C:\TASPRO7\DBA7\WBKLUGRID.DFM'
  Caption = 'Maintain Grid Lookup Data'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = True
  OnClose = 'wbklugrid.OnClose'
  No_Refresh = False
  OnStart = 'wbklugrid.OnStart'
  OpenFiles = 'wbklugrid.OnOpenFiles'
  OnDisplayScreen = 'wbklugrid.OnDisplay'
  ScreenPos = tpDesktopCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'wbklugrid'
  RememberSizeDate = 38975.677174016200000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object TPanel
    Left = 0
    Top = 86
    Width = 537
    Height = 282
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 2
    object Label2: TLabel
      Left = 16
      Top = 80
      Width = 59
      Height = 16
      Caption = 'Field Data'
    end
    object GradientLabel1: TGradientLabel
      Left = 4
      Top = 2
      Width = 66
      Height = 17
      AutoSize = False
      Caption = 'Field Data  '
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ColorTo = clWhite
      EllipsType = etNone
      GradientType = gtFullHorizontal
      Indent = 0
      LineWidth = 2
      Orientation = goHorizontal
      TransparentText = False
      VAlignment = vaTop
    end
    object dgFieldData: TTASDataGrid
      Left = 10
      Top = 21
      Width = 518
      Height = 256
      ColCount = 7
      FixedCols = 1
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowMoving, goEditing]
      TabOrder = 0
      UpCase = True
      StartAtEnd = False
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = True
      Navigation.AllowDeleteRow = True
      Navigation.AdvanceOnEnter = True
      Navigation.AdvanceAtEnd = True
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = True
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = False
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 20
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'RT_ARROW'
          CharCase = ecNormal
          DfltValue = '">"'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 150
          Alignment = taLeftJustify
          Header = 'Column Header'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'FD_COLHEADER'
          CharCase = ecNormal
          Name = 'ColHeader'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 150
          Alignment = taLeftJustify
          Header = 'Field Name'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edComboEdit
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'FD_FIELDNAME'
          CharCase = ecUpperCase
          Name = 'FieldName'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 46
          Alignment = taLeftJustify
          Header = 'Totals'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'FD_TOT'
          CharCase = ecUpperCase
          Name = 'Totals'
          AllowedChrs = ' 123456'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 0
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 35
          Alignment = taLeftJustify
          Header = 'UDF'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'FD_FUNC'
          CharCase = ecUpperCase
          Name = 'Function'
          AllowedChrs = ' IU'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 39
          Alignment = taLeftJustify
          Header = 'Type'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'FD_TYPE'
          CharCase = ecUpperCase
          Name = 'RetType'
          AllowedChrs = 'ADNIT'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 37
          Alignment = taLeftJustify
          Header = 'Size'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edInteger
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'FD_SIZE'
          CharCase = ecNormal
          Name = 'RetSize'
          AllowedChrs = '0123456789'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = True
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        20
        150
        150
        46
        35
        39
        37)
    end
  end
  object pnlPleaseWait: TPanel
    Left = 40
    Top = 200
    Width = 456
    Height = 144
    BevelInner = bvLowered
    BevelOuter = bvLowered
    Caption = 'Loading System Dictionary...'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -32
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    object pgPleaseWait: TProgressBar
      Left = 24
      Top = 112
      Width = 408
      Height = 16
      TabOrder = 0
    end
  end
  object TPanel
    Left = 0
    Top = 0
    Width = 537
    Height = 86
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    object Label1: TLabel
      Left = 16
      Top = 16
      Width = 66
      Height = 16
      Caption = 'Grid Name:'
    end
    object Label4: TLabel
      Left = 312
      Top = 16
      Width = 59
      Height = 16
      Caption = 'FD Name:'
    end
    object Label5: TLabel
      Left = 16
      Top = 48
      Width = 72
      Height = 16
      Caption = 'Form Name:'
    end
    object Label6: TLabel
      Left = 427
      Top = 45
      Width = 81
      Height = 16
      Caption = 'Security Level'
    end
    object delflag: TLabel
      Left = 83
      Top = 5
      Width = 12
      Height = 16
      Caption = '   '
    end
    object cbLUGRID_NAME: TTASComboBox
      Left = 96
      Top = 8
      Width = 200
      Height = 24
      CharCase = ecUpperCase
      ItemHeight = 16
      TabOrder = 0
      FieldName = 'tempName'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbFDName: TTASComboBox
      Left = 383
      Top = 8
      Width = 145
      Height = 24
      CharCase = ecUpperCase
      ItemHeight = 16
      TabOrder = 1
      FieldName = 'tempFD'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbxStartAtEnd: TTASCheckBox
      Left = 405
      Top = 65
      Width = 97
      Height = 17
      Caption = ' Start At End'
      TabOrder = 4
      FieldName = 'LUGRID_END     '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbeFormName: TTASComboEnter
      Left = 96
      Top = 40
      Width = 200
      Height = 21
      CharCase = ecUpperCase
      GlyphKind = gkEllipsis
      NumGlyphs = 1
      TabOrder = 2
      FieldName = 'tempFormName'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidMsg = 'This must be an existing form name.  Use WBKLOOKUP as a default.'
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExpr = 'tempFormName<>'#39#39
      ValidExprLoc = 0
      ValidExprTyp = #0
      DfltValue = #39'WBKLOOKUP'#39
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object Security: TTASNumEnter
      Left = 383
      Top = 41
      Width = 34
      Height = 21
      Alignment = taLeftJustify
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 3
      FieldName = 'SEC.LEVEL'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      DfltValue = '999'
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 368
    Width = 537
    Height = 211
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 3
    object Label3: TLabel
      Left = 16
      Top = 187
      Width = 54
      Height = 16
      Caption = 'Key Data'
    end
    object GradientLabel2: TGradientLabel
      Left = 3
      Top = 3
      Width = 65
      Height = 17
      AutoSize = False
      Caption = 'Sort Keys'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = []
      ParentFont = False
      ColorTo = clWhite
      EllipsType = etNone
      GradientType = gtFullHorizontal
      Indent = 0
      LineWidth = 2
      Orientation = goHorizontal
      TransparentText = False
      VAlignment = vaTop
    end
    object dgKeyData: TTASDataGrid
      Left = 9
      Top = 22
      Width = 519
      Height = 184
      ColCount = 4
      FixedCols = 1
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goDrawFocusSelected, goRowMoving, goEditing]
      TabOrder = 0
      UpCase = False
      StartAtEnd = False
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = True
      Navigation.AllowDeleteRow = True
      Navigation.AdvanceOnEnter = True
      Navigation.AdvanceAtEnd = True
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = False
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = True
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 20
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'RT_ARROW'
          CharCase = ecNormal
          DfltValue = '">"'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 150
          Alignment = taLeftJustify
          Header = 'Column Header'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'KD_COLHEADER'
          CharCase = ecNormal
          Name = 'KColHeader'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 150
          Alignment = taLeftJustify
          Header = 'Key Name'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edComboList
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'KD_KEYNAME'
          CharCase = ecUpperCase
          Name = 'KeyName'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 150
          Alignment = taLeftJustify
          Header = 'Match Fld Name'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edComboEdit
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'KD_FIELDNAME'
          CharCase = ecUpperCase
          Name = 'KFieldName'
          DfltValue = 'Get_Key_Name'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = True
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        20
        150
        150
        150)
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 579
    Width = 537
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 4
    object btnSave: TButton
      Left = 280
      Top = 5
      Width = 75
      Height = 25
      Caption = 'Save'
      TabOrder = 0
    end
    object btnExit: TButton
      Left = 456
      Top = 5
      Width = 75
      Height = 25
      Caption = 'Exit'
      TabOrder = 1
    end
    object btnClear: TButton
      Left = 368
      Top = 5
      Width = 75
      Height = 25
      Caption = 'Clear'
      TabOrder = 2
    end
    object btnCopy: TButton
      Left = 16
      Top = 5
      Width = 75
      Height = 25
      Caption = 'Copy'
      TabOrder = 3
    end
    object Delete: TButton
      Left = 104
      Top = 5
      Width = 75
      Height = 25
      Caption = 'Delete'
      TabOrder = 4
    end
  end
  object slFieldData: TTASStrList
    Left = 304
    Top = 48
  end
  object slKeyData: TTASStrList
    Left = 336
    Top = 48
  end
end
