object EditForm1: TEditForm1
  Left = 464
  Top = 224
  Hint = 'C:\taspro7\DBA7\T7CMACON.DFM'
  AutoScroll = False
  Caption = ' Customer Contact Information'
  ClientHeight = 602
  ClientWidth = 764
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  No_Refresh = False
  OnStart = 'CMAcon.onstart'
  OnDisplayScreen = 'CMAcon.ondisp'
  ScreenPos = tpDesktopCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7CMA'
  RememberSize = True
  RememberSizeDate = 43222.616143969910000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Emails: TGroupBox
    Left = 4
    Top = 307
    Width = 373
    Height = 260
    Caption = 'E-Mails'
    ParentBackground = False
    TabOrder = 2
    object TASENTER10: TTASENTER
      Left = 147
      Top = 208
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 17
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER2: TTASENTER
      Left = 147
      Top = 17
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 1
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER3: TTASENTER
      Left = 147
      Top = 41
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 3
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER4: TTASENTER
      Left = 147
      Top = 65
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 5
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER5: TTASENTER
      Left = 147
      Top = 89
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 7
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER6: TTASENTER
      Left = 147
      Top = 113
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 9
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER7: TTASENTER
      Left = 147
      Top = 137
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 11
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER8: TTASENTER
      Left = 147
      Top = 161
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 13
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER9: TTASENTER
      Left = 147
      Top = 185
      Width = 215
      Height = 21
      AutoSize = False
      TabOrder = 15
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.EMAIL[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER11: TTASENTER
      Left = 3
      Top = 233
      Width = 17
      Height = 21
      AutoSize = False
      TabOrder = 19
      Text = 'TASENTER2'
      Visible = False
      FieldName = 'BKCM.ACCN.EMAIL[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER1: TTASENTER
      Left = 11
      Top = 17
      Width = 133
      Height = 22
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 0
      FieldName = 'BKCM.ACCN.EMLBL[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER32: TTASENTER
      Left = 11
      Top = 41
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 2
      FieldName = 'BKCM.ACCN.EMLBL[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER33: TTASENTER
      Left = 11
      Top = 65
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 4
      FieldName = 'BKCM.ACCN.EMLBL[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER34: TTASENTER
      Left = 11
      Top = 89
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 6
      FieldName = 'BKCM.ACCN.EMLBL[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER35: TTASENTER
      Left = 11
      Top = 113
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 8
      FieldName = 'BKCM.ACCN.EMLBL[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER36: TTASENTER
      Left = 11
      Top = 137
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 10
      FieldName = 'BKCM.ACCN.EMLBL[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER37: TTASENTER
      Left = 11
      Top = 161
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 12
      FieldName = 'BKCM.ACCN.EMLBL[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER38: TTASENTER
      Left = 11
      Top = 185
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 14
      FieldName = 'BKCM.ACCN.EMLBL[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER39: TTASENTER
      Left = 11
      Top = 209
      Width = 133
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 16
      FieldName = 'BKCM.ACCN.EMLBL[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER40: TTASENTER
      Left = 11
      Top = 233
      Width = 9
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 18
      Visible = False
      FieldName = 'BKCM.ACCN.EMLBL[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbEmailAck: TTASCheckBox
      Left = 16
      Top = 234
      Width = 90
      Height = 17
      Alignment = taLeftJustify
      Caption = 'Include: Ack'
      TabOrder = 20
      FieldName = 'email.ack'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbEmailPS: TTASCheckBox
      Left = 110
      Top = 234
      Width = 55
      Height = 17
      Alignment = taLeftJustify
      Caption = 'PkSlip'
      TabOrder = 21
      FieldName = 'email.pkslip'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbEmailInv: TTASCheckBox
      Left = 170
      Top = 234
      Width = 53
      Height = 17
      Alignment = taLeftJustify
      Caption = 'Invoice'
      TabOrder = 22
      FieldName = 'email.invoice'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbEmailQT: TTASCheckBox
      Left = 228
      Top = 234
      Width = 51
      Height = 17
      Alignment = taLeftJustify
      Caption = 'Quote'
      TabOrder = 23
      FieldName = 'email.quote'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbEmailSM: TTASCheckBox
      Left = 285
      Top = 234
      Width = 77
      Height = 17
      Hint = 'Statement'
      Alignment = taLeftJustify
      Caption = 'Statement'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 24
      FieldName = 'email.statement'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object APPanel: TPanel
      Left = 3
      Top = 230
      Width = 359
      Height = 29
      BevelOuter = bvNone
      TabOrder = 25
      Visible = False
      object TASCheckBox1: TTASCheckBox
        Left = 124
        Top = 6
        Width = 68
        Height = 17
        Hint = 'Statement'
        Alignment = taLeftJustify
        Caption = 'RFQ'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        FieldName = 'email.rfq'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox2: TTASCheckBox
        Left = 11
        Top = 6
        Width = 99
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Include: PO '
        TabOrder = 1
        FieldName = 'email.PO'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox3: TTASCheckBox
        Left = 214
        Top = 6
        Width = 68
        Height = 17
        Hint = 'Statement'
        Alignment = taLeftJustify
        Caption = 'E-Pay'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 2
        FieldName = 'email.epay'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 764
    Height = 46
    Align = alTop
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 0
    object Label1: TLabel
      Left = 8
      Top = 15
      Width = 64
      Height = 16
      Caption = 'Customer '
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Custname: TLabel
      Left = 332
      Top = 20
      Width = 4
      Height = 16
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label2: TLabel
      Left = 227
      Top = 5
      Width = 89
      Height = 16
      Caption = 'Contact Name'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label43: TLabel
      Left = 227
      Top = 26
      Width = 51
      Height = 16
      Caption = 'Position'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object Label3: TLabel
      Left = 600
      Top = 15
      Width = 102
      Height = 16
      Caption = 'Primary Contact'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object contact: TTASENTER
      Left = 320
      Top = 2
      Width = 266
      Height = 21
      AutoSize = False
      TabOrder = 0
      FieldName = 'BKCM.ACCN.CON  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_contname()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER42: TTASENTER
      Left = 320
      Top = 23
      Width = 266
      Height = 21
      AutoSize = False
      TabOrder = 1
      FieldName = 'BKCM.ACCN.TITLE[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER43: TTASENTER
      Left = 78
      Top = 13
      Width = 86
      Height = 24
      TabStop = False
      ReadOnly = True
      TabOrder = 3
      Text = 'TASENTER43'
      FieldName = 'BKCM.ACCN.CODE '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER63: TTASENTER
      Left = 711
      Top = 13
      Width = 18
      Height = 24
      CharCase = ecUpperCase
      TabOrder = 2
      Text = 'TASENTER63'
      FieldName = 'BKCM.ACCN.PRIM '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
  end
  object Phone: TGroupBox
    Left = 5
    Top = 46
    Width = 372
    Height = 260
    Caption = 'Phone Numbers'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 1
    object TASENTER12: TTASENTER
      Left = 205
      Top = 17
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 1
      FieldName = 'BKCM.ACCN.PHONE[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER13: TTASENTER
      Left = 205
      Top = 41
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 3
      FieldName = 'BKCM.ACCN.PHONE[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER14: TTASENTER
      Left = 205
      Top = 65
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 5
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER15: TTASENTER
      Left = 205
      Top = 89
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 7
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER16: TTASENTER
      Left = 205
      Top = 113
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 9
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER17: TTASENTER
      Left = 205
      Top = 137
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 11
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER18: TTASENTER
      Left = 205
      Top = 161
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 13
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER19: TTASENTER
      Left = 205
      Top = 185
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 15
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER20: TTASENTER
      Left = 205
      Top = 209
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 17
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER21: TTASENTER
      Left = 205
      Top = 233
      Width = 157
      Height = 21
      AutoSize = False
      TabOrder = 19
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.PHONE[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object phone1: TTASComboEnter
      Left = 11
      Top = 17
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 0
      FieldName = 'BKCM.ACCN.PHLBL[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone2: TTASComboEnter
      Left = 11
      Top = 41
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 2
      FieldName = 'BKCM.ACCN.PHLBL[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone3: TTASComboEnter
      Left = 11
      Top = 66
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 4
      FieldName = 'BKCM.ACCN.PHLBL[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone4: TTASComboEnter
      Left = 11
      Top = 89
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 6
      FieldName = 'BKCM.ACCN.PHLBL[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone5: TTASComboEnter
      Left = 11
      Top = 113
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 8
      FieldName = 'BKCM.ACCN.PHLBL[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone6: TTASComboEnter
      Left = 11
      Top = 138
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 10
      FieldName = 'BKCM.ACCN.PHLBL[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone7: TTASComboEnter
      Left = 11
      Top = 161
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 12
      FieldName = 'BKCM.ACCN.PHLBL[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone8: TTASComboEnter
      Left = 11
      Top = 185
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 14
      FieldName = 'BKCM.ACCN.PHLBL[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone9: TTASComboEnter
      Left = 11
      Top = 209
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 16
      FieldName = 'BKCM.ACCN.PHLBL[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object phone10: TTASComboEnter
      Left = 11
      Top = 233
      Width = 193
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      GlyphKind = gkDropDown
      NumGlyphs = 1
      ParentCtl3D = False
      TabOrder = 18
      FieldName = 'BKCM.ACCN.PHLBL[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object Misc: TGroupBox
    Left = 388
    Top = 46
    Width = 370
    Height = 260
    Caption = 'Misc. Information'
    ParentBackground = False
    TabOrder = 3
    object TASENTER22: TTASENTER
      Left = 167
      Top = 17
      Width = 192
      Height = 21
      AutoSize = False
      TabOrder = 1
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER23: TTASENTER
      Left = 166
      Top = 41
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 3
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER24: TTASENTER
      Left = 166
      Top = 65
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 5
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER25: TTASENTER
      Left = 166
      Top = 89
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 7
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.alph1[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER26: TTASENTER
      Left = 166
      Top = 113
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 9
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER27: TTASENTER
      Left = 166
      Top = 137
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 11
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER28: TTASENTER
      Left = 166
      Top = 161
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 13
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER29: TTASENTER
      Left = 166
      Top = 185
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 15
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER30: TTASENTER
      Left = 166
      Top = 209
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 17
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER31: TTASENTER
      Left = 166
      Top = 233
      Width = 194
      Height = 21
      AutoSize = False
      TabOrder = 19
      Text = 'TASENTER2'
      FieldName = 'BKCM.ACCN.ALPH1[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER41: TTASENTER
      Left = 11
      Top = 17
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 0
      FieldName = 'BKCM.ACCN.MSLBL[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER44: TTASENTER
      Left = 11
      Top = 41
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 2
      FieldName = 'BKCM.ACCN.MSLBL[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER45: TTASENTER
      Left = 11
      Top = 65
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 4
      FieldName = 'BKCM.ACCN.MSLBL[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER46: TTASENTER
      Left = 11
      Top = 89
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 6
      FieldName = 'BKCM.ACCN.MSLBL[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER47: TTASENTER
      Left = 11
      Top = 113
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 8
      FieldName = 'BKCM.ACCN.MSLBL[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER48: TTASENTER
      Left = 11
      Top = 137
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 10
      FieldName = 'BKCM.ACCN.MSLBL[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER49: TTASENTER
      Left = 11
      Top = 161
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 12
      FieldName = 'BKCM.ACCN.MSLBL[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER50: TTASENTER
      Left = 11
      Top = 185
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 14
      FieldName = 'BKCM.ACCN.MSLBL[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER51: TTASENTER
      Left = 11
      Top = 209
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 16
      FieldName = 'BKCM.ACCN.MSLBL[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER52: TTASENTER
      Left = 11
      Top = 233
      Width = 154
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 18
      FieldName = 'BKCM.ACCN.MSLBL[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object DATES: TGroupBox
    Left = 388
    Top = 307
    Width = 370
    Height = 260
    Caption = 'Misc. Dates'
    ParentBackground = False
    TabOrder = 4
    object TASDateEdit1: TTASDateEdit
      Left = 239
      Top = 17
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 1
      FieldName = 'BMCM.ACCN.DATE1[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit2: TTASDateEdit
      Left = 239
      Top = 41
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 3
      FieldName = 'BMCM.ACCN.DATE1[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit3: TTASDateEdit
      Left = 239
      Top = 65
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 5
      FieldName = 'BMCM.ACCN.DATE1[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit4: TTASDateEdit
      Left = 239
      Top = 89
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 7
      FieldName = 'BMCM.ACCN.DATE1[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit5: TTASDateEdit
      Left = 239
      Top = 113
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 9
      FieldName = 'BMCM.ACCN.DATE1[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit6: TTASDateEdit
      Left = 239
      Top = 137
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 11
      FieldName = 'BMCM.ACCN.DATE1[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit7: TTASDateEdit
      Left = 239
      Top = 161
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 13
      FieldName = 'BMCM.ACCN.DATE1[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit8: TTASDateEdit
      Left = 239
      Top = 185
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 15
      FieldName = 'BMCM.ACCN.DATE1[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit9: TTASDateEdit
      Left = 239
      Top = 209
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 17
      FieldName = 'BMCM.ACCN.DATE1[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASDateEdit10: TTASDateEdit
      Left = 239
      Top = 233
      Width = 121
      Height = 21
      BlanksChar = '0'
      NumGlyphs = 2
      StartOfWeek = Sun
      TabOrder = 19
      FieldName = 'BMCM.ACCN.DATE1[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER53: TTASENTER
      Left = 11
      Top = 17
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 0
      FieldName = 'BKCM.ACCN.DTLBL[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER54: TTASENTER
      Left = 11
      Top = 41
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 2
      FieldName = 'BKCM.ACCN.DTLBL[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER55: TTASENTER
      Left = 11
      Top = 65
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 4
      FieldName = 'BKCM.ACCN.DTLBL[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER56: TTASENTER
      Left = 11
      Top = 89
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 6
      FieldName = 'BKCM.ACCN.DTLBL[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER57: TTASENTER
      Left = 11
      Top = 113
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 8
      FieldName = 'BKCM.ACCN.DTLBL[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER58: TTASENTER
      Left = 11
      Top = 137
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 10
      FieldName = 'BKCM.ACCN.DTLBL[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER59: TTASENTER
      Left = 11
      Top = 161
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 12
      FieldName = 'BKCM.ACCN.DTLBL[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER60: TTASENTER
      Left = 11
      Top = 185
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 14
      FieldName = 'BKCM.ACCN.DTLBL[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER61: TTASENTER
      Left = 11
      Top = 209
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 16
      FieldName = 'BKCM.ACCN.DTLBL[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASENTER62: TTASENTER
      Left = 11
      Top = 233
      Width = 224
      Height = 21
      TabStop = False
      BorderStyle = bsNone
      Color = clMenu
      Ctl3D = False
      ParentCtl3D = False
      TabOrder = 18
      FieldName = 'BKCM.ACCN.DTLBL[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 568
    Width = 764
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 5
    object cmaconSAVE: TGlyphBtn
      Left = 631
      Top = 5
      Width = 62
      Height = 25
      Caption = '&Save'
      TabOrder = 0
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object cmaconExit: TGlyphBtn
      Left = 694
      Top = 5
      Width = 61
      Height = 25
      Caption = 'E&xit'
      TabOrder = 1
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object cmaconDELETE: TGlyphBtn
      Left = 97
      Top = 5
      Width = 71
      Height = 25
      Caption = '&Delete'
      TabOrder = 2
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
        F8F8F80000000000005A5A5A5A5A5A525252525252292929000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8212121949494FFFFFFCECECEDEDEDE94
        8C8CA5A5A56B6B6B636363393929000000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252B5ADADEFEFEF949494C6BDBD9494949494945252526B6B6B5A5A5A2121
        10F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEFA5A5A5C6C6C69494949C9C9C4A4A4A6B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F85252529C9C9CD6D6D6C6BDBD9C9C9C94
        94946B6B6B6B6B6B737373292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        393929949494C6BDBDCECECEC6BDBDA5A5A5A5A5A5A5A5A56B6B6B4A4A4A1010
        10F8F8F8F8F8F8F8F8F8F8F8F8000000A5A594DEDEDEC6C6C6BDB5B5BDBDBDBD
        BDBD8C8C8C8484846B6B6B6363635A5A5A000000F8F8F8F8F8F8F8F8F8000000
        737352D6CECEFFFFFFE7E7E7CECECEC6C6C6293939525252C6C6C69C94947B7B
        7B000000F8F8F8F8F8F8F8F8F80000005A5A5AADA5A5EFEFEFDEDEDE4A5A4A42
        5263848473525252B5B5B57B7B7B4A4A4A000000F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F80000000000003939392121217B7B6B314242000000000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F800
        0000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
      GlyphKind = bkCustom
    end
    object cmaconADD: TGlyphBtn
      Left = 5
      Top = 5
      Width = 91
      Height = 25
      Caption = 'Add &New'
      TabOrder = 3
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7ABB0AB6D8368426A3932
        60273B6435576E567D837DB5B5B5F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7608C5F198211158B00158B001D8B002C7A002C6F042868154864488F8F
        8FF0F3F7F0F3F7F0F3F7F0F3F7F0F3F7429143029C0202A00402A004029C0202
        97000994011C85013773002C6F04355D338F8F8FF0F3F7F0F3F7F0F3F767A068
        08A9130AA40D019C091AB12575E59385EAA46AE38B08A9130788003773002C6F
        04486448F0F3F7F0F3F7C0CEC01DAD2412AA230AA118019C09279D22E6EFE3FF
        FFFFCBF4D600A80E0788000788003773002868157D837DF0F3F779B77B28B63C
        18B12D0CBB2D02BB2616A527D8E9D8FFFFFFB4F0C500B81500A80E0BAB192385
        012C6F04576E56F0F3F74EAC5440C75B039B188ACD97BBE8CBB8E1C4EAEDEAF8
        F4F7E4F6EAB4F0C5CBF4D66AE38B0994012C7A003B6435F0F3F742AD4A51D374
        039B18BFCABCFFEAFDF9EEF8ECECECF0F0F0FAF4F9FFFBFFFFFBFF85EAA4029C
        02238501326027F0F3F74EAC5467DF8C09A022A4C0A1DCDDDADFDFDEEAE9EAEC
        ECECEAE9EAD8E9D8DDEDDD7AE89802A0041D8B00426A39F0F3F775C77972DB91
        34BF5824AA3C24AA3C3C9E3DD8DCD8F9EEF8B0DCBA24A22524A2251CB52905A2
        09158B006C8467F0F3F7B6CCB65BD77272E19C25CA5D19C64F24AA3CDCDBD9FF
        EAFDB1E5C202BB2605A11205A1120AA40D198211ABB0ABF0F3F7F0F3F765CB6C
        80E0A45EDB8C25CA5D25AB419FBF9BBFCABC8ACD9716BA3712AA230BAB190AA4
        0D638E61F0F3F7F0F3F7F0F3F7F0F3F753BC607FE0A16CE09B37C75E0DA42B03
        9B1809A02216BA3718B12D0BAB19429143F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F765CB6C5DDA7772E19C63E2914AD67637C75E28B63C1AB12567A068F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7B6CCB675C7794FB25842
        AD4A4EAC5479B77BC0CEC0F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      GlyphKind = bkCustom
    end
    object cmaconBACK: TGlyphBtn
      Left = 518
      Top = 5
      Width = 111
      Height = 25
      Caption = '&Back to List'
      TabOrder = 4
      TabStop = False
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
        C8D0D4C8D0D4D3D9DCDDE2E4E7EAECEDF0F1EDF0F1E7EAECDDE2E4D3D9DCC8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CCD4D7DCE1E3D3E0D677AE7929872900
        780000780029872977AE79D3E0D6DCE1E3CCD4D7C8D0D4C8D0D4C8D0D4CBD3D6
        DDE2E49EC2A10078001BA42034CE4048EC5A4DEE6240D35427A7330078009EC2
        A1DDE2E4CBD3D6C8D0D4C8D0D4D8DDE09CC19F057E0633D33C41E44F41D14B43
        CF4E43CC5036BB4553E56F51DE6D0A7F0D9CC19FD8DDE0C8D0D4CED4D8CAD8CF
        00780033D33C3ED8493EC44542C54A37B63E228B23ADCEAD1A91205EE97A5AE1
        7A007800CAD8CFCED4D8D3D9DC6FA7721AA31F40E34D3EC3433FC1461A921E80
        B580F2F7F2FFFFFF1B912057DC696EF69433AB466FA772D3D9DCD5DADC248425
        33CE3E3FD04927A32B439843C9DEC9FFFFFFFFFFFFFFFFFF1D93235CE17066EA
        835FDD82248425D5DADCD4D8DB00780045EB5729AD3180B580FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFF1F952763E87A69EC857FFDAD007800D4D8DBCFD4D6007800
        4AED5F2BAE3580B580FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2298296AF0836FF1
        8D85FDB5007800CFD4D6C9CFD21F82203ED25049D6592DA833318F33C9DEC9FF
        FFFFFFFFFFFFFFFF239A2D70F78D78F79A6CDE931F8220C9CFD2C5CCCF5F9C62
        24A73057EE724BCF574CCF5A20982771AD71F2F7F2FFFFFF249A2E73FA908BFD
        BA3EAD54529655C5CCCFC4CCD0ABBCB30078004DDD695AE77551D66157DB6849
        C959258F29ADCEAD259A3084FCAE79E7A3007800ABBCB3C4CCD0C8D0D4C0C7CA
        79A47F087F0D56E07669F48E61E67B63E77D64E57F52C96D7CEEA977E7A20D80
        1379A47FC0C7CAC8D0D4C8D0D4C5CDD1BBC2C674A27B00780030AB435BDC7E7A
        FDA980FDB070E69A3DAD5300780074A27BBBC2C6C5CDD1C8D0D4C8D0D4C8D0D4
        C4CCD0BAC1C59CB0A54490481780190078000078001780194F93539CB0A5BAC1
        C5C4CCD0C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C0C7CBB7BEC2B0B7BBAB
        B2B6ABB2B6B0B7BBB7BEC2C0C7CBC8D0D4C8D0D4C8D0D4C8D0D4}
      GlyphKind = bkCustom
    end
    object btnOutlook: TGlyphBtn
      Left = 169
      Top = 5
      Width = 89
      Height = 25
      Caption = 'Outlook'
      TabOrder = 5
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        18000000000000030000000000000000000000000000000000000066D20670CD
        0262A42276B02770BA1761AF166FB90B6DB30268B00466AE1469B70658A01D6E
        AB085DA10658BD0052C51A84E165C6FF81D1FF79C0EC84C8FF74BBFB77C7FF6A
        BEF863BCF566BEFA6ABDFB6BBAF377BCED74BBF44E9BF10051B40667A77CCDFF
        CCFDFFBFEAFDC2FBFFA9E9FFBBF6FFBDF8FFBDFDFFACF4FF92E1FFAAF3FFC3F2
        FFC6F2FF88C8FF0D589D3393C978C7F0CEF6FFDDFFFFC3FEFF83C6DD568CA32E
        6279296278488CA363B8CEA0ECFFD0FAFFADD4EA79BBEC1E6EAB228CCB6CC2F6
        CCFCFFC0EBFE468AA73582A36EAED09ADAF98CD1F265B6D72D8EAF3690AEB5EE
        FFB8EEFF71C3FD005EA4268ED16EC6FCC3FBFF9CCEE45898BA83CAEFAAEEFF9C
        E3FF83CFF387DBFF66C6EA328CAE7BBED7A1E5FF68C1FE0064AD2B83C382D1FF
        C1FFFF669AAB80B1D1B5EBFFBDFCFF96DEFCA9F6FFA0F1FF94E4FF55A2C33B86
        9C9CEAFF6BC1FD0763AC408DCB91D9FFC3FFFF538492C8EEFFD1F9FFA9E0FF4D
        91AE428CA84C97B78FD3F88FD2F32672859AEAFF67BBF5176CB6458DC990D3FF
        BFF7FF709CA9D1EFFFC9E9FFCCFBFF639FBC95D9F68ED1F0AFEDFF96D3F32A6F
        83A3EFFF6FBFFA186AB2519BD59EDFFFCCFAFF90B3C0B3D1EED0F3FFCEFAFF54
        88A6B3EFFFB4F4FFACEBFF67A6C84B879DAEEFFF7AC8FF1568B33B8FC997DAFF
        D9FCFFC0DAE88AB2CEB6E3FFD1FAFF91BADBB5E5FFBBF5FF96DDFF5599BC92C3
        DDB5E9FF7AC7FF106BB6479ED09EE1FFE3FDFFEAFDFF95C0D38BBBD3A4C6E393
        B3D0D1F7FF98CEED4992B24389A6C0E9FFC7F0FF81CBFF0B65AC4DA3C7A0E3FA
        EAFFFFF3FFFED8FEFFA9D3DF9DBAC98BA5B560819174A2B484C6D9BBF9FFDFFF
        FFC7EAFE8DCFFF2F81BB41A0C89CEAFFD8FFFFD7F6F7D4FFFFCFFFFFD4FCFFC4
        EBFFCFFEFFC5FDFFA9EEFFBBFDFFC5F3FFBCEDFF7FC9FF0C63A53EB1F479E1FF
        9DF0FF97DBF298D5FD96D2FFA7EAFF97E0FF82D0FF81D2FF82D4FF80D0FF7FCF
        F876CDFF5ABBFF1B83E023A0F0259ADD3BA2C95FB5D9559BD05194D14FA0D92A
        84BD3290CB2584C32E84CA2077B92D8FC50E77B60370CC006AD6}
      GlyphKind = bkCustom
    end
  end
  object PhonePop: TPopupMenu
    MenuAnimation = [maBottomToTop]
    Left = 128
    Top = 160
    object N2: TMenuItem
      Caption = 'Business Phone'
    end
    object N3: TMenuItem
      Caption = 'Business Fax'
    end
    object N4: TMenuItem
      Caption = 'Mobil'
    end
    object N5: TMenuItem
      Caption = 'Home'
    end
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 184
    Top = 4
  end
end
