object EditForm1: TEditForm1
  Left = 382
  Top = 264
  Hint = 'C:\TASPro7\DBA7\T7ROA.DFM'
  AutoScroll = False
  Caption = 'RO-A'
  ClientHeight = 477
  ClientWidth = 672
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7ROA.OnClose'
  No_Refresh = False
  OnStart = 'T7ROA.OnStart'
  OpenFiles = 'T7ROA.OnOpenFiles'
  OnDisplayScreen = 'T7ROA.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7ROA'
  RememberSize = True
  RememberSizeDate = 45293.516719328710000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object CyclePanel: TPanel
    Left = 5
    Top = 90
    Width = 664
    Height = 349
    TabOrder = 7
    object Label11: TLabel
      Left = 218
      Top = 196
      Width = 202
      Height = 16
      Caption = 'Cycle Time Threshold (In Seconds)'
    end
    object Label13: TLabel
      Left = 235
      Top = 216
      Width = 30
      Height = 16
      Caption = 'From'
    end
    object Label18: TLabel
      Left = 310
      Top = 216
      Width = 13
      Height = 16
      Caption = 'To'
    end
    object Label21: TLabel
      Left = 380
      Top = 216
      Width = 12
      Height = 16
      Caption = '%'
    end
    object Label39: TLabel
      Left = 175
      Top = 235
      Width = 27
      Height = 16
      Caption = 'RUN'
    end
    object Label40: TLabel
      Left = 175
      Top = 323
      Width = 43
      Height = 16
      Caption = 'SETUP'
    end
    object btnCycleOK: TGlyphBtn
      Left = 577
      Top = 316
      Width = 75
      Height = 25
      Caption = 'Ok'
      TabOrder = 9
      GlyphKind = bkCustom
    end
    object CycleGrid: TTASDataGrid
      Left = 0
      Top = 4
      Width = 661
      Height = 183
      TabStop = False
      ColCount = 8
      Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
      TabOrder = 10
      UpCase = False
      StartAtEnd = True
      PrePrgLoc = 0
      PostPrgLoc = 0
      Navigation.AllowInsertRow = False
      Navigation.AllowDeleteRow = True
      Navigation.AdvanceOnEnter = True
      Navigation.AdvanceAtEnd = False
      Navigation.AdvanceDirection = adLeftRight
      Navigation.AdvanceAuto = False
      Navigation.InsertPosition = pInsertBefore
      Navigation.CursorWalkEditor = False
      Navigation.AllowAddRecListF = True
      MouseActions.ColSelect = False
      MouseActions.RowSelect = False
      MouseActions.DirectEdit = False
      MouseActions.DirectComboDrop = False
      MouseActions.CaretPositioning = False
      PasswordChar = '*'
      Columns = <
        item
          Color = clWindow
          Width = 61
          Alignment = taLeftJustify
          Header = 'Date'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYC.DATE'
          CharCase = ecNormal
          Name = 'WO'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 87
          Alignment = taCenter
          Header = 'WO Num'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCWONUM'
          CharCase = ecNormal
          Name = 'ShipQtyCol'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 65
          Alignment = taLeftJustify
          Header = 'Machine'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCMACH'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 62
          Alignment = taRightJustify
          Header = 'HRs'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCHR'
          CharCase = ecNormal
          Name = 'Item'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 64
          Alignment = taRightJustify
          Header = 'Min.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCMIN'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 53
          Alignment = taRightJustify
          Header = 'Sec.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCSEC'
          CharCase = ecNormal
          Name = 'wo'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 83
          Alignment = taRightJustify
          Header = 'Parts/Cycle'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCPARTS'
          CharCase = ecNormal
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end
        item
          Color = clWindow
          Width = 173
          Alignment = taLeftJustify
          Header = 'Employee'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          Editor = edDefault
          Fixed = False
          ReadOnly = False
          Password = False
          ComboItemsSort = False
          SpinMin = 0
          SpinMax = 0
          SpinStep = 0
          EditLength = 0
          Borders = []
          BorderPen.Color = clSilver
          FieldName = 'LIST.CYCEMP'
          CharCase = ecNormal
          Name = 'BXQty'
          PrePrgLoc = 0
          PostPrgLoc = 0
          ValidPrgLoc = 0
          ClickPrgLoc = 0
          ChangePrgLoc = 0
          DecimalChrs = 2
          FormatOnEnter = True
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          TimeFieldType = tf_5
          ElapsedTime = False
        end>
      ExtraFields = <>
      AutoNumAlign = False
      SelectionColor = clHighlight
      SelectionTextColor = clHighlightText
      SelectionRectangle = False
      FixedFont.Charset = DEFAULT_CHARSET
      FixedFont.Color = clWindowText
      FixedFont.Height = -13
      FixedFont.Name = 'Arial'
      FixedFont.Style = []
      VAlignment = vtaTop
      Hovering = False
      EnhRowColMove = False
      HintColor = clYellow
      CurrentRow = 1
      CurrentCol = 1
      GridFileHandle = 0
      GridFileKeyNum = 0
      NoAutoUpdate = False
      ColWidths = (
        61
        87
        65
        62
        64
        53
        83
        173)
    end
    object EnterCycle1: TTASNumEnter
      Left = 227
      Top = 234
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 0
      FieldName = 'CYCLE.TIME[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle2: TTASNumEnter
      Left = 296
      Top = 234
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 1
      FieldName = 'CYCLE.TIME[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle3: TTASNumEnter
      Left = 363
      Top = 234
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 2
      FieldName = 'CYCLE.TIME[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle4: TTASNumEnter
      Left = 227
      Top = 259
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 3
      FieldName = 'CYCLE.TIME[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle5: TTASNumEnter
      Left = 296
      Top = 259
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 4
      FieldName = 'CYCLE.TIME[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle6: TTASNumEnter
      Left = 363
      Top = 259
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 5
      FieldName = 'CYCLE.TIME[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle7: TTASNumEnter
      Left = 227
      Top = 283
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 6
      FieldName = 'CYCLE.TIME[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCycle8: TTASNumEnter
      Left = 363
      Top = 283
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 7
      FieldName = 'CYCLE.TIME[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter2: TTASNumEnter
      Left = 363
      Top = 321
      Width = 45
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 8
      FieldName = 'CYCLE.TIME[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
  end
  object MainPanel: TPanel
    Left = 0
    Top = 88
    Width = 672
    Height = 355
    Align = alClient
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    object Label10: TLabel
      Left = 18
      Top = 6
      Width = 58
      Height = 16
      Caption = 'Sequence'
      Transparent = True
    end
    object Label12: TLabel
      Left = 18
      Top = 30
      Width = 28
      Height = 16
      Caption = 'Oper'
      Transparent = True
    end
    object Label15: TLabel
      Left = 18
      Top = 54
      Width = 27
      Height = 16
      Caption = 'Type'
      Transparent = True
    end
    object Label16: TLabel
      Left = 186
      Top = 6
      Width = 65
      Height = 16
      Caption = 'Description'
      Transparent = True
    end
    object Label17: TLabel
      Left = 421
      Top = 6
      Width = 73
      Height = 16
      Caption = 'Work Center'
      Transparent = True
    end
    object Label19: TLabel
      Left = 584
      Top = 6
      Width = 38
      Height = 16
      Caption = 'Rout #'
      Transparent = True
    end
    object Label20: TLabel
      Left = 638
      Top = 6
      Width = 24
      Height = 16
      Caption = 'Line'
      Transparent = True
    end
    object Label22: TLabel
      Left = 18
      Top = 125
      Width = 73
      Height = 16
      Caption = 'Processes #'
      Transparent = True
    end
    object Label23: TLabel
      Left = 100
      Top = 125
      Width = 56
      Height = 16
      Caption = 'Time/Part'
      Transparent = True
    end
    object Label24: TLabel
      Left = 211
      Top = 125
      Width = 62
      Height = 16
      Caption = 'Parts/Hour'
      Transparent = True
    end
    object Label25: TLabel
      Left = 439
      Top = 125
      Width = 34
      Height = 16
      Caption = 'Setup'
      Transparent = True
    end
    object Label26: TLabel
      Left = 18
      Top = 178
      Width = 62
      Height = 16
      Caption = 'OVERLAP'
    end
    object Label27: TLabel
      Left = 100
      Top = 176
      Width = 46
      Height = 16
      Caption = 'Forward'
    end
    object Label28: TLabel
      Left = 100
      Top = 199
      Width = 57
      Height = 16
      Caption = 'Backward'
    end
    object Label29: TLabel
      Left = 251
      Top = 176
      Width = 40
      Height = 16
      Caption = '[hours]'
    end
    object Label30: TLabel
      Left = 251
      Top = 199
      Width = 37
      Height = 16
      Caption = '[parts]'
    end
    object Label31: TLabel
      Left = 403
      Top = 198
      Width = 59
      Height = 16
      Caption = 'Persons #'
    end
    object Label32: TLabel
      Left = 18
      Top = 229
      Width = 49
      Height = 16
      Caption = 'Machine'
      Transparent = True
    end
    object Label33: TLabel
      Left = 18
      Top = 254
      Width = 23
      Height = 16
      Caption = 'Tool'
      Transparent = True
    end
    object Label34: TLabel
      Left = 18
      Top = 278
      Width = 146
      Height = 16
      Caption = 'OUTSIDE PROCESSING'
    end
    object Label35: TLabel
      Left = 18
      Top = 299
      Width = 40
      Height = 16
      Caption = 'Vendor'
      Transparent = True
    end
    object Label36: TLabel
      Left = 18
      Top = 323
      Width = 27
      Height = 16
      Caption = 'Cost'
    end
    object Label37: TLabel
      Left = 267
      Top = 323
      Width = 66
      Height = 16
      Caption = 'Min Charge'
    end
    object Label38: TLabel
      Left = 475
      Top = 323
      Width = 60
      Height = 16
      Caption = 'Lead Time'
      Transparent = True
    end
    object Label1: TLabel
      Left = 19
      Top = 77
      Width = 54
      Height = 16
      Caption = 'Seq Type'
      Transparent = True
    end
    object Label5: TLabel
      Left = 305
      Top = 125
      Width = 79
      Height = 16
      Caption = 'Decimal Time'
      Transparent = True
    end
    object Label6: TLabel
      Left = 19
      Top = 102
      Width = 59
      Height = 16
      Caption = 'Time Type'
    end
    object Label7: TLabel
      Left = 130
      Top = 102
      Width = 69
      Height = 16
      Caption = 'Lines/Comp'
    end
    object Label8: TLabel
      Left = 583
      Top = 125
      Width = 84
      Height = 16
      Caption = 'Min. Run Time'
      Transparent = True
    end
    object EnterSeq: TTASNumEnter
      Left = 100
      Top = 4
      Width = 44
      Height = 21
      AutoSize = False
      DisplayFormat = '0;0'
      TabOrder = 0
      FieldName = 'SCRN.OPER'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_seq()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      KeyTraps = 'F2|LIST_LINES'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterType: TTASComboBox
      Left = 100
      Top = 49
      Width = 167
      Height = 24
      ItemHeight = 16
      TabOrder = 3
      Text = 'EnterType'
      Items.Strings = (
        'L - Labor'
        'P - Outside Processing'
        'A - Alternate Operation')
      FieldName = 'MTRO.TYPE.STR'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_type()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object MTRO_OPERDESC_R: TTASENTER
      Left = 184
      Top = 27
      Width = 224
      Height = 21
      AutoSize = False
      TabOrder = 2
      Text = 'MTRO_OPERDESC_R'
      FieldName = 'MTRO.OPERDESC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterWC: TTASComboEnter
      Left = 419
      Top = 28
      Width = 158
      Height = 21
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 5
      Text = 'EnterWC'
      FieldName = 'MTRO.WC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_wc()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERWC.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object MTRO_NUM: TTASNumEnter
      Left = 584
      Top = 28
      Width = 44
      Height = 21
      AutoSize = False
      DisplayFormat = '00;00'
      TabOrder = 6
      FieldName = 'MTRO.NUM'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_routnum()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object CUR_LINE: TTASNumEnter
      Left = 638
      Top = 28
      Width = 26
      Height = 21
      TabStop = False
      AutoSize = False
      DisplayFormat = '00;00'
      ReadOnly = True
      TabOrder = 7
      FieldName = 'CUR.LINE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_WCDESC: TTASENTER
      Left = 419
      Top = 51
      Width = 157
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 8
      Text = 'DISP_WCDESC'
      FieldName = 'DISP.WCDESC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterNumProc: TTASNumEnter
      Left = 18
      Top = 144
      Width = 60
      Height = 21
      AutoSize = False
      DisplayFormat = '0;0'
      TabOrder = 15
      FieldName = 'mtro.num.proces'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_numproc()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterTimePart: TTASTimeEnter
      Left = 100
      Top = 144
      Width = 100
      Height = 21
      AutoSize = False
      TabOrder = 16
      Text = 'EnterTimePart'
      FieldName = 'MTRO.TIMEPART'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_timepart()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      FocusOnObject = 'enterpartshr'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterPartsHr: TTASNumEnter
      Left = 210
      Top = 144
      Width = 83
      Height = 21
      AutoSize = False
      DisplayFormat = '0.00;0.00'
      TabOrder = 17
      FieldName = 'MTRO.PARTSHR'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_partshr()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      FocusOnObject = 'enterlongtime'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterSetup: TTASTimeEnter
      Left = 440
      Top = 144
      Width = 84
      Height = 21
      AutoSize = False
      TabOrder = 19
      Text = 'EnterSetup'
      FieldName = 'MTRO.SETUPHRS'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'post.setup('#39'N'#39')'
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterOverLapF: TTASNumEnter
      Left = 175
      Top = 172
      Width = 60
      Height = 21
      AutoSize = False
      DisplayFormat = '00;00'
      TabOrder = 22
      FieldName = 'MTRO.OVERLAP'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_overlap()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterOverLapB: TTASNumEnter
      Left = 176
      Top = 197
      Width = 60
      Height = 21
      AutoSize = False
      DisplayFormat = '0.00;0.00'
      TabOrder = 23
      FieldName = 'MTRO.NEGOVLP'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_overlap()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object tagSTDTime: TTASCheckBox
      Left = 402
      Top = 175
      Width = 104
      Height = 17
      Alignment = taLeftJustify
      Caption = 'Std Time?'
      TabOrder = 24
      FieldName = 'MTRO.STD.TIME'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object EnterPerson: TTASNumEnter
      Left = 493
      Top = 194
      Width = 123
      Height = 21
      AutoSize = False
      DisplayFormat = '0.00;0.00'
      TabOrder = 25
      FieldName = 'MTRO.NUM.PERSON'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_person()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterMachine: TTASComboEnter
      Left = 100
      Top = 227
      Width = 140
      Height = 21
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 26
      Text = 'MTRO_TMACHINE'
      FieldName = 'MTRO.TMACHINE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_machine()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERMACHINE.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object MTRO_TMACHDESC: TTASENTER
      Left = 267
      Top = 227
      Width = 350
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 27
      Text = 'MTRO_TMACHDESC'
      FieldName = 'MTRO.TMACHDESC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterTool: TTASComboEnter
      Left = 100
      Top = 251
      Width = 140
      Height = 21
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 28
      Text = 'ENTERTOOL'
      FieldName = 'MTRO.TOOL'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_tool()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERTOOL.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object MTRO_TOOLDESC: TTASENTER
      Left = 268
      Top = 251
      Width = 350
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 29
      Text = 'MTRO_TOOLDESC'
      FieldName = 'MTRO.TOOLDESC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterVend: TTASComboEnter
      Left = 100
      Top = 297
      Width = 140
      Height = 21
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 30
      Text = 'EnterVend'
      FieldName = 'MTRO.VENDCODE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_vendor()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERVEND.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object MTRO_VENDNAME: TTASENTER
      Left = 266
      Top = 296
      Width = 350
      Height = 21
      TabStop = False
      AutoSize = False
      ReadOnly = True
      TabOrder = 31
      Text = 'MTRO_VENDNAME'
      FieldName = 'MTRO.VENDNAME'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterVendCost: TTASNumEnter
      Left = 100
      Top = 321
      Width = 140
      Height = 21
      AutoSize = False
      DecimalPlaces = 6
      DisplayFormat = '0.000000;0.000000'
      TabOrder = 32
      FieldName = 'MTRO.VENDCOST'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterCharge: TTASNumEnter
      Left = 344
      Top = 321
      Width = 96
      Height = 21
      AutoSize = False
      DisplayFormat = '0.00;0.00'
      TabOrder = 33
      FieldName = 'MTRO.MIN.CHG'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterLeadTime: TTASNumEnter
      Left = 559
      Top = 321
      Width = 60
      Height = 21
      AutoSize = False
      DisplayFormat = '00;00'
      TabOrder = 34
      FieldName = 'MTRO.LEAD'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_leadtime()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterOper: TTASNumEnter
      Left = 100
      Top = 26
      Width = 43
      Height = 21
      AutoSize = False
      DisplayFormat = '0'
      TabOrder = 1
      FieldName = 'MTRO.OP.TEMP.NO'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_oper()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      KeyTraps = 'F2|OPERLOOKUP.CLICK'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object EnterSeqType: TTASENTER
      Left = 99
      Top = 75
      Width = 24
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 4
      Text = 'ENTERSEQTYPE'
      FieldName = 'seq.type'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = 'RS CFL'
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterLongTime: TTASNumEnter
      Left = 305
      Top = 144
      Width = 121
      Height = 21
      AutoSize = False
      DecimalPlaces = 7
      DisplayFormat = '0.0000000;-0.0000000'
      TabOrder = 18
      FieldName = 'mtro.longtime'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_LongTime()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      FocusOnObject = 'entersetup'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object entAtype: TTASENTER
      Left = 100
      Top = 100
      Width = 22
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 9
      Text = 'ENTATYPE'
      FieldName = 'accu.type'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      AllowedChrs = 'LCFK'
      ReturnIsTab = True
      SelectStart = 0
      FocusOnObject = 'entAnum'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object entAnum: TTASNumEnter
      Left = 210
      Top = 100
      Width = 81
      Height = 21
      AutoSize = False
      DecimalPlaces = 0
      DisplayFormat = '0'
      TabOrder = 10
      FieldName = 'accu.num'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      FocusOnObject = 'enternumproc'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object minrun: TTASTimeEnter
      Left = 584
      Top = 144
      Width = 84
      Height = 21
      AutoSize = False
      TabOrder = 21
      Text = 'EnterSetup'
      FieldName = 'MTRO.DEF.TIME  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'post.setup('#39'A'#39')'
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object cbPrint: TTASCheckBox
      Left = 421
      Top = 79
      Width = 80
      Height = 17
      Alignment = taLeftJustify
      Caption = 'Print?'
      TabOrder = 11
      FieldName = 'MTRO.PRINT'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbParallel: TTASCheckBox
      Left = 421
      Top = 100
      Width = 80
      Height = 17
      Alignment = taLeftJustify
      Caption = 'Parallel?'
      TabOrder = 14
      FieldName = 'parallel'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbCycleTimeReqd: TTASCheckBox
      Left = 515
      Top = 79
      Width = 154
      Height = 17
      Caption = ' Cycle Time Required?'
      TabOrder = 12
      FieldName = 'cycle.Time.Reqd'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object cbCycleCalcReqd: TTASCheckBox
      Left = 515
      Top = 99
      Width = 154
      Height = 17
      Caption = ' Time/Part Required?'
      TabOrder = 13
      FieldName = 'cycle.calc.Reqd'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object EnterDSetup: TTASNumEnter
      Left = 440
      Top = 144
      Width = 83
      Height = 21
      AutoSize = False
      DecimalPlaces = 4
      DisplayFormat = '0.0000'
      TabOrder = 20
      FieldName = 'setuphrs.dec'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'post.setup('#39'D'#39')'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      FocusOnObject = 'enterlongtime'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object OperLookup: TGlyphBtn
      Left = 143
      Top = 24
      Width = 24
      Height = 24
      Hint = 'Lookup'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 35
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      Spacing = 3
      GlyphKind = bkCustom
    end
  end
  object ESTPanel: TPanel
    Left = 81
    Top = 90
    Width = 525
    Height = 351
    BevelInner = bvLowered
    ParentBackground = False
    TabOrder = 6
    Visible = False
    object Label2: TLabel
      Left = 26
      Top = 22
      Width = 66
      Height = 16
      Caption = 'Qty Breaks'
    end
    object Label3: TLabel
      Left = 199
      Top = 22
      Width = 70
      Height = 16
      Caption = 'Parts / Hour'
    end
    object Label4: TLabel
      Left = 371
      Top = 22
      Width = 66
      Height = 16
      Caption = 'Setup Time'
    end
    object TASNumEnter1: TTASNumEnter
      Left = 22
      Top = 46
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 0
      FieldName = 'est.qty[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object ph1: TTASNumEnter
      Left = 195
      Top = 46
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 1
      FieldName = 'BKRT.PARTSHR[1]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter1: TTASTimeEnter
      Left = 368
      Top = 46
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 2
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[1]     '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter3: TTASNumEnter
      Left = 22
      Top = 71
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 3
      FieldName = 'est.qty[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter4: TTASNumEnter
      Left = 195
      Top = 71
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 4
      FieldName = 'BKRT.PARTSHR[2]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter2: TTASTimeEnter
      Left = 368
      Top = 71
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 5
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter5: TTASNumEnter
      Left = 22
      Top = 96
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 6
      FieldName = 'est.qty[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter6: TTASNumEnter
      Left = 22
      Top = 121
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 9
      FieldName = 'est.qty[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter7: TTASNumEnter
      Left = 195
      Top = 96
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 7
      FieldName = 'BKRT.PARTSHR[3]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter8: TTASNumEnter
      Left = 195
      Top = 121
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 10
      FieldName = 'BKRT.PARTSHR[4]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter3: TTASTimeEnter
      Left = 368
      Top = 96
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 8
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASTimeEnter4: TTASTimeEnter
      Left = 368
      Top = 121
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 11
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter9: TTASNumEnter
      Left = 22
      Top = 146
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 12
      FieldName = 'est.qty[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter10: TTASNumEnter
      Left = 195
      Top = 146
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 13
      FieldName = 'BKRT.PARTSHR[5]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter5: TTASTimeEnter
      Left = 368
      Top = 146
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 14
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter11: TTASNumEnter
      Left = 22
      Top = 171
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 15
      FieldName = 'est.qty[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter12: TTASNumEnter
      Left = 195
      Top = 171
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 16
      FieldName = 'BKRT.PARTSHR[6]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter6: TTASTimeEnter
      Left = 368
      Top = 171
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 17
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter13: TTASNumEnter
      Left = 22
      Top = 196
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 18
      FieldName = 'est.qty[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter14: TTASNumEnter
      Left = 195
      Top = 196
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 19
      FieldName = 'BKRT.PARTSHR[7]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter7: TTASTimeEnter
      Left = 368
      Top = 196
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 20
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter15: TTASNumEnter
      Left = 22
      Top = 221
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 21
      FieldName = 'est.qty[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter16: TTASNumEnter
      Left = 195
      Top = 221
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 22
      FieldName = 'BKRT.PARTSHR[8]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter8: TTASTimeEnter
      Left = 368
      Top = 221
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 23
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter17: TTASNumEnter
      Left = 22
      Top = 246
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 24
      FieldName = 'est.qty[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter18: TTASNumEnter
      Left = 195
      Top = 246
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 25
      FieldName = 'BKRT.PARTSHR[9]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter9: TTASTimeEnter
      Left = 368
      Top = 246
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 26
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASNumEnter19: TTASNumEnter
      Left = 22
      Top = 271
      Width = 121
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clMenu
      DisplayFormat = ',0.00;-,0.00'
      ReadOnly = True
      TabOrder = 27
      FieldName = 'est.qty[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASNumEnter20: TTASNumEnter
      Left = 195
      Top = 271
      Width = 121
      Height = 21
      AutoSize = False
      DisplayFormat = ',0.00;-,0.00'
      TabOrder = 28
      FieldName = 'BKRT.PARTSHR[10]  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object TASTimeEnter10: TTASTimeEnter
      Left = 368
      Top = 271
      Width = 109
      Height = 21
      AutoSize = False
      TabOrder = 29
      Text = 'TASTimeEnter1'
      FieldName = 'BKRT.SETUP[10] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      ReturnIsTab = True
      SelectStart = 0
      TimeFieldType = tf_5
      ElapsedTime = False
      AMString = 'AM'
      PMString = 'PM'
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object btnok: TGlyphBtn
      Left = 444
      Top = 317
      Width = 75
      Height = 25
      Caption = 'Ok'
      TabOrder = 30
      GlyphKind = bkCustom
    end
  end
  object ToolBar1: TToolBar
    Left = 0
    Top = 0
    Width = 672
    Height = 29
    ButtonHeight = 26
    ButtonWidth = 8
    Caption = 'ToolBar1'
    EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
    EdgeInner = esLowered
    List = True
    TabOrder = 5
    Transparent = True
    object btnFirst: TGlyphBtn
      Left = 0
      Top = 0
      Width = 25
      Height = 26
      Hint = 'Find First'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 8
      TabStop = False
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00BBC0C400999D9E007678790062626100626261007577
        770091959600B1B8BA00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00B7BABC009797950091908D009F9D9A00A5A3A1009C9A98008583
        8100626261006B6D6D009CA0A200FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00C4C7C800B4B3B000BFBCB800D4D0CC00E3DFDB00E8E3DF00E5E1DC00D7D3
        D000B8B5B200858381005F605F009CA0A200FFFFFE00FFFFFE00FFFFFE00CCD2
        D400D3D2CF00D9D5D100E5E1DC00EDE8E300EFEBE600F0EBE700F0EBE700EFEB
        E600E7E3DF00CBC6C3008C8A88006B6D6D00B3B8BC00FFFFFE00FFFFFE00DBDD
        DD00EFEAE500ECE7E300EFEAE500F0EBE700F0EBE700F0EBE700F0EBE700EFE9
        E400EFEBE600E8E3DF00C0BCB9007B7A790094989900FFFFFE00FFFFFE00E6E5
        E300F0ECE700F0EBE700EFEBE600967F6F00F0EBE700F0EBE700DED5CF00C0B2
        A800F0EBE700EFEBE600DBD7D4009D9B990082838400FFFFFE00FFFFFE00EFEB
        E800F1EDE800F0EBE700F0EBE7008D746200F0EBE700D1C5BC009C867700B7A7
        9B00F0EBE700F0EBE700E8E3DF00B7B4B00081807F00FFFFFE00FFFFFE00EFEB
        E800F1EDEA00F0EBE700F0EBE7008D736200E9E2DC00826E6200866E5E00B3A1
        9500F0EBE700F0EBE700EEE9E400C8C3C00092918E00FFFFFE00FFFFFE00E7E7
        E600F1EFEB00F0ECE800F0EBE7008C726100F0EBE700DED7D20085746900A895
        8600F0EBE700F0EBE700EFEBE600CCC8C400A9A9A800FFFFFE00FFFFFE00DCDF
        E000F2EFED00F1EEEA00F0EBE700846C5C00F0EBE700F0EBE700E7E2DC00B4A8
        9D00F0EBE700F0EBE700EEE9E400CECAC500BCC0C000FFFFFE00FFFFFE00D0D6
        D800EBEBEA00F2EFEC00F1EDE900F0EBE700F0EBE700F0EBE700F0EBE700F0EB
        E700F0EBE700F0EBE700F0EBE700D4D3D000C9CFD000FFFFFE00FFFFFE00FFFF
        FE00D9DCDF00EFEFEE00F2EFED00F1EEEB00F0ECE800F0ECE700F0EBE700F0EC
        E700F0ECE800F1EDE900EEEBE600D6D8D900FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00D9DCDF00EBEBEB00F2F0EF00F2EFED00F1EFEB00F1EFEB00F1EE
        EB00F1EEEB00EAE9E600D8DBDC00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00D0D6D900DCE0E200E7E9E800EFEFEC00EFEEEB00E7E7
        E700DCDFDF00D0D6D800FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00}
      Spacing = 3
      GlyphKind = bkCustom
    end
    object btnPrev: TGlyphBtn
      Left = 25
      Top = 0
      Width = 25
      Height = 26
      Hint = 'Find Previous'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8B1B8BA91959675777762
        6261626261767879999D9EBBC0C4F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F89CA0A26B6D6D6262618583819C9A98A5A3A19F9D9A91908D979795B7BA
        BCF8F8F8F8F8F8F8F8F8F8F8F8F8F8F89CA0A25F605F858381B8B5B2D7D3D0E5
        E1DCE8E3DFE3DFDBD4D0CCBFBCB8B4B3B0C4C7C8F8F8F8F8F8F8F8F8F8B3B8BC
        6B6D6D8C8A88CBC6C3E7E3DFEFEBE6F0EBE7F0EBE7EFEBE6EDE8E3E5E1DCD9D5
        D1D3D2CFCCD2D4F8F8F8F8F8F89498997B7A79C0BCB9E8E3DFEFEBE6F0EBE7F0
        EBE7F0EBE7DFD3CAD3C1B4EFEAE5ECE7E3EFEAE5DBDDDDF8F8F8F8F8F8828384
        9D9B99DBD7D4EFEBE6F0EBE7F0EBE7EBE3DECAB4A6B89D89BAA190EFEBE6F0EB
        E7F0ECE7E6E5E3F8F8F8F8F8F881807FB7B4B0E8E3DFF0EBE7F0EBE7D4C4B8BD
        A493B69985AA8971AE9989F0EBE7F0EBE7F1EDE8EFEBE8F8F8F8F8F8F892918E
        C8C3C0EEE9E4F0EBE7C9B3A4B2927DAE8D76AC8A73A68570AE9989F0EBE7F0EB
        E7F1EDEAEFEBE8F8F8F8F8F8F8A9A9A8CCC8C4EFEBE6F0EBE7F0EBE7D0C4BA9A
        806EA0816DA4846EAE9989F0EBE7F0ECE8F1EFEBE7E7E6F8F8F8F8F8F8BCC0C0
        CECAC5EEE9E4F0EBE7F0EBE7F0EBE7F0EBE7BCACA0907665A79385F0EBE7F1EE
        EAF2EFEDDCDFE0F8F8F8F8F8F8C9CFD0D4D3D0F0EBE7F0EBE7F0EBE7F0EBE7F0
        EBE7F0EBE7EBE6E0D7CCC4F1EDE9F2EFECEBEBEAD0D6D8F8F8F8F8F8F8F8F8F8
        D6D8D9EEEBE6F1EDE9F0ECE8F0ECE7F0EBE7F0ECE7F0ECE8F1EEEBF2EFEDEFEF
        EED9DCDFF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8D8DBDCEAE9E6F1EEEBF1EEEBF1
        EFEBF1EFEBF2EFEDF2F0EFEBEBEBD9DCDFF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8F8F8F8D0D6D8DCDFDFE7E7E7EFEEEBEFEFECE7E9E8DCE0E2D0D6D9F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
      Spacing = 3
      GlyphKind = bkCustom
    end
    object btnNext: TGlyphBtn
      Left = 50
      Top = 0
      Width = 25
      Height = 26
      Hint = 'Find Next'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8BBC0C4999D9E76787962
        6261626261757777919596B1B8BAF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8B7BABC97979591908D9F9D9AA5A3A19C9A988583816262616B6D6D9CA0
        A2F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8C4C7C8B4B3B0BFBCB8D4D0CCE3DFDBE8
        E3DFE5E1DCD7D3D0B8B5B28583815F605F9CA0A2F8F8F8F8F8F8F8F8F8CCD2D4
        D3D2CFD9D5D1E5E1DCEDE8E3EFEBE6F0EBE7F0EBE7EFEBE6E7E3DFCBC6C38C8A
        886B6D6DB3B8BCF8F8F8F8F8F8DBDDDDEFEAE5ECE7E3EFEAE5D3C1B4DFD3CAF0
        EBE7F0EBE7F0EBE7EFEBE6E8E3DFC0BCB97B7A79949899F8F8F8F8F8F8E6E5E3
        F0ECE7F0EBE7EFEBE6BAA190B89D89CAB4A6EBE3DEF0EBE7F0EBE7EFEBE6DBD7
        D49D9B99828384F8F8F8F8F8F8EFEBE8F1EDE8F0EBE7F0EBE7AE9989AA8971B6
        9985BDA493D4C4B8F0EBE7F0EBE7E8E3DFB7B4B081807FF8F8F8F8F8F8EFEBE8
        F1EDEAF0EBE7F0EBE7AE9989A68570AC8A73AE8D76B2927DC9B3A4F0EBE7EEE9
        E4C8C3C092918EF8F8F8F8F8F8E7E7E6F1EFEBF0ECE8F0EBE7AE9989A4846EA0
        816D9A806ED0C4BAF0EBE7F0EBE7EFEBE6CCC8C4A9A9A8F8F8F8F8F8F8DCDFE0
        F2EFEDF1EEEAF0EBE7A79385907665BCACA0F0EBE7F0EBE7F0EBE7F0EBE7EEE9
        E4CECAC5BCC0C0F8F8F8F8F8F8D0D6D8EBEBEAF2EFECF1EDE9D7CCC4EBE6E0F0
        EBE7F0EBE7F0EBE7F0EBE7F0EBE7F0EBE7D4D3D0C9CFD0F8F8F8F8F8F8F8F8F8
        D9DCDFEFEFEEF2EFEDF1EEEBF0ECE8F0ECE7F0EBE7F0ECE7F0ECE8F1EDE9EEEB
        E6D6D8D9F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8D9DCDFEBEBEBF2F0EFF2EFEDF1
        EFEBF1EFEBF1EEEBF1EEEBEAE9E6D8DBDCF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8F8F8F8D0D6D9DCE0E2E7E9E8EFEFECEFEEEBE7E7E7DCDFDFD0D6D8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
      Spacing = 3
      GlyphKind = bkCustom
    end
    object btnLast: TGlyphBtn
      Left = 75
      Top = 0
      Width = 25
      Height = 26
      Hint = 'Find Last'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 9
      TabStop = False
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00BBC0C400999D9E007678790062626100626261007577
        770091959600B1B8BA00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00B7BABC009797950091908D009F9D9A00A5A3A1009C9A98008583
        8100626261006B6D6D009CA0A200FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00C4C7C800B4B3B000BFBCB800D4D0CC00E3DFDB00E8E3DF00E5E1DC00D7D3
        D000B8B5B200858381005F605F009CA0A200FFFFFE00FFFFFE00FFFFFE00CCD2
        D400D3D2CF00D9D5D100E5E1DC00EDE8E300EFEBE600F0EBE700F0EBE700EFEB
        E600E7E3DF00CBC6C3008C8A88006B6D6D00B3B8BC00FFFFFE00FFFFFE00DBDD
        DD00EFEAE500ECE7E300EFEAE500EFE9E400F0EBE700F0EBE700F0EBE700F0EB
        E700EFEBE600E8E3DF00C0BCB9007B7A790094989900FFFFFE00FFFFFE00E6E5
        E300F0ECE700F0EBE700EFEBE600B8A89D00E0D8D200F0EBE700F0EBE700967F
        6F00F0EBE700EFEBE600DBD7D4009D9B990082838400FFFFFE00FFFFFE00EFEB
        E800F1EDE800F0EBE700F0EBE700A7948700A4908300D8CFC700F0EBE7008E75
        6300F0EBE700F0EBE700E8E3DF00B7B4B00081807F00FFFFFE00FFFFFE00EFEB
        E800F1EDEA00F0EBE700F0EBE7009D8D81008E7563009D877800E7E1DB008D74
        6200F0EBE700F0EBE700EEE9E400C8C3C00092918E00FFFFFE00FFFFFE00E7E7
        E600F1EFEB00F0ECE800F0EBE70099897E008D7A6D00E1DAD400F0EBE7008D73
        6200F0EBE700F0EBE700EFEBE600CCC8C400A9A9A800FFFFFE00FFFFFE00DCDF
        E000F2EFED00F1EEEA00F0EBE700B0A39A00E8E2DD00F0EBE700F0EBE700846C
        5C00F0EBE700F0EBE700EEE9E400CECAC500BCC0C000FFFFFE00FFFFFE00D0D6
        D800EBEBEA00F2EFEC00F1EDE900F0EBE700F0EBE700F0EBE700F0EBE700F0EB
        E700F0EBE700F0EBE700F0EBE700D4D3D000C9CFD000FFFFFE00FFFFFE00FFFF
        FE00D9DCDF00EFEFEE00F2EFED00F1EEEB00F0ECE800F0ECE700F0EBE700F0EC
        E700F0ECE800F1EDE900EEEBE600D6D8D900FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00D9DCDF00EBEBEB00F2F0EF00F2EFED00F1EFEB00F1EFEB00F1EE
        EB00F1EEEB00EAE9E600D8DBDC00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00D0D6D900DCE0E200E7E9E800EFEFEC00EFEEEB00E7E7
        E700DCDFDF00D0D6D800FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00}
      Spacing = 3
      GlyphKind = bkCustom
    end
    object ToolButton1: TToolButton
      Left = 100
      Top = 0
      Width = 2
      Caption = 'ToolButton1'
      Style = tbsDivider
    end
    object btnClear: TGlyphBtn
      Left = 102
      Top = 0
      Width = 25
      Height = 26
      Hint = 'Clear Data'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 7
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4000000
        000000000000000000C8D0D4000000000000000000C8D0D4C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D400000000000000000000000000000000000000000000
        0000C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000
        C8D0D4C8D0D4000000000000000000C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D4000000000000C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4C8D0D4000000000000C8D0D4000000000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D400
        0000000080000080000000C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4000000C8D0D40000000000FF0000FF0000FF000080000000C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D400000000
        00FF0000FF0000FF0000FF000080000000C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4000000C8D0D4C8D0D40000000000FF0000FF0000FF0000000080
        80000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D4C8
        D0D40000000000FF00000000FFFF000000008080000000C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00000000FF
        FF000000008080000000C8D0D4C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D400000000FFFF00000000FFFF008080008080C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FF
        FF00FFFF00FFFF008080C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00FFFF00FFFFC8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0
        D400000000FFFF00FFFFC8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF}
      Spacing = 3
      GlyphKind = bkCustom
    end
    object btnAdd: TGlyphBtn
      Left = 127
      Top = 0
      Width = 23
      Height = 26
      Hint = 'Add New'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7ABB0AB6D8368426A3932
        60273B6435576E567D837DB5B5B5F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7608C5F198211158B00158B001D8B002C7A002C6F042868154864488F8F
        8FF0F3F7F0F3F7F0F3F7F0F3F7F0F3F7429143029C0202A00402A004029C0202
        97000994011C85013773002C6F04355D338F8F8FF0F3F7F0F3F7F0F3F767A068
        08A9130AA40D019C091AB12575E59385EAA46AE38B08A9130788003773002C6F
        04486448F0F3F7F0F3F7C0CEC01DAD2412AA230AA118019C09279D22E6EFE3FF
        FFFFCBF4D600A80E0788000788003773002868157D837DF0F3F779B77B28B63C
        18B12D0CBB2D02BB2616A527D8E9D8FFFFFFB4F0C500B81500A80E0BAB192385
        012C6F04576E56F0F3F74EAC5440C75B039B188ACD97BBE8CBB8E1C4EAEDEAF8
        F4F7E4F6EAB4F0C5CBF4D66AE38B0994012C7A003B6435F0F3F742AD4A51D374
        039B18BFCABCFFEAFDF9EEF8ECECECF0F0F0FAF4F9FFFBFFFFFBFF85EAA4029C
        02238501326027F0F3F74EAC5467DF8C09A022A4C0A1DCDDDADFDFDEEAE9EAEC
        ECECEAE9EAD8E9D8DDEDDD7AE89802A0041D8B00426A39F0F3F775C77972DB91
        34BF5824AA3C24AA3C3C9E3DD8DCD8F9EEF8B0DCBA24A22524A2251CB52905A2
        09158B006C8467F0F3F7B6CCB65BD77272E19C25CA5D19C64F24AA3CDCDBD9FF
        EAFDB1E5C202BB2605A11205A1120AA40D198211ABB0ABF0F3F7F0F3F765CB6C
        80E0A45EDB8C25CA5D25AB419FBF9BBFCABC8ACD9716BA3712AA230BAB190AA4
        0D638E61F0F3F7F0F3F7F0F3F7F0F3F753BC607FE0A16CE09B37C75E0DA42B03
        9B1809A02216BA3718B12D0BAB19429143F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F765CB6C5DDA7772E19C63E2914AD67637C75E28B63C1AB12567A068F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7B6CCB675C7794FB25842
        AD4A4EAC5479B77BC0CEC0F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      GlyphKind = bkCustom
    end
    object btnDelete: TGlyphBtn
      Left = 150
      Top = 0
      Width = 23
      Height = 26
      Hint = 'Delete'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 5
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
        F8F8F80000000000005A5A5A5A5A5A525252525252292929000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8212121949494FFFFFFCECECEDEDEDE94
        8C8CA5A5A56B6B6B636363393929000000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252B5ADADEFEFEF949494C6BDBD9494949494945252526B6B6B5A5A5A2121
        10F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEFA5A5A5C6C6C69494949C9C9C4A4A4A6B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F85252529C9C9CD6D6D6C6BDBD9C9C9C94
        94946B6B6B6B6B6B737373292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        393929949494C6BDBDCECECEC6BDBDA5A5A5A5A5A5A5A5A56B6B6B4A4A4A1010
        10F8F8F8F8F8F8F8F8F8F8F8F8000000A5A594DEDEDEC6C6C6BDB5B5BDBDBDBD
        BDBD8C8C8C8484846B6B6B6363635A5A5A000000F8F8F8F8F8F8F8F8F8000000
        737352D6CECEFFFFFFE7E7E7CECECEC6C6C6293939525252C6C6C69C94947B7B
        7B000000F8F8F8F8F8F8F8F8F80000005A5A5AADA5A5EFEFEFDEDEDE4A5A4A42
        5263848473525252B5B5B57B7B7B4A4A4A000000F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F80000000000003939392121217B7B6B314242000000000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F800
        0000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
      GlyphKind = bkCustom
    end
    object btnCopy: TGlyphBtn
      Left = 173
      Top = 0
      Width = 23
      Height = 26
      Hint = 'Copy Item'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 6
      TabStop = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFBA
        6E47AA5429AA5429A250279B4C259648238F46228A4321864120FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFC17955FDF9F6CEB09CCCAF9BCAAD9AC7AC
        99C6AB98C4A997894321FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFC9
        8564FFFFFFDA8C5CD18351D18351D18351D18351C6AB988E4522FEFEFFB7A293
        634935634935634935634935634935D19273FFFFFFFEFDFBFBEFEAF5DED3F0CE
        BEEDC3AFC7AC99924723FEFEFFB7A293F8F3F0EADFD7E6D9CFE1D2C7DDCBBFD8
        9F82FFFFFFF3A77FE7976EDA8C5CD18351D18351CAAE9A984A25FEFEFFB7A293
        FBF8F7E5AE81DEA173DA9C6ED59768E0AA90FFFFFFFFFFFFFFFFFFFBF4F0F7E4
        DBF2D3C5CCAE9A9D4D25FEFEFFBBA697FEFDFCFBF6F5F6EFEBF1E6E0ECDED6E7
        B59CFFFFFFFCAE8AFCAE8AF1DBD2E78E60B3572AAC5429A45027FEFEFFC1AB9C
        FFFFFFFAC59FF0B88EE5AE81DEA173ECBDA6FFFFFFFFFFFFFFFFFFFFFFFFEA9A
        72F0C9B2B1572BB9A49AFEFEFFC7B2A3FFFFFFFFFFFFFCFAF9F8F2F0F3EAE6F0
        C4AEFFFFFFFFFFFFFFFFFFFFFFFFEBA785C56535C0AA9FFEFEFFFEFEFFCFB9A9
        FFFFFFFFDABAFFD0AEF0DED2B7A293F0C4AEEFC2ABEFC1AAEFB9A0EDB092EDB0
        92CAB6ABFEFEFFFEFEFFFEFEFFD4BEAFFFFFFFFFFFFFFFFFFFFEFDFCBBA696D4
        C5BA8F725BB2ADA9FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFD8C2B2
        FFFFFFFFFFFFFFFFFFFFFFFFC7B1A2A58266B4AFACFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFD8C2B2D8C2B2D4BFAED4BFAECEB8A9C8B2A3C2
        BCB7FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF}
      GlyphKind = bkCustom
    end
    object btnRoutings: TGlyphBtn
      Left = 196
      Top = 0
      Width = 23
      Height = 26
      Hint = 'Display Routing Lines'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 10
      TabStop = False
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF002F2F2F002F2F2F00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF001E1E1E0074FFFF0019FFFF001E1E
        1E00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF000F0F0F0056FFFF007BFFFF0074FFFF000EFF
        FF000F0F0F00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF000202020026FFFF0045FFFF0051FFFF004BFFFF0035FF
        FF0006F9FF0002020200FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF000000000000F6FF00000000000000000026FFFF0023FFFF0013FF
        FF0000FCFF0000EAFF0000000000FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF000000000000E4FF0000EEFF00000000000000000000FCFF0000FCFF0000F8
        FF0000F1FF0000E7FF0000DDFF0000000000FFFFFF00FFFFFF00FFFFFF000000
        000000D2FF0000D9FF000CEAFF001E1E1E00252525003AF1FF003AF1FF003AF1
        FF0039EAFF0012DCFF0000D2FF0000D2FF0000000000FFFFFF000000000002C1
        FF004CDCFF0054DCFF0054E3FF00363636003636360054E9FF0054E9FF00458F
        9B0054E3FF0054DCFF0054DCFF0054D5FF0000C6FF00000000000000000065D5
        FF0065DCFF0065DCFF0065DCFF00424242004242420065E4FF0065E4FF004242
        42004C747D0065DCFF0065DCFF0065D5FF0054D5FF0000000000FFFFFF000000
        00007FDCFF007FDCFF007CE1FF007CE1FF005252520052525200525252005252
        520052525200525252007FDCFF0065D5FF0000000000FFFFFF00FFFFFF00FFFF
        FF000000000098E1FF0098E1FF0098E1FF0098E4FF0098E4FF0098E4FF006264
        64006A72760098E1FF007BD6FF0000000000FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF0000000000B3E6FF00B2E8FF00B2E8FF00B2E8FF00B2E8FF00B2E8
        FF00B2E8FF0091DDFF0000000000FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF0000000000CCEEFF00CCF0FF00CCF0FF00CCF0FF00CCF0
        FF00A9E2FF0000000000FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF0000000000E6F7FF00E6F7FF00E6F7FF00BBE8
        FF0000000000FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF0000000000FAFDFF00CCEEFF000000
        0000FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF000000000000000000FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00}
      GlyphKind = bkCustom
    end
    object btnTimes: TGlyphBtn
      Left = 219
      Top = 0
      Width = 23
      Height = 26
      Hint = 'times'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 11
      TabStop = False
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00CBCBCB0074737300807C7900847B760080797600716E
        6D007B6E6E00C4C6C700FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00A0949200817B790094918F00A5978F00A3979200AB9B9400A498
        9100B0928F008D817F00CDC5C500FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00AEA8A50090958800BAA58B00D3CAB700CEC1BD007D88CC00ADB0C900D6D3
        D100B2B1A000AC8D8700AE9C9800C9C9CA00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00A19E9D00C2B89F00EFE0C100F8ECD000F1DDB800D1C2B900E4D9CC00FDFB
        F600F3F4F100B7AFA9009E938F009F8A8000CFCBC800FFFFFE00FFFFFE00A9A8
        A800CBBBA600F4E2BF00F8E2B900F8E1B500F8E1B500F8E1B500F1D5A700F5DC
        AF00FEFDFA00F8F5F100BEB1A300A19892006A686800FFFFFE00FFFFFE00AAA8
        A800DBC7AB00F8E9C900F8E5BE00F8ECD000F7E2B900F4DDB100F7DFB200F1D4
        A600F7E0B400F9F2E200DED5C400B4A38F0074717100FFFFFE00FFFFFE00AAA9
        A800D8CBB700F0EBD800F8EFD900F7ECD000EADDC100C1B19100CEB28E00CDC2
        9C00DAC2A100EFE4C800CFD8D700AAA59E00907D7900FFFFFE00FFFFFE00AAA9
        A80093A3C800CAD4E800F8F5EA00F7EFDB00C7C8B10077756E005C5149005457
        4C006C635D008D888000A1B0DC007B86A6008B7E7C00FFFFFE00FFFFFE00A9A8
        A800CDCACF00EDF0F800FBF9F300F8F2E400E2DDC5009D999600515252008C6B
        5800CEBC9A00D3C3A500D7CDCA00AC9B9C00847C7800FFFFFE00FFFFFE00EAE7
        E100A9A8A800FCFAF400FDFDFB00F9F6EC00F8F2E400F6EEDB00B3B89E005256
        5000A68B6700F8ECD000D2D0B50094998C0074737300FFFFFE00FFFFFE00FFFF
        FE00A9A8A800F3EAE300FDFDFB00FDFDF900FBF9F300F8F5EB00F8EFDB00AFB4
        980053525100AA948300C8B89D008783820097949200FFFFFE00FFFFFE00FFFF
        FE00ECE6E100ABAAA900F2EAE500FCFAF400EEF1F800C2D5EE00E8F0EC00F8E8
        C700C2B19E00706A6700A4978F009F9D9C00DEE0E000FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00EAE3E100ABA9A900ACAAA900D1CCCF008AA4CA00C5D0D000DACD
        BC00CFBEA600ADA7A400B1B0AF00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00F1EDEA00ECE7E300ABA9A900AAA9A800C8BFB600C0BB
        B600B4B0AD00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFF
        FE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00FFFFFE00}
      GlyphKind = bkCustom
    end
    object btnSpecs: TGlyphBtn
      Left = 242
      Top = 0
      Width = 23
      Height = 26
      Hint = 'Specs'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 12
      TabStop = False
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000FEFEFF00FEFE
        FF00999999000000000000000000000000000000000000000000000000000000
        00000000000000000000000000000000000000000000FEFEFF00FEFEFF00FEFE
        FF0099999900CCCCCC00CCCCCC00CCCCCC00CCCCCC00CCCCCC00CCCCCC00CCCC
        CC00CCCCCC00CCCCCC00CCCCCC00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF0099663300996633009966330099663300996633009966
        33009966330099663300FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF0099663300996633009966330099663300996633009966
        33009966330099663300FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF0099663300996633009966330099663300996633009966
        33009966330099663300FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF0099663300996633009966330099663300996633009966
        33009966330099663300FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF00FFFFFF00FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF0099663300996633009966330099663300996633009966
        33009966330099663300FFFFFF00CCCCCC0000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF0000000000000000000000000000000000FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF0099663300996633009966330099663300996633009966
        3300FFFFFF0099999900FFFFFF0000000000FEFEFF00FEFEFF00FEFEFF00FEFE
        FF0099999900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
        FF00FFFFFF009999990000000000FEFEFF00FEFEFF00FEFEFF00FEFEFF00FEFE
        FF00999999009999990099999900999999009999990099999900999999009999
        99009999990099999900FEFEFF00FEFEFF00FEFEFF00FEFEFF00}
      GlyphKind = bkCustom
    end
    object btnCycle: TGlyphBtn
      Left = 265
      Top = 0
      Width = 23
      Height = 26
      Hint = 'Display Cycle Times and Setup'
      Caption = 'CT'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 13
      TabStop = False
      GlyphKind = bkCustom
    end
    object HNotes: TPanel
      Left = 288
      Top = 0
      Width = 27
      Height = 26
      Ctl3D = True
      ParentBackground = False
      ParentCtl3D = False
      TabOrder = 0
      object btnNotes: TGlyphBtn
        Left = 2
        Top = 2
        Width = 23
        Height = 22
        Hint = 'Notes'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        TabStop = False
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
          FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE0000006B6B6B7B7B7BEF
          EFEFEFEFEFBDBDBDDEDEDEDEDEDED6D6D6ADADADA5A5A5ADADADFFFFFEFFFFFE
          FFFFFE0000006B6B6B7B7B7BEFEFEFDEDEDEDEDEDEDEDEDEBDBDBDADADADA5A5
          A531313131394200316BFFFFFEFFFFFE0000006B6B6B7B7B7BEFEFEFEFEFEFBD
          BDBDADADADADADAD29293142424A313942313942294A731052A5FFFFFE000000
          6B6B6B7B7B7BEFEFEFEFEFEFEFEFEF3131313939394A5A73526BA5426BB5426B
          B54A73BD3963CE317BE70000000000007B7B7BEFEFEFEFEFEFEFEFEFEFEFEF4A
          4A4A4A4A4A638494C6D6F7B5CEF7B5CEF78CADF78CADF7638CDE000000000000
          EFEFEFEFEFEF000000EFEFEFEFEFEFEFEFEFEFEFEFBDBDBD738CBD4A84B59CA5
          D6BDBDE7CEE7FFCEE7FF000000C8D0D4000000ADADAD7B7B7BEFEFEFEFEFEFEF
          EFEFEFEFEFEFEFEFBDBDBDEFEFEFDEDEDE7B7B7B396B84294A73FFFFFE000000
          000000000000ADADADEFEFEF000000EFEFEFEFEFEFEFEFEFEFEFEFBDBDBDDEDE
          DEDEDEDEDEDEDEDEDEDEFFFFFEFFFFFE000000C8D0D4000000ADADAD7B7B7BEF
          EFEFEFEFEFEFEFEFEFEFEFEFEFEFBDBDBDDEDEDEDEDEDEDEDEDEFFFFFEFFFFFE
          FFFFFE000000C8D0D4000000ADADADEFEFEF000000EFEFEFDEDEDEDEDEDEDEDE
          DEDEDEDEDEDEDE000000FFFFFEFFFFFEFFFFFEFFFFFE000000000000000000AD
          ADAD7B7B7BEFEFEFEFEFEFDEDEDEDEDEDEDEDEDE000000FFFFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFE000000C8D0D4000000ADADADDEDEDE000000DEDEDEDEDE
          DE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE00000000
          0000000000ADADAD7B7B7BDEDEDE000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE
          FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE000000C8D0D4000000ADADAD000000FFFF
          FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
          FFFE000000C8D0D4000000FFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
        GlyphKind = bkCustom
      end
    end
    object HLinks: TPanel
      Left = 315
      Top = 0
      Width = 27
      Height = 26
      Ctl3D = True
      ParentBackground = False
      ParentCtl3D = False
      TabOrder = 1
      object btnLinks: TGlyphBtn
        Left = 2
        Top = 2
        Width = 23
        Height = 22
        Hint = 'Links'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        TabStop = False
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFA4A4FFA4A4
          0E65890E6589FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4
          A4FFA4A4FFA4A4FFA4A4FFA4A40E658946FFFF54A2CD0E6589FFA4A4FFA4A4FF
          A4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4126A8E
          00D2D246FFFF54A2CD11698E1878A01878A01878A0FFA4A4FFA4A4FFA4A4FFA4
          A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A416709400D2D246FFFF54A2CD16709500
          D2D246FFFF1878A0FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FFA4A4FF9B9BFF9B9B
          FF9B9B1C779D00D2D246FFFF54A2CD227EA500D2D246FFFF1878A0FFA4A4FFA4
          A4FFA4A4FFA4A4FFA4A4FF9B9BFF9B9BFF9B9B5EA1BD227FA400D2D246FFFF22
          7EA516709400D2D246FFFF1878A0FFA4A4FFA4A4FFA4A4FFA4A4FF8888FF9B9B
          FF9B9B1B7BA346FFFF2685AC2785ABFFA4A4FFA4A416709400D2D246FFFF1878
          A0FFA4A4FFA4A4FFA4A4FF8888FF8888FF9B9B2080A800D2D246FFFF167094FF
          A4A4FFA4A4FFA4A416709400D2D246FFFF1878A0FFA4A4FFA4A4FF8888FF8888
          FF8888FF9B9B2585AD00D2D246FFFF167094FFA4A4FFA4A40E65890E658900D2
          D21878A0FFA4A4FFA4A4FF7777FF8888FF8888FF8888FF9B9B2B8BB300D2D246
          FFFF1670940E658946FFFF54A2CD0E65893898C0FFA4A4FFA4A4FF7777FF7777
          FF8888FF8888FF8888FF9B9B3190B800D2D246FFFF126A8E00D2D246FFFF54A2
          CD11698EFFA4A4FFA4A4FF7777FF7777FF7777FF8888FF8888FF8888FF9B9B35
          95BC00D2D246FFFF16709400D2D246FFFF54A2CD167095FFA4A4FF6C6CFF7777
          FF7777FF7777FF8888FF8888FF8888FF9B9B3898C03898C074B7D31C779D00D2
          D246FFFF54A2CD227EA5FF6C6CFF6C6CFF7777FF7777FF7777FF8888FF8888FF
          8888FF9B9BFF9B9BFF9B9BFF9B9B227FA400D2D246FFFF227EA5FF6C6CFF6C6C
          FF6C6CFF7777FF7777FF7777FF8888FF8888FF8888FF9B9BFF9B9BFF9B9BFF9B
          9B2685AC2785ABFFA4A4FF6C6CFF6C6CFF6C6CFF6C6CFF7777FF7777FF7777FF
          8888FF8888FF8888FF9B9BFF9B9BFF9B9BFF9B9BFF9B9BFF9B9B}
        GlyphKind = bkCustom
      end
    end
  end
  object EvoToolBar: TToolBar
    Left = 554
    Top = 3
    Width = 116
    Height = 25
    Align = alCustom
    Anchors = [akTop, akRight]
    EdgeBorders = []
    Images = EvoToobarImages
    TabOrder = 3
    Transparent = False
    Visible = False
    object ETB5: TToolButton
      Left = 0
      Top = 0
      Caption = 'ETB5'
      Visible = False
    end
    object ETB4: TToolButton
      Left = 23
      Top = 0
      Caption = 'ETB4'
      Visible = False
    end
    object ETB3: TToolButton
      Left = 46
      Top = 0
      Caption = 'ETB3'
      Visible = False
    end
    object ETB2: TToolButton
      Left = 69
      Top = 0
      Caption = 'ETB2'
      Visible = False
    end
    object ETB1: TToolButton
      Left = 92
      Top = 0
      Caption = 'ETB1'
      Visible = False
    end
  end
  object ETBcombo: TTASComboBox
    Left = 430
    Top = 2
    Width = 168
    Height = 24
    Style = csDropDownList
    ItemHeight = 16
    TabOrder = 4
    Visible = False
    FieldName = 'ETBcomboval'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Panel3: TPanel
    Left = 0
    Top = 443
    Width = 672
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 2
    object btnExit: TGlyphBtn
      Left = 604
      Top = 5
      Width = 65
      Height = 25
      Caption = 'E&xit'
      TabOrder = 1
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnSave: TGlyphBtn
      Left = 538
      Top = 5
      Width = 65
      Height = 25
      Hint = 'Save'
      Caption = '&Save '
      TabOrder = 0
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
  end
  object Panel7: TPanel
    Left = 0
    Top = 29
    Width = 672
    Height = 59
    Align = alTop
    BevelOuter = bvNone
    BorderStyle = bsSingle
    TabOrder = 0
    object Gradient3: TGradient
      Left = 0
      Top = 0
      Width = 668
      Height = 55
      Align = alClient
      Style = gsReflectedH
    end
    object Shape3: TShape
      Left = 0
      Top = 0
      Width = 668
      Height = 55
      Align = alClient
      Brush.Style = bsClear
      Pen.Mode = pmBlack
      Shape = stRoundRect
    end
    object Label9: TLabel
      Left = 18
      Top = 8
      Width = 28
      Height = 16
      Caption = ' Part'
      Transparent = True
    end
    object Label14: TLabel
      Left = 18
      Top = 32
      Width = 48
      Height = 16
      Caption = 'Lot Size'
      Transparent = True
    end
    object EnterItem: TTASComboEnter
      Left = 97
      Top = 6
      Width = 158
      Height = 21
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 0
      Text = 'ENTERITEM'
      FieldName = 'SCRN.CODE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExpr = 'vld_item()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|ENTERITEM.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object EnterDesc: TTASENTER
      Left = 268
      Top = 6
      Width = 351
      Height = 21
      AutoSize = False
      TabOrder = 1
      Text = 'EnterDesc'
      FieldName = 'SCRN.DESC'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_ItemDesc()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object EnterLot: TTASNumEnter
      Left = 97
      Top = 30
      Width = 158
      Height = 21
      AutoSize = False
      DisplayFormat = '0;0'
      TabOrder = 2
      FieldName = 'HOLD.LOT'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_lotsz()'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 453
    Top = 65525
  end
  object EvoToobarImages: TImageList
    Left = 432
    Top = 65532
    Bitmap = {
      494C0101060009007C0010001000FFFFFFFFFF10FFFFFFFFFFFFFFFF424D3600
      0000000000003600000028000000400000002000000001002000000000000020
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000007373730073737300737373000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000CE944200CE8C3100D69C
      5200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000073737300BD632900AD6B42006B524A007373730000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000DEA55200BD843900000000000000
      0000D69C5200B57B39006B5231006B5231006B5231006B5231006B5231000000
      000000000000000000000000000000000000000000007373730073737300BD63
      2900EF7B0800FF732100FF940800FFAD310094634A007373730073737300B57B
      5A00737373007373730073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFAD4200AD7B4200000000000000
      00006B523100C67B3100DE943900EFAD4200F7B55200DEB56300EFAD42006B52
      31006B5231000000000000000000000000008452520084525200E79C5A00EF84
      1000D6846300FFAD3100FF8C0800FFA51000FFBD6300AD7B6B0084525200FF94
      0000845252008452520073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFB54A00AD7B4200000000006B52
      3100E79C3100F79C3900EF943100EF9C3100F7A53900F7BD5200FFD67300EFCE
      8C00B57B39006B523100000000000000000094634A00F7F7E700F7F7E700F7F7
      E700FFF7E700F7DEAD00F7941800FF940000FFAD3100FFC68400FFBD5A00FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000E7AD6300DE9C29006B523100F7A5
      3100EF9C3100E7942900E79429007352310073523100B5732900F7B54200FFD6
      6B00F7D69400B57B3900000000000000000094636300FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00F7DEAD00FF9C0800FF9C0800FFBD5A00FFC68400FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000F7B53900F7AD3100EFA5
      2900E7942900DE8C290084522900000000000000000000000000B5732900F7AD
      3900FFD66B00DEB57B00B57B390000000000A56B6B00FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00F7941800FFAD2900FF940000FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000E7B56300F7B53100EFA5
      2900E7942100A56318006B5231006B5231006B5231006B5231006B5231006B52
      31006B5231006B5231006B52310000000000AD7B6B00FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FF5A3100EF6B4200EF523100EF6B4200FF5A
      3100FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F7BD3900EFAD
      2900E79C2100D67B2900D67B2900D67B2900D67B2900D67B2900D67B2900D67B
      2900D67B2900D67B2900B57B390000000000B58C7300FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00CECECE00D6D6D600F7EFDE00F7E7
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000F7C6
      4200EFAD2900E79C2100DE942100E7942900E7942900E7942900E7942900EF94
      3100F79C3900EFA54200B57B390000000000B58C7300FFFFFF00FF5A3100EF6B
      4200E7522900C6734200C68C7B00FFFFFF00FFFFFF00FFFFFF00294A84007394
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000EFCE940000000000F7C6
      4200F7C64200BD8429006B4A21000000000000000000B5732900CE8C3100EF94
      2900EF9C3100EF9C3100B57B390000000000C6947B00FFFFFF00FF8C0800FF8C
      0800FF5A3100AD4A1800FFF7EF00FFFFFF00FFFFFF00FFFFFF007394D6007394
      D600FFFFF700AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000EFCE94000000
      0000F7C64200E7AD39006B5229005A42290073523100B5732900E79C2900E794
      2900F7A53900B57B39000000000000000000D6A58400FFFFFF00FF8C0800FFBD
      5A00FFAD2900F7941800BD632900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
      FF00FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000D6BD8C00E7CE
      8C0000000000F7DE8C00E7B53900B5842100CE8C2100E7A52900E79C2100EFA5
      2900EFA53900B57B39000000000000000000DEAD8400DEAD8400FF8C0800DEAD
      8400F7A55A00FFC68400EF943900BD632900C69C9400C69C9400C69C9400C69C
      9400C69C9400AD7B7B0000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000D6BD
      8C00D6BD8C00E7D66300E7D66300F7D64200F7B53100EFAD2900EFAD2900EFA5
      3100B57B390000000000EFAD4200000000000000000000000000FF8C08000000
      000000000000F7A55A00FFDEAD00EFB58C00BD632900BD523900C6734200A563
      4200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000D6BD8C00D6BD8C00D6BD8C00DEB55200FFCE4A00B57B3900B57B
      39000000000000000000EFAD4200000000000000000000000000000000000000
      00000000000000000000F7A55A00FFEFBD00FFE7AD00DE8C5200944A18000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000AD9A880046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000AD9A8800CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000212121004242
      3900424239004242390042423900424239004242390042423900424239004242
      3900424239004242390042423900000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000AD9A
      8800FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B7B00F7F7
      FF00F7F7FF00F7F7FF00BDBDBD00F7F7FF00F7F7FF00003939005A5A5A00F7EF
      E700F7F7FF00F7F7FF0042423900000000000000000046403800464038004640
      380046403800464038004640380046403800464038004640380046403800FFE8
      D400FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000027596100000000000000000027596100000000000000
      00000000000000000000000000000000000000000000000000005A5A5A00BDBD
      BD00BDBDBD00BDBDBD009C9C9400BDBDBD00BDBDBD005A5A5A0042BDBD005252
      4A00BDBDBD00BDBDBD004242390000000000AD9A8800FFE5CE00CAB39E00CAB3
      9E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00FFE8D400FFEB
      D900FFEBD900FFEBD900BBA69200464038008080000080800000800000008000
      0000800000008000000080000000800000008000000080000000800000008000
      0000800000008000000080000000000000000000000027596100000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000275961000000000000000000000000005A5A5A00DED6
      D600DED6D600DED6D600ADADAD00DED6D600DED6D600F7F7FF005A5A5A005ADE
      DE0052524A00F7EFE7004242390000000000AD9A8800FFEDDD00FFE3C900FFE3
      C900FFE3C900FFE3C9008B7C6D0000000000EDD2B900FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BBA692004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      6100000000000000000080808000808080008080800080808000000000000000
      0000275961002759610000000000000000000000000000000000393900003939
      00003939000039390000393900003939000052523100ADADAD009C9C94005A5A
      5A005ADEDE0052524A002121210000000000AD9A8800FFF1E400FFE3C900FFE3
      C900FFE3C900FFE3C900F2D6BD00ECD1B800FFE5CE00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BFAA96004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF00FFFF
      FF00C8D0D4000000000080000000000000000000000000000000275961002759
      6100000000008080800091919100838383008080800080808000808080000000
      0000275961002759610000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000DED6D600BDBDBD00F7F7
      FF007B7B7B006BADAD004242390000000000AD9A8800FFF4EA00FDE0C600FFE3
      C900FFE3C900FFE3C9008B7C6D0076695C00DCC3AD00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400C4AE99004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      61000000000080808000AAAAAA00919191008383830080808000808080000000
      00002759610027596100000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD005A5A5A005ADEDE0021212100AD9A8800FFF7F000FADEC400FADE
      C400FFE3C900FFE3C900DCC3AD00655A4E006F635700F4D8BF00FFE8D400FFE8
      D400FFE8D400FFE8D400CAB39E004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF000000
      0000FFFFFF0000000000800000000000000000000000000000002E6770002E67
      70000000000080808000AAAAAA00AAAAAA009191910080808000808080000000
      00002E6770002E67700000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF00393939005A9C9C00AD9A8800FFF9F300FADEC400FADE
      C400FADEC400FFE3C900FFE3C900DCC3AD00524840005F544A00FADEC400FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000377E8800377E
      8800000000000000000080808000808080008080800080808000000000000000
      0000377E8800377E880000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD00BDBDBD004242390000000000AD9A8800FFF9F300F6DAC000FADE
      C400EDD2B900D1BAA400DCC3AD00FFE3C900B29D8B0083746600C2AC9700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF000000000000C8D0
      D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400808000008080
      00008080000080800000800000000000000000000000000000004397A3004397
      A3004397A3000000000000000000000000000000000000000000000000004397
      A3004397A3004397A300000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF004242390000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00D1BAA400524840005C524800ECD1B800726559005F544A00D5BCA700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF0000000000FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00C8D0D400808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B0000393900005A5A5A005A5A5A007B7B
      7B007B7B7B007B7B7B002121210000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00F4D8BF00AA978500000000000000000000000000B29D8B00FFE3C900FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF0000000000000000
      0000000000000000000000000000000000000000000000000000808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      00000000000091919100000000004EA9B6004EA9B60000000000919191000000
      00000000000000000000000000000000000000000000000000009C9C0000ADAD
      6B00BD9C7B00BD9C7B00BD9C7B007B7339003939000042423900000000000000
      000000000000000000000000000000000000AD9A8800FFF9F300FFF9F300FFF9
      F300FFF9F300FFF9F300FFF9F300FFF9F300FFF9F300FFF4EA00FFF1E400FFF1
      E400FFEBD900FFEBD900FFE5CE004640380080800000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF0080800000000000000000000000000000000000000000
      0000000000000000000091919100000000000000000091919100000000000000
      00000000000000000000000000000000000000000000000000007B7B00005A5A
      5A005A5A5A005A5A5A005A5A5A00313131003939000042423900000000000000
      00000000000000000000000000000000000000000000AD9A8800AD9A8800AD9A
      8800A69382009C8B7B0092827300857669007B6D600072655900655A4E005248
      4000524840004640380046403800000000000000000080800000808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080800000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B00007B7B
      00007B7B00007B7B00007B7B00007B7B00002121000000000000000000000000
      000000000000000000000000000000000000424D3E000000000000003E000000
      2800000040000000200000000100010000000000000100000000000000000000
      000000000000000000000000FFFFFF00FFFFFFFF00000000FFFFF8FF00000000
      8FFFF07F00000000301F80010000000030070001000000002003000100000000
      000300010000000081C10001000000008001000100000000C001000100000000
      E001000100000000A181000100000000D003000100000000C803000300000000
      E005D80F00000000F80DFC1F00000000FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFF1FFFFFFFFC001FFE1FFFFFFFFC00180018001FC3FC001000000008001C001
      0000000080018000000000008001800000000000800180000000000080018000
      00000000800180000000000080018001000000008001800100000000C813803F
      00000000FC3F803F80018001FFFF807F00000000000000000000000000000000
      000000000000}
  end
  object NOTEMEMO: TTASStrList
    Left = 440
    Top = 65534
  end
end
