object EditForm3: TEditForm3
  Left = 470
  Top = 201
  Hint = 'C:\TASPro7\DBA7\T7GLA.DFM'
  AutoScroll = False
  Caption = 'GL-A'
  ClientHeight = 458
  ClientWidth = 644
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7GLA.OnClose'
  No_Refresh = False
  OnStart = 'T7GLA.OnStart'
  OpenFiles = 'T7GLA.OnOpenFiles'
  OnDisplayScreen = 'T7GLA.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7GLA'
  RememberSize = True
  RememberSizeDate = 45278.672016365740000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Panel2: TPanel
    Left = 0
    Top = 82
    Width = 644
    Height = 342
    Align = alClient
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    object ACCT_HDR4: TLabel
      Left = 509
      Top = 3
      Width = 113
      Height = 16
      Alignment = taCenter
      AutoSize = False
      Caption = 'ACCT_HDR4'
    end
    object ACCT_HDR3: TLabel
      Left = 395
      Top = 3
      Width = 113
      Height = 16
      Alignment = taCenter
      AutoSize = False
      Caption = 'ACCT_HDR3'
    end
    object ACCT_HDR2: TLabel
      Left = 280
      Top = 3
      Width = 113
      Height = 16
      Alignment = taCenter
      AutoSize = False
      Caption = 'ACCT_HDR2'
    end
    object ACCT_HDR1: TLabel
      Left = 166
      Top = 3
      Width = 113
      Height = 16
      Alignment = taCenter
      AutoSize = False
      Caption = 'ACCT_HDR1'
    end
    object Label5: TLabel
      Left = 43
      Top = 25
      Width = 46
      Height = 16
      Caption = 'Beg Bal'
    end
    object Label6: TLabel
      Left = 4
      Top = 39
      Width = 34
      Height = 32
      Caption = 'Beg '#13#10'Dates'
    end
    object Label7: TLabel
      Left = 43
      Top = 311
      Width = 46
      Height = 16
      Caption = 'End Bal'
    end
    object DISP_ACCT1_1: TTASNumEnter
      Left = 165
      Top = 22
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 0
      FieldName = 'DISP.ACCT1[1] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_1: TTASNumEnter
      Left = 280
      Top = 22
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 1
      FieldName = 'DISP.ACCT2[1] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_1: TTASNumEnter
      Left = 396
      Top = 22
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 2
      FieldName = 'DISP.ACCT3[1] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_1: TTASNumEnter
      Left = 511
      Top = 22
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 3
      FieldName = 'DISP.ACCT4[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_2: TTASNumEnter
      Left = 165
      Top = 50
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 5
      FieldName = 'DISP.ACCT1[2] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_2: TTASNumEnter
      Left = 280
      Top = 50
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 6
      FieldName = 'DISP.ACCT2[2] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_2: TTASNumEnter
      Left = 396
      Top = 50
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 7
      FieldName = 'DISP.ACCT3[2] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_2: TTASNumEnter
      Left = 511
      Top = 50
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 8
      FieldName = 'DISP.ACCT4[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_3: TTASNumEnter
      Left = 165
      Top = 71
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 10
      FieldName = 'DISP.ACCT1[3] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_3: TTASNumEnter
      Left = 280
      Top = 71
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 11
      FieldName = 'DISP.ACCT2[3] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_3: TTASNumEnter
      Left = 396
      Top = 71
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 12
      FieldName = 'DISP.ACCT3[3] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_3: TTASNumEnter
      Left = 511
      Top = 71
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 13
      FieldName = 'DISP.ACCT4[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_4: TTASNumEnter
      Left = 165
      Top = 92
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 15
      FieldName = 'DISP.ACCT1[4] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_4: TTASNumEnter
      Left = 280
      Top = 92
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 16
      FieldName = 'DISP.ACCT2[4] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_4: TTASNumEnter
      Left = 396
      Top = 92
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 17
      FieldName = 'DISP.ACCT3[4] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_4: TTASNumEnter
      Left = 511
      Top = 92
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 18
      FieldName = 'DISP.ACCT4[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_5: TTASNumEnter
      Left = 165
      Top = 113
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 20
      FieldName = 'DISP.ACCT1[5] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_5: TTASNumEnter
      Left = 280
      Top = 113
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 21
      FieldName = 'DISP.ACCT2[5] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_5: TTASNumEnter
      Left = 396
      Top = 113
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 22
      FieldName = 'DISP.ACCT3[5] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_5: TTASNumEnter
      Left = 511
      Top = 113
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 23
      FieldName = 'DISP.ACCT4[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_6: TTASNumEnter
      Left = 165
      Top = 134
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 25
      FieldName = 'DISP.ACCT1[6] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_6: TTASNumEnter
      Left = 280
      Top = 134
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 26
      FieldName = 'DISP.ACCT2[6] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_6: TTASNumEnter
      Left = 396
      Top = 134
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 27
      FieldName = 'DISP.ACCT3[6] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_6: TTASNumEnter
      Left = 511
      Top = 134
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 28
      FieldName = 'DISP.ACCT4[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_7: TTASNumEnter
      Left = 165
      Top = 155
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 30
      FieldName = 'DISP.ACCT1[7] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_7: TTASNumEnter
      Left = 280
      Top = 155
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 31
      FieldName = 'DISP.ACCT2[7] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_7: TTASNumEnter
      Left = 396
      Top = 155
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 32
      FieldName = 'DISP.ACCT3[7] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_7: TTASNumEnter
      Left = 511
      Top = 155
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 33
      FieldName = 'DISP.ACCT4[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_8: TTASNumEnter
      Left = 165
      Top = 176
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 35
      FieldName = 'DISP.ACCT1[8] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_8: TTASNumEnter
      Left = 280
      Top = 176
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 36
      FieldName = 'DISP.ACCT2[8] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_8: TTASNumEnter
      Left = 396
      Top = 176
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 37
      FieldName = 'DISP.ACCT3[8] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_8: TTASNumEnter
      Left = 511
      Top = 176
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 38
      FieldName = 'DISP.ACCT4[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_9: TTASNumEnter
      Left = 165
      Top = 197
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 40
      FieldName = 'DISP.ACCT1[9] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_9: TTASNumEnter
      Left = 280
      Top = 197
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 41
      FieldName = 'DISP.ACCT2[9] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_9: TTASNumEnter
      Left = 396
      Top = 197
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 42
      FieldName = 'DISP.ACCT3[9] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_9: TTASNumEnter
      Left = 511
      Top = 197
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 43
      FieldName = 'DISP.ACCT4[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_10: TTASNumEnter
      Left = 165
      Top = 218
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 45
      FieldName = 'DISP.ACCT1[10] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_10: TTASNumEnter
      Left = 280
      Top = 218
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 46
      FieldName = 'DISP.ACCT2[10] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_10: TTASNumEnter
      Left = 396
      Top = 218
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 47
      FieldName = 'DISP.ACCT3[10] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_10: TTASNumEnter
      Left = 511
      Top = 218
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 48
      FieldName = 'DISP.ACCT4[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_11: TTASNumEnter
      Left = 165
      Top = 239
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 50
      FieldName = 'DISP.ACCT1[11] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_11: TTASNumEnter
      Left = 280
      Top = 239
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 51
      FieldName = 'DISP.ACCT2[11] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_11: TTASNumEnter
      Left = 396
      Top = 239
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 52
      FieldName = 'DISP.ACCT3[11] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_11: TTASNumEnter
      Left = 511
      Top = 239
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 53
      FieldName = 'DISP.ACCT4[11]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_12: TTASNumEnter
      Left = 165
      Top = 260
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 55
      FieldName = 'DISP.ACCT1[12] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_12: TTASNumEnter
      Left = 280
      Top = 260
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 56
      FieldName = 'DISP.ACCT2[12] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_12: TTASNumEnter
      Left = 396
      Top = 260
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 57
      FieldName = 'DISP.ACCT3[12] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_12: TTASNumEnter
      Left = 511
      Top = 260
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 58
      FieldName = 'DISP.ACCT4[12]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_13: TTASNumEnter
      Left = 165
      Top = 281
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 60
      FieldName = 'DISP.ACCT1[13] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_13: TTASNumEnter
      Left = 280
      Top = 281
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 61
      FieldName = 'DISP.ACCT2[13] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_13: TTASNumEnter
      Left = 396
      Top = 281
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 62
      FieldName = 'DISP.ACCT3[13] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_13: TTASNumEnter
      Left = 511
      Top = 281
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 63
      FieldName = 'DISP.ACCT4[13]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT1_14: TTASNumEnter
      Left = 165
      Top = 309
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 64
      FieldName = 'DISP.ACCT1[14] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT2_14: TTASNumEnter
      Left = 280
      Top = 309
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 65
      FieldName = 'DISP.ACCT2[14] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DISP_ACCT3_14: TTASNumEnter
      Left = 396
      Top = 309
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 66
      FieldName = 'DISP.ACCT3[14] '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object DSP_ACCT4_14: TTASNumEnter
      Left = 511
      Top = 309
      Width = 115
      Height = 21
      TabStop = False
      AutoSize = False
      Color = clWhite
      ReadOnly = True
      TabOrder = 67
      FieldName = 'DISP.ACCT4[14]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      FastSearchType = fsNum
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      ButtonWidthNum = 0
      FldModified = False
      GlyphKind = gkCustom
      NumGlyphs = 2
      ButtonWidth = 0
    end
    object SHOW_DATE_1: TTASDateEdit
      Left = 43
      Top = 50
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 4
      FieldName = 'SHOW.DATE[1]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_2: TTASDateEdit
      Left = 43
      Top = 71
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 9
      FieldName = 'SHOW.DATE[2]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_3: TTASDateEdit
      Left = 43
      Top = 92
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 14
      FieldName = 'SHOW.DATE[3]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_4: TTASDateEdit
      Left = 43
      Top = 113
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 19
      FieldName = 'SHOW.DATE[4]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_5: TTASDateEdit
      Left = 43
      Top = 134
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 24
      FieldName = 'SHOW.DATE[5]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_6: TTASDateEdit
      Left = 43
      Top = 155
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 29
      FieldName = 'SHOW.DATE[6]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_7: TTASDateEdit
      Left = 43
      Top = 176
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 34
      FieldName = 'SHOW.DATE[7]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_8: TTASDateEdit
      Left = 43
      Top = 197
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 39
      FieldName = 'SHOW.DATE[8]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_9: TTASDateEdit
      Left = 43
      Top = 218
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 44
      FieldName = 'SHOW.DATE[9]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_10: TTASDateEdit
      Left = 43
      Top = 239
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 49
      FieldName = 'SHOW.DATE[10]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_11: TTASDateEdit
      Left = 43
      Top = 260
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 54
      FieldName = 'SHOW.DATE[11]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object SHOW_DATE_12: TTASDateEdit
      Left = 43
      Top = 281
      Width = 121
      Height = 21
      TabStop = False
      BlanksChar = '0'
      NumGlyphs = 2
      ReadOnly = True
      TabOrder = 59
      FieldName = 'SHOW.DATE[12]'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object BudgetPanel: TPanel
      Left = 72
      Top = 2
      Width = 536
      Height = 336
      BevelInner = bvLowered
      ParentBackground = False
      ParentColor = True
      TabOrder = 68
      Visible = False
      object Label10: TLabel
        Left = 20
        Top = 62
        Width = 34
        Height = 32
        Caption = 'Beg '#13#10'Dates'
      end
      object Label11: TLabel
        Left = 161
        Top = 48
        Width = 46
        Height = 16
        Caption = 'Beg Bal'
      end
      object Label13: TLabel
        Left = 27
        Top = 9
        Width = 149
        Height = 29
        Caption = 'Edit Budgets'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -24
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label14: TLabel
        Left = 214
        Top = 21
        Width = 119
        Height = 18
        Caption = 'CURRENT YEAR'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object Label15: TLabel
        Left = 361
        Top = 22
        Width = 85
        Height = 18
        Caption = 'NEXT YEAR'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -15
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object TASDateEdit1: TTASDateEdit
        Left = 59
        Top = 73
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 14
        FieldName = 'SHOW.DATE[1]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit2: TTASDateEdit
        Left = 59
        Top = 94
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 15
        FieldName = 'SHOW.DATE[2]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit3: TTASDateEdit
        Left = 59
        Top = 115
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 16
        FieldName = 'SHOW.DATE[3]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit4: TTASDateEdit
        Left = 59
        Top = 136
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 17
        FieldName = 'SHOW.DATE[4]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit5: TTASDateEdit
        Left = 59
        Top = 157
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 18
        FieldName = 'SHOW.DATE[5]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit6: TTASDateEdit
        Left = 59
        Top = 178
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 19
        FieldName = 'SHOW.DATE[6]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit7: TTASDateEdit
        Left = 59
        Top = 199
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 20
        FieldName = 'SHOW.DATE[7]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit8: TTASDateEdit
        Left = 59
        Top = 220
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 21
        FieldName = 'SHOW.DATE[8]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit9: TTASDateEdit
        Left = 59
        Top = 241
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 22
        FieldName = 'SHOW.DATE[9]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit10: TTASDateEdit
        Left = 59
        Top = 262
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 23
        FieldName = 'SHOW.DATE[10]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit11: TTASDateEdit
        Left = 59
        Top = 283
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 24
        FieldName = 'SHOW.DATE[11]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASDateEdit12: TTASDateEdit
        Left = 59
        Top = 304
        Width = 121
        Height = 21
        TabStop = False
        BlanksChar = '0'
        NumGlyphs = 2
        ReadOnly = True
        TabOrder = 25
        FieldName = 'SHOW.DATE[12]'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASNumEnter1: TTASNumEnter
        Left = 217
        Top = 45
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 0
        FieldName = 'DISP.ACCT2[1] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter2: TTASNumEnter
        Left = 217
        Top = 73
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 1
        FieldName = 'DISP.ACCT2[2] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter3: TTASNumEnter
        Left = 217
        Top = 94
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 2
        FieldName = 'DISP.ACCT2[3] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter4: TTASNumEnter
        Left = 217
        Top = 115
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 3
        FieldName = 'DISP.ACCT2[4] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter5: TTASNumEnter
        Left = 217
        Top = 136
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 4
        FieldName = 'DISP.ACCT2[5] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter6: TTASNumEnter
        Left = 217
        Top = 157
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 5
        FieldName = 'DISP.ACCT2[6] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter7: TTASNumEnter
        Left = 217
        Top = 178
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 6
        FieldName = 'DISP.ACCT2[7] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter8: TTASNumEnter
        Left = 217
        Top = 199
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 7
        FieldName = 'DISP.ACCT2[8] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter9: TTASNumEnter
        Left = 217
        Top = 220
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 8
        FieldName = 'DISP.ACCT2[9] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter10: TTASNumEnter
        Left = 217
        Top = 241
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 9
        FieldName = 'DISP.ACCT2[10] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter11: TTASNumEnter
        Left = 217
        Top = 262
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 10
        FieldName = 'DISP.ACCT2[11] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter12: TTASNumEnter
        Left = 217
        Top = 283
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 11
        FieldName = 'DISP.ACCT2[12] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter13: TTASNumEnter
        Left = 217
        Top = 304
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 12
        FieldName = 'DISP.ACCT2[13] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object btnBSave: TGlyphBtn
        Left = 472
        Top = 309
        Width = 23
        Height = 25
        TabOrder = 13
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
          FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
          4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
          7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
          6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
          85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
          D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
          559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
          8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
          9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
          F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
          EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
          FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
          BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
          F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
          C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
          FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
        GlyphKind = bkCustom
      end
      object btnBexit: TGlyphBtn
        Left = 496
        Top = 309
        Width = 23
        Height = 25
        TabOrder = 26
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
          DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
          E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
          19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
          5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
          EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
          43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
          707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
          D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
          6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
          7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
          D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
          FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
          8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
          D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
          F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
          91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
          DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
          77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
          8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
          EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
          90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
          3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
          AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
          BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
        GlyphKind = bkCustom
      end
      object GlyphBtn1: TGlyphBtn
        Left = 681
        Top = 309
        Width = 23
        Height = 25
        TabOrder = 27
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
          FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
          4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
          7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
          6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
          85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
          D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
          559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
          8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
          9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
          F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
          EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
          FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
          BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
          F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
          C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
          FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
          FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
          FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
        GlyphKind = bkCustom
      end
      object GlyphBtn2: TGlyphBtn
        Left = 705
        Top = 309
        Width = 23
        Height = 25
        TabOrder = 28
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
          DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
          E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
          19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
          5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
          EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
          43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
          707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
          D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
          6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
          7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
          D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
          FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
          8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
          D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
          F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
          91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
          DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
          77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
          8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
          EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
          90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
          3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
          AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
          BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
        GlyphKind = bkCustom
      end
      object TASNumEnter14: TTASNumEnter
        Left = 348
        Top = 45
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 29
        FieldName = 'DISP.BUDGET[1] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter15: TTASNumEnter
        Left = 348
        Top = 73
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 30
        FieldName = 'DISP.BUDGET[2] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter16: TTASNumEnter
        Left = 348
        Top = 94
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 31
        FieldName = 'DISP.BUDGET[3] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter17: TTASNumEnter
        Left = 348
        Top = 115
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 32
        FieldName = 'DISP.BUDGET[4] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter18: TTASNumEnter
        Left = 348
        Top = 136
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 33
        FieldName = 'DISP.BUDGET[5] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter19: TTASNumEnter
        Left = 348
        Top = 157
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 34
        FieldName = 'DISP.BUDGET[6] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter20: TTASNumEnter
        Left = 348
        Top = 178
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 35
        FieldName = 'DISP.BUDGET[7] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter21: TTASNumEnter
        Left = 348
        Top = 199
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 36
        FieldName = 'DISP.BUDGET[8] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter22: TTASNumEnter
        Left = 348
        Top = 220
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 37
        FieldName = 'DISP.BUDGET[9] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter23: TTASNumEnter
        Left = 348
        Top = 241
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 38
        FieldName = 'DISP.BUDGET[10] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter24: TTASNumEnter
        Left = 348
        Top = 262
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 39
        FieldName = 'DISP.BUDGET[11] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter25: TTASNumEnter
        Left = 348
        Top = 283
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 40
        FieldName = 'DISP.BUDGET[12] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
      object TASNumEnter26: TTASNumEnter
        Left = 348
        Top = 304
        Width = 115
        Height = 21
        AutoSize = False
        Color = clWhite
        TabOrder = 41
        FieldName = 'DISP.BUDGET[13] '
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        FastSearchType = fsNum
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        ButtonWidthNum = 0
        FldModified = False
        GlyphKind = gkCustom
        NumGlyphs = 2
        ButtonWidth = 0
      end
    end
  end
  object ToolBar1: TToolBar
    Left = 0
    Top = 0
    Width = 644
    Height = 29
    ButtonHeight = 24
    Caption = 'ToolBar1'
    EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
    EdgeInner = esLowered
    TabOrder = 3
    Transparent = True
    object btnFirst: TGlyphBtn
      Left = 0
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Find First'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 0
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800B1B8BA00919596007577770062626100626261007678
        7900999D9E00BBC0C400F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F8009CA0A2006B6D6D0062626100858381009C9A9800A5A3A1009F9D
        9A0091908D0097979500B7BABC00F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F8009CA0A2005F605F0085838100B8B5B200D7D3D000E5E1DC00E8E3DF00E3DF
        DB00D4D0CC00BFBCB800B4B3B000C4C7C800F8F8F800F8F8F800F8F8F800B3B8
        BC006B6D6D008C8A8800CBC6C300E7E3DF00EFEBE600F0EBE700F0EBE700EFEB
        E600EDE8E300E5E1DC00D9D5D100D3D2CF00CCD2D400F8F8F800F8F8F8009498
        99007B7A7900C0BCB900E8E3DF00EFEBE600F0EBE700F0EBE700F0EBE700DFD3
        CA00D3C1B400EFEAE500ECE7E300EFEAE500DBDDDD00F8F8F800F8F8F8008283
        84009D9B9900DBD7D400EFEBE600F0EBE700F0EBE700EBE3DE00CAB4A600B89D
        8900BAA19000EFEBE600F0EBE700F0ECE700E6E5E300F8F8F800F8F8F8008180
        7F00B7B4B000E8E3DF00F0EBE700F0EBE700D4C4B800BDA49300B6998500AA89
        7100AE998900F0EBE700F0EBE700F1EDE800EFEBE800F8F8F800F8F8F8009291
        8E00C8C3C000EEE9E400F0EBE700C9B3A400B2927D00AE8D7600AC8A7300A685
        7000AE998900F0EBE700F0EBE700F1EDEA00EFEBE800F8F8F800F8F8F800A9A9
        A800CCC8C400EFEBE600F0EBE700F0EBE700D0C4BA009A806E00A0816D00A484
        6E00AE998900F0EBE700F0ECE800F1EFEB00E7E7E600F8F8F800F8F8F800BCC0
        C000CECAC500EEE9E400F0EBE700F0EBE700F0EBE700F0EBE700BCACA0009076
        6500A7938500F0EBE700F1EEEA00F2EFED00DCDFE000F8F8F800F8F8F800C9CF
        D000D4D3D000F0EBE700F0EBE700F0EBE700F0EBE700F0EBE700F0EBE700EBE6
        E000D7CCC400F1EDE900F2EFEC00EBEBEA00D0D6D800F8F8F800F8F8F800F8F8
        F800D6D8D900EEEBE600F1EDE900F0ECE800F0ECE700F0EBE700F0ECE700F0EC
        E800F1EEEB00F2EFED00EFEFEE00D9DCDF00F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800D8DBDC00EAE9E600F1EEEB00F1EEEB00F1EFEB00F1EFEB00F2EF
        ED00F2F0EF00EBEBEB00D9DCDF00F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800D0D6D800DCDFDF00E7E7E700EFEEEB00EFEFEC00E7E9
        E800DCE0E200D0D6D900F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800}
      GlyphKind = bkCustom
    end
    object btnPrev: TGlyphBtn
      Left = 23
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Find Previous'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 1
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800B1B8BA00919596007577770062626100626261007678
        7900999D9E00BBC0C400F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F8009CA0A2006B6D6D0062626100858381009C9A9800A5A3A1009F9D
        9A0091908D0097979500B7BABC00F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F8009CA0A2005F605F0085838100B8B5B200D7D3D000E5E1DC00E8E3DF00E3DF
        DB00D4D0CC00BFBCB800B4B3B000C4C7C800F8F8F800F8F8F800F8F8F800B3B8
        BC006B6D6D008C8A8800CBC6C300E7E3DF00EFEBE600F0EBE700F0EBE700EFEB
        E600EDE8E300E5E1DC00D9D5D100D3D2CF00CCD2D400F8F8F800F8F8F8009498
        99007B7A7900C0BCB900E8E3DF00EFEBE600F0EBE700F0EBE700F0EBE700DFD3
        CA00D3C1B400EFEAE500ECE7E300EFEAE500DBDDDD00F8F8F800F8F8F8008283
        84009D9B9900DBD7D400EFEBE600F0EBE700F0EBE700EBE3DE00CAB4A600B89D
        8900BAA19000EFEBE600F0EBE700F0ECE700E6E5E300F8F8F800F8F8F8008180
        7F00B7B4B000E8E3DF00F0EBE700F0EBE700D4C4B800BDA49300B6998500AA89
        7100AE998900F0EBE700F0EBE700F1EDE800EFEBE800F8F8F800F8F8F8009291
        8E00C8C3C000EEE9E400F0EBE700C9B3A400B2927D00AE8D7600AC8A7300A685
        7000AE998900F0EBE700F0EBE700F1EDEA00EFEBE800F8F8F800F8F8F800A9A9
        A800CCC8C400EFEBE600F0EBE700F0EBE700D0C4BA009A806E00A0816D00A484
        6E00AE998900F0EBE700F0ECE800F1EFEB00E7E7E600F8F8F800F8F8F800BCC0
        C000CECAC500EEE9E400F0EBE700F0EBE700F0EBE700F0EBE700BCACA0009076
        6500A7938500F0EBE700F1EEEA00F2EFED00DCDFE000F8F8F800F8F8F800C9CF
        D000D4D3D000F0EBE700F0EBE700F0EBE700F0EBE700F0EBE700F0EBE700EBE6
        E000D7CCC400F1EDE900F2EFEC00EBEBEA00D0D6D800F8F8F800F8F8F800F8F8
        F800D6D8D900EEEBE600F1EDE900F0ECE800F0ECE700F0EBE700F0ECE700F0EC
        E800F1EEEB00F2EFED00EFEFEE00D9DCDF00F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800D8DBDC00EAE9E600F1EEEB00F1EEEB00F1EFEB00F1EFEB00F2EF
        ED00F2F0EF00EBEBEB00D9DCDF00F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800D0D6D800DCDFDF00E7E7E700EFEEEB00EFEFEC00E7E9
        E800DCE0E200D0D6D900F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800}
      GlyphKind = bkCustom
    end
    object btnSearch: TGlyphBtn
      Left = 46
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Search'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 2
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000F0F3F700F0F3
        F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700F0F3F700F0F3F700737778004D51520004080900090D0E003D41
        420084868700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F7009193940084868700A3A7A80085898A00BBC0C100C9CECF008085
        8600585C5D0034363700A1A3A400F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700979B9C00979B9C00DBE0E100BDC2C300D7DFDF00C3C8C900CCD1
        D200CCD1D2009EA2A300161A1B0096989900F0F3F700F0F3F700F0F3F700F0F3
        F700AFB1B200A5A9AA00C4C9CA00C5CDCD00C0CACA00C2CCCC00CED8D800C0CA
        CA0000010100BEC3C400989C9D004A4C4D00BCBEBF00F0F3F700F0F3F700B9BD
        BE00777B7C00E2E7E800CBD3D300CAD4D400C2CCCC00CED8D800C0CACA000001
        010000010100D6DEDE00BDC2C30055595A0080828300F0F3F700F0F3F700ABAF
        B000B9BDBE00D2D7D800C3CBCB00C9D3D300C7D1D100C0CACA00000101000001
        0100C0CACA00D2DADA00BCC1C2009398990042464700F0F3F700F0F3F7008387
        8800C8CDCE00C2CACA00CDD5D50000010100000101000001010000010100C6D2
        D200D0DADA00C2CCCC00C7CCCD00BDC2C3000B0F1000F0F3F700F0F3F7008387
        8800C5CACB00CDD5D50000010100CFD9D900BBC7C700CED8D80000010100C8D4
        D400C4CECE00CED8D800CDD2D300BDC2C3000B0F1000F0F3F700F0F3F7008E92
        9300ACB0B100C9CECF0000010100C4CECE00CED8D800C0CACA0000010100BECA
        CA00CFD9D900C1C9C900C2C7C800808586004D515200F0F3F700F0F3F700BDC1
        C2009DA1A200D7DCDD0000010100D7E1E100BAC4C400D5DFDF0000010100CED8
        D800D0D8D800C3CBCB00C5CACB006F7374006C6E6F00F0F3F700F0F3F700E7E9
        EA0095979800BABEBF00BEC3C400000101000001010000010100C0CACA00C6CE
        CE00C7CFCF00DADFE00095999A00585A5B00D2D4D500F0F3F700F0F3F700F0F3
        F700CED0D1009B9FA000B7BBBC00D0D5D600C5CACB00C0CACA00CED8D800CCD1
        D200C3C8C900ACB0B10081858600A3A5A600F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700C8CACB0095979800999D9E00B8BCBD00C2C7C800D2D7D800AFB4
        B500B2B6B70092949500D1D3D400F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700F0F3F700F0F3F700BCC0C1009CA0A100818586007F838400999D
        9E00BDBFC000F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3
        F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700F0F3F700}
      GlyphKind = bkCustom
    end
    object btnNext: TGlyphBtn
      Left = 69
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Find Next'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 3
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800BBC0C400999D9E007678790062626100626261007577
        770091959600B1B8BA00F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800B7BABC009797950091908D009F9D9A00A5A3A1009C9A98008583
        8100626261006B6D6D009CA0A200F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800C4C7C800B4B3B000BFBCB800D4D0CC00E3DFDB00E8E3DF00E5E1DC00D7D3
        D000B8B5B200858381005F605F009CA0A200F8F8F800F8F8F800F8F8F800CCD2
        D400D3D2CF00D9D5D100E5E1DC00EDE8E300EFEBE600F0EBE700F0EBE700EFEB
        E600E7E3DF00CBC6C3008C8A88006B6D6D00B3B8BC00F8F8F800F8F8F800DBDD
        DD00EFEAE500ECE7E300EFEAE500D3C1B400DFD3CA00F0EBE700F0EBE700F0EB
        E700EFEBE600E8E3DF00C0BCB9007B7A790094989900F8F8F800F8F8F800E6E5
        E300F0ECE700F0EBE700EFEBE600BAA19000B89D8900CAB4A600EBE3DE00F0EB
        E700F0EBE700EFEBE600DBD7D4009D9B990082838400F8F8F800F8F8F800EFEB
        E800F1EDE800F0EBE700F0EBE700AE998900AA897100B6998500BDA49300D4C4
        B800F0EBE700F0EBE700E8E3DF00B7B4B00081807F00F8F8F800F8F8F800EFEB
        E800F1EDEA00F0EBE700F0EBE700AE998900A6857000AC8A7300AE8D7600B292
        7D00C9B3A400F0EBE700EEE9E400C8C3C00092918E00F8F8F800F8F8F800E7E7
        E600F1EFEB00F0ECE800F0EBE700AE998900A4846E00A0816D009A806E00D0C4
        BA00F0EBE700F0EBE700EFEBE600CCC8C400A9A9A800F8F8F800F8F8F800DCDF
        E000F2EFED00F1EEEA00F0EBE700A793850090766500BCACA000F0EBE700F0EB
        E700F0EBE700F0EBE700EEE9E400CECAC500BCC0C000F8F8F800F8F8F800D0D6
        D800EBEBEA00F2EFEC00F1EDE900D7CCC400EBE6E000F0EBE700F0EBE700F0EB
        E700F0EBE700F0EBE700F0EBE700D4D3D000C9CFD000F8F8F800F8F8F800F8F8
        F800D9DCDF00EFEFEE00F2EFED00F1EEEB00F0ECE800F0ECE700F0EBE700F0EC
        E700F0ECE800F1EDE900EEEBE600D6D8D900F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800D9DCDF00EBEBEB00F2F0EF00F2EFED00F1EFEB00F1EFEB00F1EE
        EB00F1EEEB00EAE9E600D8DBDC00F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800D0D6D900DCE0E200E7E9E800EFEFEC00EFEEEB00E7E7
        E700DCDFDF00D0D6D800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800}
      GlyphKind = bkCustom
    end
    object btnLast: TGlyphBtn
      Left = 92
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Find Last'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 4
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800BBC0C400999D9E007678790062626100626261007577
        770091959600B1B8BA00F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800B7BABC009797950091908D009F9D9A00A5A3A1009C9A98008583
        8100626261006B6D6D009CA0A200F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800C4C7C800B4B3B000BFBCB800D4D0CC00E3DFDB00E8E3DF00E5E1DC00D7D3
        D000B8B5B200858381005F605F009CA0A200F8F8F800F8F8F800F8F8F800CCD2
        D400D3D2CF00D9D5D100E5E1DC00EDE8E300EFEBE600F0EBE700F0EBE700EFEB
        E600E7E3DF00CBC6C3008C8A88006B6D6D00B3B8BC00F8F8F800F8F8F800DBDD
        DD00EFEAE500ECE7E300EFEAE500D3C1B400DFD3CA00F0EBE700F0EBE700F0EB
        E700EFEBE600E8E3DF00C0BCB9007B7A790094989900F8F8F800F8F8F800E6E5
        E300F0ECE700F0EBE700EFEBE600BAA19000B89D8900CAB4A600EBE3DE00F0EB
        E700F0EBE700EFEBE600DBD7D4009D9B990082838400F8F8F800F8F8F800EFEB
        E800F1EDE800F0EBE700F0EBE700AE998900AA897100B6998500BDA49300D4C4
        B800F0EBE700F0EBE700E8E3DF00B7B4B00081807F00F8F8F800F8F8F800EFEB
        E800F1EDEA00F0EBE700F0EBE700AE998900A6857000AC8A7300AE8D7600B292
        7D00C9B3A400F0EBE700EEE9E400C8C3C00092918E00F8F8F800F8F8F800E7E7
        E600F1EFEB00F0ECE800F0EBE700AE998900A4846E00A0816D009A806E00D0C4
        BA00F0EBE700F0EBE700EFEBE600CCC8C400A9A9A800F8F8F800F8F8F800DCDF
        E000F2EFED00F1EEEA00F0EBE700A793850090766500BCACA000F0EBE700F0EB
        E700F0EBE700F0EBE700EEE9E400CECAC500BCC0C000F8F8F800F8F8F800D0D6
        D800EBEBEA00F2EFEC00F1EDE900D7CCC400EBE6E000F0EBE700F0EBE700F0EB
        E700F0EBE700F0EBE700F0EBE700D4D3D000C9CFD000F8F8F800F8F8F800F8F8
        F800D9DCDF00EFEFEE00F2EFED00F1EEEB00F0ECE800F0ECE700F0EBE700F0EC
        E700F0ECE800F1EDE900EEEBE600D6D8D900F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800D9DCDF00EBEBEB00F2F0EF00F2EFED00F1EFEB00F1EFEB00F1EE
        EB00F1EEEB00EAE9E600D8DBDC00F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800D0D6D900DCE0E200E7E9E800EFEFEC00EFEEEB00E7E7
        E700DCDFDF00D0D6D800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8
        F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800F8F8F800}
      GlyphKind = bkCustom
    end
    object btnClear: TGlyphBtn
      Left = 115
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Clear Data'
      ParentShowHint = False
      ShowHint = True
      TabOrder = 5
      Glyph.Data = {
        36040000424D3604000000000000360000002800000010000000100000000100
        2000000000000004000000000000000000000000000000000000C8D0D4000000
        0000000000000000000000000000C8D0D400000000000000000000000000C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400000000000000
        0000000000000000000000000000000000000000000000000000C8D0D400C8D0
        D400C8D0D40000000000C8D0D400C8D0D400C8D0D400C8D0D400000000000000
        0000C8D0D400C8D0D400000000000000000000000000C8D0D400C8D0D4000000
        0000C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400000000000000
        0000C8D0D400C8D0D400C8D0D4000000000000000000C8D0D400C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D4000000
        000000000000C8D0D400C8D0D4000000000000000000C8D0D400000000000000
        0000C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D4000000000000000000C8D0D40000000000C8D0D40000000000000080000000
        800000000000C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D400C8D0D400C8D0D40000000000C8D0D400000000000000FF000000FF000000
        FF000000800000000000C8D0D400C8D0D400C8D0D400C8D0D400C8D0D4000000
        000000000000C8D0D400C8D0D400C8D0D400000000000000FF000000FF000000
        FF000000FF000000800000000000C8D0D400C8D0D400C8D0D400C8D0D4000000
        000000000000C8D0D40000000000C8D0D400C8D0D400000000000000FF000000
        FF000000FF00000000000080800000000000C8D0D400C8D0D400C8D0D400C8D0
        D4000000000000000000C8D0D40000000000C8D0D400C8D0D400000000000000
        FF000000000000FFFF00000000000080800000000000C8D0D400C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D4000000
        000000FFFF000000000000FFFF00000000000080800000000000C8D0D400C8D0
        D400C8D0D400C8D0D40000000000C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D4000000000000FFFF000000000000FFFF000080800000808000C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D400C8D0D4000000000000FFFF0000FFFF0000FFFF0000808000C8D0D400C8D0
        D400C8D0D40000000000C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D400C8D0D400C8D0D4000000000000FFFF0000FFFF0000FFFF00C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D4000000000000FFFF0000FFFF00C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0
        D400C8D0D400C8D0D400C8D0D400C8D0D4000000000000FFFF00}
      GlyphKind = bkCustom
    end
  end
  object EvoToolBar: TToolBar
    Left = 525
    Top = 3
    Width = 116
    Height = 25
    Align = alCustom
    Anchors = [akTop, akRight]
    EdgeBorders = []
    Images = EvoToobarImages
    TabOrder = 4
    Transparent = False
    Visible = False
    object ETB5: TToolButton
      Left = 0
      Top = 0
      Caption = 'ETB5'
      Visible = False
    end
    object ETB4: TToolButton
      Left = 23
      Top = 0
      Caption = 'ETB4'
      Visible = False
    end
    object ETB3: TToolButton
      Left = 46
      Top = 0
      Caption = 'ETB3'
      Visible = False
    end
    object ETB2: TToolButton
      Left = 69
      Top = 0
      Caption = 'ETB2'
      Visible = False
    end
    object ETB1: TToolButton
      Left = 92
      Top = 0
      Caption = 'ETB1'
      Visible = False
    end
  end
  object ETBcombo: TTASComboBox
    Left = 423
    Top = 2
    Width = 168
    Height = 24
    Style = csDropDownList
    ItemHeight = 16
    TabOrder = 5
    Visible = False
    FieldName = 'ETBcomboval'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Panel3: TPanel
    Left = 0
    Top = 424
    Width = 644
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 2
    object btnExit: TGlyphBtn
      Left = 563
      Top = 5
      Width = 78
      Height = 23
      Caption = 'E&xit'
      TabOrder = 3
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnBudget: TGlyphBtn
      Left = 8
      Top = 5
      Width = 74
      Height = 23
      Caption = 'Budget'
      TabOrder = 0
      Visible = False
      GlyphKind = bkCustom
    end
    object btnNextYear: TGlyphBtn
      Left = 82
      Top = 5
      Width = 74
      Height = 23
      Caption = 'Next Year'
      TabOrder = 1
      Visible = False
      GlyphKind = bkCustom
    end
    object btnPrevYear: TGlyphBtn
      Left = 156
      Top = 5
      Width = 74
      Height = 23
      Caption = 'Prev Year'
      TabOrder = 2
      Visible = False
      GlyphKind = bkCustom
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 29
    Width = 644
    Height = 53
    Align = alTop
    BevelOuter = bvNone
    BorderStyle = bsSingle
    TabOrder = 0
    object Gradient4: TGradient
      Left = 0
      Top = 0
      Width = 640
      Height = 49
      Align = alClient
      Style = gsReflectedH
    end
    object Shape1: TShape
      Left = 0
      Top = 0
      Width = 640
      Height = 49
      Align = alClient
      Brush.Style = bsClear
      Pen.Mode = pmBlack
      Shape = stRoundRect
    end
    object Label2: TLabel
      Left = 13
      Top = 1
      Width = 61
      Height = 16
      Caption = 'Acct Code'
      Transparent = True
    end
    object Label12: TLabel
      Left = 133
      Top = 1
      Width = 27
      Height = 16
      Caption = 'Dept'
      Transparent = True
    end
    object Label1: TLabel
      Left = 178
      Top = 1
      Width = 65
      Height = 16
      Caption = 'Description'
      Transparent = True
    end
    object Label3: TLabel
      Left = 454
      Top = 1
      Width = 27
      Height = 16
      Caption = 'Type'
      Transparent = True
    end
    object Label4: TLabel
      Left = 555
      Top = 1
      Width = 75
      Height = 16
      Caption = 'Normal Dr/Cr'
      Transparent = True
    end
    object Label8: TLabel
      Left = 492
      Top = 1
      Width = 57
      Height = 16
      Caption = 'Non-Cash'
      Transparent = True
    end
    object Label9: TLabel
      Left = 128
      Top = 17
      Width = 4
      Height = 18
      Caption = '-'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial Black'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object BKGL_ACCT: TTASComboEnter
      Left = 13
      Top = 17
      Width = 115
      Height = 21
      CharCase = ecUpperCase
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
        0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
        A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
        DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
        AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
        9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
        D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
        B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
        C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
        0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
        C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
        D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
        CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
        9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
        CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
        0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
        CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
        86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
        C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      NumGlyphs = 1
      TabOrder = 0
      Text = 'BKGL_ACCT'
      FieldName = 'BKGL.ACCT'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_glacct("A")'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|BTNSEARCH.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object BKGL_GLDPT: TTASENTER
      Left = 133
      Top = 17
      Width = 39
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 1
      Text = 'BKGL_GLDPT'
      FieldName = 'BKGL.GLDPT'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = True
      ValidUserEsc = False
      ValidExpr = 'vld_glacct('#39'D'#39')'
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      KeyTraps = 'F2|BTNSEARCH.CLICK'
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object BKGL_ACCTD: TTASENTER
      Left = 178
      Top = 17
      Width = 270
      Height = 21
      AutoSize = False
      CharCase = ecUpperCase
      TabOrder = 2
      Text = 'BKGL_ACCTD'
      FieldName = 'BKGL.ACCTD'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object BKGL_TYPE: TTASENTER
      Left = 459
      Top = 18
      Width = 20
      Height = 21
      TabStop = False
      AutoSize = False
      CharCase = ecUpperCase
      ReadOnly = True
      TabOrder = 3
      Text = 'BKGL_TYPE'
      FieldName = 'BKGL.TYPE'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object BKGL_CR_DR: TTASENTER
      Left = 583
      Top = 18
      Width = 20
      Height = 21
      TabStop = False
      AutoSize = False
      CharCase = ecUpperCase
      ReadOnly = True
      TabOrder = 4
      Text = 'BKGL_CR_DR'
      FieldName = 'BKGL.CR.DR'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
    object TASENTER1: TTASENTER
      Left = 513
      Top = 18
      Width = 20
      Height = 21
      TabStop = False
      AutoSize = False
      CharCase = ecUpperCase
      ReadOnly = True
      TabOrder = 5
      Text = 'BKGL_TYPE'
      FieldName = 'BKGL.NON.CASH  '
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = True
    end
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 237
    Top = 65517
  end
  object EvoToobarImages: TImageList
    Left = 328
    Top = 65516
    Bitmap = {
      494C010106000900140010001000FFFFFFFFFF10FFFFFFFFFFFFFFFF424D3600
      0000000000003600000028000000400000002000000001002000000000000020
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000007373730073737300737373000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000CE944200CE8C3100D69C
      5200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000073737300BD632900AD6B42006B524A007373730000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000DEA55200BD843900000000000000
      0000D69C5200B57B39006B5231006B5231006B5231006B5231006B5231000000
      000000000000000000000000000000000000000000007373730073737300BD63
      2900EF7B0800FF732100FF940800FFAD310094634A007373730073737300B57B
      5A00737373007373730073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFAD4200AD7B4200000000000000
      00006B523100C67B3100DE943900EFAD4200F7B55200DEB56300EFAD42006B52
      31006B5231000000000000000000000000008452520084525200E79C5A00EF84
      1000D6846300FFAD3100FF8C0800FFA51000FFBD6300AD7B6B0084525200FF94
      0000845252008452520073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFB54A00AD7B4200000000006B52
      3100E79C3100F79C3900EF943100EF9C3100F7A53900F7BD5200FFD67300EFCE
      8C00B57B39006B523100000000000000000094634A00F7F7E700F7F7E700F7F7
      E700FFF7E700F7DEAD00F7941800FF940000FFAD3100FFC68400FFBD5A00FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000E7AD6300DE9C29006B523100F7A5
      3100EF9C3100E7942900E79429007352310073523100B5732900F7B54200FFD6
      6B00F7D69400B57B3900000000000000000094636300FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00F7DEAD00FF9C0800FF9C0800FFBD5A00FFC68400FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000F7B53900F7AD3100EFA5
      2900E7942900DE8C290084522900000000000000000000000000B5732900F7AD
      3900FFD66B00DEB57B00B57B390000000000A56B6B00FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00F7941800FFAD2900FF940000FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000E7B56300F7B53100EFA5
      2900E7942100A56318006B5231006B5231006B5231006B5231006B5231006B52
      31006B5231006B5231006B52310000000000AD7B6B00FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FF5A3100EF6B4200EF523100EF6B4200FF5A
      3100FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F7BD3900EFAD
      2900E79C2100D67B2900D67B2900D67B2900D67B2900D67B2900D67B2900D67B
      2900D67B2900D67B2900B57B390000000000B58C7300FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00CECECE00D6D6D600F7EFDE00F7E7
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000F7C6
      4200EFAD2900E79C2100DE942100E7942900E7942900E7942900E7942900EF94
      3100F79C3900EFA54200B57B390000000000B58C7300FFFFFF00FF5A3100EF6B
      4200E7522900C6734200C68C7B00FFFFFF00FFFFFF00FFFFFF00294A84007394
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000EFCE940000000000F7C6
      4200F7C64200BD8429006B4A21000000000000000000B5732900CE8C3100EF94
      2900EF9C3100EF9C3100B57B390000000000C6947B00FFFFFF00FF8C0800FF8C
      0800FF5A3100AD4A1800FFF7EF00FFFFFF00FFFFFF00FFFFFF007394D6007394
      D600FFFFF700AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000EFCE94000000
      0000F7C64200E7AD39006B5229005A42290073523100B5732900E79C2900E794
      2900F7A53900B57B39000000000000000000D6A58400FFFFFF00FF8C0800FFBD
      5A00FFAD2900F7941800BD632900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
      FF00FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000D6BD8C00E7CE
      8C0000000000F7DE8C00E7B53900B5842100CE8C2100E7A52900E79C2100EFA5
      2900EFA53900B57B39000000000000000000DEAD8400DEAD8400FF8C0800DEAD
      8400F7A55A00FFC68400EF943900BD632900C69C9400C69C9400C69C9400C69C
      9400C69C9400AD7B7B0000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000D6BD
      8C00D6BD8C00E7D66300E7D66300F7D64200F7B53100EFAD2900EFAD2900EFA5
      3100B57B390000000000EFAD4200000000000000000000000000FF8C08000000
      000000000000F7A55A00FFDEAD00EFB58C00BD632900BD523900C6734200A563
      4200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000D6BD8C00D6BD8C00D6BD8C00DEB55200FFCE4A00B57B3900B57B
      39000000000000000000EFAD4200000000000000000000000000000000000000
      00000000000000000000F7A55A00FFEFBD00FFE7AD00DE8C5200944A18000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000AD9A880046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000AD9A8800CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000212121004242
      3900424239004242390042423900424239004242390042423900424239004242
      3900424239004242390042423900000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000AD9A
      8800FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B7B00F7F7
      FF00F7F7FF00F7F7FF00BDBDBD00F7F7FF00F7F7FF00003939005A5A5A00F7EF
      E700F7F7FF00F7F7FF0042423900000000000000000046403800464038004640
      380046403800464038004640380046403800464038004640380046403800FFE8
      D400FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000027596100000000000000000027596100000000000000
      00000000000000000000000000000000000000000000000000005A5A5A00BDBD
      BD00BDBDBD00BDBDBD009C9C9400BDBDBD00BDBDBD005A5A5A0042BDBD005252
      4A00BDBDBD00BDBDBD004242390000000000AD9A8800FFE5CE00CAB39E00CAB3
      9E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00FFE8D400FFEB
      D900FFEBD900FFEBD900BBA69200464038008080000080800000800000008000
      0000800000008000000080000000800000008000000080000000800000008000
      0000800000008000000080000000000000000000000027596100000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000275961000000000000000000000000005A5A5A00DED6
      D600DED6D600DED6D600ADADAD00DED6D600DED6D600F7F7FF005A5A5A005ADE
      DE0052524A00F7EFE7004242390000000000AD9A8800FFEDDD00FFE3C900FFE3
      C900FFE3C900FFE3C9008B7C6D0000000000EDD2B900FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BBA692004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      6100000000000000000080808000808080008080800080808000000000000000
      0000275961002759610000000000000000000000000000000000393900003939
      00003939000039390000393900003939000052523100ADADAD009C9C94005A5A
      5A005ADEDE0052524A002121210000000000AD9A8800FFF1E400FFE3C900FFE3
      C900FFE3C900FFE3C900F2D6BD00ECD1B800FFE5CE00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BFAA96004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF00FFFF
      FF00C8D0D4000000000080000000000000000000000000000000275961002759
      6100000000008080800091919100838383008080800080808000808080000000
      0000275961002759610000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000DED6D600BDBDBD00F7F7
      FF007B7B7B006BADAD004242390000000000AD9A8800FFF4EA00FDE0C600FFE3
      C900FFE3C900FFE3C9008B7C6D0076695C00DCC3AD00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400C4AE99004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      61000000000080808000AAAAAA00919191008383830080808000808080000000
      00002759610027596100000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD005A5A5A005ADEDE0021212100AD9A8800FFF7F000FADEC400FADE
      C400FFE3C900FFE3C900DCC3AD00655A4E006F635700F4D8BF00FFE8D400FFE8
      D400FFE8D400FFE8D400CAB39E004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF000000
      0000FFFFFF0000000000800000000000000000000000000000002E6770002E67
      70000000000080808000AAAAAA00AAAAAA009191910080808000808080000000
      00002E6770002E67700000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF00393939005A9C9C00AD9A8800FFF9F300FADEC400FADE
      C400FADEC400FFE3C900FFE3C900DCC3AD00524840005F544A00FADEC400FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000377E8800377E
      8800000000000000000080808000808080008080800080808000000000000000
      0000377E8800377E880000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD00BDBDBD004242390000000000AD9A8800FFF9F300F6DAC000FADE
      C400EDD2B900D1BAA400DCC3AD00FFE3C900B29D8B0083746600C2AC9700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF000000000000C8D0
      D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400808000008080
      00008080000080800000800000000000000000000000000000004397A3004397
      A3004397A3000000000000000000000000000000000000000000000000004397
      A3004397A3004397A300000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF004242390000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00D1BAA400524840005C524800ECD1B800726559005F544A00D5BCA700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF0000000000FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00C8D0D400808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B0000393900005A5A5A005A5A5A007B7B
      7B007B7B7B007B7B7B002121210000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00F4D8BF00AA978500000000000000000000000000B29D8B00FFE3C900FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF0000000000000000
      0000000000000000000000000000000000000000000000000000808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      00000000000091919100000000004EA9B6004EA9B60000000000919191000000
      00000000000000000000000000000000000000000000000000009C9C0000ADAD
      6B00BD9C7B00BD9C7B00BD9C7B007B7339003939000042423900000000000000
      000000000000000000000000000000000000AD9A8800FFF9F300FFF9F300FFF9
      F300FFF9F300FFF9F300FFF9F300FFF9F300FFF9F300FFF4EA00FFF1E400FFF1
      E400FFEBD900FFEBD900FFE5CE004640380080800000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF0080800000000000000000000000000000000000000000
      0000000000000000000091919100000000000000000091919100000000000000
      00000000000000000000000000000000000000000000000000007B7B00005A5A
      5A005A5A5A005A5A5A005A5A5A00313131003939000042423900000000000000
      00000000000000000000000000000000000000000000AD9A8800AD9A8800AD9A
      8800A69382009C8B7B0092827300857669007B6D600072655900655A4E005248
      4000524840004640380046403800000000000000000080800000808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080800000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B00007B7B
      00007B7B00007B7B00007B7B00007B7B00002121000000000000000000000000
      000000000000000000000000000000000000424D3E000000000000003E000000
      2800000040000000200000000100010000000000000100000000000000000000
      000000000000000000000000FFFFFF00FFFFFFFF00000000FFFFF8FF00000000
      8FFFF07F00000000301F80010000000030070001000000002003000100000000
      000300010000000081C10001000000008001000100000000C001000100000000
      E001000100000000A181000100000000D003000100000000C803000300000000
      E005D80F00000000F80DFC1F00000000FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFF1FFFFFFFFC001FFE1FFFFFFFFC00180018001FC3FC001000000008001C001
      0000000080018000000000008001800000000000800180000000000080018000
      00000000800180000000000080018001000000008001800100000000C813803F
      00000000FC3F803F80018001FFFF807F00000000000000000000000000000000
      000000000000}
  end
end
