object EditForm1: TEditForm1
  Left = 344
  Top = 219
  Hint = 'C:\TASPro7\DBA7\T7GLB.DFM'
  AutoScroll = False
  Caption = 'GL-B'
  ClientHeight = 493
  ClientWidth = 634
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7GLB.OnClose'
  No_Refresh = False
  OnStart = 'T7GLB.OnStart'
  OpenFiles = 'T7GLB.OnOpenFiles'
  OnDisplayScreen = 'T7GLB.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7GLB'
  RememberSize = True
  RememberSizeDate = 44917.496114976850000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object GLBPAGE: TTASPageControl
    Left = 0
    Top = 29
    Width = 634
    Height = 409
    ActivePage = GLTranL
    Align = alClient
    TabOrder = 4
    TabStop = False
    PageIndex = 0
    PageName = 'GLTranL'
    object GLTranL: TTabSheet
      Caption = 'GJ Trans List'
      object Panel1: TPanel
        Left = 0
        Top = 49
        Width = 626
        Height = 329
        Align = alClient
        BevelInner = bvLowered
        BevelOuter = bvLowered
        Caption = 'Panel1'
        TabOrder = 1
        object dbgGLB1: TTASDataGrid
          Left = 2
          Top = 2
          Width = 622
          Height = 325
          Align = alClient
          ColCount = 9
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
          TabOrder = 0
          UpCase = False
          StartAtEnd = True
          PrePrgLoc = 0
          PostPrgLoc = 0
          Navigation.AllowInsertRow = False
          Navigation.AllowDeleteRow = False
          Navigation.AdvanceOnEnter = True
          Navigation.AdvanceAtEnd = False
          Navigation.AdvanceDirection = adLeftRight
          Navigation.AdvanceAuto = False
          Navigation.InsertPosition = pInsertBefore
          Navigation.CursorWalkEditor = False
          Navigation.AllowAddRecListF = False
          MouseActions.ColSelect = False
          MouseActions.RowSelect = False
          MouseActions.DirectEdit = False
          MouseActions.DirectComboDrop = False
          MouseActions.CaretPositioning = False
          PasswordChar = '*'
          Columns = <
            item
              Color = clWindow
              Width = 92
              Alignment = taRightJustify
              Header = 'Transaction #'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.TRANSNM'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 46
              Alignment = taLeftJustify
              Header = 'Posted'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.POSTED'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 52
              Alignment = taLeftJustify
              Header = 'Lines'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.NUMLNES'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 62
              Alignment = taLeftJustify
              Header = 'Date'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.TRANSDT'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 35
              Alignment = taLeftJustify
              Header = 'Type'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.TYPE   '
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 143
              Alignment = taLeftJustify
              Header = 'Code'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.CVCODE'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 46
              Alignment = taLeftJustify
              Header = 'Bank'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.CHKACT'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 78
              Alignment = taLeftJustify
              Header = 'Dp/Ck #'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'BKGL.GJ.INVCHKN'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 42
              Alignment = taLeftJustify
              Header = 'Tag'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edCheckBox
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'TAGGED'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end>
          ExtraFields = <>
          AutoNumAlign = False
          SelectionColor = clHighlight
          SelectionTextColor = clHighlightText
          SelectionRectangle = False
          FixedFont.Charset = DEFAULT_CHARSET
          FixedFont.Color = clWindowText
          FixedFont.Height = -13
          FixedFont.Name = 'Arial'
          FixedFont.Style = []
          VAlignment = vtaTop
          Hovering = False
          EnhRowColMove = False
          HintColor = clYellow
          FastSearchFld = 'FSN'
          CurrentRow = 1
          CurrentCol = 1
          GridFileHandle = 0
          GridFileKeyNum = 0
          NoAutoUpdate = False
          ColWidths = (
            92
            46
            52
            62
            35
            143
            46
            78
            42)
        end
      end
      object Panel2: TPanel
        Left = 0
        Top = 0
        Width = 626
        Height = 49
        Align = alTop
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 0
        object Gradient4: TGradient
          Left = 0
          Top = 0
          Width = 622
          Height = 45
          Align = alClient
          Style = gsReflectedH
        end
        object Shape1: TShape
          Left = 0
          Top = 0
          Width = 622
          Height = 45
          Align = alClient
          Brush.Style = bsClear
          Pen.Mode = pmBlack
          Shape = stRoundRect
        end
        object Label3: TLabel
          Left = 20
          Top = 14
          Width = 41
          Height = 16
          Caption = 'Search'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          Transparent = True
        end
        object Label2: TLabel
          Left = 335
          Top = 15
          Width = 67
          Height = 16
          Caption = 'Sort List by'
          Transparent = True
        end
        object Title: TLabel
          Left = 200
          Top = 15
          Width = 130
          Height = 16
          Alignment = taCenter
          AutoSize = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object FSD: TTASDateEdit
          Left = 67
          Top = 12
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          TabOrder = 2
          Visible = False
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object cbKeys1: TTASComboBox
          Left = 416
          Top = 10
          Width = 199
          Height = 24
          Style = csDropDownList
          CharCase = ecUpperCase
          ItemHeight = 16
          TabOrder = 1
          Items.Strings = (
            'TRANS #'
            'TRANS DATE')
          FieldName = 'cbIndexName'
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 0
          ReturnIsTab = False
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object FSN: TTASNumEnter
          Left = 67
          Top = 12
          Width = 121
          Height = 21
          AutoSize = False
          DecimalPlaces = 0
          DisplayFormat = '0;0; '
          MaxLength = 6
          TabOrder = 0
          Visible = False
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
      end
    end
    object GLTranD: TTabSheet
      Caption = 'GJ Trans Details'
      Enabled = False
      object Panel4: TPanel
        Left = 0
        Top = 0
        Width = 626
        Height = 66
        Align = alTop
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 0
        object Gradient1: TGradient
          Left = 0
          Top = 0
          Width = 622
          Height = 62
          Align = alClient
          Style = gsReflectedH
        end
        object Shape2: TShape
          Left = 0
          Top = 0
          Width = 622
          Height = 62
          Align = alClient
          Brush.Style = bsClear
          Pen.Mode = pmBlack
          Shape = stRoundRect
        end
        object Label1: TLabel
          Left = 123
          Top = 21
          Width = 116
          Height = 16
          Caption = 'Transaction Number'
          Transparent = True
        end
        object TNUMSTR: TTASENTER
          Left = 276
          Top = 19
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          ReadOnly = True
          TabOrder = 0
          Text = 'TNUMSTR'
          FieldName = 'TNUMSTR'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
      end
      object Panel5: TPanel
        Left = 0
        Top = 66
        Width = 626
        Height = 312
        Align = alClient
        BevelInner = bvLowered
        BevelOuter = bvLowered
        TabOrder = 1
        object Label4: TLabel
          Left = 123
          Top = 49
          Width = 128
          Height = 16
          Caption = 'Transaction Type [1-5]'
        end
        object Label5: TLabel
          Left = 123
          Top = 125
          Width = 98
          Height = 16
          Caption = 'Transaction Date'
        end
        object Label6: TLabel
          Left = 123
          Top = 150
          Width = 118
          Height = 16
          Caption = 'Bank Account [1-99]'
        end
        object Label7: TLabel
          Left = 123
          Top = 196
          Width = 121
          Height = 16
          Caption = 'GJ Transaction Code'
        end
        object Label8: TLabel
          Left = 123
          Top = 220
          Width = 134
          Height = 16
          Caption = 'Deposit/Check Number'
        end
        object Label30: TLabel
          Left = 123
          Top = 246
          Width = 69
          Height = 16
          Caption = 'Job Number'
        end
        object BKGL_GJ_TYPE: TTASENTER
          Left = 276
          Top = 75
          Width = 42
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 7
          Text = 'BKGL_GJ_TYPE'
          FieldName = 'BKGL.GJ.TYPE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BKGL_GJ_TRANSDT: TTASDateEdit
          Left = 276
          Top = 123
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 1
          FieldName = 'BKGL.GJ.TRANSDT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_tdate()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FocusOnObject = 'BKGL_GJ_CVCODE'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object TYPE_DESC: TTASENTER
          Left = 276
          Top = 99
          Width = 330
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 8
          Text = 'TYPE_DESC'
          FieldName = 'TYPE.DESC'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterBank: TTASComboEnter
          Left = 276
          Top = 148
          Width = 48
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 2
          Text = 'ENTERBANK'
          FieldName = 'Adsp.chkact'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_chkact()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          AllowedChrs = '1234567890'
          ReturnIsTab = True
          KeyTraps = 'F2|ENTERBANK.CLICK'
          SelectStart = 0
          FocusOnObject = 'BKGL_GJ_CVCODE'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object CHK_NAME: TTASENTER
          Left = 276
          Top = 170
          Width = 330
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 9
          Text = 'CHK_NAME'
          FieldName = 'CHK_NAME'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BKGL_GJ_CVCODE: TTASENTER
          Left = 276
          Top = 194
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 3
          Text = 'BKGL_GJ_CVCODE'
          FieldName = 'BKGL.GJ.CVCODE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_cvcode()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BKGL_GJ_INVCHKN: TTASNumEnter
          Left = 276
          Top = 218
          Width = 121
          Height = 21
          AutoSize = False
          DisplayFormat = '0;-0'
          TabOrder = 4
          FieldName = 'BKGL.GJ.INVCHKN'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_chkn()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object Job: TTASENTER
          Left = 276
          Top = 244
          Width = 143
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 5
          FieldName = 'BKGL.GJ.JOB    '
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_job()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|JOB.CLICK'
          SelectStart = 0
          FocusOnObject = 'defjobs'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object ttype: TTASComboBox
          Left = 276
          Top = 48
          Width = 200
          Height = 24
          ItemHeight = 0
          TabOrder = 0
          Text = 'ttype'
          Items.Strings = (
            '1   [GJ]    General Journal           '
            '2   [CR]   Cash Receipts            '
            '3   [CD]   Cash Disbursements   '
            '4   [TT]    Transaction Template   '
            '5   [GJ]    Beginning Balance       ')
          FieldName = 'BKGL.GJ.TYPEN  '
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_ttype()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 0
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object DEFJobs: TButton
          Left = 277
          Top = 269
          Width = 143
          Height = 25
          Caption = 'Default Jobs'
          TabOrder = 6
          Visible = False
        end
      end
    end
    object GLTranLI: TTabSheet
      Caption = 'Trans Line Items'
      Enabled = False
      object Panel6: TPanel
        Left = 0
        Top = 0
        Width = 626
        Height = 39
        Align = alTop
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 0
        object Gradient2: TGradient
          Left = 0
          Top = 0
          Width = 622
          Height = 35
          Align = alClient
          Style = gsReflectedH
        end
        object Shape3: TShape
          Left = 0
          Top = 0
          Width = 622
          Height = 35
          Align = alClient
          Brush.Style = bsClear
          Pen.Mode = pmBlack
          Shape = stRoundRect
        end
        object Label9: TLabel
          Left = 20
          Top = 11
          Width = 41
          Height = 16
          Caption = 'Search'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          Transparent = True
        end
        object Label10: TLabel
          Left = 335
          Top = 12
          Width = 67
          Height = 16
          Caption = 'Sort List by'
          Transparent = True
        end
        object fastAlpha: TTASENTER
          Left = 68
          Top = 8
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 0
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object cbKeys: TTASComboBox
          Left = 416
          Top = 7
          Width = 199
          Height = 24
          Style = csDropDownList
          CharCase = ecUpperCase
          ItemHeight = 0
          TabOrder = 1
          Items.Strings = (
            'GL ACCOUNT'
            'DESCRIPTION'
            'DEBIT AMOUNT'
            'CREDIT AMOUNT')
          FieldName = 'cbIndexName'
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 0
          ReturnIsTab = False
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
      end
      object Panel7: TPanel
        Left = 0
        Top = 39
        Width = 626
        Height = 214
        Align = alClient
        BevelInner = bvLowered
        BevelOuter = bvLowered
        TabOrder = 1
        object dbgGLB: TTASDataGrid
          Left = 2
          Top = 2
          Width = 622
          Height = 210
          Align = alClient
          ColCount = 6
          RowCount = 100
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowSelect]
          TabOrder = 0
          UpCase = False
          StartAtEnd = False
          PrePrgLoc = 0
          PostPrgLoc = 0
          Navigation.AllowInsertRow = False
          Navigation.AllowDeleteRow = False
          Navigation.AdvanceOnEnter = True
          Navigation.AdvanceAtEnd = False
          Navigation.AdvanceDirection = adLeftRight
          Navigation.AdvanceAuto = False
          Navigation.InsertPosition = pInsertBefore
          Navigation.CursorWalkEditor = False
          Navigation.AllowAddRecListF = False
          MouseActions.ColSelect = False
          MouseActions.RowSelect = False
          MouseActions.DirectEdit = False
          MouseActions.DirectComboDrop = False
          MouseActions.CaretPositioning = False
          PasswordChar = '*'
          Columns = <
            item
              Color = clWindow
              Width = 72
              Alignment = taLeftJustify
              Header = 'GL Account'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'LINE.ACCT'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 41
              Alignment = taLeftJustify
              Header = 'Dept'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'LINE_GLDPT'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 230
              Alignment = taLeftJustify
              Header = 'Description'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'LINE.DESC'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 82
              Alignment = taLeftJustify
              Header = 'Debit Amount'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'DR.DISP'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 86
              Alignment = taLeftJustify
              Header = 'Credit Amount'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'CR.DISP'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end
            item
              Color = clWindow
              Width = 80
              Alignment = taLeftJustify
              Header = 'Job'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -13
              Font.Name = 'Arial'
              Font.Style = []
              Editor = edDefault
              Fixed = False
              ReadOnly = False
              Password = False
              ComboItemsSort = False
              SpinMin = 0
              SpinMax = 0
              SpinStep = 0
              EditLength = 0
              Borders = []
              BorderPen.Color = clSilver
              FieldName = 'LINE.JOB'
              CharCase = ecNormal
              PrePrgLoc = 0
              PostPrgLoc = 0
              ValidPrgLoc = 0
              ClickPrgLoc = 0
              ChangePrgLoc = 0
              DecimalChrs = 2
              FormatOnEnter = True
              ValidCheckOnExit = False
              ValidUserEsc = False
              ValidExprLoc = 0
              ValidExprTyp = #0
              TimeFieldType = tf_5
              ElapsedTime = False
            end>
          ExtraFields = <>
          AutoNumAlign = False
          SelectionColor = clHighlight
          SelectionTextColor = clHighlightText
          SelectionRectangle = False
          FixedFont.Charset = DEFAULT_CHARSET
          FixedFont.Color = clWindowText
          FixedFont.Height = -13
          FixedFont.Name = 'Arial'
          FixedFont.Style = []
          VAlignment = vtaTop
          Hovering = False
          EnhRowColMove = False
          HintColor = clYellow
          CurrentRow = 1
          CurrentCol = 1
          GridFileHandle = 0
          GridFileKeyNum = 0
          NoAutoUpdate = False
          ColWidths = (
            72
            41
            230
            82
            86
            80)
        end
      end
      object Panel8: TPanel
        Left = 0
        Top = 253
        Width = 626
        Height = 125
        Align = alBottom
        BevelInner = bvLowered
        BevelOuter = bvLowered
        TabOrder = 2
        object Label11: TLabel
          Left = 5
          Top = 11
          Width = 116
          Height = 16
          Caption = 'Transaction Number'
          Transparent = True
        end
        object Label12: TLabel
          Left = 5
          Top = 34
          Width = 98
          Height = 16
          Caption = 'Transaction Date'
        end
        object Label13: TLabel
          Left = 5
          Top = 58
          Width = 101
          Height = 16
          Caption = 'Transaction Code'
        end
        object Label14: TLabel
          Left = 5
          Top = 80
          Width = 134
          Height = 16
          Caption = 'Deposit/Check Number'
        end
        object Label15: TLabel
          Left = 5
          Top = 102
          Width = 30
          Height = 16
          Caption = 'Bank'
        end
        object Label16: TLabel
          Left = 407
          Top = 102
          Width = 17
          Height = 16
          Caption = 'GL'
        end
        object Label17: TLabel
          Left = 348
          Top = 11
          Width = 108
          Height = 16
          Caption = 'Needed to balance'
        end
        object TNUMSTR_1: TTASENTER
          Left = 153
          Top = 9
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 0
          Text = 'TNUMSTR_1'
          FieldName = 'TNUMSTR'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BKGL_GJ_TRANSDT_1: TTASDateEdit
          Left = 153
          Top = 32
          Width = 121
          Height = 21
          BlanksChar = '0'
          NumGlyphs = 2
          StartOfWeek = Sun
          TabOrder = 1
          FieldName = 'BKGL.GJ.TRANSDT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object BKGL_GJ_CVCODE_1: TTASENTER
          Left = 153
          Top = 55
          Width = 121
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 2
          Text = 'BKGL_GJ_CVCODE_1'
          FieldName = 'BKGL.GJ.CVCODE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BKGL_GJ_INVCHKN_1: TTASNumEnter
          Left = 153
          Top = 78
          Width = 121
          Height = 21
          AutoSize = False
          DisplayFormat = '0;-0'
          TabOrder = 3
          FieldName = 'BKGL.GJ.INVCHKN'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object EDIT_BANK_1: TTASENTER
          Left = 128
          Top = 100
          Width = 24
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 4
          Text = 'EDIT_BANK_1'
          FieldName = 'EDIT.BANK'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_BANKNAME_1: TTASENTER
          Left = 153
          Top = 100
          Width = 250
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 5
          Text = 'EDIT_BANKNAME_1'
          FieldName = 'EDIT.BANKNAME'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_BANKGL_1: TTASENTER
          Left = 429
          Top = 100
          Width = 191
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 8
          Text = 'EDIT_BANKGL_1'
          FieldName = 'EDIT.BANKGL'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object NEEDBAL_AMT: TTASNumEnter
          Left = 316
          Top = 32
          Width = 178
          Height = 21
          AutoSize = False
          TabOrder = 6
          FieldName = 'NEEDBAL.AMT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object NEEDBAL_TYPE: TTASENTER
          Left = 505
          Top = 32
          Width = 30
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 7
          Text = 'NEEDBAL_TYPE'
          FieldName = 'NEEDBAL.TYPE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
      end
    end
    object GLTranLID: TTabSheet
      Caption = 'Trans Line Item Details'
      Enabled = False
      object Panel9: TPanel
        Left = 0
        Top = 89
        Width = 626
        Height = 289
        Align = alClient
        BevelInner = bvLowered
        BevelOuter = bvLowered
        TabOrder = 1
        object Label21: TLabel
          Left = 123
          Top = 18
          Width = 121
          Height = 16
          Caption = 'GJ Transaction Code'
        end
        object Label22: TLabel
          Left = 123
          Top = 44
          Width = 134
          Height = 16
          Caption = 'Deposit/Check Number'
        end
        object Label23: TLabel
          Left = 123
          Top = 65
          Width = 81
          Height = 16
          Caption = 'Bank Account'
        end
        object Label24: TLabel
          Left = 123
          Top = 106
          Width = 102
          Height = 16
          Caption = 'Bank GL Account'
        end
        object Label25: TLabel
          Left = 123
          Top = 130
          Width = 108
          Height = 16
          Caption = 'Needed to balance'
        end
        object Label26: TLabel
          Left = 123
          Top = 152
          Width = 109
          Height = 16
          Caption = 'Default Description'
          Transparent = True
        end
        object Label27: TLabel
          Left = 123
          Top = 188
          Width = 68
          Height = 16
          Caption = 'GL Account'
        end
        object Label28: TLabel
          Left = 123
          Top = 212
          Width = 122
          Height = 16
          Caption = 'Line Item Description'
        end
        object Label29: TLabel
          Left = 123
          Top = 236
          Width = 100
          Height = 16
          Caption = 'Line item amount'
        end
        object Label31: TLabel
          Left = 123
          Top = 264
          Width = 69
          Height = 16
          Caption = 'Job Number'
        end
        object BKGL_GJ_CVCODE_2: TTASENTER
          Left = 276
          Top = 16
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 7
          Text = 'BKGL_GJ_CVCODE_2'
          FieldName = 'BKGL.GJ.CVCODE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          FldModified = True
        end
        object TICSTR: TTASENTER
          Left = 276
          Top = 38
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 8
          Text = 'TICSTR'
          FieldName = 'TICSTR'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_BANKNAME: TTASENTER
          Left = 276
          Top = 82
          Width = 330
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 10
          Text = 'EDIT_BANKNAME'
          FieldName = 'EDIT.BANKNAME'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_BANKGL: TTASENTER
          Left = 276
          Top = 104
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 11
          Text = 'EDIT_BANKGL'
          FieldName = 'EDIT.BANKGL'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_BANK: TTASENTER
          Left = 276
          Top = 60
          Width = 32
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 9
          Text = 'EDIT_BANK'
          FieldName = 'EDIT.BANK'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_NBAMT: TTASNumEnter
          Left = 276
          Top = 127
          Width = 178
          Height = 21
          TabStop = False
          AutoSize = False
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 12
          FieldName = 'EDIT.NBAMT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object EDIT_NBTYPE: TTASENTER
          Left = 460
          Top = 127
          Width = 30
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 13
          Text = 'EDIT_NBTYPE'
          FieldName = 'EDIT.NBTYPE'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          FldModified = True
        end
        object DFLT_DESC: TTASENTER
          Left = 276
          Top = 150
          Width = 330
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          TabOrder = 6
          Text = 'DFLT_DESC'
          FieldName = 'DFLT_DESC'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clBtnFace
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_ACCT: TTASComboEnter
          Left = 276
          Top = 186
          Width = 121
          Height = 21
          CharCase = ecUpperCase
          Glyph.Data = {
            36030000424D3603000000000000360000002800000010000000100000000100
            1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
            0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
            A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
            DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
            AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
            9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
            D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
            B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
            C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
            0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
            C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
            D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
            CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
            9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
            CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
            0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
            CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
            86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
            C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
            F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
            F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
            F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
          NumGlyphs = 1
          TabOrder = 0
          Text = 'EDIT_ACCT'
          FieldName = 'EDIT.ACCT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_glacct("A")'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|EDIT_ACCT.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_DESC: TTASENTER
          Left = 276
          Top = 210
          Width = 330
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 2
          Text = 'EDIT_DESC'
          FieldName = 'EDIT.DESC'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          FocusOnObject = 'EDIT_AMT'
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_DEPT: TTASENTER
          Left = 400
          Top = 186
          Width = 76
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 1
          Text = 'EDIT_DEPT'
          FieldName = 'EDIT.DEPT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_glacct("D")'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EDIT_DC: TTASComboBox
          Left = 483
          Top = 233
          Width = 121
          Height = 24
          CharCase = ecUpperCase
          ItemHeight = 0
          TabOrder = 4
          Text = 'EDIT_DC'
          Items.Strings = (
            'DEBIT'
            'CREDIT')
          FieldName = 'EDIT.DC'
          DropDownPrgLoc = -1
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = -1
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ItemNumber = 0
          ReturnIsTab = True
          KeyTraps = 'UPAR|EDIT_DC.CLICK|DNAR|EDIT_DC.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
        object EDIT_AMT: TTASNumEnter
          Left = 276
          Top = 234
          Width = 204
          Height = 21
          AutoSize = False
          TabOrder = 3
          FieldName = 'EDIT.AMT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_editamt()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          FastSearchType = fsNum
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          ButtonWidthNum = 0
          FldModified = False
          GlyphKind = gkCustom
          NumGlyphs = 2
          ButtonWidth = 0
        end
        object Edit_JOB: TTASENTER
          Left = 276
          Top = 262
          Width = 154
          Height = 21
          AutoSize = False
          CharCase = ecUpperCase
          TabOrder = 5
          Text = 'EDIT_JOB'
          FieldName = 'EDIT.JOB'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_edit_job()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          KeyTraps = 'F2|EDITJOB.CLICK'
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
      end
      object Panel10: TPanel
        Left = 0
        Top = 0
        Width = 626
        Height = 89
        Align = alTop
        BevelOuter = bvNone
        BorderStyle = bsSingle
        TabOrder = 0
        object Gradient3: TGradient
          Left = 0
          Top = 0
          Width = 622
          Height = 85
          Align = alClient
          Style = gsReflectedH
        end
        object Shape4: TShape
          Left = 0
          Top = 0
          Width = 622
          Height = 85
          Align = alClient
          Brush.Style = bsClear
          Pen.Mode = pmBlack
          Shape = stRoundRect
        end
        object Label18: TLabel
          Left = 123
          Top = 11
          Width = 116
          Height = 16
          Caption = 'Transaction Number'
          Transparent = True
        end
        object Label19: TLabel
          Left = 123
          Top = 34
          Width = 98
          Height = 16
          Caption = 'Transaction Type'
          Transparent = True
        end
        object Label20: TLabel
          Left = 123
          Top = 57
          Width = 98
          Height = 16
          Caption = 'Transaction Date'
          Transparent = True
        end
        object TNUMSTR_2: TTASENTER
          Left = 276
          Top = 9
          Width = 121
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 0
          Text = 'TNUMSTR_2'
          FieldName = 'TNUMSTR'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object TYPE_DESC2: TTASENTER
          Left = 276
          Top = 32
          Width = 330
          Height = 21
          TabStop = False
          AutoSize = False
          CharCase = ecUpperCase
          Color = clBtnFace
          ReadOnly = True
          TabOrder = 1
          Text = 'TYPE_DESC2'
          FieldName = 'TYPE.DESC2'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object BKGL_GJ_TRANSDT_2: TTASDateEdit
          Left = 276
          Top = 55
          Width = 121
          Height = 21
          TabStop = False
          BlanksChar = '0'
          Color = clBtnFace
          NumGlyphs = 2
          ReadOnly = True
          StartOfWeek = Sun
          TabOrder = 2
          FieldName = 'BKGL.GJ.TRANSDT'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = False
          ValidUserEsc = False
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = False
        end
      end
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 438
    Width = 634
    Height = 55
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 0
    object btnExit: TGlyphBtn
      Left = 547
      Top = 28
      Width = 85
      Height = 25
      Caption = 'E&xit'
      TabOrder = 12
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnAdd: TGlyphBtn
      Left = 3
      Top = 3
      Width = 85
      Height = 25
      Caption = '&Add'
      TabOrder = 8
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7ABB0AB6D8368426A3932
        60273B6435576E567D837DB5B5B5F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F7608C5F198211158B00158B001D8B002C7A002C6F042868154864488F8F
        8FF0F3F7F0F3F7F0F3F7F0F3F7F0F3F7429143029C0202A00402A004029C0202
        97000994011C85013773002C6F04355D338F8F8FF0F3F7F0F3F7F0F3F767A068
        08A9130AA40D019C091AB12575E59385EAA46AE38B08A9130788003773002C6F
        04486448F0F3F7F0F3F7C0CEC01DAD2412AA230AA118019C09279D22E6EFE3FF
        FFFFCBF4D600A80E0788000788003773002868157D837DF0F3F779B77B28B63C
        18B12D0CBB2D02BB2616A527D8E9D8FFFFFFB4F0C500B81500A80E0BAB192385
        012C6F04576E56F0F3F74EAC5440C75B039B188ACD97BBE8CBB8E1C4EAEDEAF8
        F4F7E4F6EAB4F0C5CBF4D66AE38B0994012C7A003B6435F0F3F742AD4A51D374
        039B18BFCABCFFEAFDF9EEF8ECECECF0F0F0FAF4F9FFFBFFFFFBFF85EAA4029C
        02238501326027F0F3F74EAC5467DF8C09A022A4C0A1DCDDDADFDFDEEAE9EAEC
        ECECEAE9EAD8E9D8DDEDDD7AE89802A0041D8B00426A39F0F3F775C77972DB91
        34BF5824AA3C24AA3C3C9E3DD8DCD8F9EEF8B0DCBA24A22524A2251CB52905A2
        09158B006C8467F0F3F7B6CCB65BD77272E19C25CA5D19C64F24AA3CDCDBD9FF
        EAFDB1E5C202BB2605A11205A1120AA40D198211ABB0ABF0F3F7F0F3F765CB6C
        80E0A45EDB8C25CA5D25AB419FBF9BBFCABC8ACD9716BA3712AA230BAB190AA4
        0D638E61F0F3F7F0F3F7F0F3F7F0F3F753BC607FE0A16CE09B37C75E0DA42B03
        9B1809A02216BA3718B12D0BAB19429143F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
        F0F3F765CB6C5DDA7772E19C63E2914AD67637C75E28B63C1AB12567A068F0F3
        F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7B6CCB675C7794FB25842
        AD4A4EAC5479B77BC0CEC0F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      GlyphKind = bkCustom
    end
    object btnCopy: TGlyphBtn
      Left = 173
      Top = 28
      Width = 85
      Height = 26
      Caption = '&Copy'
      TabOrder = 10
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFBA
        6E47AA5429AA5429A250279B4C259648238F46228A4321864120FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFC17955FDF9F6CEB09CCCAF9BCAAD9AC7AC
        99C6AB98C4A997894321FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFC9
        8564FFFFFFDA8C5CD18351D18351D18351D18351C6AB988E4522FEFEFFB7A293
        634935634935634935634935634935D19273FFFFFFFEFDFBFBEFEAF5DED3F0CE
        BEEDC3AFC7AC99924723FEFEFFB7A293F8F3F0EADFD7E6D9CFE1D2C7DDCBBFD8
        9F82FFFFFFF3A77FE7976EDA8C5CD18351D18351CAAE9A984A25FEFEFFB7A293
        FBF8F7E5AE81DEA173DA9C6ED59768E0AA90FFFFFFFFFFFFFFFFFFFBF4F0F7E4
        DBF2D3C5CCAE9A9D4D25FEFEFFBBA697FEFDFCFBF6F5F6EFEBF1E6E0ECDED6E7
        B59CFFFFFFFCAE8AFCAE8AF1DBD2E78E60B3572AAC5429A45027FEFEFFC1AB9C
        FFFFFFFAC59FF0B88EE5AE81DEA173ECBDA6FFFFFFFFFFFFFFFFFFFFFFFFEA9A
        72F0C9B2B1572BB9A49AFEFEFFC7B2A3FFFFFFFFFFFFFCFAF9F8F2F0F3EAE6F0
        C4AEFFFFFFFFFFFFFFFFFFFFFFFFEBA785C56535C0AA9FFEFEFFFEFEFFCFB9A9
        FFFFFFFFDABAFFD0AEF0DED2B7A293F0C4AEEFC2ABEFC1AAEFB9A0EDB092EDB0
        92CAB6ABFEFEFFFEFEFFFEFEFFD4BEAFFFFFFFFFFFFFFFFFFFFEFDFCBBA696D4
        C5BA8F725BB2ADA9FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFD8C2B2
        FFFFFFFFFFFFFFFFFFFFFFFFC7B1A2A58266B4AFACFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFD8C2B2D8C2B2D4BFAED4BFAECEB8A9C8B2A3C2
        BCB7FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF}
      GlyphKind = bkCustom
    end
    object btnEdit: TGlyphBtn
      Left = 88
      Top = 3
      Width = 85
      Height = 25
      Caption = '&Edit'
      TabOrder = 9
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF75716E57
        5451000000919698FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFA39D98FDFEFE5193A90E1216939C9FFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFB7A29363493563493563493563493586796EA39D9888
        B7C774CEE2499AB20E1216777570634935634935634935FEFEFFB7A293FDFBF9
        E1DCD8E0D7D2DFD2CADFCEC3C3BDB84D9CB38CE0EE62BFD7499AB20E1216B3A6
        9BCFB4A3634935FEFEFFB7A293FEFEFED2B9ABCFB4A6CDAFA0FBECE3C2A79AAC
        A4A057A0B58CE0EE62BFD7499AB20E1216AAA198634935FEFEFFB7A293FEFEFE
        FEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD7D0C965A6B78CE0EE62BFD7499A
        B20E12166F6A63FEFEFFB7A293FEFEFED6C1B5D4BDB1D2B9ABFDF7F3CDAFA0CA
        AA9AC7A594D7D0C973ACB98CE0EE6CC4D97D86863535908D90A6BAA596FEFEFE
        FEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD7D0C97DB0BBCAB8
        AC7385D15E6CAD353590BEA99AFEFEFEDAC8BDD8C5BAD6C1B5FEFEFED2B9ABCF
        B4A6CDAFA0FBECE3C7A594AFA7A35E6CAD708FDF5E76D05E6CADC3AE9EFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD0C9
        D45E6CAD5E6CADAEB2BEC8B2A3FEFEFEDBCAC0DBCAC0DAC8BDFEFEFED6C1B5D4
        BDB1D2B9ABFDF7F3CDAFA0CAAA9AC8AFA2D1C1B6857568FEFEFFCCB6A7FEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFCF2
        ECFBECE3634935FEFEFFEAAA8BEAAA8BEAAA8BE9A584E99F7AE7976EE68E62E5
        8656E37D4AE37640E27239E27239E27239E27239C8622FFEFEFFEAAA8BFFC2A2
        FEC09FFDBD9AFCB996FBB590FAB08BF9AB84F8A77DF6A277F59D71F5996AF395
        65F39565CD6531FEFEFFEAAA8BEAAA8BEAAA8BEAAA8BEAA686E9A17FE89B76E7
        946CE68E62E58758E4814EE47B46E3763EE3763EE27239FEFEFF}
      GlyphKind = bkCustom
    end
    object btnDelete: TGlyphBtn
      Left = 173
      Top = 3
      Width = 85
      Height = 25
      Caption = '&Delete'
      TabOrder = 11
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
        F8F8F80000000000005A5A5A5A5A5A525252525252292929000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8212121949494FFFFFFCECECEDEDEDE94
        8C8CA5A5A56B6B6B636363393929000000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252B5ADADEFEFEF949494C6BDBD9494949494945252526B6B6B5A5A5A2121
        10F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEF949494C6BDBD9494949494944242426B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8525252949494EFEFEF949494C6BDBD94
        94949494944242426B6B6B292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        525252949494EFEFEFA5A5A5C6C6C69494949C9C9C4A4A4A6B6B6B2929292929
        29F8F8F8F8F8F8F8F8F8F8F8F8F8F8F85252529C9C9CD6D6D6C6BDBD9C9C9C94
        94946B6B6B6B6B6B737373292929292929F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
        393929949494C6BDBDCECECEC6BDBDA5A5A5A5A5A5A5A5A56B6B6B4A4A4A1010
        10F8F8F8F8F8F8F8F8F8F8F8F8000000A5A594DEDEDEC6C6C6BDB5B5BDBDBDBD
        BDBD8C8C8C8484846B6B6B6363635A5A5A000000F8F8F8F8F8F8F8F8F8000000
        737352D6CECEFFFFFFE7E7E7CECECEC6C6C6293939525252C6C6C69C94947B7B
        7B000000F8F8F8F8F8F8F8F8F80000005A5A5AADA5A5EFEFEFDEDEDE4A5A4A42
        5263848473525252B5B5B57B7B7B4A4A4A000000F8F8F8F8F8F8F8F8F8F8F8F8
        F8F8F80000000000003939392121217B7B6B314242000000000000000000F8F8
        F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F800
        0000F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
      GlyphKind = bkCustom
    end
    object btnNotes: TGlyphBtn
      Left = 547
      Top = 3
      Width = 85
      Height = 25
      Caption = '&Notes'
      TabOrder = 5
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF75716E57
        5451000000919698FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFA39D98FDFEFE5193A90E1216939C9FFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFB7A29363493563493563493563493586796EA39D9888
        B7C774CEE2499AB20E1216777570634935634935634935FEFEFFB7A293FDFBF9
        E1DCD8E0D7D2DFD2CADFCEC3C3BDB84D9CB38CE0EE62BFD7499AB20E1216B3A6
        9BCFB4A3634935FEFEFFB7A293FEFEFED2B9ABCFB4A6CDAFA0FBECE3C2A79AAC
        A4A057A0B58CE0EE62BFD7499AB20E1216AAA198634935FEFEFFB7A293FEFEFE
        FEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD7D0C965A6B78CE0EE62BFD7499A
        B20E12166F6A63FEFEFFB7A293FEFEFED6C1B5D4BDB1D2B9ABFDF7F3CDAFA0CA
        AA9AC7A594D7D0C973ACB98CE0EE6CC4D97D86863535908D90A6BAA596FEFEFE
        FEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD7D0C97DB0BBCAB8
        AC7385D15E6CAD353590BEA99AFEFEFEDAC8BDD8C5BAD6C1B5FEFEFED2B9ABCF
        B4A6CDAFA0FBECE3C7A594AFA7A35E6CAD708FDF5E76D05E6CADC3AE9EFEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFBECE3FAE7DBD0C9
        D45E6CAD5E6CADAEB2BEC8B2A3FEFEFEDBCAC0DBCAC0DAC8BDFEFEFED6C1B5D4
        BDB1D2B9ABFDF7F3CDAFA0CAAA9AC8AFA2D1C1B6857568FEFEFFCCB6A7FEFEFE
        FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFDFBF9FDF7F3FCF2ECFCF2
        ECFBECE3634935FEFEFFEAAA8BEAAA8BEAAA8BE9A584E99F7AE7976EE68E62E5
        8656E37D4AE37640E27239E27239E27239E27239C8622FFEFEFFEAAA8BFFC2A2
        FEC09FFDBD9AFCB996FBB590FAB08BF9AB84F8A77DF6A277F59D71F5996AF395
        65F39565CD6531FEFEFFEAAA8BEAAA8BEAAA8BEAAA8BEAA686E9A17FE89B76E7
        946CE68E62E58758E4814EE47B46E3763EE3763EE27239FEFEFF}
      GlyphKind = bkCustom
    end
    object btnReverse: TGlyphBtn
      Left = 258
      Top = 3
      Width = 85
      Height = 25
      Caption = '&Reverse'
      TabOrder = 6
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF999999
        999999999999999999999999999999999999999999999999999999FEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFF999999FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFFCCCCCCFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF999999
        FFFFFFFFFFFFFFFFFFFFFFFF5CB27A26984D26984D26984DCCCCCC0026BFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFF999999FFFFFFFFFFFFFFFFFFFFFFFF66D88D33
        CC6626984DFFFFFF4066FF0033FF0026BFFEFEFF0026BFFEFEFFFEFEFF999999
        FFFFFFFFFFFFFFFFFFFFFFFF66D88D66D88D33CC6626984DCCCCCC4066FF0033
        FF0026BF0026BFFEFEFFFEFEFF999999FFFFFFF7F7F7F7F7F7F7F7F766D88DFF
        FFFF66D88D33CC6626984DFFFFFF4066FF0033FF0026BFFEFEFFFEFEFF999999
        F7F7F7F7F7F7EFEFEFF7F7F7F7F7F7F7F7F7F7F7F766D88DCCCCCC4066FF4066
        FF4066FF405CCFFEFEFFFEFEFF999999EFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE6
        E6E6EFEFEFEFEFEFCCCCCCFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF999999
        EFEFEFE6E6E6E6E6E6E6E6E6E6E6E6999999999999999999999999FEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFF999999E6E6E6E6E6E6E6E6E6E6E6E6DFDFDF99
        9999FFFFFFFFFFFF999999FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF999999
        DFDFDFDFDFDFDFDFDFDFDFDF999999FFFFFFFFFFFF999999FEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFF99999999999999999999999999999999999999
        9999999999FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF}
      GlyphKind = bkCustom
    end
    object btnPrint: TGlyphBtn
      Left = 3
      Top = 29
      Width = 85
      Height = 25
      Caption = '&Print'
      TabOrder = 7
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
        99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
        ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
        666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
        A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
        8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
        EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
        BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
        E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
        E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
        CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
        F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
        C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
        CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
        C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
        DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
        EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
        B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
      GlyphKind = bkCustom
    end
    object btnPost: TGlyphBtn
      Left = 462
      Top = 28
      Width = 85
      Height = 25
      Caption = 'Post'
      TabOrder = 3
      GlyphKind = bkCustom
    end
    object btnTag: TGlyphBtn
      Left = 462
      Top = 3
      Width = 85
      Height = 25
      Caption = '&Tag'
      TabOrder = 2
      GlyphKind = bkCustom
    end
    object btnPostTag: TGlyphBtn
      Left = 377
      Top = 28
      Width = 85
      Height = 25
      Caption = 'Post Tag'
      TabOrder = 4
      GlyphKind = bkCustom
    end
    object btnTemplates: TGlyphBtn
      Left = 377
      Top = 3
      Width = 85
      Height = 25
      Caption = 'Template&s'
      TabOrder = 1
      GlyphKind = bkCustom
    end
    object btnPRTTAG: TGlyphBtn
      Left = 88
      Top = 29
      Width = 85
      Height = 25
      Caption = '&Pt Tag'
      TabOrder = 13
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFF6762635856543938384E494A605858948F8E4846469999
        99FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF9D9B9B757373E1E0E0CFCFCFAF
        ABAB9693937E7776999494D9D9D9CCCACA585253737371FFFEFFFFFEFFFFFEFF
        666563D7D6D6F2F2F2ECECECCBC8C8B0ACAC9795956261606667648B8585AAA9
        A9D3D3D3D1D0D0919191FFFEFFA2A1A1F4F4F4F3F3F3ECECECCDCBCB7B817B8D
        8989ADA9A9B6B1B1B0ACADA6A1A2858484615F5F716D6D919191FFFEFFA4A2A2
        EEEEEEC9C7C7999798BEBDBDBFBCBC9A9898908F8F8584848E8C8CB1ADAEBDBD
        BD769982767373919191FFFEFF858080ABA7A8C7C6C7DCDBDBD4D4D4E5E5E5E0
        E0E0D5D4D4C2C1C1ADA9A99B98979291915C7864696A66919191FFFEFF898181
        E3E3E3DCDCDCD4D4D4DDDDDDCDCDCDD6D5D5D3D2D2CCCBCBD1D0D1D6D7D7CECC
        CCBFBEBE7A7978919191FFFEFFC8C7C8D7D6D6D4D4D4D6D6D6BEBDBDE2E2E2F0
        F0F0EEEEEEEAEAEAE0E0E0CFCCCCCBCBCBC9C8C87A7B79FFFEFFFFFEFFFFFEFF
        C2BFC0A2A1A1C0BFBFBDB9B99E9C9CACAAAABAB9B9C6C6C6CFCFCFE4E4E4CECB
        CBACA8A8FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFABAAABE1DEDEEDDCD0D9CCC2CD
        C8C6CFCFCFD0D1D1C1C0C09F9C9CC2C0C0FFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFD0AEA3FDD3B4FDD2B3FDD2B3FDD2B3F5D1B7A9A9A9FFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFE3C9B3FDDEC2FDDEC2FD
        DEC2FDDEC2E3C3B29F9F9DFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFC4ACABF0DDCCFDE7D2FDE7D2FDE7D2FDE7D2C4B2A5FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFA19A9AFEEFE1FEEFE1FEEFE1FE
        EFE1FEEFE1A69D9CFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FAF8F9E8E2DCFDF9F1FDF9F1FDF9F1FDF9F1F0EDE9BFB6B6FFFEFFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFC7BFBEBFB6B5BFB6B5BFB6B5BFB6B5BF
        B6B5D9D6D6FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF}
      GlyphKind = bkCustom
    end
    object btnSave: TGlyphBtn
      Left = 462
      Top = 28
      Width = 85
      Height = 25
      Caption = '&Save'
      TabOrder = 0
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object btnMain: TGlyphBtn
      Left = 548
      Top = 28
      Width = 85
      Height = 25
      Caption = '&Main Scn'
      TabOrder = 14
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnLines: TGlyphBtn
      Left = 461
      Top = 29
      Width = 85
      Height = 24
      Caption = '&Lines'
      TabOrder = 15
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFFFEFFFFFE
        FFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFF
        FEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE8C7F833D42433345434A
        605D496C3B78615B55004BF6F200FC9A006100143853555E4364FFFFFEFFFFFE
        FFFFFEFFFFFE7A7276C9CACCD9DADCC1BEC1DCBBA7EB213FF1F21CC9AF008E00
        239AB0899FB7BD43526BFFFFFEFFFFFEFFFFFEFFFFFE576564FDFCFDFFF4FAFF
        F0FAFF3551E6FB00FF871D6400006F9295DFB9E7D9E1E5295523FFFFFEFFFFFE
        FFFFFEFFFFFE69807BEAEBE8E8C2C58F4B54BE8000FF941F41060066666EA08C
        85EEF8F3C1BDCE7A5354FFFFFEFFFFFEDAD9D7BEBFBD0009012D30299D8E8AFF
        F3F2965C606E140098955EBDE4E4DDE1E2FFFEFFE1D1DB4F344AFFFFFE918E87
        FEE7E2D8BEB9FFF7F0E2E6DC29362B7C8A7F47000966586AAB8C938683B05494
        94FFF4FDD9B4D4276E48AFA9A6ECF4D0F5F9E7C8B6CBFFEFE99F9666A1988127
        15368F8F91E2E8E9DDEAEAC7D9D8DCEDECE7F0F1C5C5C7615B5E675F5EEEF6D6
        F9FDEEC7B2D3FCF4C6E2FF35D1FF3A180D0F6565687076778B97978091916777
        76F8FFFFD1D1D3413B3E7F7681FCFFEAE5EBD9C4BEB0FFF3D9A7839698759739
        371288898BEAEFF1E5EFF0D4E3E3E1EEEFC0C7C8D7D6D95C575A76776EDEE3DA
        E4ECDBCAC0C2FFFCD0D7F93BD8FF401D14026567697E8385848D8EE3EEEEDBE4
        E5CACFD0C5C5C74E4A4DFFFFFE758560F9FFF7C9C0C7F4EACEF7DFDD35173898
        9389CCD0D1E5EAECCDD3D4EDF4F5565C5D484A4C49484B575457FFFFFEFFFFFE
        5E685E777D671907173B292E9C978DC6BDDFCBCFD1FBFFFFFAFFFFF8FBFD8E90
        92FEFEFFC9C8CA4F4D50FFFFFEFFFFFEFFFFFEFFFFFE7F816AE8EBD0D1D3D5F2
        FFFFFAFFFFFCFFFFF2F4F6F2F3F58D8D8FC2C1C3B6B6B7FFFFFEFFFFFEFFFFFE
        FFFFFEFFFFFE7574736D66786A727C5E7572696F7164686A7577797272747472
        74BDBCBDFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFF
        FFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
    object btnBack: TGlyphBtn
      Left = 376
      Top = 28
      Width = 85
      Height = 25
      Caption = '&Back'
      TabOrder = 16
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
        C8D0D4C8D0D4D3D9DCDDE2E4E7EAECEDF0F1EDF0F1E7EAECDDE2E4D3D9DCC8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CCD4D7DCE1E3D3E0D677AE7929872900
        780000780029872977AE79D3E0D6DCE1E3CCD4D7C8D0D4C8D0D4C8D0D4CBD3D6
        DDE2E49EC2A10078001BA42034CE4048EC5A4DEE6240D35427A7330078009EC2
        A1DDE2E4CBD3D6C8D0D4C8D0D4D8DDE09CC19F057E0633D33C41E44F41D14B43
        CF4E43CC5036BB4553E56F51DE6D0A7F0D9CC19FD8DDE0C8D0D4CED4D8CAD8CF
        00780033D33C3ED8493EC44542C54A37B63E228B23ADCEAD1A91205EE97A5AE1
        7A007800CAD8CFCED4D8D3D9DC6FA7721AA31F40E34D3EC3433FC1461A921E80
        B580F2F7F2FFFFFF1B912057DC696EF69433AB466FA772D3D9DCD5DADC248425
        33CE3E3FD04927A32B439843C9DEC9FFFFFFFFFFFFFFFFFF1D93235CE17066EA
        835FDD82248425D5DADCD4D8DB00780045EB5729AD3180B580FFFFFFFFFFFFFF
        FFFFFFFFFFFFFFFF1F952763E87A69EC857FFDAD007800D4D8DBCFD4D6007800
        4AED5F2BAE3580B580FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2298296AF0836FF1
        8D85FDB5007800CFD4D6C9CFD21F82203ED25049D6592DA833318F33C9DEC9FF
        FFFFFFFFFFFFFFFF239A2D70F78D78F79A6CDE931F8220C9CFD2C5CCCF5F9C62
        24A73057EE724BCF574CCF5A20982771AD71F2F7F2FFFFFF249A2E73FA908BFD
        BA3EAD54529655C5CCCFC4CCD0ABBCB30078004DDD695AE77551D66157DB6849
        C959258F29ADCEAD259A3084FCAE79E7A3007800ABBCB3C4CCD0C8D0D4C0C7CA
        79A47F087F0D56E07669F48E61E67B63E77D64E57F52C96D7CEEA977E7A20D80
        1379A47FC0C7CAC8D0D4C8D0D4C5CDD1BBC2C674A27B00780030AB435BDC7E7A
        FDA980FDB070E69A3DAD5300780074A27BBBC2C6C5CDD1C8D0D4C8D0D4C8D0D4
        C4CCD0BAC1C59CB0A54490481780190078000078001780194F93539CB0A5BAC1
        C5C4CCD0C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C0C7CBB7BEC2B0B7BBAB
        B2B6ABB2B6B0B7BBB7BEC2C0C7CBC8D0D4C8D0D4C8D0D4C8D0D4}
      GlyphKind = bkCustom
    end
    object btnDfltDESC: TGlyphBtn
      Left = 3
      Top = 29
      Width = 85
      Height = 25
      Caption = 'D&flt Desc'
      TabOrder = 17
      Visible = False
      GlyphKind = bkCustom
    end
    object btnViewAllLines: TGlyphBtn
      Left = 422
      Top = 3
      Width = 124
      Height = 24
      Caption = 'View All Lines'
      TabOrder = 18
      TabStop = False
      Visible = False
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        18000000000000030000000000000000000000000000000000004B4B4B000000
        0000000000000000000000000000000000000000000000000000000000000000
        00000000000000000000888888E6F1F2CECECECFCFCFCFCFCFCECECECFCFCFCE
        CECECFCFCFCFCFCFCFCFCFCFCFCFCFCFCFCECECE898989000000898989FFFFFF
        E6F1F2E6F1F2E6F1F1E6F1F2E6F1F1E6F1F1E6F1F2E6F2F2E6F1F1E6F1F1E6F1
        F1E6F1F1CFCFCF000000898989FFFFFFE6F1F1E6F1F1E6F1F2E6F1F1E6F1F2E6
        F1F2E6F1F2E6F1F1E6F1F1E7F2F2E6F1F1E6F1F2CFCFCF000000888888FFFFFF
        E7F2F2CFCFCFE6F1F1CFCFCFE6F1F1CFCFCFCECECECFCFCFCECECECECECECECE
        CEE6F1F2CFCFCF000000898989FFFFFFE6F1F2CFCFCFCFCFCFCECECECECECEE6
        F1F1E6F2F2E6F1F2E6F1F1E6F1F1E6F1F1E6F1F2CFCFCF000000898989E6F1F2
        CFCFCF8989894C4C4C4C4C4CB4858A898989CFCFCFCFCFCFCFCFCFCECECECECE
        CEE6F1F2CFCFCF000000898989000000F8B3B8E6F1F2E6F1F1E6F1F1CFCFCFB3
        8589000000CFCFCFE6F1F1E6F1F2E6F1F1E6F1F2CFCFCF000000CFCFCFFFFFFF
        FFFFFFD6A833AE3E2AAE3E2AD6A833CFCFCFCFCFCF4C4C4CCFCFCFCFCFCFCFCF
        CFE6F1F1CFCFCF000000FFFFFFFFFFFFF8B4B8D6A833AE3F2AAE3F2AAE3E2AD6
        A833CFCFCFF8B4B84C4C4CCFCFCFE6F1F1E6F1F1CECECE000000CECECEFFFFFF
        AE3E2AFFFFFFFFFFFFAE3E2AAF3F2BAE3E2ACFCFCFF8B4B84B4B4BCECECECFCF
        CFE6F2F2CFCFCF000000000000FFFFFFD6A833AE3E2AFFFFFFD6A833AE3E2AD6
        A833F8B3B84C4C4CCFCFCFCFCFCFE6F1F1E6F1F2CFCFCF000000898989000000
        000000AE3E2AAE3F2BAE3E2AAE3E2A000000000000B4858AB38589AE3E2AAE3E
        2AAE3F2AAE3E2A000000898989F8B3B8B385894C4C4C0000000000004C4C4CB3
        8589F8B3B8898989000000D6A833D5A733D6A833D6A833000000898989000000
        4C4C4CCECECECECECECFCFCFCFCFCF8989894B4B4B4C4C4C8989898989898989
        898989898989894C4C4CFFFFFEFFFFFECECECE8989894C4C4C0000004C4C4C88
        8888CFCFCFFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFEFFFFFE}
      GlyphKind = bkCustom
    end
  end
  object ToolBar1: TToolBar
    Left = 0
    Top = 0
    Width = 634
    Height = 29
    ButtonHeight = 24
    Caption = 'ToolBar1'
    EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
    EdgeInner = esLowered
    TabOrder = 1
    Transparent = True
    object CLEAR: TSpeedButton
      Left = 0
      Top = 0
      Width = 23
      Height = 24
      Hint = 'Clear Data'
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4000000
        000000000000000000C8D0D4000000000000000000C8D0D4C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D400000000000000000000000000000000000000000000
        0000C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000
        C8D0D4C8D0D4000000000000000000C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D4000000000000C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4C8D0D4000000000000C8D0D4000000000000C8D0D4C8D0D4C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D400
        0000000080000080000000C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4000000C8D0D40000000000FF0000FF0000FF000080000000C8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4C8D0D4C8D0D400000000
        00FF0000FF0000FF0000FF000080000000C8D0D4C8D0D4C8D0D4C8D0D4000000
        000000C8D0D4000000C8D0D4C8D0D40000000000FF0000FF0000FF0000000080
        80000000C8D0D4C8D0D4C8D0D4C8D0D4000000000000C8D0D4000000C8D0D4C8
        D0D40000000000FF00000000FFFF000000008080000000C8D0D4C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00000000FF
        FF000000008080000000C8D0D4C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D400000000FFFF00000000FFFF008080008080C8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FF
        FF00FFFF00FFFF008080C8D0D4C8D0D4C8D0D4000000C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF00FFFF00FFFFC8D0D4C8D0D4
        C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0
        D400000000FFFF00FFFFC8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8
        D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D400000000FFFF}
      ParentShowHint = False
      ShowHint = True
    end
  end
  object EvoToolBar: TToolBar
    Left = 514
    Top = 3
    Width = 116
    Height = 25
    Align = alCustom
    Anchors = [akTop, akRight]
    EdgeBorders = []
    Images = EvoToobarImages
    TabOrder = 3
    Transparent = False
    Visible = False
    object ETB5: TToolButton
      Left = 0
      Top = 0
      Caption = 'ETB5'
      Visible = False
    end
    object ETB4: TToolButton
      Left = 23
      Top = 0
      Caption = 'ETB4'
      Visible = False
    end
    object ETB3: TToolButton
      Left = 46
      Top = 0
      Caption = 'ETB3'
      Visible = False
    end
    object ETB2: TToolButton
      Left = 69
      Top = 0
      Caption = 'ETB2'
      Visible = False
    end
    object ETB1: TToolButton
      Left = 92
      Top = 0
      Caption = 'ETB1'
      Visible = False
    end
  end
  object ETBcombo: TTASComboBox
    Left = 414
    Top = 1
    Width = 168
    Height = 24
    Style = csDropDownList
    ItemHeight = 16
    TabOrder = 2
    Visible = False
    FieldName = 'ETBcomboval'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 237
    Top = 65517
  end
  object EvoToobarImages: TImageList
    Left = 424
    Top = 65524
    Bitmap = {
      494C0101060009007C0010001000FFFFFFFFFF10FFFFFFFFFFFFFFFF424D3600
      0000000000003600000028000000400000002000000001002000000000000020
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000007373730073737300737373000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000CE944200CE8C3100D69C
      5200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000073737300BD632900AD6B42006B524A007373730000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000DEA55200BD843900000000000000
      0000D69C5200B57B39006B5231006B5231006B5231006B5231006B5231000000
      000000000000000000000000000000000000000000007373730073737300BD63
      2900EF7B0800FF732100FF940800FFAD310094634A007373730073737300B57B
      5A00737373007373730073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFAD4200AD7B4200000000000000
      00006B523100C67B3100DE943900EFAD4200F7B55200DEB56300EFAD42006B52
      31006B5231000000000000000000000000008452520084525200E79C5A00EF84
      1000D6846300FFAD3100FF8C0800FFA51000FFBD6300AD7B6B0084525200FF94
      0000845252008452520073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFB54A00AD7B4200000000006B52
      3100E79C3100F79C3900EF943100EF9C3100F7A53900F7BD5200FFD67300EFCE
      8C00B57B39006B523100000000000000000094634A00F7F7E700F7F7E700F7F7
      E700FFF7E700F7DEAD00F7941800FF940000FFAD3100FFC68400FFBD5A00FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000E7AD6300DE9C29006B523100F7A5
      3100EF9C3100E7942900E79429007352310073523100B5732900F7B54200FFD6
      6B00F7D69400B57B3900000000000000000094636300FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00F7DEAD00FF9C0800FF9C0800FFBD5A00FFC68400FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000F7B53900F7AD3100EFA5
      2900E7942900DE8C290084522900000000000000000000000000B5732900F7AD
      3900FFD66B00DEB57B00B57B390000000000A56B6B00FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00F7941800FFAD2900FF940000FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000E7B56300F7B53100EFA5
      2900E7942100A56318006B5231006B5231006B5231006B5231006B5231006B52
      31006B5231006B5231006B52310000000000AD7B6B00FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FF5A3100EF6B4200EF523100EF6B4200FF5A
      3100FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F7BD3900EFAD
      2900E79C2100D67B2900D67B2900D67B2900D67B2900D67B2900D67B2900D67B
      2900D67B2900D67B2900B57B390000000000B58C7300FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00CECECE00D6D6D600F7EFDE00F7E7
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000F7C6
      4200EFAD2900E79C2100DE942100E7942900E7942900E7942900E7942900EF94
      3100F79C3900EFA54200B57B390000000000B58C7300FFFFFF00FF5A3100EF6B
      4200E7522900C6734200C68C7B00FFFFFF00FFFFFF00FFFFFF00294A84007394
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000EFCE940000000000F7C6
      4200F7C64200BD8429006B4A21000000000000000000B5732900CE8C3100EF94
      2900EF9C3100EF9C3100B57B390000000000C6947B00FFFFFF00FF8C0800FF8C
      0800FF5A3100AD4A1800FFF7EF00FFFFFF00FFFFFF00FFFFFF007394D6007394
      D600FFFFF700AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000EFCE94000000
      0000F7C64200E7AD39006B5229005A42290073523100B5732900E79C2900E794
      2900F7A53900B57B39000000000000000000D6A58400FFFFFF00FF8C0800FFBD
      5A00FFAD2900F7941800BD632900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
      FF00FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000D6BD8C00E7CE
      8C0000000000F7DE8C00E7B53900B5842100CE8C2100E7A52900E79C2100EFA5
      2900EFA53900B57B39000000000000000000DEAD8400DEAD8400FF8C0800DEAD
      8400F7A55A00FFC68400EF943900BD632900C69C9400C69C9400C69C9400C69C
      9400C69C9400AD7B7B0000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000D6BD
      8C00D6BD8C00E7D66300E7D66300F7D64200F7B53100EFAD2900EFAD2900EFA5
      3100B57B390000000000EFAD4200000000000000000000000000FF8C08000000
      000000000000F7A55A00FFDEAD00EFB58C00BD632900BD523900C6734200A563
      4200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000D6BD8C00D6BD8C00D6BD8C00DEB55200FFCE4A00B57B3900B57B
      39000000000000000000EFAD4200000000000000000000000000000000000000
      00000000000000000000F7A55A00FFEFBD00FFE7AD00DE8C5200944A18000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000AD9A880046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000AD9A8800CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000212121004242
      3900424239004242390042423900424239004242390042423900424239004242
      3900424239004242390042423900000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000AD9A
      8800FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B7B00F7F7
      FF00F7F7FF00F7F7FF00BDBDBD00F7F7FF00F7F7FF00003939005A5A5A00F7EF
      E700F7F7FF00F7F7FF0042423900000000000000000046403800464038004640
      380046403800464038004640380046403800464038004640380046403800FFE8
      D400FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000027596100000000000000000027596100000000000000
      00000000000000000000000000000000000000000000000000005A5A5A00BDBD
      BD00BDBDBD00BDBDBD009C9C9400BDBDBD00BDBDBD005A5A5A0042BDBD005252
      4A00BDBDBD00BDBDBD004242390000000000AD9A8800FFE5CE00CAB39E00CAB3
      9E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00FFE8D400FFEB
      D900FFEBD900FFEBD900BBA69200464038008080000080800000800000008000
      0000800000008000000080000000800000008000000080000000800000008000
      0000800000008000000080000000000000000000000027596100000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000275961000000000000000000000000005A5A5A00DED6
      D600DED6D600DED6D600ADADAD00DED6D600DED6D600F7F7FF005A5A5A005ADE
      DE0052524A00F7EFE7004242390000000000AD9A8800FFEDDD00FFE3C900FFE3
      C900FFE3C900FFE3C9008B7C6D0000000000EDD2B900FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BBA692004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      6100000000000000000080808000808080008080800080808000000000000000
      0000275961002759610000000000000000000000000000000000393900003939
      00003939000039390000393900003939000052523100ADADAD009C9C94005A5A
      5A005ADEDE0052524A002121210000000000AD9A8800FFF1E400FFE3C900FFE3
      C900FFE3C900FFE3C900F2D6BD00ECD1B800FFE5CE00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BFAA96004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF00FFFF
      FF00C8D0D4000000000080000000000000000000000000000000275961002759
      6100000000008080800091919100838383008080800080808000808080000000
      0000275961002759610000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000DED6D600BDBDBD00F7F7
      FF007B7B7B006BADAD004242390000000000AD9A8800FFF4EA00FDE0C600FFE3
      C900FFE3C900FFE3C9008B7C6D0076695C00DCC3AD00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400C4AE99004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      61000000000080808000AAAAAA00919191008383830080808000808080000000
      00002759610027596100000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD005A5A5A005ADEDE0021212100AD9A8800FFF7F000FADEC400FADE
      C400FFE3C900FFE3C900DCC3AD00655A4E006F635700F4D8BF00FFE8D400FFE8
      D400FFE8D400FFE8D400CAB39E004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF000000
      0000FFFFFF0000000000800000000000000000000000000000002E6770002E67
      70000000000080808000AAAAAA00AAAAAA009191910080808000808080000000
      00002E6770002E67700000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF00393939005A9C9C00AD9A8800FFF9F300FADEC400FADE
      C400FADEC400FFE3C900FFE3C900DCC3AD00524840005F544A00FADEC400FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000377E8800377E
      8800000000000000000080808000808080008080800080808000000000000000
      0000377E8800377E880000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD00BDBDBD004242390000000000AD9A8800FFF9F300F6DAC000FADE
      C400EDD2B900D1BAA400DCC3AD00FFE3C900B29D8B0083746600C2AC9700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF000000000000C8D0
      D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400808000008080
      00008080000080800000800000000000000000000000000000004397A3004397
      A3004397A3000000000000000000000000000000000000000000000000004397
      A3004397A3004397A300000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF004242390000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00D1BAA400524840005C524800ECD1B800726559005F544A00D5BCA700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF0000000000FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00C8D0D400808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B0000393900005A5A5A005A5A5A007B7B
      7B007B7B7B007B7B7B002121210000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00F4D8BF00AA978500000000000000000000000000B29D8B00FFE3C900FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF0000000000000000
      0000000000000000000000000000000000000000000000000000808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      00000000000091919100000000004EA9B6004EA9B60000000000919191000000
      00000000000000000000000000000000000000000000000000009C9C0000ADAD
      6B00BD9C7B00BD9C7B00BD9C7B007B7339003939000042423900000000000000
      000000000000000000000000000000000000AD9A8800FFF9F300FFF9F300FFF9
      F300FFF9F300FFF9F300FFF9F300FFF9F300FFF9F300FFF4EA00FFF1E400FFF1
      E400FFEBD900FFEBD900FFE5CE004640380080800000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF0080800000000000000000000000000000000000000000
      0000000000000000000091919100000000000000000091919100000000000000
      00000000000000000000000000000000000000000000000000007B7B00005A5A
      5A005A5A5A005A5A5A005A5A5A00313131003939000042423900000000000000
      00000000000000000000000000000000000000000000AD9A8800AD9A8800AD9A
      8800A69382009C8B7B0092827300857669007B6D600072655900655A4E005248
      4000524840004640380046403800000000000000000080800000808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080800000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B00007B7B
      00007B7B00007B7B00007B7B00007B7B00002121000000000000000000000000
      000000000000000000000000000000000000424D3E000000000000003E000000
      2800000040000000200000000100010000000000000100000000000000000000
      000000000000000000000000FFFFFF00FFFFFFFF00000000FFFFF8FF00000000
      8FFFF07F00000000301F80010000000030070001000000002003000100000000
      000300010000000081C10001000000008001000100000000C001000100000000
      E001000100000000A181000100000000D003000100000000C803000300000000
      E005D80F00000000F80DFC1F00000000FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFF1FFFFFFFFC001FFE1FFFFFFFFC00180018001FC3FC001000000008001C001
      0000000080018000000000008001800000000000800180000000000080018000
      00000000800180000000000080018001000000008001800100000000C813803F
      00000000FC3F803F80018001FFFF807F00000000000000000000000000000000
      000000000000}
  end
end
