object EditForm1: TEditForm1
  Left = 339
  Top = 250
  Hint = 'C:\TASPro7\DBA7\WBKMENUSETUP.DFM'
  AutoScroll = False
  Caption = 'Menu Item Setup'
  ClientHeight = 456
  ClientWidth = 836
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFF9AF5F5F554FFBFF5F554FFCFF5F57CF5F5F5F5EB77FFFFF5F50000F5
    F5FFFFFF9AF5F5F554FFBFF5F577FFF5F5F57CF5F5F5F5F5F5FFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFFF5F5D3BFF5F59A54F5F5FF9AF5F5FFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFFEBF5F5F5F5F55EFFFF5454AFF5F5FFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFFBFF5BF54F5F52929EBF5F5F5F5EBFFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFF9AF5D39AF5EBFF7FF5F5BFBFAF44FFFFF5F50000F5
    F5FFBFF5FFF5F59A9AF5545EF5F5AFF5BFFF9AF5F5FF549A77FFFFF5F50000F5
    F5FFBFF59AF5F5BFBFF55429F5F5F5F59AFF9AF5F59ABFF5BFFFFFF5F50000F5
    F5FFBFF5F5F5F5F5F5F554FFEBF5F5F577FF44F5F5F5F5F5BFFFFFF5F50000F5
    F5FF4454545454545454FFFF44545454FFFFFF445454545444FFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  Menu = MainMenu1
  OldCreateOrder = True
  No_Refresh = False
  OnStart = 'wbkmenusetup.onstart'
  OpenFiles = 'wbkmenusetup.openfiles'
  OnDisplayScreen = 'wbkmenusetup.ondisplay'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'wbkmenusetup'
  RememberSize = True
  RememberSizeDate = 45512.615423495370000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object pcMenuSetup: TTASPageControl
    Left = 8
    Top = 40
    Width = 832
    Height = 424
    ActivePage = tsMain
    TabOrder = 0
    PageIndex = 0
    PageName = 'tsMain'
    object tsMain: TTabSheet
      Caption = 'Groups/Buttons'
      object dgButtons: TTASDataGrid
        Left = 599
        Top = 21
        Width = 216
        Height = 352
        ColCount = 3
        Enabled = False
        FixedCols = 1
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowMoving, goEditing]
        PopupMenu = puButtons
        TabOrder = 2
        UpCase = False
        StartAtEnd = False
        PrePrgLoc = 0
        PostPrgLoc = 0
        Navigation.AllowInsertRow = False
        Navigation.AllowDeleteRow = True
        Navigation.AdvanceOnEnter = True
        Navigation.AdvanceAtEnd = True
        Navigation.AdvanceDirection = adLeftRight
        Navigation.AdvanceAuto = False
        Navigation.InsertPosition = pInsertBefore
        Navigation.CursorWalkEditor = False
        Navigation.AllowAddRecListF = True
        MouseActions.ColSelect = False
        MouseActions.RowSelect = False
        MouseActions.DirectEdit = False
        MouseActions.DirectComboDrop = False
        MouseActions.CaretPositioning = False
        PasswordChar = '*'
        Columns = <
          item
            Color = clWindow
            Width = 30
            Alignment = taLeftJustify
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            CharCase = ecNormal
            Name = 'colButtonCont'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 93
            Alignment = taLeftJustify
            Header = 'Menu Button'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edEditBtn
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'BUTTON_CAPTION'
            CharCase = ecUpperCase
            Name = 'colButtonCaptions'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = True
            ValidUserEsc = False
            ValidExpr = 'vld_menubutt()'
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 50
            Alignment = taLeftJustify
            Header = 'Image#'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edEditBtn
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'BUTTON_IMAGE'
            CharCase = ecNormal
            Name = 'colButtonImage'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = True
            ValidUserEsc = False
            ValidExpr = 'vld_imagenum()'
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end>
        ExtraFields = <
          item
            FieldName = 'BUTTON_NUM'
          end>
        AutoNumAlign = False
        SelectionColor = clHighlight
        SelectionTextColor = clHighlightText
        SelectionRectangle = False
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -13
        FixedFont.Name = 'Arial'
        FixedFont.Style = []
        VAlignment = vtaTop
        Hovering = False
        EnhRowColMove = True
        HintColor = clYellow
        CurrentRow = 1
        CurrentCol = 1
        GridFileHandle = 0
        GridFileKeyNum = 0
        NoAutoUpdate = False
        ColWidths = (
          30
          93
          50)
      end
      object dgAccessRecs: TTASDataGrid
        Left = 22
        Top = 21
        Width = 238
        Height = 352
        ColCount = 1
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goEditing]
        TabOrder = 0
        UpCase = False
        StartAtEnd = False
        PrePrgLoc = 0
        PostPrgLoc = 0
        Navigation.AllowInsertRow = False
        Navigation.AllowDeleteRow = True
        Navigation.AdvanceOnEnter = True
        Navigation.AdvanceAtEnd = True
        Navigation.AdvanceDirection = adLeftRight
        Navigation.AdvanceAuto = False
        Navigation.InsertPosition = pInsertBefore
        Navigation.CursorWalkEditor = False
        Navigation.AllowAddRecListF = True
        MouseActions.ColSelect = False
        MouseActions.RowSelect = False
        MouseActions.DirectEdit = False
        MouseActions.DirectComboDrop = False
        MouseActions.CaretPositioning = False
        PasswordChar = '*'
        Columns = <
          item
            Color = clWindow
            Width = 199
            Alignment = taLeftJustify
            Header = 'Access Code'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'ACCESS_CODE'
            CharCase = ecUpperCase
            Name = 'colAccessRecords'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end>
        ExtraFields = <>
        AutoNumAlign = False
        SelectionColor = clHighlight
        SelectionTextColor = clHighlightText
        SelectionRectangle = False
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -13
        FixedFont.Name = 'Arial'
        FixedFont.Style = []
        VAlignment = vtaTop
        Hovering = False
        EnhRowColMove = False
        HintColor = clYellow
        CurrentRow = 1
        CurrentCol = 1
        GridFileHandle = 0
        GridFileKeyNum = 0
        NoAutoUpdate = False
        ColWidths = (
          199)
      end
      object dgGroups: TTASDataGrid
        Left = 382
        Top = 21
        Width = 206
        Height = 352
        ColCount = 2
        Enabled = False
        FixedCols = 1
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowMoving, goEditing]
        PopupMenu = puGroups
        TabOrder = 1
        UpCase = False
        StartAtEnd = False
        PrePrgLoc = 0
        PostPrgLoc = 0
        Navigation.AllowInsertRow = False
        Navigation.AllowDeleteRow = True
        Navigation.AdvanceOnEnter = True
        Navigation.AdvanceAtEnd = True
        Navigation.AdvanceDirection = adLeftRight
        Navigation.AdvanceAuto = False
        Navigation.InsertPosition = pInsertBefore
        Navigation.CursorWalkEditor = False
        Navigation.AllowAddRecListF = True
        MouseActions.ColSelect = False
        MouseActions.RowSelect = False
        MouseActions.DirectEdit = False
        MouseActions.DirectComboDrop = False
        MouseActions.CaretPositioning = False
        PasswordChar = '*'
        Columns = <
          item
            Color = clWindow
            Width = 30
            Alignment = taLeftJustify
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 130
            Alignment = taLeftJustify
            Header = 'Group Button'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edComboEdit
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItems.Strings = (
              'Mfg'
              'Items'
              'Sales'
              'Queries'
              'Hand Held'
              'System Manager'
              'Accounting'
              'Pay Link'
              'Payroll'
              'Settings'
              'Other')
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'GROUP_CAPTION'
            CharCase = ecNormal
            Name = 'colGroupCaptions'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end>
        ExtraFields = <
          item
            FieldName = 'GROUP_NUM'
          end>
        AutoNumAlign = False
        SelectionColor = clHighlight
        SelectionTextColor = clHighlightText
        SelectionRectangle = False
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -13
        FixedFont.Name = 'Arial'
        FixedFont.Style = []
        VAlignment = vtaTop
        Hovering = False
        EnhRowColMove = True
        HintColor = clYellow
        CurrentRow = 1
        CurrentCol = 1
        GridFileHandle = 0
        GridFileKeyNum = 0
        NoAutoUpdate = False
        ColWidths = (
          30
          130)
      end
    end
    object tsMenuLines: TTabSheet
      Caption = 'Menu Lines'
      object Label4: TLabel
        Left = 16
        Top = 17
        Width = 65
        Height = 16
        Caption = 'New Menu:'
      end
      object Label5: TLabel
        Left = 493
        Top = 17
        Width = 123
        Height = 16
        Caption = 'Existing Menu Items:'
      end
      object dgMenuSetup: TTASDataGrid
        Left = 16
        Top = 41
        Width = 408
        Height = 336
        ColCount = 7
        Enabled = False
        FixedCols = 1
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRowMoving, goEditing]
        TabOrder = 0
        UpCase = False
        StartAtEnd = False
        PrePrgLoc = 0
        PostPrgLoc = 0
        Navigation.AllowInsertRow = True
        Navigation.AllowDeleteRow = True
        Navigation.AdvanceOnEnter = True
        Navigation.AdvanceAtEnd = True
        Navigation.AdvanceDirection = adLeftRight
        Navigation.AdvanceAuto = False
        Navigation.InsertPosition = pInsertBefore
        Navigation.CursorWalkEditor = False
        Navigation.AllowAddRecListF = False
        MouseActions.ColSelect = False
        MouseActions.RowSelect = False
        MouseActions.DirectEdit = False
        MouseActions.DirectComboDrop = False
        MouseActions.CaretPositioning = False
        PasswordChar = '*'
        Columns = <
          item
            Color = clWindow
            Width = 29
            Alignment = taLeftJustify
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -11
            Font.Name = 'MS Sans Serif'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            CharCase = ecNormal
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 58
            Alignment = taLeftJustify
            Header = 'Menu Lvl'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edInteger
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 9
            SpinStep = 0
            EditMask = '0;0; '
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_MENU_LVL'
            CharCase = ecNormal
            Name = 'ColMenuLevel'
            DfltValue = '1'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 0
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 195
            Alignment = taLeftJustify
            Header = 'Caption'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_CAPTION'
            CharCase = ecNormal
            Name = 'colCaption'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 73
            Alignment = taLeftJustify
            Header = 'Fast Sel'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edComboList
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItems.Strings = (
              '(None)'
              'Ctrl+A'
              'Ctrl+B'
              'Ctrl+C'
              'Ctrl+D'
              'Ctrl+E'
              'Ctrl+F'
              'Ctrl+G'
              'Ctrl+H'
              'Ctrl+I'
              'Ctrl+J'
              'Ctrl+K'
              'Ctrl+L'
              'Ctrl+M'
              'Ctrl+N'
              'Ctrl+O'
              'Ctrl+P'
              'Ctrl+Q'
              'Ctrl+R'
              'Ctrl+S'
              'Ctrl+T'
              'Ctrl+U'
              'Ctrl+V'
              'Ctrl+W'
              'Ctrl+X'
              'Ctrl+Y'
              'Ctrl+Z'
              'Ctrl+Alt+A'
              'Ctrl+Alt+B'
              'Ctrl+Alt+C'
              'Ctrl+Alt+D'
              'Ctrl+Alt+E'
              'Ctrl+Alt+F'
              'Ctrl+Alt+G'
              'Ctrl+Alt+H'
              'Ctrl+Alt+I'
              'Ctrl+Alt+J'
              'Ctrl+Alt+K'
              'Ctrl+Alt+L'
              'Ctrl+Alt+M'
              'Ctrl+Alt+N'
              'Ctrl+Alt+O'
              'Ctrl+Alt+P'
              'Ctrl+Alt+Q'
              'Ctrl+Alt+R'
              'Ctrl+Alt+S'
              'Ctrl+Alt+T'
              'Ctrl+Alt+U'
              'Ctrl+Alt+V'
              'Ctrl+Alt+W'
              'Ctrl+Alt+X'
              'Ctrl+Alt+Y'
              'Ctrl+Alt+Z'
              'F1'
              'F2'
              'F3'
              'F4'
              'F5'
              'F6'
              'F7'
              'F8'
              'F9'
              'F10'
              'F11'
              'F12'
              'Ctrl+F1'
              'Ctrl+F2'
              'Ctrl+F3'
              'Ctrl+F4'
              'Ctrl+F5'
              'Ctrl+F6'
              'Ctrl+F7'
              'Ctrl+F8'
              'Ctrl+F9'
              'Ctrl+F10'
              'Ctrl+F11'
              'Ctrl+F12'
              'Shift+F1'
              'Shift+F2'
              'Shift+F3'
              'Shift+F4'
              'Shift+F5'
              'Shift+F6'
              'Shift+F7'
              'Shift+F8'
              'Shift+F9'
              'Shift+F10'
              'Shift+F11'
              'Shift+F12'
              'Shift+Ctrl+F1'
              'Shift+Ctrl+F2'
              'Shift+Ctrl+F3'
              'Shift+Ctrl+F4'
              'Shift+Ctrl+F5'
              'Shift+Ctrl+F6'
              'Shift+Ctrl+F7'
              'Shift+Ctrl+F8'
              'Shift+Ctrl+F9'
              'Shift+Ctrl+F10'
              'Shift+Ctrl+F11'
              'Shift+Ctrl+F12'
              'Ins'
              'Shift+Ins'
              'Ctrl+Ins'
              'Del'
              'Shift+Del'
              'Ctrl+Del'
              'Alt+BkSp'
              'Alt+Shift+BkSp')
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_FASTSELECT'
            CharCase = ecNormal
            Name = 'colFastSelect'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 194
            Alignment = taLeftJustify
            Header = 'Program Name'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edEditBtn
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_PROGRAMNAME'
            CharCase = ecUpperCase
            Name = 'colPrgName'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 90
            Alignment = taLeftJustify
            Header = 'Icon'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edEditBtn
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_IMAGE'
            CharCase = ecNormal
            Name = 'ColImage'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 60
            Alignment = taLeftJustify
            Header = 'Label'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_LABEL'
            CharCase = ecNormal
            Name = 'ColLabel'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end>
        ExtraFields = <
          item
            FieldName = 'MI_OLD_OPT'
          end
          item
            FieldName = 'MI_OLD_CAP'
          end
          item
            FieldName = 'MI_OLD_PRGNME'
          end>
        AutoNumAlign = False
        SelectionColor = clHighlight
        SelectionTextColor = clHighlightText
        SelectionRectangle = False
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -13
        FixedFont.Name = 'Arial'
        FixedFont.Style = []
        VAlignment = vtaTop
        Hovering = False
        EnhRowColMove = True
        HintColor = clYellow
        CurrentRow = 1
        CurrentCol = 1
        GridFileHandle = 0
        GridFileKeyNum = 0
        NoAutoUpdate = False
        ColWidths = (
          29
          58
          195
          73
          194
          90
          60)
      end
      object gbtnArrowLeft: TGlyphBtn
        Left = 440
        Top = 144
        Width = 40
        Height = 25
        Enabled = False
        TabOrder = 1
        TabStop = False
        Glyph.Data = {
          76010000424D7601000000000000760000002800000020000000100000000100
          04000000000000010000120B0000120B00001000000000000000000000000000
          800000800000008080008000000080008000808000007F7F7F00BFBFBF000000
          FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00333333333333
          3333333333333333333333333333333333333333333333333333333333333333
          3333333333333FF3333333333333003333333333333F77F33333333333009033
          333333333F7737F333333333009990333333333F773337FFFFFF330099999000
          00003F773333377777770099999999999990773FF33333FFFFF7330099999000
          000033773FF33777777733330099903333333333773FF7F33333333333009033
          33333333337737F3333333333333003333333333333377333333333333333333
          3333333333333333333333333333333333333333333333333333333333333333
          3333333333333333333333333333333333333333333333333333}
        NumGlyphs = 2
        GlyphKind = bkCustom
      end
      object gbtnArrowRight: TGlyphBtn
        Left = 440
        Top = 184
        Width = 40
        Height = 25
        Enabled = False
        TabOrder = 2
        TabStop = False
        Glyph.Data = {
          76010000424D7601000000000000760000002800000020000000100000000100
          04000000000000010000120B0000120B00001000000000000000000000000000
          800000800000008080008000000080008000808000007F7F7F00BFBFBF000000
          FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF00333333333333
          3333333333333333333333333333333333333333333333333333333333333333
          3333333333333333333333333333333333333333333FF3333333333333003333
          3333333333773FF3333333333309003333333333337F773FF333333333099900
          33333FFFFF7F33773FF30000000999990033777777733333773F099999999999
          99007FFFFFFF33333F7700000009999900337777777F333F7733333333099900
          33333333337F3F77333333333309003333333333337F77333333333333003333
          3333333333773333333333333333333333333333333333333333333333333333
          3333333333333333333333333333333333333333333333333333}
        NumGlyphs = 2
        GlyphKind = bkCustom
      end
      object dgExistingMenuItems: TTASDataGrid
        Left = 488
        Top = 41
        Width = 304
        Height = 336
        ColCount = 2
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goDrawFocusSelected, goRowSelect]
        TabOrder = 3
        UpCase = False
        StartAtEnd = False
        PrePrgLoc = 0
        PostPrgLoc = 0
        Navigation.AllowInsertRow = False
        Navigation.AllowDeleteRow = False
        Navigation.AdvanceOnEnter = False
        Navigation.AdvanceAtEnd = False
        Navigation.AdvanceDirection = adLeftRight
        Navigation.AdvanceAuto = False
        Navigation.InsertPosition = pInsertBefore
        Navigation.CursorWalkEditor = False
        Navigation.AllowAddRecListF = False
        MouseActions.ColSelect = False
        MouseActions.RowSelect = False
        MouseActions.DirectEdit = False
        MouseActions.DirectComboDrop = False
        MouseActions.CaretPositioning = False
        PasswordChar = '*'
        Columns = <
          item
            Color = clWindow
            Width = 50
            Alignment = taLeftJustify
            Header = 'Opt'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_EXIST_OPT'
            CharCase = ecNormal
            Name = 'colExistingOpt'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end
          item
            Color = clWindow
            Width = 206
            Alignment = taLeftJustify
            Header = 'Caption'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Arial'
            Font.Style = []
            Editor = edDefault
            Fixed = False
            ReadOnly = False
            Password = False
            ComboItemsSort = False
            SpinMin = 0
            SpinMax = 0
            SpinStep = 0
            EditLength = 0
            Borders = []
            BorderPen.Color = clSilver
            FieldName = 'MI_EXIST_CAP'
            CharCase = ecNormal
            Name = 'colExistingCaption'
            PrePrgLoc = 0
            PostPrgLoc = 0
            ValidPrgLoc = 0
            ClickPrgLoc = 0
            ChangePrgLoc = 0
            DecimalChrs = 2
            FormatOnEnter = True
            ValidCheckOnExit = False
            ValidUserEsc = False
            ValidExprLoc = 0
            ValidExprTyp = #0
            TimeFieldType = tf_5
            ElapsedTime = False
          end>
        ExtraFields = <
          item
            FieldName = 'MI_EXIST_PRGNME'
          end>
        AutoNumAlign = False
        SelectionColor = clHighlight
        SelectionTextColor = clHighlightText
        SelectionRectangle = False
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -13
        FixedFont.Name = 'Arial'
        FixedFont.Style = []
        VAlignment = vtaTop
        Hovering = False
        EnhRowColMove = False
        HintColor = clYellow
        CurrentRow = 1
        CurrentCol = 1
        GridFileHandle = 0
        GridFileKeyNum = 0
        NoAutoUpdate = False
        ColWidths = (
          50
          206)
      end
    end
  end
  object btnExit: TButton
    Left = 760
    Top = 2
    Width = 75
    Height = 25
    Caption = 'E&xit'
    TabOrder = 1
  end
  object ToolBar1: TToolBar
    Left = 4
    Top = 0
    Width = 748
    Height = 29
    Align = alNone
    ButtonHeight = 24
    ButtonWidth = 117
    EdgeBorders = []
    TabOrder = 2
    object btnUpdatetoLatest: TButton
      Left = 0
      Top = 0
      Width = 141
      Height = 24
      Caption = '&Update to Latest Prg'
      TabOrder = 7
    end
    object btnChgPrgName: TButton
      Left = 141
      Top = 0
      Width = 123
      Height = 24
      Caption = 'Change Prg Name'
      TabOrder = 3
    end
    object btnAdd: TButton
      Left = 264
      Top = 0
      Width = 75
      Height = 24
      Caption = '&Add User'
      TabOrder = 5
    end
    object btnEdit: TButton
      Left = 339
      Top = 0
      Width = 75
      Height = 24
      Caption = '&Edit User'
      TabOrder = 0
    end
    object btnDelete: TButton
      Left = 414
      Top = 0
      Width = 75
      Height = 24
      Caption = '&Delete User'
      TabOrder = 4
    end
    object btnAddGRP: TButton
      Left = 489
      Top = 0
      Width = 75
      Height = 24
      Caption = 'Add Group'
      TabOrder = 6
    end
    object btnClose: TButton
      Left = 564
      Top = 0
      Width = 50
      Height = 24
      Caption = '&Close'
      Enabled = False
      TabOrder = 1
    end
    object btnSave: TButton
      Left = 614
      Top = 0
      Width = 51
      Height = 24
      Caption = '&Save'
      Enabled = False
      TabOrder = 2
    end
    object btnClean: TButton
      Left = 665
      Top = 0
      Width = 75
      Height = 24
      Caption = '&Clean Up'
      Enabled = False
      TabOrder = 8
      Visible = False
    end
  end
  object PanelGRP: TPanel
    Left = 350
    Top = 25
    Width = 185
    Height = 224
    BevelInner = bvLowered
    TabOrder = 3
    Visible = False
    object Label1: TLabel
      Left = 12
      Top = 121
      Width = 82
      Height = 16
      Caption = 'Group To Add:'
    end
    object Label2: TLabel
      Left = 12
      Top = 68
      Width = 104
      Height = 16
      Caption = 'User(s) to Add To:'
    end
    object Label3: TLabel
      Left = 12
      Top = 12
      Width = 68
      Height = 16
      Caption = 'Copy From:'
    end
    object GroupGRP: TTASComboBox
      Left = 11
      Top = 145
      Width = 163
      Height = 24
      AutoDropDown = True
      Style = csDropDownList
      ItemHeight = 16
      TabOrder = 2
      FieldName = 'groupname'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object GRPExit: TGlyphBtn
      Left = 128
      Top = 193
      Width = 53
      Height = 25
      Caption = 'E&xit'
      ModalResult = 1
      TabOrder = 4
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object GRPGo: TGlyphBtn
      Left = 68
      Top = 193
      Width = 59
      Height = 25
      Caption = 'Go'
      TabOrder = 3
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
        C8D0D4C8D0D4D3D9DCDDE2E4E7EAECEDF0F1EDF0F1E7EAECDDE2E4D3D9DCC8D0
        D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4CCD4D7DCE1E3D3E0D677AE7929872900
        780000780029872977AE79D3E0D6DCE1E3CCD4D7C8D0D4C8D0D4C8D0D4CBD3D6
        DDE2E49EC2A100780027A73340D3544DEE6248EC5A34CE401BA4200078009EC2
        A1DDE2E4CBD3D6C8D0D4C8D0D4D8DDE09CC19F0A7F0D51DE6D53E56F36BB4543
        CC5043CF4E41D14B41E44F33D33C057E069CC19FD8DDE0C8D0D4CED4D8CAD8CF
        0078005AE17A5EE97A1A9120ADCEAD228B2337B63E42C54A3EC4453ED84933D3
        3C007800CAD8CFCED4D8D3D9DC6FA77233AB466EF69457DC691B9120FFFFFFF2
        F7F280B5801A921E3FC1463EC34340E34D1AA31F6FA772D3D9DCD5DADC248425
        5FDD8266EA835CE1701D9323FFFFFFFFFFFFFFFFFFC9DEC943984327A32B3FD0
        4933CE3E248425D5DADCD4D8DB0078007FFDAD69EC8563E87A1F9527FFFFFFFF
        FFFFFFFFFFFFFFFFFFFFFF80B58029AD3145EB57007800D4D8DBCFD4D6007800
        85FDB56FF18D6AF083229829FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80B5802BAE
        354AED5F007800CFD4D6C9CFD21F82206CDE9378F79A70F78D239A2DFFFFFFFF
        FFFFFFFFFFC9DEC9318F332DA83349D6593ED2501F8220C9CFD2C5CCCF529655
        3EAD548BFDBA73FA90249A2EFFFFFFF2F7F271AD712098274CCF5A4BCF5757EE
        7224A7305F9C62C5CCCFC4CCD0ABBCB300780079E7A384FCAE259A30ADCEAD25
        8F2949C95957DB6851D6615AE7754DDD69007800ABBCB3C4CCD0C8D0D4C0C7CA
        79A47F0D801377E7A27CEEA952C96D64E57F63E77D61E67B69F48E56E076087F
        0D79A47FC0C7CAC8D0D4C8D0D4C5CDD1BBC2C674A27B0078003DAD5370E69A80
        FDB07AFDA95BDC7E30AB4300780074A27BBBC2C6C5CDD1C8D0D4C8D0D4C8D0D4
        C4CCD0BAC1C59CB0A54F93531780190078000078001780194490489CB0A5BAC1
        C5C4CCD0C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C0C7CBB7BEC2B0B7BBAB
        B2B6ABB2B6B0B7BBB7BEC2C0C7CBC8D0D4C8D0D4C8D0D4C8D0D4}
      GlyphKind = bkCustom
    end
    object UsersGRP: TTASComboBox
      Left = 11
      Top = 91
      Width = 163
      Height = 24
      AutoDropDown = True
      Style = csDropDownList
      ItemHeight = 16
      TabOrder = 1
      FieldName = 'username'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object CopyGRP: TTASComboBox
      Left = 11
      Top = 34
      Width = 163
      Height = 24
      AutoDropDown = True
      Style = csDropDownList
      ItemHeight = 16
      TabOrder = 0
      FieldName = 'copyname'
      DropDownPrgLoc = -1
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = -1
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      ValidCheckOnExit = False
      ValidUserEsc = False
      ValidExprLoc = 0
      ValidExprTyp = #0
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ItemNumber = 0
      ReturnIsTab = True
      SelectStart = 0
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object ProgressPanel: TPanel
    Left = 357
    Top = 170
    Width = 171
    Height = 70
    BevelInner = bvLowered
    TabOrder = 4
    Visible = False
    object ProgLabel: TLabel
      Left = 10
      Top = 12
      Width = 129
      Height = 16
      Caption = 'Loading User Data...'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object ProgBar: TProgressBar
      Left = 11
      Top = 39
      Width = 150
      Height = 16
      Smooth = True
      TabOrder = 0
    end
  end
  object CleanupPanel: TPanel
    Left = 258
    Top = 0
    Width = 402
    Height = 83
    BevelInner = bvLowered
    TabOrder = 5
    Visible = False
    object Label6: TLabel
      Left = 40
      Top = 21
      Width = 331
      Height = 16
      Caption = 'Running a Required Cleanup. This may take some time...'
    end
    object CleanupLabel: TLabel
      Left = 112
      Top = 48
      Width = 44
      Height = 16
      Caption = 'USER: '
    end
  end
  object UpdateingPanel: TPanel
    Left = 3
    Top = 34
    Width = 402
    Height = 83
    BevelInner = bvLowered
    TabOrder = 6
    Visible = False
    object Label7: TLabel
      Left = 64
      Top = 21
      Width = 267
      Height = 16
      Caption = 'Updating Users to the Latest Evo Programs....'
    end
    object Userlabel: TLabel
      Left = 112
      Top = 48
      Width = 44
      Height = 16
      Caption = 'USER: '
    end
  end
  object MainMenu1: TMainMenu
    Left = 688
    Top = 397
    object File1: TMenuItem
      Caption = '&File'
      object mniEdit: TMenuItem
        Caption = 'Edit'
        ShortCut = 113
      end
      object mniSave: TMenuItem
        Caption = 'Save'
        Enabled = False
        ShortCut = 121
      end
      object mniExit: TMenuItem
        Caption = 'Exit'
      end
    end
  end
  object slMenuSetup: TTASStrList
    Left = 272
    Top = 405
  end
  object slExistingItems: TTASStrList
    Left = 228
    Top = 405
  end
  object slGroupList: TTASStrList
    Left = 328
    Top = 400
  end
  object slButtonList: TTASStrList
    Left = 376
    Top = 400
  end
  object puButtons: TPopupMenu
    Left = 561
    Top = 407
    object mniDeleteButton: TMenuItem
      Caption = 'Delete Button'
    end
    object mniMoveToGroup: TMenuItem
      Caption = 'Move to Group'
    end
  end
  object puGroups: TPopupMenu
    Left = 456
    Top = 400
    object mniDeleteGroup: TMenuItem
      Caption = 'Delete Group'
    end
  end
end
