object EditForm1: TEditForm1
  Left = 339
  Top = 243
  Hint = 'C:\taspro7\DBA7\EvoServiceSetup.DFM'
  AutoScroll = False
  Caption = 'Create EvoService for your Server'
  ClientHeight = 216
  ClientWidth = 625
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = True
  No_Refresh = False
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'EVOServiceSETUP'
  RememberSize = True
  OnDisplayScreen = 'EvoServiceSetup.OnDisp' 
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Label1: TLabel
    Left = 16
    Top = 16
    Width = 71
    Height = 16
    Caption = 'Server Path:'
  end
  object lblServerPath: TLabel
    Left = 96
    Top = 16
    Width = 40
    Height = 16
    Caption = 'g:\path'
  end
  object Label2: TLabel
    Left = 16
    Top = 43
    Width = 48
    Height = 16
    Caption = 'Creating'
  end
  object Label7: TLabel
    Left = 4
    Top = 106
    Width = 40
    Height = 16
    Caption = 'SMTP:'
  end
  object Label9: TLabel
    Left = 4
    Top = 131
    Width = 31
    Height = 16
    Caption = 'User:'
  end
  object Label10: TLabel
    Left = 4
    Top = 156
    Width = 50
    Height = 16
    Caption = 'Passwd:'
  end
  object Label8: TLabel
    Left = 331
    Top = 106
    Width = 28
    Height = 16
    Caption = 'Port:'
  end
  object Label11: TLabel
    Left = 329
    Top = 131
    Width = 37
    Height = 16
    Caption = 'Email:'
  end
  object Label12: TLabel
    Left = 329
    Top = 156
    Width = 38
    Height = 16
    Caption = 'Name:'
  end
  object Label3: TLabel
    Left = 3
    Top = 74
    Width = 128
    Height = 23
    Caption = 'Email Settings'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Arial Black'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label30: TLabel
    Left = 329
    Top = 182
    Width = 27
    Height = 16
    Caption = 'Sec.'
  end
  object Label4: TLabel
    Left = 5
    Top = 182
    Width = 48
    Height = 16
    Caption = 'Settings'
  end
  object btnContinue: TButton
    Left = 539
    Top = 184
    Width = 75
    Height = 25
    Caption = 'Continue'
    TabOrder = 0
  end
  object entCopyFile: TTASENTER
    Left = 88
    Top = 40
    Width = 225
    Height = 24
    TabStop = False
    Color = clMenu
    ReadOnly = True
    TabOrder = 1
    FieldName = 'file_name'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object smtp: TTASENTER
    Left = 72
    Top = 104
    Width = 247
    Height = 21
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 40
    ParentFont = False
    TabOrder = 2
    FieldName = 'email.cfg.SMTP'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object User: TTASENTER
    Left = 72
    Top = 129
    Width = 247
    Height = 21
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 40
    ParentFont = False
    TabOrder = 3
    FieldName = 'email.cfg.user'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidMsg = 'That is not a valid email Format.'
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExpr = '"@" $ email.cfg.bcc .and.  "." $ email.cfg.bcc'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Pass: TTASENTER
    Left = 72
    Top = 154
    Width = 247
    Height = 21
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 40
    ParentFont = False
    PasswordChar = '*'
    TabOrder = 4
    FieldName = 'email.cfg.pass'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object email: TTASENTER
    Left = 373
    Top = 129
    Width = 243
    Height = 21
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 80
    ParentFont = False
    TabOrder = 5
    FieldName = 'email.cfg.Email'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidMsg = 'That is not a valid email Format.'
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExpr = '"@" $ email.cfg.email .and.  "." $ email.cfg.email'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Name: TTASENTER
    Left = 373
    Top = 154
    Width = 242
    Height = 21
    AutoSize = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    MaxLength = 40
    ParentFont = False
    TabOrder = 6
    FieldName = 'email.cfg.Name'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object TestEmail: TGlyphBtn
    Left = 516
    Top = 100
    Width = 102
    Height = 25
    Caption = 'TestEmail'
    TabOrder = 7
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000C8D0D4C8D0D4
      C8D0D4C8D0D4C8D0D4737373737373737373C8D0D4C8D0D4C8D0D4C8D0D4C8D0
      D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4737373BD6329AD6B426B
      524A737373C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4737373
      737373BD6329EF7B08FF7321FF9408FFAD3194634A737373737373B57B5A7373
      73737373737373C8D0D4845252845252E79C5AEF8410D68463FFAD31FF8C08FF
      A510FFBD63AD7B6B845252FF9400845252845252737373C8D0D494634AF7F7E7
      F7F7E7F7F7E7FFF7E7F7DEADF79418FF9400FFAD31FFC684FFBD5AFF9400FFF7
      EFAD7B7B737373C8D0D4946363FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7DEADFF
      9C08FF9C08FFBD5AFFC684FF9400FFF7EFAD7B7B737373C8D0D4A56B6BFFFFFF
      FFFFFFF7F7F7CECECECECECECECECECECECEF79418FFAD29FF9400FF9400FFF7
      EFAD7B7B737373C8D0D4AD7B6BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      5A31EF6B42EF5231EF6B42FF5A31FFF7EFAD7B7B737373C8D0D4B58C73FFFFFF
      FFFFFFF7F7F7CECECECECECECECECECECECECECECED6D6D6F7EFDEF7E7D6FFF7
      EFAD7B7B737373C8D0D4B58C73FFFFFFFF5A31EF6B42E75229C67342C68C7BFF
      FFFFFFFFFFFFFFFF294A847394D6FFF7EFAD7B7B737373C8D0D4C6947BFFFFFF
      FF8C08FF8C08FF5A31AD4A18FFF7EFFFFFFFFFFFFFFFFFFF7394D67394D6FFFF
      F7AD7B7B737373C8D0D4D6A584FFFFFFFF8C08FFBD5AFFAD29F79418BD6329FF
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7EFAD7B7B737373C8D0D4DEAD84DEAD84
      FF8C08DEAD84F7A55AFFC684EF9439BD6329C69C94C69C94C69C94C69C94C69C
      94AD7B7BC8D0D4C8D0D4C8D0D4C8D0D4FF8C08C8D0D4C8D0D4F7A55AFFDEADEF
      B58CBD6329BD5239C67342A56342C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4
      C8D0D4C8D0D4C8D0D4C8D0D4F7A55AFFEFBDFFE7ADDE8C52944A18C8D0D4C8D0
      D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8
      D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4C8D0D4}
    GlyphKind = bkCustom
  end
  object GroupBox1: TGroupBox
    Left = 335
    Top = 10
    Width = 283
    Height = 81
    Caption = 'Windows OS'
    TabOrder = 8
    object TASRadioButton1: TTASRadioButton
      Left = 67
      Top = 27
      Width = 165
      Height = 17
      Caption = '32 Bit Operating Systsm'
      TabOrder = 0
      FieldName = 'thirtytwo'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = False
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
    object TASRadioButton2: TTASRadioButton
      Left = 67
      Top = 55
      Width = 170
      Height = 17
      Caption = '64 Bit Operating System'
      TabOrder = 1
      FieldName = 'sixtyfour'
      DispPrgLoc = -1
      ClickPrgLoc = -1
      ChangePrgLoc = 0
      PrePrgLoc = -1
      PostPrgLoc = -1
      ValidPrgLoc = -1
      Group = 0
      NoClickOn = False
      NoClickOff = False
      ReturnIsTab = False
      PreRetFalse = False
      EntryFont.Charset = DEFAULT_CHARSET
      EntryFont.Color = clWindowText
      EntryFont.Height = -11
      EntryFont.Name = 'MS Sans Serif'
      EntryFont.Style = []
      EntryBGColor = clWhite
      EntryUseDflt = True
      FldModified = False
    end
  end
  object emailSEC: TTASComboBox
    Left = 373
    Top = 180
    Width = 113
    Height = 24
    Color = clMenu
    ItemHeight = 16
    TabOrder = 9
    Text = 'Subject Fields'
    Items.Strings = (
      'NONE'
      'SSL'
      'STARTTLS')
    FieldName = 'email.cfg.sec'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object smtpport: TTASNumEnter
    Left = 373
    Top = 105
    Width = 56
    Height = 21
    AutoSize = False
    DecimalPlaces = 0
    DisplayFormat = '0'
    TabOrder = 10
    FieldName = 'smtpport'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASENTER1: TTASENTER
    Left = 71
    Top = 180
    Width = 247
    Height = 24
    TabStop = False
    Color = clMenu
    TabOrder = 11
    Text = 'TASENTER1'
    FieldName = 'esettings'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 261
    Top = 65528
  end
  object MSGLIST: TTASStrList
    Left = 296
    Top = 65528
  end
end
