object EditForm2: TEditForm2
  Left = 379
  Top = 252
  Width = 649
  Height = 490
  Hint = 'C:\TASPRO7\DBA7\caldrillbt.DFM'
  Caption = 'caldrillbt'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'caldrillbt.OnClose'
  No_Refresh = False
  OnStart = 'caldrillbt.OnStart'
  OpenFiles = 'caldrillbt.OnOpenFiles'
  ScreenPos = tpDesktopCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'caldrillbt'
  OnDisplayScreen = 'caldrillbt.OnDisp'      
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Panel2: TPanel
    Left = 0
    Top = 0
    Width = 629
    Height = 20
    Alignment = taLeftJustify
    Caption = 
      ' Sunday           Monday           Tuesday           Wednesday  ' +
      '   Thursday          Friday               Saturday'
    TabOrder = 0
  end
  object Exit: TGlyphBtn
    Left = 565
    Top = 420
    Width = 63
    Height = 25
Caption = 'E&xit'   
    TabOrder = 1
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
      DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
      E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
      19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
      5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
      EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
      43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
      707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
      D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
      6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
      7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
      D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
      FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
      8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
      D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
      F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
      91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
      DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
      77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
      8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
      EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
      90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
      3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
      AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
      BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
    GlyphKind = bkCustom
  end
  object Panel1: TPanel
    Left = 0
    Top = 22
    Width = 630
    Height = 395
    TabOrder = 2
    object GlyphBtn1: TGlyphBtn
      Left = 0
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      GlyphKind = bkCustom
    end
    object GlyphBtn2: TGlyphBtn
      Left = 90
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      GlyphKind = bkCustom
    end
    object GlyphBtn3: TGlyphBtn
      Left = 180
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      GlyphKind = bkCustom
    end
    object GlyphBtn4: TGlyphBtn
      Left = 270
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 3
      GlyphKind = bkCustom
    end
    object GlyphBtn5: TGlyphBtn
      Left = 360
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 4
      GlyphKind = bkCustom
    end
    object GlyphBtn6: TGlyphBtn
      Left = 450
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 5
      GlyphKind = bkCustom
    end
    object GlyphBtn7: TGlyphBtn
      Left = 540
      Top = 0
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 6
      GlyphKind = bkCustom
    end
    object GlyphBtn8: TGlyphBtn
      Left = 0
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 7
      GlyphKind = bkCustom
    end
    object GlyphBtn9: TGlyphBtn
      Left = 90
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 8
      GlyphKind = bkCustom
    end
    object GlyphBtn10: TGlyphBtn
      Left = 180
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 9
      GlyphKind = bkCustom
    end
    object GlyphBtn11: TGlyphBtn
      Left = 270
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 10
      GlyphKind = bkCustom
    end
    object GlyphBtn12: TGlyphBtn
      Left = 360
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 11
      GlyphKind = bkCustom
    end
    object GlyphBtn13: TGlyphBtn
      Left = 450
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 12
      GlyphKind = bkCustom
    end
    object GlyphBtn14: TGlyphBtn
      Left = 540
      Top = 66
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 13
      GlyphKind = bkCustom
    end
    object GlyphBtn15: TGlyphBtn
      Left = 0
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 14
      GlyphKind = bkCustom
    end
    object GlyphBtn16: TGlyphBtn
      Left = 90
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 15
      GlyphKind = bkCustom
    end
    object GlyphBtn17: TGlyphBtn
      Left = 180
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 16
      GlyphKind = bkCustom
    end
    object GlyphBtn18: TGlyphBtn
      Left = 270
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 17
      GlyphKind = bkCustom
    end
    object GlyphBtn19: TGlyphBtn
      Left = 360
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 18
      GlyphKind = bkCustom
    end
    object GlyphBtn20: TGlyphBtn
      Left = 450
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 19
      Spacing = 0
      GlyphKind = bkCustom
    end
    object GlyphBtn21: TGlyphBtn
      Left = 540
      Top = 132
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 20
      GlyphKind = bkCustom
    end
    object GlyphBtn22: TGlyphBtn
      Left = 0
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 21
      GlyphKind = bkCustom
    end
    object GlyphBtn23: TGlyphBtn
      Left = 90
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 22
      GlyphKind = bkCustom
    end
    object GlyphBtn24: TGlyphBtn
      Left = 180
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 23
      GlyphKind = bkCustom
    end
    object GlyphBtn25: TGlyphBtn
      Left = 270
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 24
      GlyphKind = bkCustom
    end
    object GlyphBtn26: TGlyphBtn
      Left = 360
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 25
      GlyphKind = bkCustom
    end
    object GlyphBtn27: TGlyphBtn
      Left = 450
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 26
      GlyphKind = bkCustom
    end
    object GlyphBtn28: TGlyphBtn
      Left = 540
      Top = 198
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 27
      GlyphKind = bkCustom
    end
    object GlyphBtn29: TGlyphBtn
      Left = 0
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 28
      GlyphKind = bkCustom
    end
    object GlyphBtn30: TGlyphBtn
      Left = 90
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 29
      GlyphKind = bkCustom
    end
    object GlyphBtn31: TGlyphBtn
      Left = 180
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 30
      GlyphKind = bkCustom
    end
    object GlyphBtn32: TGlyphBtn
      Left = 270
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 31
      GlyphKind = bkCustom
    end
    object GlyphBtn33: TGlyphBtn
      Left = 360
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 32
      GlyphKind = bkCustom
    end
    object GlyphBtn34: TGlyphBtn
      Left = 450
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 33
      GlyphKind = bkCustom
    end
    object GlyphBtn35: TGlyphBtn
      Left = 540
      Top = 264
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 34
      GlyphKind = bkCustom
    end
    object GlyphBtn36: TGlyphBtn
      Left = 0
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 35
      GlyphKind = bkCustom
    end
    object GlyphBtn37: TGlyphBtn
      Left = 90
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 36
      GlyphKind = bkCustom
    end
    object GlyphBtn38: TGlyphBtn
      Left = 180
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 37
      GlyphKind = bkCustom
    end
    object GlyphBtn39: TGlyphBtn
      Left = 270
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 38
      GlyphKind = bkCustom
    end
    object GlyphBtn40: TGlyphBtn
      Left = 360
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 39
      GlyphKind = bkCustom
    end
    object GlyphBtn41: TGlyphBtn
      Left = 450
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 40
      GlyphKind = bkCustom
    end
    object GlyphBtn42: TGlyphBtn
      Left = 540
      Top = 329
      Width = 89
      Height = 65
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 41
      GlyphKind = bkCustom
    end
  end
  object Prev: TGlyphBtn
    Left = 14
    Top = 420
    Width = 75
    Height = 25
    Caption = '&Previous'
    TabOrder = 3
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8B1B8BA91959675777762
      6261626261767879999D9EBBC0C4F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F89CA0A26B6D6D6262618583819C9A98A5A3A19F9D9A91908D979795B7BA
      BCF8F8F8F8F8F8F8F8F8F8F8F8F8F8F89CA0A25F605F858381B8B5B2D7D3D0E5
      E1DCE8E3DFE3DFDBD4D0CCBFBCB8B4B3B0C4C7C8F8F8F8F8F8F8F8F8F8B3B8BC
      6B6D6D8C8A88CBC6C3E7E3DFEFEBE6F0EBE7F0EBE7EFEBE6EDE8E3E5E1DCD9D5
      D1D3D2CFCCD2D4F8F8F8F8F8F89498997B7A79C0BCB9E8E3DFEFEBE6F0EBE7F0
      EBE7F0EBE7DFD3CAD3C1B4EFEAE5ECE7E3EFEAE5DBDDDDF8F8F8F8F8F8828384
      9D9B99DBD7D4EFEBE6F0EBE7F0EBE7EBE3DECAB4A6B89D89BAA190EFEBE6F0EB
      E7F0ECE7E6E5E3F8F8F8F8F8F881807FB7B4B0E8E3DFF0EBE7F0EBE7D4C4B8BD
      A493B69985AA8971AE9989F0EBE7F0EBE7F1EDE8EFEBE8F8F8F8F8F8F892918E
      C8C3C0EEE9E4F0EBE7C9B3A4B2927DAE8D76AC8A73A68570AE9989F0EBE7F0EB
      E7F1EDEAEFEBE8F8F8F8F8F8F8A9A9A8CCC8C4EFEBE6F0EBE7F0EBE7D0C4BA9A
      806EA0816DA4846EAE9989F0EBE7F0ECE8F1EFEBE7E7E6F8F8F8F8F8F8BCC0C0
      CECAC5EEE9E4F0EBE7F0EBE7F0EBE7F0EBE7BCACA0907665A79385F0EBE7F1EE
      EAF2EFEDDCDFE0F8F8F8F8F8F8C9CFD0D4D3D0F0EBE7F0EBE7F0EBE7F0EBE7F0
      EBE7F0EBE7EBE6E0D7CCC4F1EDE9F2EFECEBEBEAD0D6D8F8F8F8F8F8F8F8F8F8
      D6D8D9EEEBE6F1EDE9F0ECE8F0ECE7F0EBE7F0ECE7F0ECE8F1EEEBF2EFEDEFEF
      EED9DCDFF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8D8DBDCEAE9E6F1EEEBF1EEEBF1
      EFEBF1EFEBF2EFEDF2F0EFEBEBEBD9DCDFF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8D0D6D8DCDFDFE7E7E7EFEEEBEFEFECE7E9E8DCE0E2D0D6D9F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
    GlyphKind = bkCustom
  end
  object next: TGlyphBtn
    Left = 90
    Top = 420
    Width = 75
    Height = 25
    Caption = '&Next'
    ModalResult = 5
    TabOrder = 4
    Glyph.Data = {
      36030000424D3603000000000000360000002800000010000000100000000100
      1800000000000003000000000000000000000000000000000000F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8BBC0C4999D9E76787962
      6261626261757777919596B1B8BAF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8B7BABC97979591908D9F9D9AA5A3A19C9A988583816262616B6D6D9CA0
      A2F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8C4C7C8B4B3B0BFBCB8D4D0CCE3DFDBE8
      E3DFE5E1DCD7D3D0B8B5B28583815F605F9CA0A2F8F8F8F8F8F8F8F8F8CCD2D4
      D3D2CFD9D5D1E5E1DCEDE8E3EFEBE6F0EBE7F0EBE7EFEBE6E7E3DFCBC6C38C8A
      886B6D6DB3B8BCF8F8F8F8F8F8DBDDDDEFEAE5ECE7E3EFEAE5D3C1B4DFD3CAF0
      EBE7F0EBE7F0EBE7EFEBE6E8E3DFC0BCB97B7A79949899F8F8F8F8F8F8E6E5E3
      F0ECE7F0EBE7EFEBE6BAA190B89D89CAB4A6EBE3DEF0EBE7F0EBE7EFEBE6DBD7
      D49D9B99828384F8F8F8F8F8F8EFEBE8F1EDE8F0EBE7F0EBE7AE9989AA8971B6
      9985BDA493D4C4B8F0EBE7F0EBE7E8E3DFB7B4B081807FF8F8F8F8F8F8EFEBE8
      F1EDEAF0EBE7F0EBE7AE9989A68570AC8A73AE8D76B2927DC9B3A4F0EBE7EEE9
      E4C8C3C092918EF8F8F8F8F8F8E7E7E6F1EFEBF0ECE8F0EBE7AE9989A4846EA0
      816D9A806ED0C4BAF0EBE7F0EBE7EFEBE6CCC8C4A9A9A8F8F8F8F8F8F8DCDFE0
      F2EFEDF1EEEAF0EBE7A79385907665BCACA0F0EBE7F0EBE7F0EBE7F0EBE7EEE9
      E4CECAC5BCC0C0F8F8F8F8F8F8D0D6D8EBEBEAF2EFECF1EDE9D7CCC4EBE6E0F0
      EBE7F0EBE7F0EBE7F0EBE7F0EBE7F0EBE7D4D3D0C9CFD0F8F8F8F8F8F8F8F8F8
      D9DCDFEFEFEEF2EFEDF1EEEBF0ECE8F0ECE7F0EBE7F0ECE7F0ECE8F1EDE9EEEB
      E6D6D8D9F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8D9DCDFEBEBEBF2F0EFF2EFEDF1
      EFEBF1EFEBF1EEEBF1EEEBEAE9E6D8DBDCF8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8D0D6D9DCE0E2E7E9E8EFEFECEFEEEBE7E7E7DCDFDFD0D6D8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8
      F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8F8}
    Layout = blGlyphRight
    GlyphKind = bkCustom
  end
end
