object EditForm1: TEditForm1
  Left = 296
  Top = 199
  Width = 525
  Height = 415
  Hint = 'S:\tas70\Samples\chartBarModal.DFM'
  Caption = 'Bar Chart Values & Captions'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFF9AF5F5F554FFBFF5F554FFCFF5F57CF5F5F5F5EB77FFFFF5F50000F5
    F5FFFFFF9AF5F5F554FFBFF5F577FFF5F5F57CF5F5F5F5F5F5FFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFFF5F5D3BFF5F59A54F5F5FF9AF5F5FFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFFEBF5F5F5F5F55EFFFF5454AFF5F5FFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFFBFF5BF54F5F52929EBF5F5F5F5EBFFFFF5F50000F5
    F5FFFFFFFFF5F59AFFFFFF9AF5D39AF5EBFF7FF5F5BFBFAF44FFFFF5F50000F5
    F5FFBFF5FFF5F59A9AF5545EF5F5AFF5BFFF9AF5F5FF549A77FFFFF5F50000F5
    F5FFBFF59AF5F5BFBFF55429F5F5F5F59AFF9AF5F59ABFF5BFFFFFF5F50000F5
    F5FFBFF5F5F5F5F5F5F554FFEBF5F5F577FF44F5F5F5F5F5BFFFFFF5F50000F5
    F5FF4454545454545454FFFF44545454FFFFFF445454545444FFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  No_Refresh = False
  OnStart = 'barStart'
  ScreenPos = tpDesigned
  SpecifiedTop = 0
  SpecifiedLeft = 0
  RememberSizeDate = 38614.729591284730000000
  SourceAttached = False
  DesignSize = (
    517
    381)
  PixelsPerInch = 96
  TextHeight = 16
  object RxLabel3: TRxLabel
    Left = 39
    Top = 152
    Width = 98
    Height = 16
    Caption = 'Series 1 Values:'
  end
  object RxLabel5: TRxLabel
    Left = 39
    Top = 80
    Width = 89
    Height = 16
    Caption = 'Series 1 Label:'
  end
  object RxLabel46: TRxLabel
    Left = 27
    Top = 174
    Width = 9
    Height = 16
    Caption = '1'
  end
  object RxLabel47: TRxLabel
    Left = 26
    Top = 206
    Width = 9
    Height = 16
    Caption = '2'
  end
  object RxLabel48: TRxLabel
    Left = 26
    Top = 238
    Width = 9
    Height = 16
    Caption = '3'
  end
  object RxLabel2: TRxLabel
    Left = 8
    Top = 10
    Width = 85
    Height = 16
    Caption = 'Chart Caption:'
  end
  object RxLabel1: TRxLabel
    Left = 183
    Top = 152
    Width = 98
    Height = 16
    Caption = 'Series 2 Values:'
  end
  object RxLabel4: TRxLabel
    Left = 183
    Top = 80
    Width = 89
    Height = 16
    Caption = 'Series 2 Label:'
  end
  object RxLabel6: TRxLabel
    Left = 171
    Top = 174
    Width = 9
    Height = 16
    Caption = '1'
  end
  object RxLabel7: TRxLabel
    Left = 170
    Top = 206
    Width = 9
    Height = 16
    Caption = '2'
  end
  object RxLabel8: TRxLabel
    Left = 170
    Top = 238
    Width = 9
    Height = 16
    Caption = '3'
  end
  object RxLabel12: TRxLabel
    Left = 327
    Top = 152
    Width = 98
    Height = 16
    Caption = 'Series 3 Values:'
  end
  object RxLabel13: TRxLabel
    Left = 327
    Top = 80
    Width = 89
    Height = 16
    Caption = 'Series 3 Label:'
  end
  object RxLabel14: TRxLabel
    Left = 315
    Top = 174
    Width = 9
    Height = 16
    Caption = '1'
  end
  object RxLabel15: TRxLabel
    Left = 314
    Top = 206
    Width = 9
    Height = 16
    Caption = '2'
  end
  object RxLabel16: TRxLabel
    Left = 314
    Top = 238
    Width = 9
    Height = 16
    Caption = '3'
  end
  object Label1: TLabel
    Left = 40
    Top = 275
    Width = 82
    Height = 16
    Caption = 'Series 1 Color'
  end
  object Label2: TLabel
    Left = 184
    Top = 275
    Width = 82
    Height = 16
    Caption = 'Series 2 Color'
  end
  object Label3: TLabel
    Left = 328
    Top = 275
    Width = 82
    Height = 16
    Caption = 'Series 3 Color'
  end
  object gd1: TGradient
    Left = 40
    Top = 328
    Width = 120
    Height = 16
    ColorBegin = clBtnFace
  end
  object gd2: TGradient
    Left = 184
    Top = 328
    Width = 120
    Height = 16
    ColorBegin = clBtnFace
  end
  object gd3: TGradient
    Left = 328
    Top = 328
    Width = 120
    Height = 16
    ColorBegin = clBtnFace
  end
  object entBarSL1: TTASENTER
    Left = 39
    Top = 100
    Width = 121
    Height = 24
    TabOrder = 1
    FieldName = 'BarSLBL[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object NumbarSV11: TTASNumEnter
    Left = 39
    Top = 172
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 2
    FieldName = 'BarSval1[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object btnbarModal: TButton
    Left = 428
    Top = 355
    Width = 75
    Height = 25
    Anchors = [akRight, akBottom]
    Caption = 'Ok'
    ModalResult = 1
    TabOrder = 16
  end
  object entBarCaption: TTASENTER
    Left = 8
    Top = 28
    Width = 288
    Height = 24
    TabOrder = 0
    FieldName = 'BarCaption'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object numbarSV12: TTASNumEnter
    Left = 39
    Top = 204
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 3
    FieldName = 'barSval1[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object NumbarSV13: TTASNumEnter
    Left = 39
    Top = 236
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 4
    FieldName = 'barSval1[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASENTER1: TTASENTER
    Left = 183
    Top = 100
    Width = 121
    Height = 24
    TabOrder = 6
    FieldName = 'BarSLBL[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object TASNumEnter1: TTASNumEnter
    Left = 183
    Top = 172
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 7
    FieldName = 'BarSval2[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter2: TTASNumEnter
    Left = 183
    Top = 204
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 8
    FieldName = 'barSval2[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter3: TTASNumEnter
    Left = 183
    Top = 236
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 9
    FieldName = 'barSval2[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASENTER2: TTASENTER
    Left = 327
    Top = 100
    Width = 121
    Height = 24
    TabOrder = 11
    FieldName = 'BarSLBL[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object TASNumEnter7: TTASNumEnter
    Left = 327
    Top = 172
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 12
    FieldName = 'BarSval3[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter8: TTASNumEnter
    Left = 327
    Top = 204
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 13
    FieldName = 'barSval3[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter9: TTASNumEnter
    Left = 327
    Top = 236
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    FormatOnEditing = True
    TabOrder = 14
    FieldName = 'barSval3[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object cmbColor1: TTASNumEnter
    Left = 40
    Top = 296
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    TabOrder = 5
    FieldName = 'BarColor[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 20
    FldModified = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
  end
  object cmbColor2: TTASNumEnter
    Left = 184
    Top = 296
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    TabOrder = 10
    FieldName = 'BarColor[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 20
    FldModified = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
  end
  object cmbColor3: TTASNumEnter
    Left = 328
    Top = 296
    Width = 121
    Height = 21
    AutoSize = False
    DisplayFormat = '0'
    TabOrder = 15
    FieldName = 'BarColor[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 20
    FldModified = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
  end
end
