object EditForm1: TEditForm1
  Left = 341
  Top = 152
  Width = 468
  Height = 532
  Hint = 'S:\tas70\Samples\ChartDemo.DFM'
  Caption = 'Addsum TAS 7i Chart Demo Program'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    000001000100202010FF00000000E80200001600000028000000200000004000
    0000010004000000000000000000000000000000000000000000000000000000
    0000000080000080000000808000800000008000800080800000C0C0C0008080
    80000000FF0000FF000000FFFF00FF000000FF00FF00FFFF0000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000FFFFFFFFF00000000000000000000FFFFFFFFFFFFFFF00000000000
    0000FFFFFFFFFFFFFFFFFF0000000000000FFFFFF00000000FFFFFFF00000000
    00FFFFF0000000000000FFFF000000000FFFF0000000000000000FFFF0000000
    0FFF000000000000000000FFFF000000FFFF000FFFF000FFFFF0000000000000
    FFF000FFFFFF0FFFFFFF00000000000FFFF00FFFFFFFFFFFFFFFFF000000000F
    FF00FFFFFFFFFFFFF00FFFF00000000FFF00FFFFF000FFFFF000FFF00000000F
    FF00FFFF00000FFFF0000FFF0000000FFF00FFFF00000FFFF0000FFF0000000F
    FF00FFFF000000FFFF0000FFF000000FFF00FFFF000000FFFF0000FFF000000F
    FF00FFFFF00000FFFF0000FFF0000000FFF00FFFF00000FFFF0000FFF0000000
    FFF00FFFFF000FFFFF0000FFF0000000FFF000FFFFFFFFFFFF0000FFF0000000
    0FFF00FFFFFFFFFFFFF00FFFF00000000FFFF00FFFFFFF0FFFF00FFF00000000
    00FFFF000FFFF00FFFF0FFFF00000000000FFFF000000000000FFFF000000000
    0000FFFFF00000000FFFFF000000000000000FFFFFFFFFFFFFFFF00000000000
    000000FFFFFFFFFFFFFF000000000000000000000FFFFFFFF000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000}
  OldCreateOrder = False
  Position = poDesktopCenter
  No_Refresh = False
  ScreenPos = tpDesktopCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  RememberSizeDate = 38614.831082766210000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object LineChart: TLineChart
    Left = 2
    Top = 64
    Width = 442
    Height = 352
    NSeries = 2
    NPoint = 6
    BorderWidth = 15
    ForeColor = clWindowText
    BackColor = clWindow
    Legend.Alignment = laRight
    Legend.Color = clWindow
    Legend.Frame = True
    Legend.Visible = True
    Legend.MaxWidth = 50
    AntiAlias = aaHi
    BitmapImageH = 0
    BitmapImageW = 0
    BitmapImageB = 0
    SeriesColor1 = clBlue
    SeriesColor2 = clRed
    SeriesColor3 = clLime
    SeriesColor4 = clAqua
    SeriesColor5 = clYellow
    SeriesColor6 = clFuchsia
    SeriesColor7 = clNavy
    SeriesColor8 = clMaroon
    SeriesColor9 = clGreen
    SeriesColor10 = clTeal
    SeriesColor11 = clBlack
    SeriesColor12 = clBlack
    SeriesColor13 = clBlack
    SeriesColor14 = clBlack
    SeriesColor15 = clBlack
    SeriesColor16 = clBlack
    SeriesColor17 = clBlack
    SeriesColor18 = clBlack
    SeriesColor19 = clBlack
    SeriesColor20 = clBlack
    SeriesColor21 = clBlack
    SeriesColor22 = clBlack
    SeriesColor23 = clBlack
    SeriesColor24 = clBlack
    SeriesColor25 = clBlack
    SeriesColor26 = clBlack
    SeriesColor27 = clBlack
    SeriesColor28 = clBlack
    SeriesColor29 = clBlack
    SeriesColor30 = clBlack
    SeriesColor31 = clBlack
    SeriesColor32 = clBlack
    SeriesColor33 = clBlack
    SeriesColor34 = clBlack
    SeriesColor35 = clBlack
    SeriesColor36 = clBlack
    BarStyle1 = bsBar
    BarStyle2 = bsBar
    BarStyle3 = bsBar
    BarStyle4 = bsBar
    BarStyle5 = bsBar
    BarStyle6 = bsBar
    BarStyle7 = bsBar
    BarStyle8 = bsBar
    BarStyle9 = bsBar
    BarStyle10 = bsBar
    BarStyle11 = bsBar
    BarStyle12 = bsBar
    BarStyle13 = bsBar
    BarStyle14 = bsBar
    BarStyle15 = bsBar
    BarStyle16 = bsBar
    BarStyle17 = bsBar
    BarStyle18 = bsBar
    BarStyle19 = bsBar
    BarStyle20 = bsBar
    BarStyle21 = bsBar
    BarStyle22 = bsBar
    BarStyle23 = bsBar
    BarStyle24 = bsBar
    BarStyle25 = bsBar
    BarStyle26 = bsBar
    BarStyle27 = bsBar
    BarStyle28 = bsBar
    BarStyle29 = bsBar
    BarStyle30 = bsBar
    BarStyle31 = bsBar
    BarStyle32 = bsBar
    BarStyle33 = bsBar
    BarStyle34 = bsBar
    BarStyle35 = bsBar
    BarStyle36 = bsBar
    ChartKind1 = ncLine
    ChartKind2 = ncLine
    ChartKind3 = ncLine
    ChartKind4 = ncLine
    ChartKind5 = ncLine
    ChartKind6 = ncLine
    ChartKind7 = ncLine
    ChartKind8 = ncLine
    ChartKind9 = ncLine
    ChartKind10 = ncLine
    ChartKind11 = ncLine
    ChartKind12 = ncLine
    ChartKind13 = ncLine
    ChartKind14 = ncLine
    ChartKind15 = ncLine
    ChartKind16 = ncLine
    ChartKind17 = ncLine
    ChartKind18 = ncLine
    ChartKind19 = ncLine
    ChartKind20 = ncLine
    ChartKind21 = ncLine
    ChartKind22 = ncLine
    ChartKind23 = ncLine
    ChartKind24 = ncLine
    ChartKind25 = ncLine
    ChartKind26 = ncLine
    ChartKind27 = ncLine
    ChartKind28 = ncLine
    ChartKind29 = ncLine
    ChartKind30 = ncLine
    ChartKind31 = ncLine
    ChartKind32 = ncLine
    ChartKind33 = ncLine
    ChartKind34 = ncLine
    ChartKind35 = ncLine
    ChartKind36 = ncLine
    XAxis = [aoVisible, aoLabel, aoLine, aoTick]
    YLeftAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
    YRightAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
    Options = [coRotateXLabel]
    WallColor = clBtnFace
    XGridColor = clBtnShadow
    YLeftGridColor = clBtnShadow
    YRightGridColor = clBtnShadow
    Percent3D = 10
    YLeftInitValue.Max = 10.000000000000000000
    YLeftInitValue.Enabled = True
    YRightInitValue.Max = 10.000000000000000000
    YRightInitValue.Enabled = True
    NVisiblePoint = 6
    LeftVisiblePoint = 1
    HintOptions = [hoSeries, hoPoint, hoValue, hoPercent, hoFocus]
    ParentShowHint = False
    ShowHint = True
    Visible = False
  end
  object PieChart: TPieChart
    Left = -8
    Top = 64
    Width = 442
    Height = 336
    Options = []
    Exploded = True
    PercentExplode = 30
    HintOptions = [hoSeries, hoPoint, hoValue, hoPercent, hoFocus]
    BitmapImageH = 0
    BitmapImageW = 0
    BitmapImageB = 0
    SeriesColor1 = clBlack
    SeriesColor2 = clBlack
    SeriesColor3 = clBlack
    SeriesColor4 = clBlack
    SeriesColor5 = clBlack
    SeriesColor6 = clBlack
    SeriesColor7 = clBlack
    SeriesColor8 = clBlack
    SeriesColor9 = clBlack
    SeriesColor10 = clBlack
    SeriesColor11 = clBlack
    SeriesColor12 = clBlack
    SeriesColor13 = clBlack
    SeriesColor14 = clBlack
    SeriesColor15 = clBlack
    SeriesColor16 = clBlack
    SeriesColor17 = clBlack
    SeriesColor18 = clBlack
    SeriesColor19 = clBlack
    SeriesColor20 = clBlack
    SeriesColor21 = clBlack
    SeriesColor22 = clBlack
    SeriesColor23 = clBlack
    SeriesColor24 = clBlack
    SeriesColor25 = clBlack
    SeriesColor26 = clBlack
    SeriesColor27 = clBlack
    SeriesColor28 = clBlack
    SeriesColor29 = clBlack
    SeriesColor30 = clBlack
    SeriesColor31 = clBlack
    SeriesColor32 = clBlack
    SeriesColor33 = clBlack
    SeriesColor34 = clBlack
    SeriesColor35 = clBlack
    SeriesColor36 = clBlack
    NSeries = 5
    NPoint = 1
    BorderWidth = 15
    ForeColor = clWindowText
    BackColor = clWindow
    Legend.Alignment = laRight
    Legend.Color = clWindow
    Legend.Frame = True
    Legend.Visible = True
    Legend.MaxWidth = 50
    AntiAlias = aaHi
    ValueFormat = None
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    ParentShowHint = False
    ShowHint = True
    Visible = False
  end
  object BarChart: TBarChart
    Left = 1
    Top = 75
    Width = 440
    Height = 333
    XAxis = [aoVisible, aoLabel, aoLine, aoTick]
    YAxis = [aoVisible, aoLabel, aoLine, aoTick, aoGrid]
    Options = []
    WallColor = clBtnFace
    XGridColor = clBtnShadow
    YGridColor = clBtnShadow
    Percent3D = 25
    XLabelPos = xlLeft
    HintOptions = [hoSeries, hoPoint, hoValue, hoPercent, hoFocus]
    SaveToBitmapBool = False
    BitmapImageH = 0
    BitmapImageW = 0
    BitmapImageB = 0
    SeriesColor1 = clBlue
    SeriesColor2 = clRed
    SeriesColor3 = clLime
    SeriesColor4 = clAqua
    SeriesColor5 = clYellow
    SeriesColor6 = clBlack
    SeriesColor7 = clBlack
    SeriesColor8 = clBlack
    SeriesColor9 = clBlack
    SeriesColor10 = clBlack
    SeriesColor11 = clBlack
    SeriesColor12 = clBlack
    SeriesColor13 = clBlack
    SeriesColor14 = clBlack
    SeriesColor15 = clBlack
    SeriesColor16 = clBlack
    SeriesColor17 = clBlack
    SeriesColor18 = clBlack
    SeriesColor19 = clBlack
    SeriesColor20 = clBlack
    SeriesColor21 = clBlack
    SeriesColor22 = clBlack
    SeriesColor23 = clBlack
    SeriesColor24 = clBlack
    SeriesColor25 = clBlack
    SeriesColor26 = clBlack
    SeriesColor27 = clBlack
    SeriesColor28 = clBlack
    SeriesColor29 = clBlack
    SeriesColor30 = clBlack
    SeriesColor31 = clBlack
    SeriesColor32 = clBlack
    SeriesColor33 = clBlack
    SeriesColor34 = clBlack
    SeriesColor35 = clBlack
    SeriesColor36 = clBlack
    BarStyle1 = bsBar
    BarStyle2 = bsBar
    BarStyle3 = bsBar
    BarStyle4 = bsBar
    BarStyle5 = bsBar
    BarStyle6 = bsBar
    BarStyle7 = bsBar
    BarStyle8 = bsBar
    BarStyle9 = bsBar
    BarStyle10 = bsBar
    BarStyle11 = bsBar
    BarStyle12 = bsBar
    BarStyle13 = bsBar
    BarStyle14 = bsBar
    BarStyle15 = bsBar
    BarStyle16 = bsBar
    BarStyle17 = bsBar
    BarStyle18 = bsBar
    BarStyle19 = bsBar
    BarStyle20 = bsBar
    BarStyle21 = bsBar
    BarStyle22 = bsBar
    BarStyle23 = bsBar
    BarStyle24 = bsBar
    BarStyle25 = bsBar
    BarStyle26 = bsBar
    BarStyle27 = bsBar
    BarStyle28 = bsBar
    BarStyle29 = bsBar
    BarStyle30 = bsBar
    BarStyle31 = bsBar
    BarStyle32 = bsBar
    BarStyle33 = bsBar
    BarStyle34 = bsBar
    BarStyle35 = bsBar
    BarStyle36 = bsBar
    NSeries = 3
    NPoint = 3
    BorderWidth = 15
    ForeColor = clWindowText
    BackColor = clWhite
    Legend.Alignment = laRight
    Legend.Color = clWindow
    Legend.Frame = True
    Legend.Visible = True
    Legend.MaxWidth = 50
    AntiAlias = aaHi
    ValueFormat = General
    ParentShowHint = False
    ShowHint = True
    Visible = False
  end
  object Label1: TLabel
    Left = 158
    Top = 11
    Width = 82
    Height = 16
    Caption = 'Bar chart type'
  end
  object Label2: TLabel
    Left = 160
    Top = 38
    Width = 113
    Height = 16
    Caption = 'Format for numbers'
  end
  object cmbFormat: TTASComboBox
    Left = 6
    Top = 35
    Width = 145
    Height = 24
    Style = csDropDownList
    DropDownCount = 6
    ItemHeight = 16
    TabOrder = 1
    Items.Strings = (
      'Exponent'
      'Fixed'
      'General'
      'Number'
      'Currency'
      'None')
    FieldName = 'formatType'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    DfltValue = 'Currency'
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 4984672
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object BtnValues: TButton
    Left = 248
    Top = 454
    Width = 99
    Height = 25
    Caption = 'Enter &Values'
    TabOrder = 2
  end
  object cmbChartType: TTASComboBox
    Left = 6
    Top = 5
    Width = 145
    Height = 24
    Style = csDropDownList
    DropDownCount = 3
    ItemHeight = 16
    TabOrder = 0
    Items.Strings = (
      'Bar Chart'
      'Line Chart'
      'Pie Chart')
    FieldName = 'ChartType'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    DfltValue = 'Bar Chart'
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 4984672
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object btnSave: TClrButton
    Left = 360
    Top = 454
    Width = 96
    Height = 25
    Caption = 'Save and &Print'
    TabOrder = 3
    Color = clBtnFace
    PrePrgLoc = -1
    PostPrgLoc = -1
    HotButton = True
    HotColor = clHighlight
    HotColorOut = clBtnFace
    FontColorIn = clHighlightText
    FontColorOut = clBlack
  end
  object StatusBar1: TStatusBar
    Left = 0
    Top = 486
    Width = 460
    Height = 19
    Panels = <>
  end
end
