object EditForm1: TEditForm1
  Left = 294
  Top = 196
  Width = 227
  Height = 706
  Hint = 'D:\TASPro6\ht6wo.DFM'
  HorzScrollBar.Visible = False
  VertScrollBar.Increment = 36
  VertScrollBar.Size = 9
  BorderIcons = [biSystemMenu, biMinimize]
  Caption = 'Work Orders'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000000000000A80C00001600000028000000200000004000
    0000010018000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000FFFFFFFFFFFF00
    0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000033CCFF33CCFF
    000000FFFFFFFFFFFFFFFFFF0000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000FF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000033CCFF33CCFF33CCFF
    000000FFFFFFFFFFFF0000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000FF
    FFFFFFFFFFFFFFFFFFFFFF00000000000033CCFF33CCFF33CCFF33CCFF33CCFF
    000000FFFFFF0000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000FF
    FFFFFFFFFF00000000000033CCFF33CCFF33CCFF33CCFF000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF33CCFF33CCFF0000006699CC6699CC6699CC
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF33CCFF0000006699CC6699CC6699CC6699CC
    6699CC0000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF33CCFF0000006699CC6699CC6699CC6699CC
    6699CC0000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF0000006699CC6699CC6699CC6699CC6699CC
    6699CC6699CC0000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF0000006699CC000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF0000006699CC0000006699CC6699CC6699CC
    6699CC6699CC6699CC6699CC6699CC6699CC0000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF0000006699CC6699CC6699CC6699CC6699CC
    6699CC6699CC6699CC6699CC6699CC6699CC0000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000033
    CCFF33CCFF00000033CCFF33CCFF33CCFF0000006699CC6699CC6699CC6699CC
    6699CC6699CC6699CC6699CC6699CC0000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000033
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF0000006699CC6699CC6699CC
    6699CC6699CC6699CC6699CC6699CC0000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000033CCFF33CCFF33CCFF33CCFF33CCFF33CCFF000000000000000000
    6699CC6699CC6699CC6699CC0000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000033CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000033
    CCFF33CCFF00000033CCFF33CCFF33CCFF00000000000000000000000033CCFF
    33CCFF33CCFF33CCFF33CCFF0000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000033CCFF33CCFF00
    000000000033CCFF33CCFF33CCFF000000FFFFFFFFFFFFFFFFFFFFFFFF000000
    33CCFF33CCFF33CCFF33CCFF0000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000033CCFF33CCFF00
    000033CCFF33CCFF33CCFF000000FFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFF
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000033CCFF33CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    000000FFFFFFFFFFFFFFFFFF0000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000033CCFF33CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    000000FFFFFF000000FFFFFF0000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000033CCFF33CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF33CCFF000000FFFFFFFFFFFFFFFFFFFFFFFF000000
    FFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000033CCFF33CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF000000000000000000000000000000
    FFFFFFFFFFFFFFFFFF0000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000033CCFF33CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000033CCFF33CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000033CCFF33CCFF33
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000033CCFF00000033
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000033CCFF33
    CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF33CCFF000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000033CCFF33CCFF33CCFF33CCFF33CCFF33CCFF000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FE00
    000FFF00001FFF80003FFFC0007FFFC000FFFFE001FFFFF000FFFFF000FFFFF0
    007FFFF0000FFFF00007FFE00007FFC0000FFFC0000FFF40001FFF40003FFF00
    001FFF00001FFF00003FFE00001FFE00001FFE00001FFE00003FFE00007FFE00
    01FFFF0003FFFF0003FFFE8007FFFE800FFFFF303FFFFF8DFFFFFFC3FFFF}
  OldCreateOrder = False
  No_Refresh = False
  OpenFiles = 'open.files'
  OnDisplayScreen = 'redraw'
  ScreenPos = tpSpecified
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'ht6wo'
  RememberSizeDate = 38160.570139328700000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 14
  object Label1: TLabel
    Left = 5
    Top = 52
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label2: TLabel
    Left = 92
    Top = 52
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel1: TBevel
    Left = -1
    Top = 87
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label3: TLabel
    Left = 5
    Top = 140
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label4: TLabel
    Left = 92
    Top = 140
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel2: TBevel
    Left = -1
    Top = 175
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label5: TLabel
    Left = 5
    Top = 228
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label6: TLabel
    Left = 92
    Top = 228
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel3: TBevel
    Left = -1
    Top = 263
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label7: TLabel
    Left = 5
    Top = 316
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label8: TLabel
    Left = 92
    Top = 316
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel4: TBevel
    Left = -1
    Top = 351
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label9: TLabel
    Left = 5
    Top = 404
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label10: TLabel
    Left = 92
    Top = 404
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel5: TBevel
    Left = -1
    Top = 439
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label11: TLabel
    Left = 5
    Top = 493
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label12: TLabel
    Left = 92
    Top = 493
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel6: TBevel
    Left = -1
    Top = 528
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label13: TLabel
    Left = 5
    Top = 581
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label14: TLabel
    Left = 92
    Top = 581
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel7: TBevel
    Left = -1
    Top = 616
    Width = 208
    Height = 15
    Shape = bsTopLine
  end
  object Label15: TLabel
    Left = 5
    Top = 669
    Width = 23
    Height = 28
    Caption = 'Start'#13#10'Qty'
  end
  object Label16: TLabel
    Left = 92
    Top = 669
    Width = 18
    Height = 28
    Caption = 'End'#13#10'Qty'
  end
  object Bevel8: TBevel
    Left = 16
    Top = 712
    Width = 167
    Height = 50
    Shape = bsTopLine
  end
  object wc: TTASENTER
    Left = 3
    Top = 7
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 0
    Text = 'workcenter'
    FieldName = 'WCT[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object Desc: TTASENTER
    Left = 3
    Top = 31
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 2
    Text = 'Desc'
    FieldName = 'desc[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY1: TTASNumEnter
    Left = 33
    Top = 56
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 3
    FieldName = 'sqty[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object eqty: TTASNumEnter
    Left = 116
    Top = 56
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 4
    FieldName = 'EQTY[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object Go1: TButton
    Left = 180
    Top = 55
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 5
  end
  object TASENTER1: TTASENTER
    Left = 3
    Top = 95
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 6
    Text = 'workcenter'
    FieldName = 'WCT[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER3: TTASENTER
    Left = 3
    Top = 119
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 8
    Text = 'Desc'
    FieldName = 'desc[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY2: TTASNumEnter
    Left = 33
    Top = 144
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 9
    FieldName = 'sqty[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter2: TTASNumEnter
    Left = 116
    Top = 144
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 10
    FieldName = 'eqty[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go2: TButton
    Left = 180
    Top = 143
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 11
  end
  object TASENTER4: TTASENTER
    Left = 3
    Top = 183
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 12
    Text = 'workcenter'
    FieldName = 'WCT[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER6: TTASENTER
    Left = 3
    Top = 207
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 14
    Text = 'Desc'
    FieldName = 'desc[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY3: TTASNumEnter
    Left = 33
    Top = 232
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 15
    FieldName = 'sqty[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter4: TTASNumEnter
    Left = 116
    Top = 232
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 16
    FieldName = 'eqty[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go3: TButton
    Left = 180
    Top = 231
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 17
  end
  object TASENTER7: TTASENTER
    Left = 3
    Top = 271
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 18
    Text = 'workcenter'
    FieldName = 'WCT[4]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER9: TTASENTER
    Left = 3
    Top = 295
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 20
    Text = 'Desc'
    FieldName = 'desc[4]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY4: TTASNumEnter
    Left = 33
    Top = 320
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 21
    FieldName = 'sqty[4]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter6: TTASNumEnter
    Left = 116
    Top = 320
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 22
    FieldName = 'eqty[4]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go4: TButton
    Left = 180
    Top = 319
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 23
  end
  object TASENTER10: TTASENTER
    Left = 3
    Top = 359
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 24
    Text = 'workcenter'
    FieldName = 'WCT[5]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER12: TTASENTER
    Left = 3
    Top = 383
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 26
    Text = 'Desc'
    FieldName = 'desc[5]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY5: TTASNumEnter
    Left = 33
    Top = 408
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 27
    FieldName = 'sqty[5]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter8: TTASNumEnter
    Left = 116
    Top = 408
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 28
    FieldName = 'eqty[5]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go5: TButton
    Left = 180
    Top = 407
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 29
  end
  object TASENTER13: TTASENTER
    Left = 3
    Top = 448
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 30
    Text = 'workcenter'
    FieldName = 'WCT[6]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER15: TTASENTER
    Left = 3
    Top = 472
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 32
    Text = 'Desc'
    FieldName = 'desc[6]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY6: TTASNumEnter
    Left = 33
    Top = 497
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 33
    FieldName = 'sqty[6]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter10: TTASNumEnter
    Left = 116
    Top = 497
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 34
    FieldName = 'eqty[6]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go6: TButton
    Left = 180
    Top = 496
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 35
  end
  object TASENTER16: TTASENTER
    Left = 3
    Top = 536
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 36
    Text = 'workcenter'
    FieldName = 'WCT[7]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER18: TTASENTER
    Left = 3
    Top = 560
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 38
    Text = 'Desc'
    FieldName = 'desc[7]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY7: TTASNumEnter
    Left = 33
    Top = 584
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 39
    FieldName = 'sqty[7]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter12: TTASNumEnter
    Left = 116
    Top = 585
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 40
    FieldName = 'eqty[7]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go7: TButton
    Left = 180
    Top = 584
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 41
  end
  object TASENTER19: TTASENTER
    Left = 3
    Top = 624
    Width = 73
    Height = 20
    TabStop = False
    Color = clInfoBk
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 42
    Text = 'workcenter'
    FieldName = 'WCT[8]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object TASENTER21: TTASENTER
    Left = 3
    Top = 648
    Width = 202
    Height = 20
    TabStop = False
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 44
    Text = 'Desc'
    FieldName = 'desc[8]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object SQTY8: TTASNumEnter
    Left = 33
    Top = 673
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 45
    FieldName = 'sqty[8]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object TASNumEnter14: TTASNumEnter
    Left = 116
    Top = 673
    Width = 51
    Height = 20
    AutoSize = False
    Ctl3D = False
    DisplayFormat = '0'
    ParentCtl3D = False
    TabOrder = 46
    FieldName = 'eqty[8]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = 0
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    FastSearchType = fsNum
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    ButtonWidthNum = 0
    FldModified = False
    GlyphKind = gkCustom
    NumGlyphs = 2
    ButtonWidth = 0
  end
  object go8: TButton
    Left = 180
    Top = 672
    Width = 25
    Height = 25
    Caption = 'Go'
    TabOrder = 47
  end
  object ITEM1: TTASComboEnter
    Left = 80
    Top = 7
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 1
    Text = 'ITEM1'
    FieldName = 'ITEM[1]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(1)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object ITEM2: TTASComboEnter
    Left = 80
    Top = 95
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 7
    Text = 'ITEM1'
    FieldName = 'ITEM[2]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(2)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object ITEM3: TTASComboEnter
    Left = 80
    Top = 183
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 13
    Text = 'ITEM1'
    FieldName = 'ITEM[3]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(3)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object ITEM4: TTASComboEnter
    Left = 80
    Top = 271
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 19
    Text = 'ITEM1'
    FieldName = 'ITEM[4]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(4)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object ITEM5: TTASComboEnter
    Left = 79
    Top = 359
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 25
    Text = 'ITEM1'
    FieldName = 'ITEM[5]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(5)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object ITEM6: TTASComboEnter
    Left = 79
    Top = 448
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 31
    Text = 'ITEM1'
    FieldName = 'ITEM[6]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(6)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object ITEM7: TTASComboEnter
    Left = 79
    Top = 536
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 37
    Text = 'ITEM1'
    FieldName = 'ITEM[7]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(7)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object ITEM8: TTASComboEnter
    Left = 79
    Top = 624
    Width = 125
    Height = 20
    CharCase = ecUpperCase
    Ctl3D = False
    GlyphKind = gkEllipsis
    NumGlyphs = 1
    ParentCtl3D = False
    TabOrder = 43
    Text = 'ITEM1'
    FieldName = 'ITEM[8]'
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = True
    ValidUserEsc = False
    ValidExpr = 'chk.item(8)'
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = True
  end
  object refreshtimer: TRtnTimer
    Enabled = False
    Interval = 10000
    CallPrgLoc = 0
    SecondsBtwnCalls = 10
    Left = 8
    Top = 56
  end
end
