object EditForm1: TEditForm1
  Left = 443
  Top = 145
  Hint = 'C:\TASPro7\DBA7\T7DET.DFM'
  AutoScroll = False
  Caption = 'Web Import'
  ClientHeight = 591
  ClientWidth = 685
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = []
  FormStyle = fsStayOnTop
  Icon.Data = {
    0000010001002020000001000800A80800001600000028000000200000004000
    0000010008000000000080040000000000000000000000000000000000000000
    0000DED3FF00D6D3FF00FF00FF000000FF00E7FFF700ADF7F700ADE3F700ADCF
    F700ADBEF700F7AAF700E7AAF700CEAAF700BDAAF700ADAAF700E7FFEF00D6FB
    EF00EFEFEF0084EFEF0063EBEF00E7E3EF0084D7EF00FFD3EF0063CBEF0084BA
    EF0063A6EF00849EEF00EF86EF00D686EF00BD86EF009C86EF008C86EF006382
    EF00EF61EF00CE61EF00A561EF008461EF006361EF00D6FBE700ADF7E70039E7
    E700EFE3E700FFD3E700D6D3E70039BAE700F7AAE700398EE7003965E700423C
    E700E738E700BD38E7008C38E7006338E700D6FBDE00FFD3DE00C6C3DE00FFFB
    D600EFFBD600E7FBD600DEFBD600D6FBD600FFEFD60084EFD600FFE7D600FFDB
    D600D6D7D60018D7D600FFD3D600E7D3D600B5B2D60018AAD600EF86D6001879
    D600184DD600D61CD600AD1CD6007B1CD6004A1CD600211CD600ADF7CE0063EB
    CE00F7AACE00A5A2CE00EF61CE00DEC3C6009492C600ADF7BD0084EFBD0039E7
    BD00BDBEBD00F7AABD00EF86BD008482BD00E738BD00D6B2B50018B2B500188A
    B5007371B5001865B5001841B500B518B5008C18B5006318B5003918B5001818
    B500F7F7AD00E7F7AD00CEF7AD00BDF7AD00ADF7AD00F7E3AD0018D7AD00F7CF
    AD00F7BEAD00F7AAAD006361AD00D61CAD0063EBA500A5A6A500CEA2A500A5A2
    A500EF61A5005251A50084EF9C00C69A9C00EF869C0042419C00C69294003130
    940039E78C0018B28C008C8E8C00108E8C00106D8C0010518C00E7388C001030
    8C0021208C00B5188C0010148C008C108C006B108C0052108C0031108C00EFEF
    8400D6EF8400BDEF84009CEF840084EF840063EB8400EFD78400EFBA8400EF9E
    8400EF868400BD828400EF618400101084000000840018D77B00D61C7B007375
    7300108E6B008C106B00EFEB6300CEEB6300A5EB630084EB630063EB630039E7
    6300EFCB630018B26300EFA66300EF82630008656300EF616300AD6163000851
    6300E738630008246300B5186300630C6300520C6300390C63005A5D5A00108E
    5200086552008C105200630C520018D74A00D61C4A00424542009C414200E7E7
    3900BDE739008CE7390063E7390039E73900E7BA390018B23900E78E3900E765
    390008653900393C3900E7383900B5183900630C3900108E3100943031003130
    31008C103100086521008C202100D6D71800ADD718007BD718004AD71800B5B2
    18008CB2180063B2180039B21800D6AA1800B58A1800D6791800B5651800D64D
    1800B53C1800D61C1800B51818008C8E10006B8E1000528E1000108E10008C6D
    10008C5110008C30100084101000636508005265080021650800635108006338
    080063240800FFFF000000FF0000FF0000008400000000000000000000000000
    0000000000000000000000000000000000000000000000000000FFFFFF000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    00000000000000000000000000000000000000000000000000000000000000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF59AFF5F5AF7CFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFBFF576FF599AAF59FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFF5F5AF7CFFFF59BF59FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFAFF57F9ABF9AFF59AFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFF7CF5AFFFFFAFBF78FFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFAFF57CFFFF9AF578FFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFAFBF59FFFFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFAFBF59FFF5BFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFF7CAFF5BF7CFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F50000F5
    F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5F5000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    0001800000018000000180000001800000018000000180000001800000018000
    00018000000180000001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF}
  OldCreateOrder = False
  OnClose = 'T7DET.OnClose'
  No_Refresh = False
  OnStart = 'T7DET.OnStart'
  OpenFiles = 'T7DET.OnOpenFiles'
  OnDisplayScreen = 'T7DET.OnDisp'
  ScreenPos = tpScreenCenter
  SpecifiedTop = 0
  SpecifiedLeft = 0
  SourceFile = 'T7DET'
  RememberSize = True
  RememberSizeDate = 45433.699803807870000000
  SourceAttached = False
  PixelsPerInch = 96
  TextHeight = 16
  object Panel1: TPanel
    Left = 0
    Top = 29
    Width = 685
    Height = 528
    Align = alClient
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 1
    object ImpFldsPanel: TPanel
      Left = 2
      Top = 2
      Width = 681
      Height = 524
      Align = alClient
      ParentBackground = False
      TabOrder = 2
      object GroupBox3: TGroupBox
        Left = 176
        Top = 1
        Width = 165
        Height = 520
        Hint = 'Import SO Header Records (BKARINV)'
        Caption = 'Order Header Records'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 0
        object Label11: TLabel
          Left = 5
          Top = 21
          Width = 155
          Height = 16
          Caption = 'Rec Designator Type = H'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label13: TLabel
          Left = 5
          Top = 42
          Width = 100
          Height = 16
          Caption = '**Customer Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label14: TLabel
          Left = 5
          Top = 60
          Width = 91
          Height = 16
          Caption = '**Order Number'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label15: TLabel
          Left = 5
          Top = 77
          Width = 81
          Height = 16
          Caption = 'Ship To Name'
        end
        object Label16: TLabel
          Left = 5
          Top = 111
          Width = 105
          Height = 16
          Caption = 'Ship To Address 2'
        end
        object Label17: TLabel
          Left = 5
          Top = 128
          Width = 70
          Height = 16
          Caption = 'Ship To City'
        end
        object Label26: TLabel
          Left = 5
          Top = 145
          Width = 78
          Height = 16
          Caption = 'Ship To State'
        end
        object Label27: TLabel
          Left = 5
          Top = 162
          Width = 118
          Height = 16
          Caption = 'Ship To Postal Code'
        end
        object Label28: TLabel
          Left = 5
          Top = 179
          Width = 92
          Height = 16
          Caption = 'Ship To Country'
        end
        object Label29: TLabel
          Left = 5
          Top = 196
          Width = 92
          Height = 16
          Caption = 'Ship To Contact'
        end
        object Label30: TLabel
          Left = 5
          Top = 213
          Width = 105
          Height = 16
          Caption = 'Ship To Telephone'
        end
        object Label31: TLabel
          Left = 5
          Top = 230
          Width = 59
          Height = 16
          Caption = 'Tax Group'
        end
        object Label47: TLabel
          Left = 5
          Top = 94
          Width = 105
          Height = 16
          Caption = 'Ship To Address 1'
        end
        object Label49: TLabel
          Left = 5
          Top = 281
          Width = 57
          Height = 16
          Caption = 'Sales Tax'
        end
        object Label50: TLabel
          Left = 5
          Top = 247
          Width = 84
          Height = 16
          Caption = 'Order Subtotal'
        end
        object Label51: TLabel
          Left = 5
          Top = 264
          Width = 40
          Height = 16
          Caption = 'Freight'
        end
        object Label52: TLabel
          Left = 5
          Top = 298
          Width = 63
          Height = 16
          Caption = 'Order Total'
        end
        object Label38: TLabel
          Left = 5
          Top = 315
          Width = 49
          Height = 16
          Caption = 'Ship Via'
        end
        object Label73: TLabel
          Left = 118
          Top = 44
          Width = 34
          Height = 14
          Caption = 'Field...'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsItalic]
          ParentFont = False
        end
        object Label74: TLabel
          Left = 153
          Top = 42
          Width = 7
          Height = 16
          Caption = '2'
        end
        object Label75: TLabel
          Left = 127
          Top = 60
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label76: TLabel
          Left = 153
          Top = 60
          Width = 7
          Height = 16
          Caption = '3'
        end
        object Label77: TLabel
          Left = 127
          Top = 77
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label78: TLabel
          Left = 153
          Top = 77
          Width = 7
          Height = 16
          Caption = '4'
        end
        object Label79: TLabel
          Left = 127
          Top = 94
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label80: TLabel
          Left = 153
          Top = 94
          Width = 7
          Height = 16
          Caption = '5'
        end
        object Label81: TLabel
          Left = 127
          Top = 111
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label82: TLabel
          Left = 153
          Top = 111
          Width = 7
          Height = 16
          Caption = '6'
        end
        object Label83: TLabel
          Left = 127
          Top = 128
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label84: TLabel
          Left = 153
          Top = 128
          Width = 7
          Height = 16
          Caption = '7'
        end
        object Label85: TLabel
          Left = 127
          Top = 145
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label86: TLabel
          Left = 153
          Top = 145
          Width = 7
          Height = 16
          Caption = '8'
        end
        object Label87: TLabel
          Left = 127
          Top = 162
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label88: TLabel
          Left = 153
          Top = 162
          Width = 7
          Height = 16
          Caption = '9'
        end
        object Label89: TLabel
          Left = 127
          Top = 179
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label90: TLabel
          Left = 148
          Top = 179
          Width = 14
          Height = 16
          Caption = '10'
        end
        object Label91: TLabel
          Left = 127
          Top = 196
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label92: TLabel
          Left = 148
          Top = 196
          Width = 13
          Height = 16
          Caption = '11'
        end
        object Label93: TLabel
          Left = 148
          Top = 213
          Width = 14
          Height = 16
          Caption = '12'
        end
        object Label94: TLabel
          Left = 127
          Top = 213
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label95: TLabel
          Left = 127
          Top = 230
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label96: TLabel
          Left = 148
          Top = 230
          Width = 14
          Height = 16
          Caption = '13'
        end
        object Label97: TLabel
          Left = 127
          Top = 247
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label98: TLabel
          Left = 148
          Top = 247
          Width = 14
          Height = 16
          Caption = '14'
        end
        object Label99: TLabel
          Left = 127
          Top = 264
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label100: TLabel
          Left = 148
          Top = 264
          Width = 14
          Height = 16
          Caption = '15'
        end
        object Label101: TLabel
          Left = 127
          Top = 281
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label102: TLabel
          Left = 148
          Top = 281
          Width = 14
          Height = 16
          Caption = '16'
        end
        object Label103: TLabel
          Left = 127
          Top = 298
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label104: TLabel
          Left = 148
          Top = 298
          Width = 14
          Height = 16
          Caption = '17'
        end
        object Label105: TLabel
          Left = 127
          Top = 315
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label106: TLabel
          Left = 148
          Top = 315
          Width = 14
          Height = 16
          Caption = '18'
        end
        object Label120: TLabel
          Left = 5
          Top = 332
          Width = 137
          Height = 16
          Caption = 'Ship To Customer Code'
        end
        object Label121: TLabel
          Left = 5
          Top = 349
          Width = 128
          Height = 16
          Caption = 'Customer PO Number'
        end
        object Label122: TLabel
          Left = 5
          Top = 366
          Width = 49
          Height = 16
          Caption = 'Location'
        end
        object Label123: TLabel
          Left = 142
          Top = 332
          Width = 8
          Height = 16
          Caption = '..'
        end
        object Label124: TLabel
          Left = 148
          Top = 332
          Width = 14
          Height = 16
          Caption = '19'
        end
        object Label125: TLabel
          Left = 134
          Top = 349
          Width = 16
          Height = 16
          Caption = '....'
        end
        object Label126: TLabel
          Left = 148
          Top = 349
          Width = 14
          Height = 16
          Caption = '20'
        end
        object Label127: TLabel
          Left = 127
          Top = 366
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label128: TLabel
          Left = 148
          Top = 366
          Width = 14
          Height = 16
          Caption = '21'
        end
        object Label153: TLabel
          Left = 5
          Top = 383
          Width = 52
          Height = 16
          Caption = 'Currency'
        end
        object Label155: TLabel
          Left = 148
          Top = 383
          Width = 14
          Height = 16
          Caption = '22'
        end
        object Label156: TLabel
          Left = 5
          Top = 400
          Width = 68
          Height = 16
          Caption = '*Order Date'
        end
        object Label158: TLabel
          Left = 149
          Top = 400
          Width = 14
          Height = 16
          Caption = '23'
        end
        object Label154: TLabel
          Left = 127
          Top = 383
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label157: TLabel
          Left = 127
          Top = 400
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label246: TLabel
          Left = 5
          Top = 417
          Width = 89
          Height = 16
          Caption = 'Sales Person 1'
        end
        object Label247: TLabel
          Left = 127
          Top = 417
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label248: TLabel
          Left = 149
          Top = 417
          Width = 14
          Height = 16
          Caption = '24'
        end
        object Label249: TLabel
          Left = 5
          Top = 434
          Width = 89
          Height = 16
          Caption = 'Sales Person 2'
        end
        object Label250: TLabel
          Left = 127
          Top = 434
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label251: TLabel
          Left = 149
          Top = 434
          Width = 14
          Height = 16
          Caption = '25'
        end
        object Label256: TLabel
          Left = 5
          Top = 451
          Width = 84
          Height = 16
          Caption = 'Cust Ref Code'
        end
        object Label257: TLabel
          Left = 5
          Top = 468
          Width = 69
          Height = 16
          Caption = 'Job Number'
        end
        object Label258: TLabel
          Left = 127
          Top = 451
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label259: TLabel
          Left = 127
          Top = 468
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label260: TLabel
          Left = 149
          Top = 451
          Width = 14
          Height = 16
          Caption = '26'
        end
        object Label261: TLabel
          Left = 149
          Top = 468
          Width = 14
          Height = 16
          Caption = '27'
        end
        object Label262: TLabel
          Left = 5
          Top = 485
          Width = 101
          Height = 16
          Caption = 'Order Description'
        end
        object Label263: TLabel
          Left = 127
          Top = 485
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label264: TLabel
          Left = 149
          Top = 485
          Width = 14
          Height = 16
          Caption = '28'
        end
        object Label268: TLabel
          Left = 5
          Top = 502
          Width = 84
          Height = 16
          Caption = 'Terms Number'
        end
        object Label270: TLabel
          Left = 149
          Top = 502
          Width = 14
          Height = 16
          Caption = '29'
        end
        object Label269: TLabel
          Left = 127
          Top = 502
          Width = 24
          Height = 16
          Caption = '......'
        end
      end
      object GroupBox4: TGroupBox
        Left = 344
        Top = 1
        Width = 165
        Height = 342
        Hint = 'Import SO Line Records (BKARINVL)'
        Caption = 'Order Line Records'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 1
        object Label32: TLabel
          Left = 5
          Top = 21
          Width = 154
          Height = 16
          Caption = 'Rec Designator Type = L'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label33: TLabel
          Left = 5
          Top = 42
          Width = 91
          Height = 16
          Caption = '**Order Number'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label34: TLabel
          Left = 5
          Top = 60
          Width = 84
          Height = 16
          Caption = '**Item Number'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label35: TLabel
          Left = 5
          Top = 77
          Width = 59
          Height = 16
          Caption = '**Quantity'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label36: TLabel
          Left = 5
          Top = 94
          Width = 57
          Height = 16
          Caption = 'Unit Price'
        end
        object Label37: TLabel
          Left = 5
          Top = 111
          Width = 51
          Height = 16
          Caption = 'Discount'
        end
        object Label69: TLabel
          Left = 117
          Top = 44
          Width = 34
          Height = 14
          Caption = 'Field...'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsItalic]
          ParentFont = False
        end
        object Label70: TLabel
          Left = 153
          Top = 42
          Width = 7
          Height = 16
          Caption = '2'
        end
        object Label71: TLabel
          Left = 127
          Top = 60
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label72: TLabel
          Left = 153
          Top = 60
          Width = 7
          Height = 16
          Caption = '3'
        end
        object Label107: TLabel
          Left = 127
          Top = 77
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label108: TLabel
          Left = 153
          Top = 77
          Width = 7
          Height = 16
          Caption = '4'
        end
        object Label109: TLabel
          Left = 127
          Top = 94
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label110: TLabel
          Left = 153
          Top = 94
          Width = 7
          Height = 16
          Caption = '5'
        end
        object Label111: TLabel
          Left = 127
          Top = 111
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label112: TLabel
          Left = 153
          Top = 111
          Width = 7
          Height = 16
          Caption = '6'
        end
        object Label117: TLabel
          Left = 5
          Top = 128
          Width = 125
          Height = 16
          Caption = '*Estimated Ship Date'
        end
        object Label118: TLabel
          Left = 5
          Top = 145
          Width = 84
          Height = 16
          Caption = '*Promise Date'
        end
        object DateFLabel: TLabel
          Left = 3
          Top = 256
          Width = 134
          Height = 16
          Caption = '*Format (YYYYMMDD)'
        end
        object Label129: TLabel
          Left = 127
          Top = 145
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label130: TLabel
          Left = 153
          Top = 145
          Width = 7
          Height = 16
          Caption = '8'
        end
        object Label131: TLabel
          Left = 127
          Top = 128
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label132: TLabel
          Left = 153
          Top = 128
          Width = 7
          Height = 16
          Caption = '7'
        end
        object Label136: TLabel
          Left = 3
          Top = 282
          Width = 100
          Height = 16
          Caption = '**Required Fields'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label145: TLabel
          Left = 5
          Top = 162
          Width = 94
          Height = 16
          Caption = 'Item Description'
        end
        object Label146: TLabel
          Left = 127
          Top = 162
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label147: TLabel
          Left = 153
          Top = 162
          Width = 7
          Height = 16
          Caption = '9'
        end
        object Label119: TLabel
          Left = 5
          Top = 179
          Width = 104
          Height = 16
          Caption = '***SO Line # (Ref)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlue
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label160: TLabel
          Left = 127
          Top = 179
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label161: TLabel
          Left = 148
          Top = 179
          Width = 14
          Height = 16
          Caption = '10'
        end
        object Label244: TLabel
          Left = 3
          Top = 306
          Width = 152
          Height = 16
          Caption = '***Required for INFO Recs'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlue
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label271: TLabel
          Left = 5
          Top = 196
          Width = 119
          Height = 16
          Caption = 'Back Order Quantity'
        end
        object Label272: TLabel
          Left = 127
          Top = 196
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label273: TLabel
          Left = 148
          Top = 196
          Width = 13
          Height = 16
          Caption = '11'
        end
      end
      object GroupBox5: TGroupBox
        Left = 344
        Top = 383
        Width = 165
        Height = 138
        Hint = 'Import Payment Record (BKARINVT)'
        Caption = 'Payment Records'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 2
        object Label44: TLabel
          Left = 5
          Top = 21
          Width = 155
          Height = 16
          Caption = 'Rec Designator Type = P'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label45: TLabel
          Left = 5
          Top = 42
          Width = 91
          Height = 16
          Caption = '**Order Number'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label46: TLabel
          Left = 5
          Top = 62
          Width = 110
          Height = 16
          Caption = '**Payment Amount'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label113: TLabel
          Left = 118
          Top = 44
          Width = 34
          Height = 14
          Caption = 'Field...'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsItalic]
          ParentFont = False
        end
        object Label114: TLabel
          Left = 153
          Top = 42
          Width = 7
          Height = 16
          Caption = '2'
        end
        object Label115: TLabel
          Left = 127
          Top = 62
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label116: TLabel
          Left = 153
          Top = 62
          Width = 7
          Height = 16
          Caption = '3'
        end
        object Label138: TLabel
          Left = 21
          Top = 104
          Width = 100
          Height = 16
          Caption = '**Required Fields'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
      end
      object GroupBox2: TGroupBox
        Left = 8
        Top = 1
        Width = 165
        Height = 520
        Hint = 'Import Customer Record (BKARCUST)'
        Caption = 'Customer Records'
        Ctl3D = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Arial'
        Font.Style = []
        ParentCtl3D = False
        ParentFont = False
        ParentShowHint = False
        ShowHint = True
        TabOrder = 3
        object Label12: TLabel
          Left = 5
          Top = 21
          Width = 155
          Height = 16
          Caption = 'Rec Designator Type = C'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label18: TLabel
          Left = 5
          Top = 42
          Width = 100
          Height = 16
          Caption = '**Customer Code'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label19: TLabel
          Left = 5
          Top = 60
          Width = 104
          Height = 16
          Caption = '**Customer Name'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label20: TLabel
          Left = 5
          Top = 77
          Width = 97
          Height = 16
          Caption = 'Bill To Address 1'
        end
        object Label21: TLabel
          Left = 5
          Top = 94
          Width = 97
          Height = 16
          Caption = 'Bill To Address 2'
        end
        object Label22: TLabel
          Left = 5
          Top = 111
          Width = 23
          Height = 16
          Caption = 'City'
        end
        object Label23: TLabel
          Left = 5
          Top = 128
          Width = 31
          Height = 16
          Caption = 'State'
        end
        object Label24: TLabel
          Left = 5
          Top = 145
          Width = 71
          Height = 16
          Caption = 'Postal Code'
        end
        object Label25: TLabel
          Left = 5
          Top = 162
          Width = 45
          Height = 16
          Caption = 'Country'
        end
        object Label39: TLabel
          Left = 5
          Top = 179
          Width = 45
          Height = 16
          Caption = 'Contact'
        end
        object Label40: TLabel
          Left = 5
          Top = 196
          Width = 58
          Height = 16
          Caption = 'Telephone'
        end
        object Label41: TLabel
          Left = 5
          Top = 213
          Width = 84
          Height = 16
          Caption = 'Email Address'
        end
        object Label42: TLabel
          Left = 117
          Top = 44
          Width = 34
          Height = 14
          Caption = 'Field...'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsItalic]
          ParentFont = False
        end
        object Label43: TLabel
          Left = 152
          Top = 42
          Width = 7
          Height = 16
          Caption = '2'
        end
        object Label48: TLabel
          Left = 152
          Top = 60
          Width = 7
          Height = 16
          Caption = '3'
        end
        object Label53: TLabel
          Left = 124
          Top = 60
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label54: TLabel
          Left = 124
          Top = 77
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label55: TLabel
          Left = 152
          Top = 77
          Width = 7
          Height = 16
          Caption = '4'
        end
        object Label56: TLabel
          Left = 124
          Top = 111
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label57: TLabel
          Left = 152
          Top = 111
          Width = 7
          Height = 16
          Caption = '6'
        end
        object Label58: TLabel
          Left = 152
          Top = 94
          Width = 7
          Height = 16
          Caption = '5'
        end
        object Label59: TLabel
          Left = 124
          Top = 94
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label60: TLabel
          Left = 124
          Top = 128
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label61: TLabel
          Left = 152
          Top = 128
          Width = 7
          Height = 16
          Caption = '7'
        end
        object Label62: TLabel
          Left = 124
          Top = 145
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label63: TLabel
          Left = 152
          Top = 145
          Width = 7
          Height = 16
          Caption = '8'
        end
        object Label64: TLabel
          Left = 124
          Top = 162
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label65: TLabel
          Left = 152
          Top = 162
          Width = 7
          Height = 16
          Caption = '9'
        end
        object Label66: TLabel
          Left = 124
          Top = 179
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label67: TLabel
          Left = 148
          Top = 179
          Width = 14
          Height = 16
          Caption = '10'
        end
        object Label68: TLabel
          Left = 124
          Top = 196
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label133: TLabel
          Left = 148
          Top = 196
          Width = 13
          Height = 16
          Caption = '11'
        end
        object Label134: TLabel
          Left = 124
          Top = 213
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label135: TLabel
          Left = 147
          Top = 213
          Width = 14
          Height = 16
          Caption = '12'
        end
        object Label139: TLabel
          Left = 5
          Top = 386
          Width = 100
          Height = 16
          Caption = '**Required Fields'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label137: TLabel
          Left = 5
          Top = 230
          Width = 49
          Height = 16
          Caption = 'Ship Via'
        end
        object Label140: TLabel
          Left = 5
          Top = 247
          Width = 59
          Height = 16
          Caption = 'Tax Group'
        end
        object Label141: TLabel
          Left = 124
          Top = 230
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label142: TLabel
          Left = 124
          Top = 247
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label143: TLabel
          Left = 148
          Top = 247
          Width = 14
          Height = 16
          Caption = '14'
        end
        object Label144: TLabel
          Left = 148
          Top = 230
          Width = 14
          Height = 16
          Caption = '13'
        end
        object Label150: TLabel
          Left = 5
          Top = 264
          Width = 52
          Height = 16
          Caption = 'Currency'
        end
        object Label151: TLabel
          Left = 124
          Top = 264
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label152: TLabel
          Left = 148
          Top = 264
          Width = 14
          Height = 16
          Caption = '15'
        end
        object Label253: TLabel
          Left = 5
          Top = 281
          Width = 46
          Height = 16
          Caption = 'Territory'
        end
        object Label254: TLabel
          Left = 124
          Top = 281
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label255: TLabel
          Left = 148
          Top = 281
          Width = 14
          Height = 16
          Caption = '16'
        end
        object Label265: TLabel
          Left = 5
          Top = 298
          Width = 84
          Height = 16
          Caption = 'Terms Number'
        end
        object Label266: TLabel
          Left = 124
          Top = 298
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label267: TLabel
          Left = 148
          Top = 298
          Width = 14
          Height = 16
          Caption = '17'
        end
      end
      object GroupBox6: TGroupBox
        Left = 513
        Top = 1
        Width = 165
        Height = 520
        Hint = 'Import SO Line INFO Records (ISSOINFO)  '
        Caption = 'SO Line INFO Records'
        ParentShowHint = False
        ShowHint = True
        TabOrder = 4
        object Label162: TLabel
          Left = 5
          Top = 21
          Width = 150
          Height = 16
          Caption = 'Rec Designator Type = I'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label163: TLabel
          Left = 5
          Top = 42
          Width = 91
          Height = 16
          Caption = '**Order Number'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label164: TLabel
          Left = 5
          Top = 60
          Width = 100
          Height = 16
          Caption = '***SO Line# (Ref)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlue
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
        end
        object Label165: TLabel
          Left = 5
          Top = 77
          Width = 80
          Height = 16
          Caption = 'Alpha[1] Field'
        end
        object Label166: TLabel
          Left = 5
          Top = 111
          Width = 80
          Height = 16
          Caption = 'Alpha[3] Field'
        end
        object Label167: TLabel
          Left = 5
          Top = 128
          Width = 80
          Height = 16
          Caption = 'Alpha[4] Field'
        end
        object Label168: TLabel
          Left = 5
          Top = 145
          Width = 80
          Height = 16
          Caption = 'Alpha[5] Field'
        end
        object Label169: TLabel
          Left = 5
          Top = 162
          Width = 80
          Height = 16
          Caption = 'Alpha[6] Field'
        end
        object Label170: TLabel
          Left = 5
          Top = 179
          Width = 80
          Height = 16
          Caption = 'Alpha[7] Field'
        end
        object Label171: TLabel
          Left = 5
          Top = 196
          Width = 80
          Height = 16
          Caption = 'Alpha[8] Field'
        end
        object Label172: TLabel
          Left = 5
          Top = 213
          Width = 80
          Height = 16
          Caption = 'Alpha[9] Field'
        end
        object Label173: TLabel
          Left = 5
          Top = 230
          Width = 87
          Height = 16
          Caption = 'Alpha[10] Field'
        end
        object Label174: TLabel
          Left = 5
          Top = 94
          Width = 80
          Height = 16
          Caption = 'Alpha[2] Field'
        end
        object Label180: TLabel
          Left = 118
          Top = 44
          Width = 34
          Height = 14
          Caption = 'Field...'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsItalic]
          ParentFont = False
        end
        object Label181: TLabel
          Left = 153
          Top = 42
          Width = 7
          Height = 16
          Caption = '2'
        end
        object Label182: TLabel
          Left = 127
          Top = 60
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label183: TLabel
          Left = 153
          Top = 60
          Width = 7
          Height = 16
          Caption = '3'
        end
        object Label184: TLabel
          Left = 127
          Top = 77
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label185: TLabel
          Left = 153
          Top = 77
          Width = 7
          Height = 16
          Caption = '4'
        end
        object Label186: TLabel
          Left = 127
          Top = 94
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label187: TLabel
          Left = 153
          Top = 94
          Width = 7
          Height = 16
          Caption = '5'
        end
        object Label188: TLabel
          Left = 127
          Top = 111
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label189: TLabel
          Left = 153
          Top = 111
          Width = 7
          Height = 16
          Caption = '6'
        end
        object Label190: TLabel
          Left = 127
          Top = 128
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label191: TLabel
          Left = 153
          Top = 128
          Width = 7
          Height = 16
          Caption = '7'
        end
        object Label192: TLabel
          Left = 127
          Top = 145
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label193: TLabel
          Left = 153
          Top = 145
          Width = 7
          Height = 16
          Caption = '8'
        end
        object Label194: TLabel
          Left = 127
          Top = 162
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label195: TLabel
          Left = 153
          Top = 162
          Width = 7
          Height = 16
          Caption = '9'
        end
        object Label196: TLabel
          Left = 127
          Top = 179
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label197: TLabel
          Left = 148
          Top = 179
          Width = 14
          Height = 16
          Caption = '10'
        end
        object Label198: TLabel
          Left = 127
          Top = 196
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label199: TLabel
          Left = 148
          Top = 196
          Width = 13
          Height = 16
          Caption = '11'
        end
        object Label200: TLabel
          Left = 148
          Top = 213
          Width = 14
          Height = 16
          Caption = '12'
        end
        object Label201: TLabel
          Left = 127
          Top = 213
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label202: TLabel
          Left = 127
          Top = 230
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label203: TLabel
          Left = 148
          Top = 230
          Width = 14
          Height = 16
          Caption = '13'
        end
        object Label204: TLabel
          Left = 127
          Top = 247
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label205: TLabel
          Left = 148
          Top = 247
          Width = 14
          Height = 16
          Caption = '14'
        end
        object Label206: TLabel
          Left = 127
          Top = 264
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label207: TLabel
          Left = 148
          Top = 264
          Width = 14
          Height = 16
          Caption = '15'
        end
        object Label208: TLabel
          Left = 127
          Top = 281
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label209: TLabel
          Left = 148
          Top = 281
          Width = 14
          Height = 16
          Caption = '16'
        end
        object Label210: TLabel
          Left = 127
          Top = 298
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label211: TLabel
          Left = 148
          Top = 298
          Width = 14
          Height = 16
          Caption = '17'
        end
        object Label212: TLabel
          Left = 127
          Top = 315
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label213: TLabel
          Left = 148
          Top = 315
          Width = 14
          Height = 16
          Caption = '18'
        end
        object Label217: TLabel
          Left = 127
          Top = 332
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label218: TLabel
          Left = 148
          Top = 332
          Width = 14
          Height = 16
          Caption = '19'
        end
        object Label219: TLabel
          Left = 127
          Top = 349
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label220: TLabel
          Left = 148
          Top = 349
          Width = 14
          Height = 16
          Caption = '20'
        end
        object Label221: TLabel
          Left = 127
          Top = 366
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label222: TLabel
          Left = 148
          Top = 366
          Width = 14
          Height = 16
          Caption = '21'
        end
        object Label224: TLabel
          Left = 148
          Top = 383
          Width = 14
          Height = 16
          Caption = '22'
        end
        object Label226: TLabel
          Left = 149
          Top = 400
          Width = 14
          Height = 16
          Caption = '23'
        end
        object Label227: TLabel
          Left = 127
          Top = 383
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label228: TLabel
          Left = 127
          Top = 400
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label175: TLabel
          Left = 5
          Top = 247
          Width = 86
          Height = 16
          Caption = 'Alpha[11] Field'
        end
        object Label176: TLabel
          Left = 5
          Top = 264
          Width = 87
          Height = 16
          Caption = 'Alpha[12] Field'
        end
        object Label177: TLabel
          Left = 5
          Top = 281
          Width = 87
          Height = 16
          Caption = 'Alpha[13] Field'
        end
        object Label178: TLabel
          Left = 5
          Top = 298
          Width = 87
          Height = 16
          Caption = 'Alpha[14] Field'
        end
        object Label179: TLabel
          Left = 5
          Top = 315
          Width = 87
          Height = 16
          Caption = 'Alpha[15] Field'
        end
        object Label214: TLabel
          Left = 5
          Top = 332
          Width = 87
          Height = 16
          Caption = 'Alpha[16] Field'
        end
        object Label215: TLabel
          Left = 5
          Top = 349
          Width = 87
          Height = 16
          Caption = 'Alpha[17] Field'
        end
        object Label216: TLabel
          Left = 5
          Top = 366
          Width = 87
          Height = 16
          Caption = 'Alpha[18] Field'
        end
        object Label223: TLabel
          Left = 5
          Top = 383
          Width = 87
          Height = 16
          Caption = 'Alpha[19] Field'
        end
        object Label225: TLabel
          Left = 5
          Top = 400
          Width = 87
          Height = 16
          Caption = 'Alpha[20] Field'
        end
        object Label229: TLabel
          Left = 5
          Top = 417
          Width = 71
          Height = 16
          Caption = 'Date1 Field*'
        end
        object Label230: TLabel
          Left = 5
          Top = 434
          Width = 71
          Height = 16
          Caption = 'Date2 Field*'
        end
        object Label231: TLabel
          Left = 5
          Top = 451
          Width = 71
          Height = 16
          Caption = 'Date3 Field*'
        end
        object Label232: TLabel
          Left = 5
          Top = 468
          Width = 71
          Height = 16
          Caption = 'Date4 Field*'
        end
        object Label233: TLabel
          Left = 5
          Top = 485
          Width = 71
          Height = 16
          Caption = 'Date5 Field*'
        end
        object Label234: TLabel
          Left = 127
          Top = 417
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label235: TLabel
          Left = 149
          Top = 417
          Width = 14
          Height = 16
          Caption = '24'
        end
        object Label236: TLabel
          Left = 127
          Top = 434
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label237: TLabel
          Left = 149
          Top = 434
          Width = 14
          Height = 16
          Caption = '25'
        end
        object Label238: TLabel
          Left = 127
          Top = 451
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label239: TLabel
          Left = 149
          Top = 451
          Width = 14
          Height = 16
          Caption = '26'
        end
        object Label240: TLabel
          Left = 127
          Top = 468
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label241: TLabel
          Left = 149
          Top = 468
          Width = 14
          Height = 16
          Caption = '27'
        end
        object Label242: TLabel
          Left = 127
          Top = 485
          Width = 24
          Height = 16
          Caption = '......'
        end
        object Label243: TLabel
          Left = 149
          Top = 485
          Width = 14
          Height = 16
          Caption = '28'
        end
      end
    end
    object CIWebPanel: TPanel
      Left = 2
      Top = 2
      Width = 681
      Height = 524
      Align = alClient
      TabOrder = 1
      object Label1: TLabel
        Left = 174
        Top = 290
        Width = 296
        Height = 16
        Caption = 'Import to EDI Module, Open SO, or S/R file (E,S,R)'
      end
      object Label6: TLabel
        Left = 174
        Top = 255
        Width = 130
        Height = 16
        Caption = 'Bank Account Number'
        Transparent = True
      end
      object Gradient1: TGradient
        Left = 2
        Top = -1
        Width = 168
        Height = 525
        Style = gsLinearV
      end
      object Label2: TLabel
        Left = 174
        Top = 191
        Width = 314
        Height = 16
        Caption = 'New Name of FTP file to Save and Download (optional)'
        Transparent = True
      end
      object Label9: TLabel
        Left = 174
        Top = 138
        Width = 175
        Height = 16
        Caption = 'Name of File on the FTP Site?'
        Transparent = True
      end
      object Label149: TLabel
        Left = 543
        Top = 257
        Width = 135
        Height = 16
        Caption = '**Required for Payment'
        Transparent = True
      end
      object Label245: TLabel
        Left = 174
        Top = 475
        Width = 72
        Height = 16
        Hint = 'The Import File must be Comma Delimited.'
        Caption = 'Date Format'
        ParentShowHint = False
        ShowHint = True
        Transparent = True
      end
      object cbAutoMode: TTASCheckBox
        Left = 174
        Top = 343
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Run Unattended?'
        TabOrder = 6
        FieldName = 'auto.mode'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object cbUseSONum: TTASCheckBox
        Left = 174
        Top = 318
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Use Imported SO Number as actual SO Num?'
        TabOrder = 5
        FieldName = 'use.imp.sonum'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER1: TTASENTER
        Left = 497
        Top = 288
        Width = 20
        Height = 21
        AutoSize = False
        CharCase = ecUpperCase
        TabOrder = 4
        FieldName = 'import.to.edi'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_soedi()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'ESR'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER2: TTASENTER
        Left = 413
        Top = 252
        Width = 128
        Height = 21
        TabStop = False
        AutoSize = False
        ReadOnly = True
        TabOrder = 3
        Text = 'TASENTER2'
        FieldName = 'bank.name'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object EnterBankAcct: TTASComboEnter
        Left = 333
        Top = 252
        Width = 69
        Height = 21
        Color = clInfoBk
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
          F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
          F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
          0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
          F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
          A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
          DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
          AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
          9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
          D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
          B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
          C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
          0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
          C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
          D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
          CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
          9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
          CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
          0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
          CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
          86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
          C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
          F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
          F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
          F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
        NumGlyphs = 1
        ReadOnly = True
        TabOrder = 2
        Text = 'EnterBankAcct'
        FieldName = 'dsp.bank'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = -1
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_bankacct()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        KeyTraps = 'F2|ENTERBANKACCT.CLICK'
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object EnterDLFile: TTASENTER
        Left = 174
        Top = 213
        Width = 475
        Height = 21
        AutoSize = False
        TabOrder = 1
        Text = 'Import File Name'
        FieldName = 'downloadfile'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_newfile()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object EnterFTPFile: TTASENTER
        Left = 174
        Top = 159
        Width = 475
        Height = 21
        AutoSize = False
        TabOrder = 0
        Text = 'Import File Name'
        FieldName = 'ftp.FileName'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_ftpfile()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object GroupBox1: TGroupBox
        Left = 165
        Top = 19
        Width = 488
        Height = 105
        Caption = 'FTP Settings'
        TabOrder = 12
        object Label4: TLabel
          Left = 10
          Top = 22
          Width = 65
          Height = 16
          Caption = 'Host Name'
          Transparent = True
        end
        object Label3: TLabel
          Left = 10
          Top = 46
          Width = 65
          Height = 16
          Caption = 'User Name'
          Transparent = True
        end
        object Label5: TLabel
          Left = 10
          Top = 70
          Width = 57
          Height = 16
          Caption = 'Password'
          Transparent = True
        end
        object EnterPSWD: TTASENTER
          Left = 96
          Top = 68
          Width = 375
          Height = 21
          AutoSize = False
          PasswordChar = '*'
          TabOrder = 2
          Text = 'TASENTER3'
          FieldName = 'ftp.password'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_ftpPSWD()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterUser: TTASENTER
          Left = 96
          Top = 44
          Width = 375
          Height = 21
          AutoSize = False
          TabOrder = 1
          Text = 'TASENTER3'
          FieldName = 'ftp.userName'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_user()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
        object EnterHost: TTASENTER
          Left = 96
          Top = 20
          Width = 375
          Height = 21
          AutoSize = False
          TabOrder = 0
          Text = 'EnterHost'
          FieldName = 'ftp.hostName'
          DispPrgLoc = -1
          ClickPrgLoc = -1
          ChangePrgLoc = 0
          PrePrgLoc = -1
          PostPrgLoc = -1
          ValidPrgLoc = -1
          ValidCheckOnExit = True
          ValidUserEsc = False
          ValidExpr = 'vld_host()'
          ValidExprLoc = 0
          ValidExprTyp = #0
          Group = 0
          NoClickOn = False
          NoClickOff = False
          ReturnIsTab = True
          SelectStart = 0
          PreRetFalse = False
          EntryFont.Charset = DEFAULT_CHARSET
          EntryFont.Color = clWindowText
          EntryFont.Height = -11
          EntryFont.Name = 'MS Sans Serif'
          EntryFont.Style = []
          EntryBGColor = clWhite
          EntryUseDflt = True
          FldModified = True
        end
      end
      object TASCheckBox2: TTASCheckBox
        Left = 174
        Top = 369
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Add it Kit Components for Kit Parents'
        TabOrder = 7
        FieldName = 'add.kit.comps'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object cbImpError2: TTASCheckBox
        Left = 174
        Top = 396
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Print Import Error report prior to Importing Data'
        TabOrder = 8
        FieldName = 'error.check'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object cbDateFormat2: TTASComboBox
        Left = 284
        Top = 472
        Width = 216
        Height = 24
        CharCase = ecUpperCase
        ItemHeight = 16
        TabOrder = 11
        Text = 'DATE FORMAT'
        FieldName = 'date.format'
        DropDownPrgLoc = -1
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = -1
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_dateform()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ItemNumber = 0
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox4: TTASCheckBox
        Left = 174
        Top = 421
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Set Ready to Ship Flag to Y'
        TabOrder = 9
        FieldName = 'rts.flag'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox7: TTASCheckBox
        Left = 174
        Top = 447
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Skip Existing Sales Orders?'
        TabOrder = 10
        FieldName = 'skip.so'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox9: TTASCheckBox
        Left = 174
        Top = 500
        Width = 340
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Send Email Reminder for Sales Reps'
        TabOrder = 13
        FieldName = 'send.reminder'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
    end
    object DETPanel: TPanel
      Left = 2
      Top = 2
      Width = 681
      Height = 524
      Align = alClient
      TabOrder = 0
      object Gradient2: TGradient
        Left = 1
        Top = 1
        Width = 165
        Height = 523
        Style = gsLinearV
      end
      object Label7: TLabel
        Left = 166
        Top = 38
        Width = 113
        Height = 16
        Caption = 'Name of Import File'
        Transparent = True
      end
      object Label8: TLabel
        Left = 166
        Top = 125
        Width = 130
        Height = 16
        Caption = 'Bank Account Number'
        Transparent = True
      end
      object Label10: TLabel
        Left = 166
        Top = 249
        Width = 296
        Height = 16
        Caption = 'Import to EDI Module, Open SO, or S/R file (E,S,R)'
      end
      object Label148: TLabel
        Left = 542
        Top = 125
        Width = 135
        Height = 16
        Caption = '**Required for Payment'
        Transparent = True
      end
      object Label159: TLabel
        Left = 167
        Top = 189
        Width = 72
        Height = 16
        Hint = 'The Import File must be Comma Delimited.'
        Caption = 'Date Format'
        ParentShowHint = False
        ShowHint = True
        Transparent = True
      end
      object Label252: TLabel
        Left = 165
        Top = 395
        Width = 216
        Height = 16
        Caption = 'Delete or Rename Import File [D,R,N]'
      end
      object Label274: TLabel
        Left = 165
        Top = 482
        Width = 154
        Height = 16
        Caption = 'Use Imported Price [Y,N,0]'
      end
      object EnterImpFile: TTASENTER
        Left = 166
        Top = 59
        Width = 475
        Height = 21
        AutoSize = False
        TabOrder = 0
        Text = 'Import File Name'
        FieldName = 'imp.FileName'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_impfile()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object EnterDBankAcct: TTASComboEnter
        Left = 325
        Top = 123
        Width = 69
        Height = 21
        Color = clInfoBk
        Glyph.Data = {
          36030000424D3603000000000000360000002800000010000000100000000100
          1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
          F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
          F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F77377784D515204
          0809090D0E3D4142848687F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
          F0F3F7919394848687A3A7A885898ABBC0C1C9CECF808586585C5D343637A1A3
          A4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7979B9C979B9CDBE0E1BDC2C3D7
          DFDFC3C8C9CCD1D2CCD1D29EA2A3161A1B969899F0F3F7F0F3F7F0F3F7F0F3F7
          AFB1B2A5A9AAC4C9CAC5CDCDC0CACAC2CCCCCED8D8C0CACA000101BEC3C4989C
          9D4A4C4DBCBEBFF0F3F7F0F3F7B9BDBE777B7CE2E7E8CBD3D3CAD4D4C2CCCCCE
          D8D8C0CACA000101000101D6DEDEBDC2C355595A808283F0F3F7F0F3F7ABAFB0
          B9BDBED2D7D8C3CBCBC9D3D3C7D1D1C0CACA000101000101C0CACAD2DADABCC1
          C2939899424647F0F3F7F0F3F7838788C8CDCEC2CACACDD5D500010100010100
          0101000101C6D2D2D0DADAC2CCCCC7CCCDBDC2C30B0F10F0F3F7F0F3F7838788
          C5CACBCDD5D5000101CFD9D9BBC7C7CED8D8000101C8D4D4C4CECECED8D8CDD2
          D3BDC2C30B0F10F0F3F7F0F3F78E9293ACB0B1C9CECF000101C4CECECED8D8C0
          CACA000101BECACACFD9D9C1C9C9C2C7C88085864D5152F0F3F7F0F3F7BDC1C2
          9DA1A2D7DCDD000101D7E1E1BAC4C4D5DFDF000101CED8D8D0D8D8C3CBCBC5CA
          CB6F73746C6E6FF0F3F7F0F3F7E7E9EA959798BABEBFBEC3C400010100010100
          0101C0CACAC6CECEC7CFCFDADFE095999A585A5BD2D4D5F0F3F7F0F3F7F0F3F7
          CED0D19B9FA0B7BBBCD0D5D6C5CACBC0CACACED8D8CCD1D2C3C8C9ACB0B18185
          86A3A5A6F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7C8CACB959798999D9EB8BCBDC2
          C7C8D2D7D8AFB4B5B2B6B7929495D1D3D4F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7
          F0F3F7F0F3F7F0F3F7BCC0C19CA0A18185867F8384999D9EBDBFC0F0F3F7F0F3
          F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
          F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
        NumGlyphs = 1
        TabOrder = 1
        Text = 'EnterBankAcct'
        FieldName = 'dsp.bank'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = -1
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_bankacct()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        KeyTraps = 'F2|ENTERDBANKACCT.CLICK'
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object TASENTER3: TTASENTER
        Left = 405
        Top = 123
        Width = 128
        Height = 21
        TabStop = False
        AutoSize = False
        ReadOnly = True
        TabOrder = 2
        Text = 'TASENTER2'
        FieldName = 'bank.name'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = True
      end
      object TASENTER4: TTASENTER
        Left = 494
        Top = 247
        Width = 21
        Height = 21
        AutoSize = False
        CharCase = ecUpperCase
        TabOrder = 4
        FieldName = 'import.to.edi'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_soedi()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'ESR'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox1: TTASCheckBox
        Left = 166
        Top = 290
        Width = 345
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Add Kit Components to SO for Kit Parents'
        TabOrder = 5
        FieldName = 'add.kit.comps'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object cbImpError: TTASCheckBox
        Left = 166
        Top = 317
        Width = 345
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Print Import Error report prior to Importing Data'
        TabOrder = 6
        FieldName = 'error.check'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object cbDateFormat: TTASComboBox
        Left = 276
        Top = 186
        Width = 216
        Height = 24
        CharCase = ecUpperCase
        ItemHeight = 16
        TabOrder = 3
        Text = 'DATE FORMAT'
        FieldName = 'date.format'
        DropDownPrgLoc = -1
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = -1
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = True
        ValidUserEsc = False
        ValidExpr = 'vld_dateform()'
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ItemNumber = 0
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox3: TTASCheckBox
        Left = 166
        Top = 342
        Width = 345
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Set Ready to Ship Flag to Y'
        TabOrder = 7
        FieldName = 'rts.flag'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER5: TTASENTER
        Left = 494
        Top = 393
        Width = 21
        Height = 21
        AutoSize = False
        CharCase = ecUpperCase
        TabOrder = 9
        FieldName = 'rename.file'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'DRN'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox5: TTASCheckBox
        Left = 166
        Top = 425
        Width = 345
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Run Unattended?'
        TabOrder = 10
        FieldName = 'auto.mode'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox6: TTASCheckBox
        Left = 166
        Top = 367
        Width = 345
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Skip Existing Sales Orders?'
        TabOrder = 8
        FieldName = 'skip.so'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASCheckBox8: TTASCheckBox
        Left = 166
        Top = 456
        Width = 345
        Height = 17
        Alignment = taLeftJustify
        Caption = 'Send Email Reminder for Sales Reps'
        TabOrder = 11
        FieldName = 'send.reminder'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        Group = 0
        NoClickOn = False
        NoClickOff = False
        ReturnIsTab = True
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
      object TASENTER6: TTASENTER
        Left = 494
        Top = 480
        Width = 21
        Height = 21
        AutoSize = False
        CharCase = ecUpperCase
        TabOrder = 12
        FieldName = 'imp.price'
        DispPrgLoc = -1
        ClickPrgLoc = -1
        ChangePrgLoc = 0
        PrePrgLoc = -1
        PostPrgLoc = -1
        ValidPrgLoc = -1
        ValidCheckOnExit = False
        ValidUserEsc = False
        ValidExprLoc = 0
        ValidExprTyp = #0
        Group = 0
        NoClickOn = False
        NoClickOff = False
        AllowedChrs = 'YN0'
        ReturnIsTab = True
        SelectStart = 0
        PreRetFalse = False
        EntryFont.Charset = DEFAULT_CHARSET
        EntryFont.Color = clWindowText
        EntryFont.Height = -11
        EntryFont.Name = 'MS Sans Serif'
        EntryFont.Style = []
        EntryBGColor = clWhite
        EntryUseDflt = True
        FldModified = False
      end
    end
  end
  object ToolBar1: TToolBar
    Left = 0
    Top = 0
    Width = 685
    Height = 29
    ButtonHeight = 24
    Caption = 'ToolBar1'
    EdgeBorders = [ebLeft, ebTop, ebRight, ebBottom]
    EdgeInner = esLowered
    TabOrder = 0
    Transparent = True
  end
  object EvoToolBar: TToolBar
    Left = 566
    Top = 3
    Width = 116
    Height = 25
    Align = alCustom
    Anchors = [akTop, akRight]
    EdgeBorders = []
    Images = EvoToobarImages
    TabOrder = 2
    Transparent = False
    Visible = False
    object ETB5: TToolButton
      Left = 0
      Top = 0
      Caption = 'ETB5'
      Visible = False
    end
    object ETB4: TToolButton
      Left = 23
      Top = 0
      Caption = 'ETB4'
      Visible = False
    end
    object ETB3: TToolButton
      Left = 46
      Top = 0
      Caption = 'ETB3'
      Visible = False
    end
    object ETB2: TToolButton
      Left = 69
      Top = 0
      Caption = 'ETB2'
      Visible = False
    end
    object ETB1: TToolButton
      Left = 92
      Top = 0
      Caption = 'ETB1'
      Visible = False
    end
  end
  object ETBcombo: TTASComboBox
    Left = 458
    Top = 2
    Width = 168
    Height = 24
    Style = csDropDownList
    ItemHeight = 16
    TabOrder = 3
    Visible = False
    FieldName = 'ETBcomboval'
    DropDownPrgLoc = -1
    DispPrgLoc = -1
    ClickPrgLoc = -1
    ChangePrgLoc = -1
    PrePrgLoc = -1
    PostPrgLoc = -1
    ValidPrgLoc = -1
    ValidCheckOnExit = False
    ValidUserEsc = False
    ValidExprLoc = 0
    ValidExprTyp = #0
    Group = 0
    NoClickOn = False
    NoClickOff = False
    ItemNumber = 0
    ReturnIsTab = True
    SelectStart = 0
    PreRetFalse = False
    EntryFont.Charset = DEFAULT_CHARSET
    EntryFont.Color = clWindowText
    EntryFont.Height = -11
    EntryFont.Name = 'MS Sans Serif'
    EntryFont.Style = []
    EntryBGColor = clWhite
    EntryUseDflt = True
    FldModified = False
  end
  object Panel3: TPanel
    Left = 0
    Top = 557
    Width = 685
    Height = 34
    Align = alBottom
    BevelInner = bvLowered
    BevelOuter = bvLowered
    TabOrder = 4
    object btnExit: TGlyphBtn
      Left = 593
      Top = 6
      Width = 75
      Height = 24
      Caption = 'E&xit'
      TabOrder = 1
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000CED5D9DDE2E4
        DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4E6DFE4
        E6DFE4E6DDE2E4CED5D9DBE0E28E94CA4F56B83139B00F19A70F19A70F19A70F
        19A70F19A70F19A70F19A70F19A73139B04F56B88E94CADBE0E2DBE0E34E55B7
        5B69E16877EE6575EE6273ED5F71ED5C6EEC596CEC566AEB5268EB4F66EA4C63
        EA3F54DD4E55B7DBE0E3D8DDE03039AF6D7BEE5766E53E4FDA3445D53345D433
        43D33142D23141D13040CF3647D34357DF4C63EA3A45B9D8DDE0D5DBDD0F19A7
        707DEF4354DD4354DAC5CAF3606DDD3446D53345D45F6BDBC4C8F0404ED23445
        D14F66EA202DB8D5DBDDD2D7DA0F19A7737FEF4657DFC5CAF3FFFFFFF3F4FD60
        6EDE606DDDF3F4FCFFFFFFC4C8F03040CF5268EB202EB8D2D7DACED4D70F19A7
        7681EF4859E16270E3F3F4FDFFFFFFF3F4FDF3F4FDFFFFFFF3F4FC5F6BDB3141
        D0566AEB222FB8CED4D7CAD1D40F19A77A87F0495BE3384CDE6371E4F3F4FDFF
        FFFFFFFFFFF3F4FD606DDD3343D33142D15C71EC2735B9CAD1D4C7CDD10F19A7
        8697F35066E74059E36778E7F3F4FDFFFFFFFFFFFFF3F4FD6373DF3B50D7394F
        D56983EF2A39BAC7CDD1C2C9CD0F19A78EA3F46484ED7994EEF5F7FDFFFFFFF5
        F7FDF5F7FDFFFFFFF5F7FD758EE64F71DE7491F22B3BBAC2C9CDBFC6CA0F19A7
        91A4F46685EECED7F9FFFFFFF5F7FD7792EC7791EAF5F7FDFFFFFFCCD5F54F71
        DE7693F22B3BBABFC6CABAC2C50F19A792A4F56686EF6283EECDD7F87892EE52
        77E85175E6758FE9CBD5F65C7AE35475E17894F22D3CBABAC2C5B6BEC12832AB
        8FA0F5778DF25D7BEE5C7AED5B79EC5977EA5876E85674E75473E65371E4647F
        EA748DF23A46B8B6BEC1B5BCC03C44AF7783E78998F48795F48493F48191F37E
        90F37B8EF3798DF3768AF37389F37187F25F73E33C44AFB5BCC0B5BDC06E77B7
        3C44AF2731AA0F19A70F19A70F19A70F19A70F19A70F19A70F19A70F19A72731
        AA3C44AF6E77B7B5BDC0C3CBCFB8BFC3B3BABEB3BABEB3BABEB3BABEB3BABEB3
        BABEB3BABEB3BABEB3BABEB3BABEB3BABEB3BABEB8BFC3C3CBCF}
      GlyphKind = bkCustom
    end
    object btnImport: TGlyphBtn
      Left = 518
      Top = 6
      Width = 75
      Height = 24
      Caption = 'Import'
      TabOrder = 0
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF26984D26984D
        26984D26984D26984D26984D26984DFEFEFFFEFEFF0026BF0026BFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFF26984D99E5B333CC6633CC6633CC6626984DFEFEFFFE
        FEFF0026BF8099FF0033FF0026BFFEFEFFFEFEFFFEFEFF0026BF26984D99E5B3
        33CC6633CC6626984DFEFEFFFEFEFFFEFEFF0026BF8099FF0033FF0033FF0026
        BFFEFEFF0026BF0026BF26984D99E5B399E5B333CC6633CC6626984DFEFEFFFE
        FEFFFEFEFF0026BF8099FF0033FF0033FF0026BF0033FF0026BF26984D99E5B3
        26984D99E5B333CC6633CC6626984DFEFEFFFEFEFFFEFEFF0026BF8099FF0033
        FF0033FF0033FF0026BF26984D26984DFEFEFF26984D99E5B333CC6633CC6626
        984DFEFEFFFEFEFFFEFEFF0026BF8099FF0033FF0033FF0026BF26984DFEFEFF
        FEFEFFFEFEFF26984D99E5B399E5B326984DFEFEFFFEFEFF0026BF8099FF8099
        FF8099FF8099FF0026BFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF26984D26984DFE
        FEFFFEFEFF0026BF0026BF0026BF0026BF0026BF0026BF0026BFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF
        FEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFE
        FFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFE
        FEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFFFEFEFF}
      GlyphKind = bkCustom
    end
    object btnCFG: TGlyphBtn
      Left = 442
      Top = 6
      Width = 75
      Height = 24
      Caption = '&Settings'
      TabOrder = 2
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000FFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFD3A3939B9B9B96D6D6D787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD4242428383834D
        4D4D8D8D8D6D6D6D737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFD6C6C6C6A6A6A6C6C6C5D5D5D4C4C4C8989896C6C6C70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6CC3C3C38F8F8F6A6A6A7B
        7B7B7676764C4C4C8888886C6C6C6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        696969E0E0E0CCCCCCCCCCCCB4B4B47A7A7A7777774F4F4F5252528787876C6C
        6C70706FFFFEFDFFFEFDFFFEFD2E2E2EE8E8E88D8D8DCDCDCDD9D9D9D9D9D985
        85855A5A5A5F5F5F6363635050508E8E8E6C6C6C737372FFFEFD000000727272
        D3D3D36A6A6A7A7A7AC9C9C9A8A8A86464646C6C6C7C7C7CE4E4C9E5E5E55555
        559595956D6D6D787877000000898989707070CFCFCF8383839D9D9D7D7D7D80
        8080828282E7E7E7DFDFAFEFEFD7E7E7E75E5E5EA1A1A16A6A6AFFFEFD535353
        9292926E6E6EA3A3A3848484929292858585E7E7E7DCDCDCEFEFEFD4D4D4F3F3
        F3EBEBEB636363787877FFFEFDFFFEFD6262629F9F9F9F9F9F999999858585EA
        EAEAE1E1E1EFEFEFD9D9D9F3F3F3CBCBCBBFBFBF737372FFFEFDFFFEFDFFFEFD
        FFFEFD6767679F9F9F666652ECECECE2E2E2F0F0F0D9D9D9F3F3F3D1D1D1BEBE
        BE70706FFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD7B7B7BC0C0C0B2B289F1
        F1F1DBDBDBF4F4F4D2D2D2BEBEBE6F6F6EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFD7A7A7AC0C0C0AFAF84F9F9F9D3D3D3BFBFBF70706FFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD747474C0
        C0C0AAAA7BBFBFBF737372FFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD
        FFFEFDFFFEFDFFFEFDFFFEFDFFFEFD6C6C6C8C8C8C787877FFFEFDFFFEFDFFFE
        FDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFF
        FEFD7F7F7EFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFDFFFEFD}
      GlyphKind = bkCustom
    end
    object btnFields: TGlyphBtn
      Left = 6
      Top = 6
      Width = 98
      Height = 24
      Caption = '&Imp Fields'
      TabOrder = 3
      Glyph.Data = {
        36030000424D3603000000000000360000002800000010000000100000000100
        1800000000000003000000000000000000000000000000000000F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3
        F7AD9C8C424239F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7AD9C8CCEB59C424239F0F3F7F0F3F7F0F3F7
        F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7AD9C8CFFEF
        DECEB59C424239F0F3F7F0F3F742423942423942423942423942423942423942
        4239424239424239424239FFEFD6FFEFDECEB59C424239F0F3F7AD9C8CFFE7CE
        CEB59CCEB59CCEB59CCEB59CCEB59CCEB59CCEB59CCEB59CFFEFD6FFEFDEFFEF
        DEFFEFDEBDA594424239AD9C8CFFEFDEFFE7CEFFE7CEFFE7CEFFE7CE8C7B6B00
        0000EFD6BDFFEFD6FFEFD6FFEFD6FFEFD6FFEFD6BDA594424239AD9C8CFFF7E7
        FFE7CEFFE7CEFFE7CEFFE7CEF7D6BDEFD6BDFFE7CEFFEFD6FFEFD6FFEFD6FFEF
        D6FFEFD6BDAD94424239AD9C8CFFF7EFFFE7C6FFE7CEFFE7CEFFE7CE8C7B6B73
        6B5ADEC6ADFFEFD6FFEFD6FFEFD6FFEFD6FFEFD6C6AD9C424239AD9C8CFFF7F7
        FFDEC6FFDEC6FFE7CEFFE7CEDEC6AD635A4A6B6352F7DEBDFFEFD6FFEFD6FFEF
        D6FFEFD6CEB59C424239AD9C8CFFFFF7FFDEC6FFDEC6FFDEC6FFE7CEFFE7CEDE
        C6AD524A425A524AFFDEC6FFE7CEFFE7CEFFE7CECEB59C424239AD9C8CFFFFF7
        F7DEC6FFDEC6EFD6BDD6BDA5DEC6ADFFE7CEB59C8C847363C6AD94FFE7CEFFE7
        CEFFE7CECEB59C424239AD9C8CFFFFF7F7DEBDF7DEBDD6BDA5524A425A524AEF
        D6BD73635A5A524AD6BDA5FFE7CEFFE7CEFFE7CECEB59C424239AD9C8CFFFFF7
        F7DEBDF7DEBDF7DEBDAD9484000000000000000000B59C8CFFE7CEFFE7CEFFE7
        CEFFE7CECEB59C424239AD9C8CFFFFF7FFFFF7FFFFF7FFFFF7FFFFF7FFFFF7FF
        FFF7FFFFF7FFF7EFFFF7E7FFF7E7FFEFDEFFEFDEFFE7CE424239F0F3F7AD9C8C
        AD9C8CAD9C8CA594849C8C7B94847384736B7B6B6373635A635A4A524A42524A
        42424239424239F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0
        F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7F0F3F7}
      GlyphKind = bkCustom
    end
  end
  object Evoshellexe: TShellExe
    StartOption = soSW_HIDE
    Left = 493
    Top = 5
  end
  object EvoToobarImages: TImageList
    Left = 529
    Top = 5
    Bitmap = {
      494C010106000900980010001000FFFFFFFFFF10FFFFFFFFFFFFFFFF424D3600
      0000000000003600000028000000400000002000000001002000000000000020
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000007373730073737300737373000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000CE944200CE8C3100D69C
      5200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000073737300BD632900AD6B42006B524A007373730000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000DEA55200BD843900000000000000
      0000D69C5200B57B39006B5231006B5231006B5231006B5231006B5231000000
      000000000000000000000000000000000000000000007373730073737300BD63
      2900EF7B0800FF732100FF940800FFAD310094634A007373730073737300B57B
      5A00737373007373730073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFAD4200AD7B4200000000000000
      00006B523100C67B3100DE943900EFAD4200F7B55200DEB56300EFAD42006B52
      31006B5231000000000000000000000000008452520084525200E79C5A00EF84
      1000D6846300FFAD3100FF8C0800FFA51000FFBD6300AD7B6B0084525200FF94
      0000845252008452520073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000EFB54A00AD7B4200000000006B52
      3100E79C3100F79C3900EF943100EF9C3100F7A53900F7BD5200FFD67300EFCE
      8C00B57B39006B523100000000000000000094634A00F7F7E700F7F7E700F7F7
      E700FFF7E700F7DEAD00F7941800FF940000FFAD3100FFC68400FFBD5A00FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000E7AD6300DE9C29006B523100F7A5
      3100EF9C3100E7942900E79429007352310073523100B5732900F7B54200FFD6
      6B00F7D69400B57B3900000000000000000094636300FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00F7DEAD00FF9C0800FF9C0800FFBD5A00FFC68400FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000F7B53900F7AD3100EFA5
      2900E7942900DE8C290084522900000000000000000000000000B5732900F7AD
      3900FFD66B00DEB57B00B57B390000000000A56B6B00FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00F7941800FFAD2900FF940000FF94
      0000FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000E7B56300F7B53100EFA5
      2900E7942100A56318006B5231006B5231006B5231006B5231006B5231006B52
      31006B5231006B5231006B52310000000000AD7B6B00FFFFFF00FFFFFF00FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FF5A3100EF6B4200EF523100EF6B4200FF5A
      3100FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F7BD3900EFAD
      2900E79C2100D67B2900D67B2900D67B2900D67B2900D67B2900D67B2900D67B
      2900D67B2900D67B2900B57B390000000000B58C7300FFFFFF00FFFFFF00F7F7
      F700CECECE00CECECE00CECECE00CECECE00CECECE00D6D6D600F7EFDE00F7E7
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000F7C6
      4200EFAD2900E79C2100DE942100E7942900E7942900E7942900E7942900EF94
      3100F79C3900EFA54200B57B390000000000B58C7300FFFFFF00FF5A3100EF6B
      4200E7522900C6734200C68C7B00FFFFFF00FFFFFF00FFFFFF00294A84007394
      D600FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000EFCE940000000000F7C6
      4200F7C64200BD8429006B4A21000000000000000000B5732900CE8C3100EF94
      2900EF9C3100EF9C3100B57B390000000000C6947B00FFFFFF00FF8C0800FF8C
      0800FF5A3100AD4A1800FFF7EF00FFFFFF00FFFFFF00FFFFFF007394D6007394
      D600FFFFF700AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000EFCE94000000
      0000F7C64200E7AD39006B5229005A42290073523100B5732900E79C2900E794
      2900F7A53900B57B39000000000000000000D6A58400FFFFFF00FF8C0800FFBD
      5A00FFAD2900F7941800BD632900FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFF
      FF00FFF7EF00AD7B7B0073737300000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000D6BD8C00E7CE
      8C0000000000F7DE8C00E7B53900B5842100CE8C2100E7A52900E79C2100EFA5
      2900EFA53900B57B39000000000000000000DEAD8400DEAD8400FF8C0800DEAD
      8400F7A55A00FFC68400EF943900BD632900C69C9400C69C9400C69C9400C69C
      9400C69C9400AD7B7B0000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000D6BD
      8C00D6BD8C00E7D66300E7D66300F7D64200F7B53100EFAD2900EFAD2900EFA5
      3100B57B390000000000EFAD4200000000000000000000000000FF8C08000000
      000000000000F7A55A00FFDEAD00EFB58C00BD632900BD523900C6734200A563
      4200000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000D6BD8C00D6BD8C00D6BD8C00DEB55200FFCE4A00B57B3900B57B
      39000000000000000000EFAD4200000000000000000000000000000000000000
      00000000000000000000F7A55A00FFEFBD00FFE7AD00DE8C5200944A18000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      000000000000AD9A880046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000AD9A8800CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000212121004242
      3900424239004242390042423900424239004242390042423900424239004242
      3900424239004242390042423900000000000000000000000000000000000000
      000000000000000000000000000000000000000000000000000000000000AD9A
      8800FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B7B00F7F7
      FF00F7F7FF00F7F7FF00BDBDBD00F7F7FF00F7F7FF00003939005A5A5A00F7EF
      E700F7F7FF00F7F7FF0042423900000000000000000046403800464038004640
      380046403800464038004640380046403800464038004640380046403800FFE8
      D400FFEBD900CAB39E0046403800000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000027596100000000000000000027596100000000000000
      00000000000000000000000000000000000000000000000000005A5A5A00BDBD
      BD00BDBDBD00BDBDBD009C9C9400BDBDBD00BDBDBD005A5A5A0042BDBD005252
      4A00BDBDBD00BDBDBD004242390000000000AD9A8800FFE5CE00CAB39E00CAB3
      9E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00CAB39E00FFE8D400FFEB
      D900FFEBD900FFEBD900BBA69200464038008080000080800000800000008000
      0000800000008000000080000000800000008000000080000000800000008000
      0000800000008000000080000000000000000000000027596100000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000275961000000000000000000000000005A5A5A00DED6
      D600DED6D600DED6D600ADADAD00DED6D600DED6D600F7F7FF005A5A5A005ADE
      DE0052524A00F7EFE7004242390000000000AD9A8800FFEDDD00FFE3C900FFE3
      C900FFE3C900FFE3C9008B7C6D0000000000EDD2B900FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BBA692004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      6100000000000000000080808000808080008080800080808000000000000000
      0000275961002759610000000000000000000000000000000000393900003939
      00003939000039390000393900003939000052523100ADADAD009C9C94005A5A
      5A005ADEDE0052524A002121210000000000AD9A8800FFF1E400FFE3C900FFE3
      C900FFE3C900FFE3C900F2D6BD00ECD1B800FFE5CE00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400BFAA96004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF00FFFF
      FF00C8D0D4000000000080000000000000000000000000000000275961002759
      6100000000008080800091919100838383008080800080808000808080000000
      0000275961002759610000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000DED6D600BDBDBD00F7F7
      FF007B7B7B006BADAD004242390000000000AD9A8800FFF4EA00FDE0C600FFE3
      C900FFE3C900FFE3C9008B7C6D0076695C00DCC3AD00FFE8D400FFE8D400FFE8
      D400FFE8D400FFE8D400C4AE99004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000275961002759
      61000000000080808000AAAAAA00919191008383830080808000808080000000
      00002759610027596100000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD005A5A5A005ADEDE0021212100AD9A8800FFF7F000FADEC400FADE
      C400FFE3C900FFE3C900DCC3AD00655A4E006F635700F4D8BF00FFE8D400FFE8
      D400FFE8D400FFE8D400CAB39E004640380080800000FFFF0000808000000000
      0000FFFFFF0000000000FFFFFF0000000000FFFFFF0000000000FFFFFF000000
      0000FFFFFF0000000000800000000000000000000000000000002E6770002E67
      70000000000080808000AAAAAA00AAAAAA009191910080808000808080000000
      00002E6770002E67700000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF00393939005A9C9C00AD9A8800FFF9F300FADEC400FADE
      C400FADEC400FFE3C900FFE3C900DCC3AD00524840005F544A00FADEC400FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF00808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080000000000000000000000000000000377E8800377E
      8800000000000000000080808000808080008080800080808000000000000000
      0000377E8800377E880000000000000000000000000000000000C64200003939
      0000393900007B7B0000393900003939000039390000ADADAD009C9C9400BDBD
      BD00BDBDBD00BDBDBD004242390000000000AD9A8800FFF9F300F6DAC000FADE
      C400EDD2B900D1BAA400DCC3AD00FFE3C900B29D8B0083746600C2AC9700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF000000000000C8D0
      D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400C8D0D400808000008080
      00008080000080800000800000000000000000000000000000004397A3004397
      A3004397A3000000000000000000000000000000000000000000000000004397
      A3004397A3004397A300000000000000000000000000000000009C9C00006363
      00003939000063630000636300003939000039390000DED6D600BDBDBD00F7F7
      FF00F7F7FF00F7F7FF004242390000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00D1BAA400524840005C524800ECD1B800726559005F544A00D5BCA700FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFFFF0000000000FFFF
      FF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00FFFFFF00C8D0D400808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000F76B00006363
      00007B7B00009C9C0000636300007B7B0000393900005A5A5A005A5A5A007B7B
      7B007B7B7B007B7B7B002121210000000000AD9A8800FFF9F300F4D8BF00F4D8
      BF00F4D8BF00AA978500000000000000000000000000B29D8B00FFE3C900FFE5
      CE00FFE5CE00FFE5CE00CAB39E004640380080800000FFFF0000000000000000
      0000000000000000000000000000000000000000000000000000808000008080
      0000808000008080000080000000000000000000000000000000000000000000
      00000000000091919100000000004EA9B6004EA9B60000000000919191000000
      00000000000000000000000000000000000000000000000000009C9C0000ADAD
      6B00BD9C7B00BD9C7B00BD9C7B007B7339003939000042423900000000000000
      000000000000000000000000000000000000AD9A8800FFF9F300FFF9F300FFF9
      F300FFF9F300FFF9F300FFF9F300FFF9F300FFF9F300FFF4EA00FFF1E400FFF1
      E400FFEBD900FFEBD900FFE5CE004640380080800000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFFFF00FFFF0000FFFF
      FF00FFFF0000FFFFFF0080800000000000000000000000000000000000000000
      0000000000000000000091919100000000000000000091919100000000000000
      00000000000000000000000000000000000000000000000000007B7B00005A5A
      5A005A5A5A005A5A5A005A5A5A00313131003939000042423900000000000000
      00000000000000000000000000000000000000000000AD9A8800AD9A8800AD9A
      8800A69382009C8B7B0092827300857669007B6D600072655900655A4E005248
      4000524840004640380046403800000000000000000080800000808000008080
      0000808000008080000080800000808000008080000080800000808000008080
      0000808000008080000080800000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      00000000000000000000000000000000000000000000000000007B7B00007B7B
      00007B7B00007B7B00007B7B00007B7B00002121000000000000000000000000
      000000000000000000000000000000000000424D3E000000000000003E000000
      2800000040000000200000000100010000000000000100000000000000000000
      000000000000000000000000FFFFFF00FFFFFFFF00000000FFFFF8FF00000000
      8FFFF07F00000000301F80010000000030070001000000002003000100000000
      000300010000000081C10001000000008001000100000000C001000100000000
      E001000100000000A181000100000000D003000100000000C803000300000000
      E005D80F00000000F80DFC1F00000000FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF
      FFF1FFFFFFFFC001FFE1FFFFFFFFC00180018001FC3FC001000000008001C001
      0000000080018000000000008001800000000000800180000000000080018000
      00000000800180000000000080018001000000008001800100000000C813803F
      00000000FC3F803F80018001FFFF807F00000000000000000000000000000000
      000000000000}
  end
end
